/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#pragma once
#include "../../runtime/spu/spu_context.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Cross-function branch/loop = a guest tail-jump to another lifted function's
 * entry. It MUST reuse the current host frame, not nest one: SPURS task loops
 * iterate via these, so nesting overflows the host stack and silently kills the
 * process. clang's musttail guarantees the tail call (a jump); without it (or on
 * a non-clang compiler) we fall back to call+return, which only stays bounded if
 * the compiler happens to do sibling-call optimization. All lifted SPU functions
 * share the signature `void f(spu_context*)`, so the tail call is always valid. */
#if defined(__clang__)
#  define SPU_TAILCALL(call) __attribute__((musttail)) return call
#else
#  define SPU_TAILCALL(call) do { call; return; } while (0)
#endif

/* Indirect branch dispatch (bi/bisl/bid...): PC has been set to the target
 * local-store address; the runtime resolves it to the matching lifted
 * function and continues execution. Implemented by the SPU program glue. */
void spu_indirect_branch(spu_context* ctx);

/* stop/stopd hook (YDKJ): the runtime inspects the stop code, may deliver a
 * stop-and-signal event to the PPU (SPURS bring-up handshake), and longjmps the
 * host SPU thread back to spu_run_with_halt so the job does not spin past the
 * stop. Complements ctx->status; harmless where the runtime handles status. */
void spu_stop(spu_context* ctx);
/* Lower-level longjmp helper: abort the host SPU thread back to spu_run_with_halt
 * (used for the infinite no-op self-loop / idle halt idiom). */
void spu_halt(spu_context* ctx);

/* Channel access -- implemented by the runtime (MFC DMA engine, mailboxes,
 * signal notification, decrementer). See runtime/spu/spu_dma.h. */
u128 spu_rdch(spu_context* ctx, uint32_t channel);
uint32_t spu_rchcnt(spu_context* ctx, uint32_t channel);
void spu_wrch(spu_context* ctx, uint32_t channel, u128 value);

/* Execution trace (only emitted when the lifter was invoked with --trace). */
void spu_trace_init(const char* path);
void spu_trace_pc(spu_context* ctx, uint32_t pc);
void spu_trace_rt(spu_context* ctx, uint32_t rt);

#ifdef __cplusplus
}
#endif


void spu_job_0148C000_spu_func_0148C000(spu_context* ctx);
void spu_job_0148C000_spu_func_0148C018(spu_context* ctx);
void spu_job_0148C000_spu_func_0148C030(spu_context* ctx);
void spu_job_0148C000_spu_func_0148C118(spu_context* ctx);
void spu_job_0148C000_spu_func_0148C15C(spu_context* ctx);
void spu_job_0148C000_spu_func_0148C170(spu_context* ctx);
void spu_job_0148C000_spu_func_0148C190(spu_context* ctx);
void spu_job_0148C000_spu_func_0148C1A0(spu_context* ctx);
void spu_job_0148C000_spu_func_0148C224(spu_context* ctx);
void spu_job_0148C000_spu_func_0148C238(spu_context* ctx);
void spu_job_0148C000_spu_func_0148C248(spu_context* ctx);
void spu_job_0148C000_spu_func_0148C2F8(spu_context* ctx);
void spu_job_0148C000_spu_func_0148C320(spu_context* ctx);
void spu_job_0148C000_spu_func_0148C3C0(spu_context* ctx);
void spu_job_0148C000_spu_func_0148C3F0(spu_context* ctx);
void spu_job_0148C000_spu_func_0148C430(spu_context* ctx);
void spu_job_0148C000_spu_func_0148C470(spu_context* ctx);
void spu_job_0148C000_spu_func_0148C4B0(spu_context* ctx);
void spu_job_0148C000_spu_func_0148C4D0(spu_context* ctx);
void spu_job_0148C000_spu_func_0148C4E4(spu_context* ctx);
void spu_job_0148C000_spu_func_0148C500(spu_context* ctx);
void spu_job_0148C000_spu_func_0148C520(spu_context* ctx);
void spu_job_0148C000_spu_func_0148C534(spu_context* ctx);
void spu_job_0148C000_spu_func_0148C550(spu_context* ctx);
void spu_job_0148C000_spu_func_0148C570(spu_context* ctx);
void spu_job_0148C000_spu_func_0148C584(spu_context* ctx);
void spu_job_0148C000_spu_func_0148C5A8(spu_context* ctx);
void spu_job_0148C000_spu_func_0000C018(spu_context* ctx); /* external */
void spu_job_0148C000_spu_func_0000C030(spu_context* ctx); /* external */
void spu_job_0148C000_spu_func_0000C118(spu_context* ctx); /* external */
void spu_job_0148C000_spu_func_0000C15C(spu_context* ctx); /* external */
void spu_job_0148C000_spu_func_0000C170(spu_context* ctx); /* external */
void spu_job_0148C000_spu_func_0000C190(spu_context* ctx); /* external */
void spu_job_0148C000_spu_func_0000C1A0(spu_context* ctx); /* external */
void spu_job_0148C000_spu_func_0000C224(spu_context* ctx); /* external */
void spu_job_0148C000_spu_func_0000C238(spu_context* ctx); /* external */
void spu_job_0148C000_spu_func_0000C248(spu_context* ctx); /* external */
void spu_job_0148C000_spu_func_0000C2F8(spu_context* ctx); /* external */
void spu_job_0148C000_spu_func_0000C320(spu_context* ctx); /* external */
void spu_job_0148C000_spu_func_0000C3C0(spu_context* ctx); /* external */
void spu_job_0148C000_spu_func_0000C3F0(spu_context* ctx); /* external */
void spu_job_0148C000_spu_func_0000C430(spu_context* ctx); /* external */
void spu_job_0148C000_spu_func_0000C470(spu_context* ctx); /* external */
void spu_job_0148C000_spu_func_0000C4B0(spu_context* ctx); /* external */
void spu_job_0148C000_spu_func_0000C4D0(spu_context* ctx); /* external */
void spu_job_0148C000_spu_func_0000C4E4(spu_context* ctx); /* external */
void spu_job_0148C000_spu_func_0000C500(spu_context* ctx); /* external */
void spu_job_0148C000_spu_func_0000C520(spu_context* ctx); /* external */
void spu_job_0148C000_spu_func_0000C534(spu_context* ctx); /* external */
void spu_job_0148C000_spu_func_0000C550(spu_context* ctx); /* external */
void spu_job_0148C000_spu_func_0000C570(spu_context* ctx); /* external */
void spu_job_0148C000_spu_func_0000C584(spu_context* ctx); /* external */
void spu_job_0148C000_spu_func_0000C5A8(spu_context* ctx); /* external */
void spu_job_0148C000_spu_func_0000C648(spu_context* ctx); /* external */
void spu_job_0148C000_spu_func_0000C688(spu_context* ctx); /* external */
void spu_job_0148C000_spu_func_0000C6D0(spu_context* ctx); /* external */
void spu_job_0148C000_spu_func_00011090(spu_context* ctx); /* external */

/* Runtime glue (runtime/spu/spu_channels.c) */
void spu_register_function(uint32_t addr, void (*fn)(spu_context*));
/* Call once at init to register this image's functions for
 * indirect-branch dispatch (spu_indirect_branch). */
void spu_job_0148C000_spu_recomp_register(void);
