/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#pragma once
#include "../../runtime/spu/spu_context.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Cross-function branch/loop = a guest tail-jump to another lifted function's
 * entry. It MUST reuse the current host frame, not nest one: SPURS task loops
 * iterate via these, so nesting overflows the host stack and silently kills the
 * process. clang's musttail guarantees the tail call (a jump); without it (or on
 * a non-clang compiler) we fall back to call+return, which only stays bounded if
 * the compiler happens to do sibling-call optimization. All lifted SPU functions
 * share the signature `void f(spu_context*)`, so the tail call is always valid. */
#if defined(__clang__)
#  define SPU_TAILCALL(call) __attribute__((musttail)) return call
#else
#  define SPU_TAILCALL(call) do { call; return; } while (0)
#endif

/* Indirect branch dispatch (bi/bisl/bid...): PC has been set to the target
 * local-store address; the runtime resolves it to the matching lifted
 * function and continues execution. Implemented by the SPU program glue. */
void spu_indirect_branch(spu_context* ctx);

/* stop/stopd hook (YDKJ): the runtime inspects the stop code, may deliver a
 * stop-and-signal event to the PPU (SPURS bring-up handshake), and longjmps the
 * host SPU thread back to spu_run_with_halt so the job does not spin past the
 * stop. Complements ctx->status; harmless where the runtime handles status. */
void spu_stop(spu_context* ctx);
/* Lower-level longjmp helper: abort the host SPU thread back to spu_run_with_halt
 * (used for the infinite no-op self-loop / idle halt idiom). */
void spu_halt(spu_context* ctx);

/* Channel access -- implemented by the runtime (MFC DMA engine, mailboxes,
 * signal notification, decrementer). See runtime/spu/spu_dma.h. */
u128 spu_rdch(spu_context* ctx, uint32_t channel);
uint32_t spu_rchcnt(spu_context* ctx, uint32_t channel);
void spu_wrch(spu_context* ctx, uint32_t channel, u128 value);

/* Execution trace (only emitted when the lifter was invoked with --trace). */
void spu_trace_init(const char* path);
void spu_trace_pc(spu_context* ctx, uint32_t pc);
void spu_trace_rt(spu_context* ctx, uint32_t rt);

#ifdef __cplusplus
}
#endif


void spu_job_0144F600_spu_func_0144F600(spu_context* ctx);
void spu_job_0144F600_spu_func_0144F618(spu_context* ctx);
void spu_job_0144F600_spu_func_0144F630(spu_context* ctx);
void spu_job_0144F600_spu_func_0144F648(spu_context* ctx);
void spu_job_0144F600_spu_func_0144F658(spu_context* ctx);
void spu_job_0144F600_spu_func_0144F6C0(spu_context* ctx);
void spu_job_0144F600_spu_func_0144F6E8(spu_context* ctx);
void spu_job_0144F600_spu_func_0144F724(spu_context* ctx);
void spu_job_0144F600_spu_func_0144F740(spu_context* ctx);
void spu_job_0144F600_spu_func_0144F758(spu_context* ctx);
void spu_job_0144F600_spu_func_0144F7B0(spu_context* ctx);
void spu_job_0144F600_spu_func_0144F7E8(spu_context* ctx);
void spu_job_0144F600_spu_func_0144F820(spu_context* ctx);
void spu_job_0144F600_spu_func_0144F828(spu_context* ctx);
void spu_job_0144F600_spu_func_0144F86C(spu_context* ctx);
void spu_job_0144F600_spu_func_0144F898(spu_context* ctx);
void spu_job_0144F600_spu_func_0144F8D8(spu_context* ctx);
void spu_job_0144F600_spu_func_0144F924(spu_context* ctx);
void spu_job_0144F600_spu_func_0144F984(spu_context* ctx);
void spu_job_0144F600_spu_func_0144F98C(spu_context* ctx);
void spu_job_0144F600_spu_func_0144F9C8(spu_context* ctx);
void spu_job_0144F600_spu_func_0144FA00(spu_context* ctx);
void spu_job_0144F600_spu_func_0144FA18(spu_context* ctx);
void spu_job_0144F600_spu_func_0144FB04(spu_context* ctx);
void spu_job_0144F600_spu_func_0144FB14(spu_context* ctx);
void spu_job_0144F600_spu_func_0144FB60(spu_context* ctx);
void spu_job_0144F600_spu_func_0144FBA0(spu_context* ctx);
void spu_job_0144F600_spu_func_0144FBEC(spu_context* ctx);
void spu_job_0144F600_spu_func_0144FC4C(spu_context* ctx);
void spu_job_0144F600_spu_func_0144FC50(spu_context* ctx);
void spu_job_0144F600_spu_func_0144FCE8(spu_context* ctx);
void spu_job_0144F600_spu_func_0144FD34(spu_context* ctx);
void spu_job_0144F600_spu_func_0144FD98(spu_context* ctx);
void spu_job_0144F600_spu_func_0144FE20(spu_context* ctx);
void spu_job_0144F600_spu_func_0144FE6C(spu_context* ctx);
void spu_job_0144F600_spu_func_0144FED0(spu_context* ctx);
void spu_job_0144F600_spu_func_0144FF50(spu_context* ctx);
void spu_job_0144F600_spu_func_0144FF9C(spu_context* ctx);
void spu_job_0144F600_spu_func_0144FFFC(spu_context* ctx);
void spu_job_0144F600_spu_func_01450018(spu_context* ctx);
void spu_job_0144F600_spu_func_01450060(spu_context* ctx);
void spu_job_0144F600_spu_func_014500C0(spu_context* ctx);
void spu_job_0144F600_spu_func_014500F0(spu_context* ctx);
void spu_job_0144F600_spu_func_014500F4(spu_context* ctx);
void spu_job_0144F600_spu_func_01450120(spu_context* ctx);
void spu_job_0144F600_spu_func_014501B0(spu_context* ctx);
void spu_job_0144F600_spu_func_014501D8(spu_context* ctx);
void spu_job_0144F600_spu_func_01450258(spu_context* ctx);
void spu_job_0144F600_spu_func_01450280(spu_context* ctx);
void spu_job_0144F600_spu_func_01450284(spu_context* ctx);
void spu_job_0144F600_spu_func_014502B0(spu_context* ctx);
void spu_job_0144F600_spu_func_014502E8(spu_context* ctx);
void spu_job_0144F600_spu_func_01450330(spu_context* ctx);
void spu_job_0144F600_spu_func_01450338(spu_context* ctx);
void spu_job_0144F600_spu_func_0145040C(spu_context* ctx);
void spu_job_0144F600_spu_func_01450440(spu_context* ctx);
void spu_job_0144F600_spu_func_014504A0(spu_context* ctx);
void spu_job_0144F600_spu_func_014504F8(spu_context* ctx);
void spu_job_0144F600_spu_func_01450540(spu_context* ctx);
void spu_job_0144F600_spu_func_0145058C(spu_context* ctx);
void spu_job_0144F600_spu_func_0000F618(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000F630(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000F648(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000F658(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000F6C0(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000F6E8(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000F724(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000F740(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000F758(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000F7B0(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000F7E8(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000F820(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000F828(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000F86C(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000F898(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000F8D8(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000F924(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000F984(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000F98C(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000F9C8(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000FA00(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000FA18(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000FB04(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000FB14(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000FB60(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000FBA0(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000FBEC(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000FC4C(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000FC50(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000FCE8(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000FD34(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000FD98(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000FE20(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000FE6C(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000FED0(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000FF50(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000FF9C(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0000FFFC(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010018(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010060(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_000100C0(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_000100F0(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_000100F4(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010120(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_000101B0(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_000101D8(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010258(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010280(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010284(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_000102B0(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_000102E8(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010330(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010338(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0001040C(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010440(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_000104A0(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_000104F8(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010540(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0001058C(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_000105EC(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010618(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010624(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010668(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_000106C8(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_000106FC(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010728(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010750(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010778(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_000107A0(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_000107C8(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_000107F0(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010818(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010840(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010874(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010884(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0001088C(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_000108BC(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_000108EC(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0001091C(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0001094C(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0001097C(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_000109AC(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_000109DC(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010A0C(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010AF0(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010B70(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010B74(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010BA0(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010BD8(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010BE8(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010C40(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010C8C(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010CEC(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010CF0(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010D18(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010D60(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010DC0(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010DF4(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010E20(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010E74(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010E84(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010ED0(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010ED4(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010F08(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010F68(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010F8C(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010FD0(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00010FDC(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00011010(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00011050(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00011090(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_000110D8(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0001110C(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00011118(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00011148(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_000111E0(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00011208(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00011238(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00011258(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0001126C(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00011288(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_000112A8(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_000112BC(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_000112D8(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00011370(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00011398(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_000113C4(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_000113F0(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00011430(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00011450(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00011464(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00011498(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_000115C4(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00011624(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00011940(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00011A60(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_00012100(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0001C2E8(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0001C2F0(spu_context* ctx); /* external */
void spu_job_0144F600_spu_func_0001D2A0(spu_context* ctx); /* external */

/* Runtime glue (runtime/spu/spu_channels.c) */
void spu_register_function(uint32_t addr, void (*fn)(spu_context*));
/* Call once at init to register this image's functions for
 * indirect-branch dispatch (spu_indirect_branch). */
void spu_job_0144F600_spu_recomp_register(void);
