/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#include "spu_recomp.h"
#include "../../runtime/spu/spu_helpers.h"


void spu_job_01494880_spu_func_01494880(spu_context* ctx) {
        ctx->gpr[2] = spu_ila(0x17AF4);
        ctx->gpr[2] = spu_ila(0x15941);
        ctx->gpr[2] = spu_ila(0x2E4CE);
        ctx->gpr[2] = spu_ila(0x1B6E3);
        ctx->gpr[80] = spu_xori(ctx->gpr[80], 4);
        { ctx->pc = 0x14898; SPU_TAILCALL(spu_job_01494880_spu_func_00014898(ctx)); }
}

void spu_job_01494880_spu_func_01494898(spu_context* ctx) {
        ctx->gpr[80] = spu_xori(ctx->gpr[80], 4);
        { ctx->pc = 0x148B0; SPU_TAILCALL(spu_job_01494880_spu_func_000148B0(ctx)); }
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
}

void spu_job_01494880_spu_func_014948B0(spu_context* ctx) {
        ctx->gpr[2] = spu_ori(ctx->gpr[3], 0);
        ctx->gpr[3] = spu_ai(ctx->gpr[4], 48);
        ctx->gpr[4] = spu_ls_read128(ctx, ctx->gpr[2]._u32[0] + 0x20);
        ctx->gpr[4] = spu_rotqby(ctx->gpr[4], ctx->gpr[2]);
        { ctx->pc = 0x168E8; SPU_TAILCALL(spu_job_01494880_spu_func_000168E8(ctx)); }
        /* nop */;
        ctx->gpr[8] = spu_ila(0x50);
        ctx->gpr[79] = spu_link(0x14948D0); spu_host_call_push(ctx, 0x14948D0); spu_job_01494880_spu_func_000148D0(ctx); spu_host_call_pop(ctx);
        { ctx->pc = 0x14948D0; SPU_TAILCALL(spu_job_01494880_spu_func_014948D0(ctx)); }
}

void spu_job_01494880_spu_func_014948D0(spu_context* ctx) {
        ctx->gpr[11] = spu_ori(ctx->gpr[3], 0);
        ctx->gpr[3] = spu_fsmbi(0x0);
        ctx->gpr[79] = spu_sf(ctx->gpr[8], ctx->gpr[79]);
        ctx->gpr[2] = spu_fceq(ctx->gpr[7], ctx->gpr[3]);
        if (ctx->gpr[2]._u32[0] != 0) { ctx->pc = 0x149B0; SPU_TAILCALL(spu_job_01494880_spu_func_000149B0(ctx)); }
        ctx->gpr[23] = spu_ilhu(0x3F80);
        ctx->gpr[22] = spu_fceq(ctx->gpr[7], ctx->gpr[23]);
        if (ctx->gpr[22]._u32[0] == 0) { ctx->pc = 0x14970; SPU_TAILCALL(spu_job_01494880_spu_func_00014970(ctx)); }
        ctx->gpr[32] = spu_ceq(ctx->gpr[11], ctx->gpr[5]);
        ctx->gpr[31] = spu_ceq(ctx->gpr[4], ctx->gpr[6]);
        ctx->gpr[30] = spu_nor(ctx->gpr[32], ctx->gpr[32]);
        ctx->gpr[29] = spu_nor(ctx->gpr[31], ctx->gpr[31]);
        ctx->gpr[27] = spu_sfi(ctx->gpr[30], 0);
        ctx->gpr[28] = spu_sfi(ctx->gpr[29], 0);
        ctx->gpr[26] = spu_or(ctx->gpr[27], ctx->gpr[28]);
        ctx->gpr[25] = spu_ceqbi(ctx->gpr[26], 0);
        ctx->gpr[24] = spu_xsbh(ctx->gpr[25]);
        if (ctx->gpr[24]._u16[1] != 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        ctx->gpr[34] = spu_shli(ctx->gpr[4], 10);
        /* branch hint (ignored) */;
        ctx->gpr[4] = spu_shli(ctx->gpr[6], 10);
        ctx->gpr[13] = spu_a(ctx->gpr[11], ctx->gpr[34]);
        ctx->gpr[12] = spu_a(ctx->gpr[5], ctx->gpr[4]);
        ctx->gpr[14] = spu_andi(ctx->gpr[13], 15);
        ctx->gpr[7] = spu_andi(ctx->gpr[12], 15);
        ctx->gpr[33] = spu_or(ctx->gpr[7], ctx->gpr[14]);
        if (ctx->gpr[33]._u32[0] != 0) { ctx->pc = 0x149F8; SPU_TAILCALL(spu_job_01494880_spu_func_000149F8(ctx)); }
        ctx->gpr[3] = spu_il(0);
        ctx->gpr[4] = spu_il(1024);
        { ctx->pc = 0x1494944; SPU_TAILCALL(spu_job_01494880_spu_func_01494944(ctx)); }
}

void spu_job_01494880_spu_func_01494944(spu_context* ctx) {
        ctx->gpr[36] = spu_ls_read128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[12]._u32[0]);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[13]._u32[0], ctx->gpr[36]);
        ctx->gpr[3] = spu_ai(ctx->gpr[3], 16);
        ctx->gpr[35] = spu_ceq(ctx->gpr[3], ctx->gpr[4]);
        if (ctx->gpr[35]._u32[0] != 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        ctx->gpr[36] = spu_ls_read128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[12]._u32[0]);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[13]._u32[0], ctx->gpr[36]);
        ctx->gpr[3] = spu_ai(ctx->gpr[3], 16);
        ctx->gpr[35] = spu_ceq(ctx->gpr[3], ctx->gpr[4]);
        if (ctx->gpr[35]._u32[0] == 0) { ctx->pc = 0x14944; SPU_TAILCALL(spu_job_01494880_spu_func_00014944(ctx)); }
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
}

void spu_job_01494880_spu_func_01494970(spu_context* ctx) {
        ctx->gpr[9] = spu_shli(ctx->gpr[4], 10);
        /* branch hint (ignored) */;
        ctx->gpr[13] = spu_shli(ctx->gpr[6], 10);
        ctx->gpr[8] = spu_fsmbi(0x0);
        ctx->gpr[10] = spu_ila(0x10203);
        ctx->gpr[3] = spu_il(1024);
        ctx->gpr[11] = spu_a(ctx->gpr[9], ctx->gpr[11]);
        ctx->gpr[7] = spu_shufb(ctx->gpr[7], ctx->gpr[7], ctx->gpr[10]);
        ctx->gpr[4] = spu_a(ctx->gpr[13], ctx->gpr[5]);
        { ctx->pc = 0x1494994; SPU_TAILCALL(spu_job_01494880_spu_func_01494994(ctx)); }
}

void spu_job_01494880_spu_func_01494994(spu_context* ctx) {
        ctx->gpr[14] = spu_ls_read128(ctx, ctx->gpr[8]._u32[0] + ctx->gpr[4]._u32[0]);
        ctx->gpr[6] = spu_fm(ctx->gpr[14], ctx->gpr[7]);
        spu_ls_write128(ctx, ctx->gpr[8]._u32[0] + ctx->gpr[11]._u32[0], ctx->gpr[6]);
        ctx->gpr[8] = spu_ai(ctx->gpr[8], 16);
        ctx->gpr[5] = spu_ceq(ctx->gpr[8], ctx->gpr[3]);
        if (ctx->gpr[5]._u32[0] == 0) { ctx->pc = 0x14994; SPU_TAILCALL(spu_job_01494880_spu_func_00014994(ctx)); }
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
}

void spu_job_01494880_spu_func_014949B0(spu_context* ctx) {
        ctx->gpr[7] = spu_shli(ctx->gpr[4], 10);
        /* branch hint (ignored) */;
        ctx->gpr[6] = spu_il(0);
        ctx->gpr[5] = spu_a(ctx->gpr[11], ctx->gpr[7]);
        ctx->gpr[2] = spu_andi(ctx->gpr[5], 15);
        if (ctx->gpr[2]._u32[0] != 0) { ctx->pc = 0x14B00; SPU_TAILCALL(spu_job_01494880_spu_func_00014B00(ctx)); }
        ctx->gpr[3] = spu_il(0);
        ctx->gpr[4] = spu_il(1024);
        { ctx->pc = 0x14949D0; SPU_TAILCALL(spu_job_01494880_spu_func_014949D0(ctx)); }
}

void spu_job_01494880_spu_func_014949D0(spu_context* ctx) {
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[5]._u32[0], ctx->gpr[6]);
        ctx->gpr[3] = spu_ai(ctx->gpr[3], 16);
        ctx->gpr[7] = spu_ceq(ctx->gpr[3], ctx->gpr[4]);
        if (ctx->gpr[7]._u32[0] != 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[5]._u32[0], ctx->gpr[6]);
        ctx->gpr[3] = spu_ai(ctx->gpr[3], 16);
        ctx->gpr[7] = spu_ceq(ctx->gpr[3], ctx->gpr[4]);
        if (ctx->gpr[7]._u32[0] == 0) { ctx->pc = 0x149D0; SPU_TAILCALL(spu_job_01494880_spu_func_000149D0(ctx)); }
        /* nop */;
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
}

void spu_job_01494880_spu_func_014949F8(spu_context* ctx) {
        ctx->gpr[57] = spu_sf(ctx->gpr[14], ctx->gpr[7]);
        ctx->gpr[53] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + ctx->gpr[4]._u32[0]);
        ctx->gpr[61] = spu_ila(0xB560);
        ctx->gpr[54] = spu_ls_read128(ctx, ctx->gpr[12]._u32[0] + 0x10);
        ctx->gpr[60] = spu_shli(ctx->gpr[57], 4);
        ctx->gpr[51] = spu_fsmbi(0xFFFF);
        ctx->gpr[63] = spu_il(1024);
        ctx->gpr[41] = spu_ls_read128(ctx, ctx->gpr[13]._u32[0] + 0x0);
        ctx->gpr[59] = spu_a(ctx->gpr[61], ctx->gpr[79]);
        ctx->gpr[58] = spu_a(ctx->gpr[14], ctx->gpr[63]);
        ctx->gpr[55] = spu_cgti(ctx->gpr[57], 0);
        ctx->gpr[52] = spu_ls_read128(ctx, ctx->gpr[60]._u32[0] + ctx->gpr[59]._u32[0]);
        ctx->gpr[56] = spu_sfi(ctx->gpr[58], 0);
        ctx->gpr[46] = spu_rotqmby(ctx->gpr[53], ctx->gpr[57]);
        ctx->gpr[37] = spu_clgti(ctx->gpr[58], 15);
        /* nop */;
        ctx->gpr[5] = spu_sfi(ctx->gpr[14], 16);
        ctx->gpr[48] = spu_rotqmby(ctx->gpr[51], ctx->gpr[56]);
        ctx->gpr[50] = spu_ceqi(ctx->gpr[55], 0);
        ctx->gpr[49] = spu_ceqi(ctx->gpr[37], 0);
        ctx->gpr[42] = spu_shlqby(ctx->gpr[51], ctx->gpr[5]);
        ctx->gpr[47] = spu_shufb(ctx->gpr[53], ctx->gpr[54], ctx->gpr[52]);
        ctx->gpr[45] = spu_fsm(ctx->gpr[50]);
        ctx->gpr[43] = spu_fsm(ctx->gpr[49]);
        ctx->gpr[44] = spu_or(ctx->gpr[42], ctx->gpr[48]);
        ctx->gpr[39] = spu_selb(ctx->gpr[47], ctx->gpr[46], ctx->gpr[45]);
        ctx->gpr[40] = spu_selb(ctx->gpr[42], ctx->gpr[44], ctx->gpr[43]);
        ctx->gpr[38] = spu_selb(ctx->gpr[39], ctx->gpr[41], ctx->gpr[40]);
        spu_ls_write128(ctx, ctx->gpr[13]._u32[0] + 0x0, ctx->gpr[38]);
        if (ctx->gpr[37]._u32[0] == 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        ctx->gpr[7] = spu_a(ctx->gpr[12], ctx->gpr[5]);
        /* branch hint (ignored) */;
        ctx->gpr[67] = spu_ila(0xB560);
        ctx->gpr[69] = spu_andi(ctx->gpr[7], 15);
        ctx->gpr[68] = spu_il(1024);
        ctx->gpr[66] = spu_shli(ctx->gpr[69], 4);
        ctx->gpr[65] = spu_a(ctx->gpr[67], ctx->gpr[79]);
        ctx->gpr[8] = spu_sf(ctx->gpr[5], ctx->gpr[68]);
        ctx->gpr[11] = spu_a(ctx->gpr[13], ctx->gpr[5]);
        /* nop */;
        ctx->gpr[64] = spu_clgti(ctx->gpr[8], 15);
        ctx->gpr[9] = spu_ls_read128(ctx, ctx->gpr[66]._u32[0] + ctx->gpr[65]._u32[0]);
        /* nop */;
        if (ctx->gpr[64]._u32[0] == 0) { ctx->pc = 0x14AD0; SPU_TAILCALL(spu_job_01494880_spu_func_00014AD0(ctx)); }
        { ctx->pc = 0x1494AA8; SPU_TAILCALL(spu_job_01494880_spu_func_01494AA8(ctx)); }
}

void spu_job_01494880_spu_func_01494AA8(spu_context* ctx) {
        ctx->gpr[8] = spu_ai(ctx->gpr[8], -16);
        ctx->gpr[72] = spu_ls_read128(ctx, ctx->gpr[7]._u32[0] + 0x0);
        ctx->gpr[7] = spu_ai(ctx->gpr[7], 16);
        ctx->gpr[70] = spu_clgti(ctx->gpr[8], 15);
        ctx->gpr[73] = spu_ls_read128(ctx, ctx->gpr[7]._u32[0] + 0x0);
        ctx->gpr[71] = spu_shufb(ctx->gpr[72], ctx->gpr[73], ctx->gpr[9]);
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[11]._u32[0] + 0x0, ctx->gpr[71]);
        ctx->gpr[11] = spu_ai(ctx->gpr[11], 16);
        if (ctx->gpr[70]._u32[0] != 0) { ctx->pc = 0x14AA8; SPU_TAILCALL(spu_job_01494880_spu_func_00014AA8(ctx)); }
        { ctx->pc = 0x1494AD0; SPU_TAILCALL(spu_job_01494880_spu_func_01494AD0(ctx)); }
}

void spu_job_01494880_spu_func_01494AD0(spu_context* ctx) {
        /* branch hint (ignored) */;
        if (ctx->gpr[8]._u32[0] == 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        ctx->gpr[79] = spu_sfi(ctx->gpr[8], 0);
        ctx->gpr[3] = spu_ls_read128(ctx, ctx->gpr[7]._u32[0] + 0x10);
        ctx->gpr[2] = spu_il(-1);
        ctx->gpr[78] = spu_ls_read128(ctx, ctx->gpr[7]._u32[0] + 0x0);
        ctx->gpr[77] = spu_ls_read128(ctx, ctx->gpr[11]._u32[0] + 0x0);
        ctx->gpr[76] = spu_rotqmby(ctx->gpr[2], ctx->gpr[79]);
        ctx->gpr[75] = spu_shufb(ctx->gpr[78], ctx->gpr[3], ctx->gpr[9]);
        ctx->gpr[74] = spu_selb(ctx->gpr[75], ctx->gpr[77], ctx->gpr[76]);
        spu_ls_write128(ctx, ctx->gpr[11]._u32[0] + 0x0, ctx->gpr[74]);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
}

void spu_job_01494880_spu_func_01494B00(spu_context* ctx) {
        ctx->gpr[4] = spu_il(1024);
        /* branch hint (ignored) */;
        ctx->gpr[8] = spu_sfi(ctx->gpr[2], 16);
        ctx->gpr[12] = spu_fsmbi(0xFFFF);
        ctx->gpr[9] = spu_a(ctx->gpr[2], ctx->gpr[4]);
        ctx->gpr[13] = spu_clgti(ctx->gpr[9], 15);
        ctx->gpr[10] = spu_shlqby(ctx->gpr[12], ctx->gpr[8]);
        if (ctx->gpr[13]._u32[0] == 0) { ctx->pc = 0x14B7C; SPU_TAILCALL(spu_job_01494880_spu_func_00014B7C(ctx)); }
        ctx->gpr[4] = spu_sf(ctx->gpr[8], ctx->gpr[4]);
        ctx->gpr[16] = spu_ls_read128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[7]._u32[0]);
        ctx->gpr[5] = spu_a(ctx->gpr[5], ctx->gpr[8]);
        ctx->gpr[12] = spu_clgti(ctx->gpr[4], 15);
        ctx->gpr[15] = spu_and(ctx->gpr[16], ctx->gpr[10]);
        spu_ls_write128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[7]._u32[0], ctx->gpr[15]);
        /* nop */;
        if (ctx->gpr[12]._u32[0] == 0) { ctx->pc = 0x14B54; SPU_TAILCALL(spu_job_01494880_spu_func_00014B54(ctx)); }
        { ctx->pc = 0x1494B40; SPU_TAILCALL(spu_job_01494880_spu_func_01494B40(ctx)); }
}

void spu_job_01494880_spu_func_01494B40(spu_context* ctx) {
        ctx->gpr[4] = spu_ai(ctx->gpr[4], -16);
        spu_ls_write128(ctx, ctx->gpr[5]._u32[0] + 0x0, ctx->gpr[6]);
        ctx->gpr[5] = spu_ai(ctx->gpr[5], 16);
        ctx->gpr[11] = spu_clgti(ctx->gpr[4], 15);
        if (ctx->gpr[11]._u32[0] != 0) { ctx->pc = 0x14B40; SPU_TAILCALL(spu_job_01494880_spu_func_00014B40(ctx)); }
        { ctx->pc = 0x1494B54; SPU_TAILCALL(spu_job_01494880_spu_func_01494B54(ctx)); }
}

void spu_job_01494880_spu_func_01494B54(spu_context* ctx) {
        /* branch hint (ignored) */;
        /* nop */;
        if (ctx->gpr[4]._u32[0] == 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        ctx->gpr[21] = spu_sfi(ctx->gpr[4], 0);
        ctx->gpr[18] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + 0x0);
        ctx->gpr[20] = spu_il(-1);
        ctx->gpr[19] = spu_rotqmby(ctx->gpr[20], ctx->gpr[21]);
        ctx->gpr[17] = spu_and(ctx->gpr[18], ctx->gpr[19]);
        spu_ls_write128(ctx, ctx->gpr[5]._u32[0] + 0x0, ctx->gpr[17]);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
}

void spu_job_01494880_spu_func_01494B7C(spu_context* ctx) {
        /* branch hint (ignored) */;
        ctx->gpr[14] = spu_sfi(ctx->gpr[9], 0);
        ctx->gpr[5] = spu_ls_read128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[7]._u32[0]);
        /* nop */;
        /* nop */;
        /* nop */;
        ctx->gpr[9] = spu_rotqmby(ctx->gpr[12], ctx->gpr[14]);
        ctx->gpr[6] = spu_or(ctx->gpr[10], ctx->gpr[9]);
        ctx->gpr[4] = spu_and(ctx->gpr[5], ctx->gpr[6]);
        spu_ls_write128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[7]._u32[0], ctx->gpr[4]);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        ctx->gpr[14] = spu_ilhu(0x41A0);
        ctx->gpr[33] = spu_shlqbyi(ctx->gpr[3], 0);
        ctx->gpr[9] = spu_ilhu(0x3F00);
        ctx->gpr[10] = spu_shlqbyi(ctx->gpr[5], 0);
        ctx->gpr[15] = spu_fcgt(ctx->gpr[14], ctx->gpr[5]);
        ctx->gpr[22] = spu_shlqbyi(ctx->gpr[6], 0);
        ctx->gpr[9] = spu_fms(ctx->gpr[6], ctx->gpr[9], ctx->gpr[14]);
        ctx->gpr[35] = spu_shlqbyi(ctx->gpr[4], 0);
        ctx->gpr[11] = spu_sfi(ctx->gpr[15], 0);
        ctx->gpr[34] = spu_shlqbyi(ctx->gpr[7], 0);
        ctx->gpr[21] = spu_ilhu(0x42FB);
        ctx->gpr[21] = spu_iohl(ctx->gpr[21], 0x53D0);
        ctx->gpr[3] = spu_fcgt(ctx->gpr[9], ctx->gpr[5]);
        ctx->gpr[13] = spu_fcgt(ctx->gpr[14], ctx->gpr[9]);
        ctx->gpr[5] = spu_ceqi(ctx->gpr[3], 0);
        ctx->gpr[12] = spu_sfi(ctx->gpr[13], 0);
        ctx->gpr[6] = spu_selb(ctx->gpr[11], ctx->gpr[12], ctx->gpr[5]);
        ctx->gpr[5] = spu_shlqbyi(ctx->gpr[8], 0);
        ctx->gpr[4] = spu_ceqbi(ctx->gpr[6], 0);
        ctx->gpr[2] = spu_xsbh(ctx->gpr[4]);
        if (ctx->gpr[2]._u16[1] == 0) { ctx->pc = 0x14C10; SPU_TAILCALL(spu_job_01494880_spu_func_00014C10(ctx)); }
        ctx->gpr[7] = spu_ilhu(0x40C9);
        ctx->gpr[3] = spu_selb(ctx->gpr[9], ctx->gpr[10], ctx->gpr[3]);
        ctx->gpr[7] = spu_iohl(ctx->gpr[7], 0xFDA);
        ctx->gpr[21] = spu_fm(ctx->gpr[3], ctx->gpr[7]);
        /* nop */;
        { ctx->pc = 0x1494C10; SPU_TAILCALL(spu_job_01494880_spu_func_01494C10(ctx)); }
}

void spu_job_01494880_spu_func_01494C10(spu_context* ctx) {
        ctx->gpr[14] = spu_ilhu(0x3727);
        ctx->gpr[24] = spu_frest(ctx->gpr[22]);
        ctx->gpr[72] = spu_ilhu(0x7F80);
        ctx->gpr[14] = spu_iohl(ctx->gpr[14], 0xC5AC);
        ctx->gpr[65] = spu_ilhu(0x3F00);
        ctx->gpr[79] = spu_fcgt(ctx->gpr[14], ctx->gpr[5]);
        ctx->gpr[77] = spu_ilhu(0x3F35);
        ctx->gpr[78] = spu_selb(ctx->gpr[5], ctx->gpr[14], ctx->gpr[79]);
        ctx->gpr[77] = spu_iohl(ctx->gpr[77], 0x4F3);
        ctx->gpr[52] = spu_selb(ctx->gpr[78], ctx->gpr[65], ctx->gpr[72]);
        ctx->gpr[65] = spu_ilhu(0x3F80);
        ctx->gpr[12] = spu_fa(ctx->gpr[52], ctx->gpr[52]);
        ctx->gpr[64] = spu_fcgt(ctx->gpr[77], ctx->gpr[52]);
        ctx->gpr[76] = spu_ilhu(0x3F20);
        ctx->gpr[36] = spu_ilhu(0x3FA0);
        ctx->gpr[58] = spu_fcgt(ctx->gpr[77], ctx->gpr[76]);
        ctx->gpr[30] = spu_ilhu(0x3F80);
        ctx->gpr[75] = spu_selb(ctx->gpr[52], ctx->gpr[12], ctx->gpr[64]);
        ctx->gpr[54] = spu_selb(ctx->gpr[76], ctx->gpr[36], ctx->gpr[58]);
        ctx->gpr[9] = spu_fa(ctx->gpr[75], ctx->gpr[65]);
        ctx->gpr[7] = spu_fs(ctx->gpr[75], ctx->gpr[65]);
        ctx->gpr[10] = spu_fa(ctx->gpr[54], ctx->gpr[65]);
        ctx->gpr[25] = spu_fs(ctx->gpr[54], ctx->gpr[65]);
        ctx->gpr[54] = spu_ori(ctx->gpr[30], 1);
        ctx->gpr[53] = spu_ilhu(0x3E99);
        /* nop */;
        ctx->gpr[56] = spu_ilhu(0x3ECC);
        ctx->gpr[74] = spu_frest(ctx->gpr[9]);
        ctx->gpr[53] = spu_iohl(ctx->gpr[53], 0x214);
        ctx->gpr[73] = spu_frest(ctx->gpr[10]);
        ctx->gpr[56] = spu_iohl(ctx->gpr[56], 0xAE10);
        ctx->gpr[69] = spu_fi(ctx->gpr[9], ctx->gpr[74]);
        ctx->gpr[49] = spu_ilhu(0x3F2A);
        ctx->gpr[55] = spu_fi(ctx->gpr[10], ctx->gpr[73]);
        ctx->gpr[49] = spu_iohl(ctx->gpr[49], 0xAABF);
        ctx->gpr[71] = spu_and(ctx->gpr[78], ctx->gpr[72]);
        ctx->gpr[40] = spu_ilhu(0x3EDE);
        ctx->gpr[70] = spu_rotmi(ctx->gpr[71], -23);
        ctx->gpr[67] = spu_fnms(ctx->gpr[9], ctx->gpr[69], ctx->gpr[54]);
        ctx->gpr[68] = spu_fm(ctx->gpr[7], ctx->gpr[69]);
        ctx->gpr[61] = spu_fnms(ctx->gpr[10], ctx->gpr[55], ctx->gpr[54]);
        ctx->gpr[62] = spu_fm(ctx->gpr[25], ctx->gpr[55]);
        ctx->gpr[66] = spu_ai(ctx->gpr[70], -127);
        ctx->gpr[63] = spu_ai(ctx->gpr[70], -126);
        ctx->gpr[40] = spu_iohl(ctx->gpr[40], 0x5BD8);
        ctx->gpr[18] = spu_fma(ctx->gpr[67], ctx->gpr[68], ctx->gpr[68]);
        ctx->gpr[60] = spu_selb(ctx->gpr[63], ctx->gpr[66], ctx->gpr[64]);
        ctx->gpr[37] = spu_fma(ctx->gpr[61], ctx->gpr[62], ctx->gpr[62]);
        ctx->gpr[28] = spu_csflt(ctx->gpr[60], 155);
        ctx->gpr[47] = spu_ilhu(0x3E9A);
        ctx->gpr[38] = spu_ilhu(0x33A1);
        ctx->gpr[46] = spu_fm(ctx->gpr[18], ctx->gpr[18]);
        ctx->gpr[47] = spu_iohl(ctx->gpr[47], 0x2097);
        ctx->gpr[44] = spu_fm(ctx->gpr[37], ctx->gpr[37]);
        ctx->gpr[38] = spu_iohl(ctx->gpr[38], 0x3EF3);
        ctx->gpr[5] = spu_fm(ctx->gpr[28], ctx->gpr[47]);
        ctx->gpr[57] = spu_il(4);
        ctx->gpr[50] = spu_fma(ctx->gpr[46], ctx->gpr[53], ctx->gpr[56]);
        ctx->gpr[59] = spu_il(3);
        ctx->gpr[48] = spu_fma(ctx->gpr[44], ctx->gpr[53], ctx->gpr[56]);
        ctx->gpr[39] = spu_ilhu(0x3FB8);
        ctx->gpr[16] = spu_ilhu(0x32A9);
        ctx->gpr[51] = spu_selb(ctx->gpr[57], ctx->gpr[59], ctx->gpr[58]);
        ctx->gpr[45] = spu_fma(ctx->gpr[50], ctx->gpr[46], ctx->gpr[49]);
        ctx->gpr[39] = spu_iohl(ctx->gpr[39], 0xAA3B);
        ctx->gpr[43] = spu_fma(ctx->gpr[48], ctx->gpr[44], ctx->gpr[49]);
        ctx->gpr[16] = spu_iohl(ctx->gpr[16], 0x3728);
        ctx->gpr[42] = spu_csflt(ctx->gpr[51], 155);
        ctx->gpr[8] = spu_ilhu(0x3FB8);
        ctx->gpr[41] = spu_fms(ctx->gpr[45], ctx->gpr[46], ctx->gpr[7]);
        ctx->gpr[23] = spu_fma(ctx->gpr[7], ctx->gpr[40], ctx->gpr[5]);
        ctx->gpr[32] = spu_fms(ctx->gpr[43], ctx->gpr[44], ctx->gpr[25]);
        ctx->gpr[27] = spu_ilhu(0x32A5);
        ctx->gpr[8] = spu_iohl(ctx->gpr[8], 0xAA3A);
        ctx->gpr[27] = spu_iohl(ctx->gpr[27], 0x705F);
        ctx->gpr[17] = spu_fm(ctx->gpr[18], ctx->gpr[41]);
        ctx->gpr[15] = spu_fma(ctx->gpr[25], ctx->gpr[8], ctx->gpr[42]);
        ctx->gpr[31] = spu_fm(ctx->gpr[37], ctx->gpr[32]);
        ctx->gpr[37] = spu_il(0);
        ctx->gpr[12] = spu_ilhu(0x3F00);
        ctx->gpr[79] = spu_fceq(ctx->gpr[78], ctx->gpr[37]);
        ctx->gpr[29] = spu_fm(ctx->gpr[17], ctx->gpr[40]);
        ctx->gpr[32] = spu_ilhu(0x4120);
        ctx->gpr[26] = spu_fm(ctx->gpr[31], ctx->gpr[39]);
        ctx->gpr[78] = spu_fceq(ctx->gpr[32], ctx->gpr[37]);
        ctx->gpr[31] = spu_fsmbi(0x0);
        ctx->gpr[75] = spu_ilhu(0x3F7F);
        ctx->gpr[6] = spu_fi(ctx->gpr[22], ctx->gpr[24]);
        ctx->gpr[75] = spu_iohl(ctx->gpr[75], 0xFFFF);
        ctx->gpr[4] = spu_fma(ctx->gpr[28], ctx->gpr[38], ctx->gpr[29]);
        ctx->gpr[19] = spu_fma(ctx->gpr[25], ctx->gpr[27], ctx->gpr[26]);
        ctx->gpr[59] = spu_ilhu(0x3F31);
        ctx->gpr[53] = spu_ilhu(0xB914);
        ctx->gpr[59] = spu_iohl(ctx->gpr[59], 0x7217);
        ctx->gpr[3] = spu_fm(ctx->gpr[21], ctx->gpr[6]);
        ctx->gpr[20] = spu_fma(ctx->gpr[7], ctx->gpr[16], ctx->gpr[4]);
        ctx->gpr[2] = spu_fa(ctx->gpr[15], ctx->gpr[19]);
        ctx->gpr[56] = spu_ilhu(0x3AAE);
        ctx->gpr[50] = spu_ilhu(0xBE2A);
        ctx->gpr[51] = spu_ilhu(0x3EFF);
        ctx->gpr[13] = spu_fnms(ctx->gpr[3], ctx->gpr[22], ctx->gpr[21]);
        ctx->gpr[77] = spu_fa(ctx->gpr[23], ctx->gpr[20]);
        ctx->gpr[36] = spu_selb(ctx->gpr[2], ctx->gpr[78], ctx->gpr[78]);
        ctx->gpr[11] = spu_ilhu(0x3F22);
        ctx->gpr[53] = spu_iohl(ctx->gpr[53], 0x2E40);
        ctx->gpr[56] = spu_iohl(ctx->gpr[56], 0x4F6F);
        ctx->gpr[62] = spu_fma(ctx->gpr[13], ctx->gpr[6], ctx->gpr[3]);
        ctx->gpr[52] = spu_selb(ctx->gpr[77], ctx->gpr[79], ctx->gpr[79]);
        ctx->gpr[50] = spu_iohl(ctx->gpr[50], 0xAA4F);
        ctx->gpr[70] = spu_fm(ctx->gpr[52], ctx->gpr[12]);
        ctx->gpr[51] = spu_iohl(ctx->gpr[51], 0xFFFD);
        ctx->gpr[11] = spu_iohl(ctx->gpr[11], 0xF983);
        ctx->gpr[61] = spu_ori(ctx->gpr[62], 0);
        ctx->gpr[72] = spu_fm(ctx->gpr[62], ctx->gpr[11]);
        ctx->gpr[69] = spu_fm(ctx->gpr[61], ctx->gpr[11]);
        ctx->gpr[49] = spu_fm(ctx->gpr[70], ctx->gpr[36]);
        ctx->gpr[46] = spu_ilhu(0xBC08);
        ctx->gpr[44] = spu_ilhu(0xBF80);
        ctx->gpr[46] = spu_iohl(ctx->gpr[46], 0x26D);
        ctx->gpr[36] = spu_ilhu(0x8000);
        ctx->gpr[52] = spu_ilhu(0x3F00);
        ctx->gpr[76] = spu_rotmai(ctx->gpr[49], -31);
        ctx->gpr[73] = spu_selb(ctx->gpr[52], ctx->gpr[72], ctx->gpr[36]);
        ctx->gpr[71] = spu_selb(ctx->gpr[52], ctx->gpr[69], ctx->gpr[36]);
        ctx->gpr[38] = spu_ilhu(0x3D2A);
        ctx->gpr[74] = spu_andc(ctx->gpr[75], ctx->gpr[76]);
        ctx->gpr[9] = spu_fa(ctx->gpr[72], ctx->gpr[73]);
        ctx->gpr[55] = spu_fa(ctx->gpr[49], ctx->gpr[74]);
        ctx->gpr[10] = spu_fa(ctx->gpr[69], ctx->gpr[71]);
        ctx->gpr[38] = spu_iohl(ctx->gpr[38], 0xA0E5);
        ctx->gpr[57] = spu_ilhu(0x4300);
        ctx->gpr[60] = spu_ilhu(0x3FC9);
        ctx->gpr[57] = spu_iohl(ctx->gpr[57], 0xFFFF);
        ctx->gpr[68] = spu_cflts(ctx->gpr[55], 173);
        ctx->gpr[69] = spu_cflts(ctx->gpr[10], 173);
        ctx->gpr[55] = spu_cflts(ctx->gpr[9], 173);
        ctx->gpr[22] = spu_ilhu(0x7FFF);
        ctx->gpr[60] = spu_iohl(ctx->gpr[60], 0xFD9);
        ctx->gpr[19] = spu_fcgt(ctx->gpr[49], ctx->gpr[57]);
        ctx->gpr[23] = spu_ilhu(0x8000);
        ctx->gpr[64] = spu_csflt(ctx->gpr[68], 155);
        ctx->gpr[67] = spu_ai(ctx->gpr[68], 126);
        ctx->gpr[17] = spu_csflt(ctx->gpr[55], 155);
        ctx->gpr[63] = spu_shli(ctx->gpr[67], 23);
        ctx->gpr[18] = spu_csflt(ctx->gpr[69], 155);
        ctx->gpr[22] = spu_iohl(ctx->gpr[22], 0xFFFF);
        ctx->gpr[66] = spu_andc(ctx->gpr[70], ctx->gpr[23]);
        ctx->gpr[58] = spu_fs(ctx->gpr[64], ctx->gpr[49]);
        ctx->gpr[6] = spu_fa(ctx->gpr[63], ctx->gpr[63]);
        ctx->gpr[40] = spu_fnms(ctx->gpr[17], ctx->gpr[60], ctx->gpr[62]);
        ctx->gpr[39] = spu_ilhu(0x33A2);
        ctx->gpr[41] = spu_fnms(ctx->gpr[18], ctx->gpr[60], ctx->gpr[61]);
        ctx->gpr[47] = spu_cfltu(ctx->gpr[66], 173);
        ctx->gpr[39] = spu_iohl(ctx->gpr[39], 0x2168);
        ctx->gpr[27] = spu_fm(ctx->gpr[58], ctx->gpr[59]);
        ctx->gpr[60] = spu_fnms(ctx->gpr[17], ctx->gpr[39], ctx->gpr[40]);
        ctx->gpr[48] = spu_ilhu(0xC2FC);
        ctx->gpr[57] = spu_fnms(ctx->gpr[18], ctx->gpr[39], ctx->gpr[41]);
        ctx->gpr[21] = spu_fcgt(ctx->gpr[31], ctx->gpr[32]);
        ctx->gpr[20] = spu_fcgt(ctx->gpr[48], ctx->gpr[49]);
        ctx->gpr[45] = spu_fma(ctx->gpr[27], ctx->gpr[53], ctx->gpr[56]);
        ctx->gpr[43] = spu_fma(ctx->gpr[27], ctx->gpr[50], ctx->gpr[51]);
        ctx->gpr[42] = spu_fm(ctx->gpr[27], ctx->gpr[27]);
        ctx->gpr[51] = spu_ilhu(0x4000);
        ctx->gpr[26] = spu_andi(ctx->gpr[47], 1);
        ctx->gpr[66] = spu_fm(ctx->gpr[57], ctx->gpr[57]);
        ctx->gpr[29] = spu_fma(ctx->gpr[27], ctx->gpr[45], ctx->gpr[46]);
        ctx->gpr[28] = spu_fma(ctx->gpr[27], ctx->gpr[43], ctx->gpr[44]);
        ctx->gpr[8] = spu_fm(ctx->gpr[42], ctx->gpr[42]);
        ctx->gpr[68] = spu_fm(ctx->gpr[60], ctx->gpr[60]);
        ctx->gpr[25] = spu_clgt(ctx->gpr[26], ctx->gpr[37]);
        ctx->gpr[13] = spu_ilhu(0xB94C);
        ctx->gpr[24] = spu_fma(ctx->gpr[27], ctx->gpr[29], ctx->gpr[38]);
        ctx->gpr[7] = spu_fma(ctx->gpr[27], ctx->gpr[28], ctx->gpr[65]);
        ctx->gpr[11] = spu_and(ctx->gpr[21], ctx->gpr[25]);
        ctx->gpr[4] = spu_ilhu(0x3C08);
        ctx->gpr[13] = spu_iohl(ctx->gpr[13], 0x8C6D);
        ctx->gpr[4] = spu_iohl(ctx->gpr[4], 0x8342);
        ctx->gpr[16] = spu_ilhu(0xBAB2);
        ctx->gpr[3] = spu_fma(ctx->gpr[8], ctx->gpr[24], ctx->gpr[7]);
        ctx->gpr[75] = spu_fma(ctx->gpr[66], ctx->gpr[13], ctx->gpr[4]);
        ctx->gpr[71] = spu_fma(ctx->gpr[68], ctx->gpr[13], ctx->gpr[4]);
        ctx->gpr[13] = spu_ilhu(0x3F80);
        ctx->gpr[15] = spu_ilhu(0x3D2A);
        ctx->gpr[16] = spu_iohl(ctx->gpr[16], 0x4992);
        ctx->gpr[14] = spu_fm(ctx->gpr[3], ctx->gpr[6]);
        ctx->gpr[15] = spu_iohl(ctx->gpr[15], 0xA035);
        ctx->gpr[74] = spu_ilhu(0xBEFF);
        ctx->gpr[76] = spu_fma(ctx->gpr[66], ctx->gpr[16], ctx->gpr[15]);
        ctx->gpr[73] = spu_fma(ctx->gpr[68], ctx->gpr[16], ctx->gpr[15]);
        ctx->gpr[72] = spu_ilhu(0xBE2A);
        ctx->gpr[5] = spu_selb(ctx->gpr[14], ctx->gpr[22], ctx->gpr[19]);
        ctx->gpr[14] = spu_ilhu(0xC000);
        ctx->gpr[79] = spu_selb(ctx->gpr[5], ctx->gpr[37], ctx->gpr[20]);
        ctx->gpr[30] = spu_fma(ctx->gpr[34], ctx->gpr[14], ctx->gpr[51]);
        ctx->gpr[2] = spu_or(ctx->gpr[79], ctx->gpr[23]);
        ctx->gpr[74] = spu_iohl(ctx->gpr[74], 0xFFDF);
        ctx->gpr[77] = spu_selb(ctx->gpr[79], ctx->gpr[2], ctx->gpr[11]);
        ctx->gpr[72] = spu_iohl(ctx->gpr[72], 0xAAA1);
        ctx->gpr[12] = spu_selb(ctx->gpr[77], ctx->gpr[37], ctx->gpr[78]);
        ctx->gpr[64] = spu_fma(ctx->gpr[76], ctx->gpr[66], ctx->gpr[74]);
        ctx->gpr[31] = spu_frest(ctx->gpr[30]);
        ctx->gpr[56] = spu_fma(ctx->gpr[75], ctx->gpr[66], ctx->gpr[72]);
        ctx->gpr[70] = spu_frsqest(ctx->gpr[12]);
        ctx->gpr[67] = spu_fma(ctx->gpr[73], ctx->gpr[68], ctx->gpr[74]);
        ctx->gpr[59] = spu_fma(ctx->gpr[71], ctx->gpr[68], ctx->gpr[72]);
        ctx->gpr[29] = spu_fi(ctx->gpr[30], ctx->gpr[31]);
        ctx->gpr[53] = spu_fi(ctx->gpr[12], ctx->gpr[70]);
        ctx->gpr[63] = spu_andi(ctx->gpr[69], 3);
        ctx->gpr[61] = spu_fm(ctx->gpr[68], ctx->gpr[60]);
        ctx->gpr[58] = spu_fm(ctx->gpr[66], ctx->gpr[57]);
        ctx->gpr[41] = spu_ai(ctx->gpr[63], 1);
        ctx->gpr[42] = spu_andi(ctx->gpr[55], 3);
        ctx->gpr[28] = spu_fm(ctx->gpr[13], ctx->gpr[29]);
        ctx->gpr[39] = spu_fm(ctx->gpr[53], ctx->gpr[12]);
        ctx->gpr[46] = spu_fma(ctx->gpr[67], ctx->gpr[68], ctx->gpr[65]);
        ctx->gpr[43] = spu_fma(ctx->gpr[64], ctx->gpr[66], ctx->gpr[65]);
        ctx->gpr[48] = spu_fma(ctx->gpr[59], ctx->gpr[61], ctx->gpr[60]);
        ctx->gpr[45] = spu_fma(ctx->gpr[56], ctx->gpr[58], ctx->gpr[57]);
        ctx->gpr[27] = spu_fnms(ctx->gpr[28], ctx->gpr[30], ctx->gpr[13]);
        ctx->gpr[38] = spu_fnms(ctx->gpr[53], ctx->gpr[39], ctx->gpr[54]);
        ctx->gpr[40] = spu_fm(ctx->gpr[39], ctx->gpr[52]);
        ctx->gpr[50] = spu_andi(ctx->gpr[42], 1);
        ctx->gpr[49] = spu_andi(ctx->gpr[41], 1);
        ctx->gpr[47] = spu_ceq(ctx->gpr[50], ctx->gpr[37]);
        ctx->gpr[19] = spu_fma(ctx->gpr[27], ctx->gpr[29], ctx->gpr[28]);
        ctx->gpr[44] = spu_ceq(ctx->gpr[49], ctx->gpr[37]);
        ctx->gpr[18] = spu_fma(ctx->gpr[38], ctx->gpr[40], ctx->gpr[39]);
        ctx->gpr[26] = spu_selb(ctx->gpr[46], ctx->gpr[48], ctx->gpr[47]);
        ctx->gpr[24] = spu_selb(ctx->gpr[43], ctx->gpr[45], ctx->gpr[44]);
        ctx->gpr[34] = spu_andi(ctx->gpr[42], 2);
        /* nop */;
        ctx->gpr[32] = spu_andi(ctx->gpr[41], 2);
        ctx->gpr[20] = spu_frest(ctx->gpr[19]);
        ctx->gpr[25] = spu_ceq(ctx->gpr[34], ctx->gpr[37]);
        ctx->gpr[23] = spu_ceq(ctx->gpr[32], ctx->gpr[37]);
        ctx->gpr[22] = spu_xor(ctx->gpr[24], ctx->gpr[36]);
        ctx->gpr[17] = spu_fi(ctx->gpr[19], ctx->gpr[20]);
        ctx->gpr[21] = spu_xor(ctx->gpr[26], ctx->gpr[36]);
        ctx->gpr[16] = spu_ceqi(ctx->gpr[35], 1);
        ctx->gpr[6] = spu_selb(ctx->gpr[21], ctx->gpr[26], ctx->gpr[25]);
        ctx->gpr[7] = spu_selb(ctx->gpr[22], ctx->gpr[24], ctx->gpr[23]);
        ctx->gpr[8] = spu_fm(ctx->gpr[18], ctx->gpr[17]);
        ctx->gpr[10] = spu_fnms(ctx->gpr[8], ctx->gpr[19], ctx->gpr[18]);
        ctx->gpr[5] = spu_fma(ctx->gpr[10], ctx->gpr[17], ctx->gpr[8]);
        if (ctx->gpr[16]._u32[0] != 0) { ctx->pc = 0x15100; SPU_TAILCALL(spu_job_01494880_spu_func_00015100(ctx)); }
        ctx->gpr[19] = spu_fs(ctx->gpr[12], ctx->gpr[13]);
        ctx->gpr[2] = spu_fa(ctx->gpr[12], ctx->gpr[13]);
        ctx->gpr[21] = spu_fm(ctx->gpr[6], ctx->gpr[5]);
        ctx->gpr[11] = spu_fa(ctx->gpr[12], ctx->gpr[12]);
        ctx->gpr[4] = spu_fm(ctx->gpr[7], ctx->gpr[19]);
        ctx->gpr[7] = spu_fm(ctx->gpr[7], ctx->gpr[2]);
        ctx->gpr[15] = spu_fs(ctx->gpr[2], ctx->gpr[4]);
        ctx->gpr[22] = spu_fa(ctx->gpr[2], ctx->gpr[4]);
        ctx->gpr[20] = spu_fa(ctx->gpr[19], ctx->gpr[7]);
        ctx->gpr[23] = spu_fs(ctx->gpr[19], ctx->gpr[7]);
        ctx->gpr[34] = spu_fs(ctx->gpr[15], ctx->gpr[21]);
        ctx->gpr[35] = spu_fa(ctx->gpr[15], ctx->gpr[21]);
        ctx->gpr[8] = spu_fm(ctx->gpr[20], ctx->gpr[14]);
        ctx->gpr[9] = spu_fm(ctx->gpr[11], ctx->gpr[23]);
        ctx->gpr[15] = spu_fs(ctx->gpr[22], ctx->gpr[21]);
        ctx->gpr[11] = spu_fa(ctx->gpr[21], ctx->gpr[22]);
        ctx->gpr[7] = spu_fm(ctx->gpr[12], ctx->gpr[34]);
        ctx->gpr[2] = spu_fm(ctx->gpr[12], ctx->gpr[35]);
        { ctx->pc = 0x1495030; SPU_TAILCALL(spu_job_01494880_spu_func_01495030(ctx)); }
}

void spu_job_01494880_spu_func_01495030(spu_context* ctx) {
        ctx->gpr[47] = spu_il(4);
        ctx->gpr[30] = spu_frest(ctx->gpr[11]);
        ctx->gpr[43] = spu_il(8);
        ctx->gpr[71] = spu_frest(ctx->gpr[11]);
        ctx->gpr[37] = spu_il(12);
        ctx->gpr[70] = spu_frest(ctx->gpr[11]);
        ctx->gpr[63] = spu_ls_read128(ctx, ctx->gpr[33]._u32[0] + 0x0);
        ctx->gpr[74] = spu_fi(ctx->gpr[11], ctx->gpr[30]);
        ctx->gpr[69] = spu_fi(ctx->gpr[11], ctx->gpr[71]);
        ctx->gpr[78] = spu_cwd(ctx->gpr[33], 0);
        ctx->gpr[68] = spu_fi(ctx->gpr[11], ctx->gpr[70]);
        ctx->gpr[62] = spu_frest(ctx->gpr[11]);
        ctx->gpr[51] = spu_cwd(ctx->gpr[33], 4);
        ctx->gpr[59] = spu_frest(ctx->gpr[11]);
        ctx->gpr[46] = spu_cwd(ctx->gpr[33], 8);
        ctx->gpr[61] = spu_fi(ctx->gpr[11], ctx->gpr[62]);
        /* nop */;
        /* branch hint (ignored) */;
        ctx->gpr[73] = spu_fm(ctx->gpr[2], ctx->gpr[74]);
        ctx->gpr[42] = spu_cwd(ctx->gpr[33], 12);
        ctx->gpr[10] = spu_fm(ctx->gpr[9], ctx->gpr[69]);
        ctx->gpr[67] = spu_fm(ctx->gpr[7], ctx->gpr[68]);
        ctx->gpr[58] = spu_fi(ctx->gpr[11], ctx->gpr[59]);
        ctx->gpr[60] = spu_fm(ctx->gpr[8], ctx->gpr[61]);
        ctx->gpr[72] = spu_fnms(ctx->gpr[73], ctx->gpr[11], ctx->gpr[2]);
        ctx->gpr[55] = spu_fnms(ctx->gpr[10], ctx->gpr[11], ctx->gpr[9]);
        ctx->gpr[66] = spu_fnms(ctx->gpr[67], ctx->gpr[11], ctx->gpr[7]);
        ctx->gpr[57] = spu_fm(ctx->gpr[15], ctx->gpr[58]);
        ctx->gpr[8] = spu_fnms(ctx->gpr[60], ctx->gpr[11], ctx->gpr[8]);
        ctx->gpr[64] = spu_fma(ctx->gpr[72], ctx->gpr[74], ctx->gpr[73]);
        ctx->gpr[50] = spu_fma(ctx->gpr[55], ctx->gpr[69], ctx->gpr[10]);
        ctx->gpr[45] = spu_fma(ctx->gpr[66], ctx->gpr[68], ctx->gpr[67]);
        ctx->gpr[56] = spu_fnms(ctx->gpr[57], ctx->gpr[11], ctx->gpr[15]);
        ctx->gpr[41] = spu_fma(ctx->gpr[8], ctx->gpr[61], ctx->gpr[60]);
        /* nop */;
        ctx->gpr[53] = spu_shufb(ctx->gpr[64], ctx->gpr[63], ctx->gpr[78]);
        ctx->gpr[40] = spu_fma(ctx->gpr[56], ctx->gpr[58], ctx->gpr[57]);
        spu_ls_write128(ctx, ctx->gpr[33]._u32[0] + 0x0, ctx->gpr[53]);
        ctx->gpr[49] = spu_ls_read128(ctx, ctx->gpr[33]._u32[0] + ctx->gpr[47]._u32[0]);
        ctx->gpr[48] = spu_shufb(ctx->gpr[50], ctx->gpr[49], ctx->gpr[51]);
        spu_ls_write128(ctx, ctx->gpr[33]._u32[0] + ctx->gpr[47]._u32[0], ctx->gpr[48]);
        ctx->gpr[44] = spu_ls_read128(ctx, ctx->gpr[33]._u32[0] + ctx->gpr[43]._u32[0]);
        ctx->gpr[5] = spu_shufb(ctx->gpr[45], ctx->gpr[44], ctx->gpr[46]);
        spu_ls_write128(ctx, ctx->gpr[33]._u32[0] + ctx->gpr[43]._u32[0], ctx->gpr[5]);
        ctx->gpr[18] = spu_ls_read128(ctx, ctx->gpr[33]._u32[0] + ctx->gpr[37]._u32[0]);
        ctx->gpr[32] = spu_shufb(ctx->gpr[41], ctx->gpr[18], ctx->gpr[42]);
        spu_ls_write128(ctx, ctx->gpr[33]._u32[0] + ctx->gpr[37]._u32[0], ctx->gpr[32]);
        ctx->gpr[17] = spu_ls_read128(ctx, ctx->gpr[33]._u32[0] + 0x10);
        ctx->gpr[39] = spu_shufb(ctx->gpr[40], ctx->gpr[17], ctx->gpr[78]);
        spu_ls_write128(ctx, ctx->gpr[33]._u32[0] + 0x10, ctx->gpr[39]);
        /* nop */;
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
}

void spu_job_01494880_spu_func_01495100(spu_context* ctx) {
        ctx->gpr[28] = spu_fs(ctx->gpr[12], ctx->gpr[13]);
        /* branch hint (ignored) */;
        ctx->gpr[38] = spu_fa(ctx->gpr[12], ctx->gpr[13]);
        ctx->gpr[6] = spu_fm(ctx->gpr[6], ctx->gpr[5]);
        ctx->gpr[25] = spu_fm(ctx->gpr[12], ctx->gpr[14]);
        ctx->gpr[31] = spu_fm(ctx->gpr[7], ctx->gpr[28]);
        ctx->gpr[29] = spu_fm(ctx->gpr[7], ctx->gpr[38]);
        ctx->gpr[27] = spu_fa(ctx->gpr[38], ctx->gpr[31]);
        ctx->gpr[24] = spu_fs(ctx->gpr[38], ctx->gpr[31]);
        ctx->gpr[3] = spu_fs(ctx->gpr[28], ctx->gpr[29]);
        ctx->gpr[26] = spu_fa(ctx->gpr[28], ctx->gpr[29]);
        ctx->gpr[13] = spu_fs(ctx->gpr[27], ctx->gpr[6]);
        ctx->gpr[16] = spu_fa(ctx->gpr[27], ctx->gpr[6]);
        ctx->gpr[15] = spu_fs(ctx->gpr[24], ctx->gpr[6]);
        ctx->gpr[9] = spu_fm(ctx->gpr[25], ctx->gpr[26]);
        ctx->gpr[8] = spu_fa(ctx->gpr[3], ctx->gpr[3]);
        ctx->gpr[11] = spu_fa(ctx->gpr[6], ctx->gpr[24]);
        ctx->gpr[7] = spu_fm(ctx->gpr[12], ctx->gpr[13]);
        ctx->gpr[2] = spu_fm(ctx->gpr[12], ctx->gpr[16]);
        { ctx->pc = 0x15030; SPU_TAILCALL(spu_job_01494880_spu_func_00015030(ctx)); }
}

void spu_job_01494880_spu_func_01495150(spu_context* ctx) {
        ctx->gpr[13] = spu_il(-1856);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x30, ctx->gpr[82]);
        ctx->gpr[15] = spu_il(767);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x40, ctx->gpr[83]);
        ctx->gpr[82] = spu_ori(ctx->gpr[9], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x50, ctx->gpr[84]);
        ctx->gpr[84] = spu_ori(ctx->gpr[8], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x60, ctx->gpr[85]);
        ctx->gpr[85] = spu_ori(ctx->gpr[6], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x80, ctx->gpr[87]);
        ctx->gpr[87] = spu_ori(ctx->gpr[3], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x90, ctx->gpr[88]);
        ctx->gpr[88] = spu_ori(ctx->gpr[4], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xA0, ctx->gpr[89]);
        ctx->gpr[89] = spu_ori(ctx->gpr[5], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xB0, ctx->gpr[90]);
        ctx->gpr[5] = spu_il(2496);
        /* branch hint (ignored) */;
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xC0, ctx->gpr[91]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x150, ctx->gpr[126]);
        ctx->gpr[17] = spu_ila(0x928);
        ctx->gpr[126] = spu_link(0x14951A8); spu_host_call_push(ctx, 0x14951A8); spu_job_01494880_spu_func_000151A8(ctx); spu_host_call_pop(ctx);
        { ctx->pc = 0x14951A8; SPU_TAILCALL(spu_job_01494880_spu_func_014951A8(ctx)); }
}

void spu_job_01494880_spu_func_014951A8(spu_context* ctx) {
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + 0x10, ctx->gpr[0]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x10, ctx->gpr[80]);
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x20, ctx->gpr[81]);
        ctx->gpr[126] = spu_sf(ctx->gpr[17], ctx->gpr[126]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x70, ctx->gpr[86]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xD0, ctx->gpr[92]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xE0, ctx->gpr[93]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xF0, ctx->gpr[94]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x100, ctx->gpr[95]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x110, ctx->gpr[96]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x120, ctx->gpr[97]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x130, ctx->gpr[98]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x140, ctx->gpr[99]);
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x740, ctx->gpr[1]);
        ctx->gpr[1] = spu_a(ctx->gpr[1], ctx->gpr[13]);
        /* branch hint (ignored) */;
        ctx->gpr[13] = spu_ori(ctx->gpr[7], 0);
        ctx->gpr[16] = spu_ai(ctx->gpr[1], 32);
        ctx->gpr[7] = spu_il(911);
        ctx->gpr[14] = spu_ai(ctx->gpr[1], 32);
        ctx->gpr[11] = spu_a(ctx->gpr[16], ctx->gpr[15]);
        ctx->gpr[10] = spu_a(ctx->gpr[14], ctx->gpr[7]);
        ctx->gpr[2] = spu_ai(ctx->gpr[1], 159);
        ctx->gpr[12] = spu_ceqi(ctx->gpr[13], 258);
        ctx->gpr[90] = spu_andi(ctx->gpr[2], -128);
        ctx->gpr[83] = spu_andi(ctx->gpr[11], -128);
        ctx->gpr[91] = spu_andi(ctx->gpr[10], -128);
        if (ctx->gpr[12]._u32[0] != 0) { ctx->pc = 0x15248; SPU_TAILCALL(spu_job_01494880_spu_func_00015248(ctx)); }
        ctx->gpr[3] = spu_cgti(ctx->gpr[13], 258);
        if (ctx->gpr[3]._u32[0] == 0) { ctx->pc = 0x152B8; SPU_TAILCALL(spu_job_01494880_spu_func_000152B8(ctx)); }
        ctx->gpr[18] = spu_ceqi(ctx->gpr[13], 260);
        ctx->gpr[5] = spu_ila(0x23000);
        if (ctx->gpr[18]._u32[0] != 0) { ctx->pc = 0x15248; SPU_TAILCALL(spu_job_01494880_spu_func_00015248(ctx)); }
        ctx->gpr[5] = spu_ilhu(0x4);
        ctx->gpr[19] = spu_cgti(ctx->gpr[13], 259);
        ctx->gpr[5] = spu_iohl(ctx->gpr[5], 0xE200);
        /* nop */;
        if (ctx->gpr[19]._u32[0] != 0) { ctx->pc = 0x1530C; SPU_TAILCALL(spu_job_01494880_spu_func_0001530C(ctx)); }
        { ctx->pc = 0x1495248; SPU_TAILCALL(spu_job_01494880_spu_func_01495248(ctx)); }
}

void spu_job_01494880_spu_func_01495248(spu_context* ctx) {
        ctx->gpr[93] = spu_il(1856);
        ctx->gpr[0] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + 0x750);
        ctx->gpr[3] = spu_ori(ctx->gpr[5], 0);
        ctx->gpr[1] = spu_a(ctx->gpr[1], ctx->gpr[93]);
        ctx->gpr[80] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x10);
        ctx->gpr[81] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x20);
        /* branch hint (ignored) */;
        ctx->gpr[82] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x30);
        ctx->gpr[83] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x40);
        ctx->gpr[84] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x50);
        ctx->gpr[85] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x60);
        ctx->gpr[86] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x70);
        ctx->gpr[87] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x80);
        ctx->gpr[88] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x90);
        ctx->gpr[89] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0xA0);
        ctx->gpr[90] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0xB0);
        ctx->gpr[91] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0xC0);
        ctx->gpr[92] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0xD0);
        ctx->gpr[93] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0xE0);
        ctx->gpr[94] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0xF0);
        ctx->gpr[95] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x100);
        ctx->gpr[96] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x110);
        ctx->gpr[97] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x120);
        /* branch hint (ignored) */;
        ctx->gpr[98] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x130);
        ctx->gpr[99] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x140);
        ctx->gpr[126] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x150);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
}

void spu_job_01494880_spu_func_014952B8(spu_context* ctx) {
        ctx->gpr[4] = spu_ceqi(ctx->gpr[13], 3);
        if (ctx->gpr[4]._u32[0] != 0) { ctx->pc = 0x153A0; SPU_TAILCALL(spu_job_01494880_spu_func_000153A0(ctx)); }
        ctx->gpr[5] = spu_cgti(ctx->gpr[13], 3);
        if (ctx->gpr[5]._u32[0] != 0) { ctx->pc = 0x1531C; SPU_TAILCALL(spu_job_01494880_spu_func_0001531C(ctx)); }
        ctx->gpr[6] = spu_ceqi(ctx->gpr[13], 1);
        if (ctx->gpr[6]._u32[0] != 0) { ctx->pc = 0x15314; SPU_TAILCALL(spu_job_01494880_spu_func_00015314(ctx)); }
        { ctx->pc = 0x14952D0; SPU_TAILCALL(spu_job_01494880_spu_func_014952D0(ctx)); }
}

void spu_job_01494880_spu_func_014952D0(spu_context* ctx) {
        ctx->gpr[3] = spu_il(8706);
        ctx->gpr[77] = spu_ceq(ctx->gpr[13], ctx->gpr[3]);
        if (ctx->gpr[77]._u32[0] != 0) { ctx->pc = 0x155B0; SPU_TAILCALL(spu_job_01494880_spu_func_000155B0(ctx)); }
        ctx->gpr[78] = spu_cgt(ctx->gpr[13], ctx->gpr[3]);
        if (ctx->gpr[78]._u32[0] != 0) { ctx->pc = 0x15410; SPU_TAILCALL(spu_job_01494880_spu_func_00015410(ctx)); }
        ctx->gpr[81] = spu_il(512);
        ctx->gpr[79] = spu_ceq(ctx->gpr[13], ctx->gpr[81]);
        if (ctx->gpr[79]._u32[0] != 0) { ctx->pc = 0x15C20; SPU_TAILCALL(spu_job_01494880_spu_func_00015C20(ctx)); }
        ctx->gpr[83] = spu_il(8448);
        ctx->gpr[82] = spu_ceq(ctx->gpr[13], ctx->gpr[83]);
        if (ctx->gpr[82]._u32[0] != 0) { ctx->pc = 0x15714; SPU_TAILCALL(spu_job_01494880_spu_func_00015714(ctx)); }
        ctx->gpr[85] = spu_ceqi(ctx->gpr[13], 257);
        if (ctx->gpr[85]._u32[0] != 0) { ctx->pc = 0x15728; SPU_TAILCALL(spu_job_01494880_spu_func_00015728(ctx)); }
        ctx->gpr[5] = spu_il(0);
        { ctx->pc = 0x15248; SPU_TAILCALL(spu_job_01494880_spu_func_00015248(ctx)); }
}

void spu_job_01494880_spu_func_0149530C(spu_context* ctx) {
        ctx->gpr[20] = spu_cgti(ctx->gpr[13], 262);
        if (ctx->gpr[20]._u32[0] != 0) { ctx->pc = 0x152D0; SPU_TAILCALL(spu_job_01494880_spu_func_000152D0(ctx)); }
        { ctx->pc = 0x1495314; SPU_TAILCALL(spu_job_01494880_spu_func_01495314(ctx)); }
}

void spu_job_01494880_spu_func_01495314(spu_context* ctx) {
        ctx->gpr[5] = spu_il(1);
        { ctx->pc = 0x15248; SPU_TAILCALL(spu_job_01494880_spu_func_00015248(ctx)); }
}

void spu_job_01494880_spu_func_0149531C(spu_context* ctx) {
        ctx->gpr[8] = spu_ceqi(ctx->gpr[13], 9);
        if (ctx->gpr[8]._u32[0] != 0) { ctx->pc = 0x15314; SPU_TAILCALL(spu_job_01494880_spu_func_00015314(ctx)); }
        ctx->gpr[9] = spu_ceqi(ctx->gpr[13], 256);
        /* nop */;
        if (ctx->gpr[9]._u32[0] == 0) { ctx->pc = 0x152D0; SPU_TAILCALL(spu_job_01494880_spu_func_000152D0(ctx)); }
        ctx->gpr[37] = spu_ila(0x90D0);
        /* branch hint (ignored) */;
        ctx->gpr[34] = spu_ila(0xFFFF);
        ctx->gpr[33] = spu_ls_read128(ctx, ctx->gpr[84]._u32[0] + 0x0);
        ctx->gpr[6] = spu_a(ctx->gpr[37], ctx->gpr[126]);
        ctx->gpr[36] = spu_andi(ctx->gpr[6], 15);
        ctx->gpr[32] = spu_sf(ctx->gpr[36], ctx->gpr[6]);
        /* nop */;
        ctx->gpr[35] = spu_sfi(ctx->gpr[36], 0);
        ctx->gpr[8] = spu_rotqby(ctx->gpr[33], ctx->gpr[84]);
        ctx->gpr[5] = spu_ai(ctx->gpr[32], 16);
        ctx->gpr[31] = spu_ls_read128(ctx, ctx->gpr[32]._u32[0] + 0x0);
        ctx->gpr[29] = spu_rotm(ctx->gpr[34], ctx->gpr[35]);
        ctx->gpr[30] = spu_ceqbi(ctx->gpr[31], 0);
        ctx->gpr[28] = spu_gbb(ctx->gpr[30]);
        ctx->gpr[2] = spu_and(ctx->gpr[28], ctx->gpr[29]);
        { ctx->pc = 0x1495370; SPU_TAILCALL(spu_job_01494880_spu_func_01495370(ctx)); }
}

void spu_job_01494880_spu_func_01495370(spu_context* ctx) {
        if (ctx->gpr[2]._u32[0] != 0) { ctx->pc = 0x15AF0; SPU_TAILCALL(spu_job_01494880_spu_func_00015AF0(ctx)); }
        ctx->gpr[44] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + 0x0);
        ctx->gpr[43] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + 0x10);
        ctx->gpr[5] = spu_ai(ctx->gpr[5], 32);
        ctx->gpr[42] = spu_ceqbi(ctx->gpr[44], 0);
        ctx->gpr[40] = spu_ceqbi(ctx->gpr[43], 0);
        ctx->gpr[41] = spu_gbb(ctx->gpr[42]);
        ctx->gpr[39] = spu_gbb(ctx->gpr[40]);
        ctx->gpr[38] = spu_shli(ctx->gpr[41], 16);
        ctx->gpr[2] = spu_or(ctx->gpr[38], ctx->gpr[39]);
        /* nop */;
        { ctx->pc = 0x15370; SPU_TAILCALL(spu_job_01494880_spu_func_00015370(ctx)); }
}

void spu_job_01494880_spu_func_014953A0(spu_context* ctx) {
        ctx->gpr[21] = spu_cgti(ctx->gpr[9], 0);
        /* branch hint (ignored) */;
        ctx->gpr[5] = spu_il(0);
        if (ctx->gpr[21]._u32[0] == 0) { ctx->pc = 0x15248; SPU_TAILCALL(spu_job_01494880_spu_func_00015248(ctx)); }
        ctx->gpr[81] = spu_il(0);
        ctx->gpr[83] = spu_ila(0xFFFF);
        ctx->gpr[8] = spu_ai(ctx->gpr[84], 4);
        ctx->gpr[27] = spu_ls_read128(ctx, ctx->gpr[84]._u32[0] + 0x0);
        ctx->gpr[5] = spu_ori(ctx->gpr[89], 0);
        ctx->gpr[3] = spu_shlqbyi(ctx->gpr[87], 0);
        ctx->gpr[4] = spu_ori(ctx->gpr[88], 0);
        ctx->gpr[6] = spu_shlqbyi(ctx->gpr[85], 0);
        ctx->gpr[26] = spu_rotqby(ctx->gpr[27], ctx->gpr[84]);
        ctx->gpr[80] = spu_and(ctx->gpr[26], ctx->gpr[83]);
        ctx->gpr[7] = spu_rotmai(ctx->gpr[26], -16);
        ctx->gpr[9] = spu_ori(ctx->gpr[80], 0);
        ctx->gpr[0] = spu_link(0x14953E4); spu_host_call_push(ctx, 0x14953E4); spu_job_01494880_spu_func_00015150(ctx); spu_host_call_pop(ctx);
        /* branch hint (ignored) */;
        ctx->gpr[25] = spu_ai(ctx->gpr[81], 1);
        ctx->gpr[5] = spu_shlqbyi(ctx->gpr[3], 0);
        ctx->gpr[24] = spu_shli(ctx->gpr[80], 2);
}

/* Indirect-dispatch stubs for cross-function targets the
 * function detector did not seed (typically conditional
 * branches that escape a function's range). */
void spu_job_01494880_spu_func_00014898(spu_context* ctx) {
    ctx->pc = 0x14898u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_000148B0(spu_context* ctx) {
    ctx->pc = 0x148B0u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_000148D0(spu_context* ctx) {
    ctx->pc = 0x148D0u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_00014944(spu_context* ctx) {
    ctx->pc = 0x14944u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_00014970(spu_context* ctx) {
    ctx->pc = 0x14970u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_00014994(spu_context* ctx) {
    ctx->pc = 0x14994u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_000149B0(spu_context* ctx) {
    ctx->pc = 0x149B0u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_000149D0(spu_context* ctx) {
    ctx->pc = 0x149D0u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_000149F8(spu_context* ctx) {
    ctx->pc = 0x149F8u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_00014AA8(spu_context* ctx) {
    ctx->pc = 0x14AA8u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_00014AD0(spu_context* ctx) {
    ctx->pc = 0x14AD0u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_00014B00(spu_context* ctx) {
    ctx->pc = 0x14B00u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_00014B40(spu_context* ctx) {
    ctx->pc = 0x14B40u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_00014B54(spu_context* ctx) {
    ctx->pc = 0x14B54u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_00014B7C(spu_context* ctx) {
    ctx->pc = 0x14B7Cu; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_00014C10(spu_context* ctx) {
    ctx->pc = 0x14C10u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_00015030(spu_context* ctx) {
    ctx->pc = 0x15030u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_00015100(spu_context* ctx) {
    ctx->pc = 0x15100u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_00015150(spu_context* ctx) {
    ctx->pc = 0x15150u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_000151A8(spu_context* ctx) {
    ctx->pc = 0x151A8u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_00015248(spu_context* ctx) {
    ctx->pc = 0x15248u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_000152B8(spu_context* ctx) {
    ctx->pc = 0x152B8u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_000152D0(spu_context* ctx) {
    ctx->pc = 0x152D0u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_0001530C(spu_context* ctx) {
    ctx->pc = 0x1530Cu; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_00015314(spu_context* ctx) {
    ctx->pc = 0x15314u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_0001531C(spu_context* ctx) {
    ctx->pc = 0x1531Cu; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_00015370(spu_context* ctx) {
    ctx->pc = 0x15370u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_000153A0(spu_context* ctx) {
    ctx->pc = 0x153A0u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_00015410(spu_context* ctx) {
    ctx->pc = 0x15410u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_000155B0(spu_context* ctx) {
    ctx->pc = 0x155B0u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_00015714(spu_context* ctx) {
    ctx->pc = 0x15714u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_00015728(spu_context* ctx) {
    ctx->pc = 0x15728u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_00015AF0(spu_context* ctx) {
    ctx->pc = 0x15AF0u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_00015C20(spu_context* ctx) {
    ctx->pc = 0x15C20u; spu_indirect_branch(ctx);
}
void spu_job_01494880_spu_func_000168E8(spu_context* ctx) {
    ctx->pc = 0x168E8u; spu_indirect_branch(ctx);
}

/* Function table */
typedef struct { uint32_t addr; void (*func)(spu_context*); const char* name; } spu_func_entry;
static const spu_func_entry spu_function_table[] = {
    { 0x01494880u, spu_job_01494880_spu_func_01494880, "spu_job_01494880_spu_func_01494880" },
    { 0x01494898u, spu_job_01494880_spu_func_01494898, "spu_job_01494880_spu_func_01494898" },
    { 0x014948B0u, spu_job_01494880_spu_func_014948B0, "spu_job_01494880_spu_func_014948B0" },
    { 0x014948D0u, spu_job_01494880_spu_func_014948D0, "spu_job_01494880_spu_func_014948D0" },
    { 0x01494944u, spu_job_01494880_spu_func_01494944, "spu_job_01494880_spu_func_01494944" },
    { 0x01494970u, spu_job_01494880_spu_func_01494970, "spu_job_01494880_spu_func_01494970" },
    { 0x01494994u, spu_job_01494880_spu_func_01494994, "spu_job_01494880_spu_func_01494994" },
    { 0x014949B0u, spu_job_01494880_spu_func_014949B0, "spu_job_01494880_spu_func_014949B0" },
    { 0x014949D0u, spu_job_01494880_spu_func_014949D0, "spu_job_01494880_spu_func_014949D0" },
    { 0x014949F8u, spu_job_01494880_spu_func_014949F8, "spu_job_01494880_spu_func_014949F8" },
    { 0x01494AA8u, spu_job_01494880_spu_func_01494AA8, "spu_job_01494880_spu_func_01494AA8" },
    { 0x01494AD0u, spu_job_01494880_spu_func_01494AD0, "spu_job_01494880_spu_func_01494AD0" },
    { 0x01494B00u, spu_job_01494880_spu_func_01494B00, "spu_job_01494880_spu_func_01494B00" },
    { 0x01494B40u, spu_job_01494880_spu_func_01494B40, "spu_job_01494880_spu_func_01494B40" },
    { 0x01494B54u, spu_job_01494880_spu_func_01494B54, "spu_job_01494880_spu_func_01494B54" },
    { 0x01494B7Cu, spu_job_01494880_spu_func_01494B7C, "spu_job_01494880_spu_func_01494B7C" },
    { 0x01494C10u, spu_job_01494880_spu_func_01494C10, "spu_job_01494880_spu_func_01494C10" },
    { 0x01495030u, spu_job_01494880_spu_func_01495030, "spu_job_01494880_spu_func_01495030" },
    { 0x01495100u, spu_job_01494880_spu_func_01495100, "spu_job_01494880_spu_func_01495100" },
    { 0x01495150u, spu_job_01494880_spu_func_01495150, "spu_job_01494880_spu_func_01495150" },
    { 0x014951A8u, spu_job_01494880_spu_func_014951A8, "spu_job_01494880_spu_func_014951A8" },
    { 0x01495248u, spu_job_01494880_spu_func_01495248, "spu_job_01494880_spu_func_01495248" },
    { 0x014952B8u, spu_job_01494880_spu_func_014952B8, "spu_job_01494880_spu_func_014952B8" },
    { 0x014952D0u, spu_job_01494880_spu_func_014952D0, "spu_job_01494880_spu_func_014952D0" },
    { 0x0149530Cu, spu_job_01494880_spu_func_0149530C, "spu_job_01494880_spu_func_0149530C" },
    { 0x01495314u, spu_job_01494880_spu_func_01495314, "spu_job_01494880_spu_func_01495314" },
    { 0x0149531Cu, spu_job_01494880_spu_func_0149531C, "spu_job_01494880_spu_func_0149531C" },
    { 0x01495370u, spu_job_01494880_spu_func_01495370, "spu_job_01494880_spu_func_01495370" },
    { 0x014953A0u, spu_job_01494880_spu_func_014953A0, "spu_job_01494880_spu_func_014953A0" },
    { 0, NULL, NULL }
};

void spu_job_01494880_spu_recomp_register(void) {
    for (const spu_func_entry* e = spu_function_table; e->func; ++e)
        spu_register_function(e->addr, e->func);
}
