/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#pragma once
#include "../../runtime/spu/spu_context.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Cross-function branch/loop = a guest tail-jump to another lifted function's
 * entry. It MUST reuse the current host frame, not nest one: SPURS task loops
 * iterate via these, so nesting overflows the host stack and silently kills the
 * process. clang's musttail guarantees the tail call (a jump); without it (or on
 * a non-clang compiler) we fall back to call+return, which only stays bounded if
 * the compiler happens to do sibling-call optimization. All lifted SPU functions
 * share the signature `void f(spu_context*)`, so the tail call is always valid. */
#if defined(__clang__)
#  define SPU_TAILCALL(call) __attribute__((musttail)) return call
#else
#  define SPU_TAILCALL(call) do { call; return; } while (0)
#endif

/* Indirect branch dispatch (bi/bisl/bid...): PC has been set to the target
 * local-store address; the runtime resolves it to the matching lifted
 * function and continues execution. Implemented by the SPU program glue. */
void spu_indirect_branch(spu_context* ctx);

/* stop/stopd hook (YDKJ): the runtime inspects the stop code, may deliver a
 * stop-and-signal event to the PPU (SPURS bring-up handshake), and longjmps the
 * host SPU thread back to spu_run_with_halt so the job does not spin past the
 * stop. Complements ctx->status; harmless where the runtime handles status. */
void spu_stop(spu_context* ctx);
/* Lower-level longjmp helper: abort the host SPU thread back to spu_run_with_halt
 * (used for the infinite no-op self-loop / idle halt idiom). */
void spu_halt(spu_context* ctx);

/* Channel access -- implemented by the runtime (MFC DMA engine, mailboxes,
 * signal notification, decrementer). See runtime/spu/spu_dma.h. */
u128 spu_rdch(spu_context* ctx, uint32_t channel);
uint32_t spu_rchcnt(spu_context* ctx, uint32_t channel);
void spu_wrch(spu_context* ctx, uint32_t channel, u128 value);

/* Execution trace (only emitted when the lifter was invoked with --trace). */
void spu_trace_init(const char* path);
void spu_trace_pc(spu_context* ctx, uint32_t pc);
void spu_trace_rt(spu_context* ctx, uint32_t rt);

#ifdef __cplusplus
}
#endif


void spu_job_01494880_spu_func_01494880(spu_context* ctx);
void spu_job_01494880_spu_func_01494898(spu_context* ctx);
void spu_job_01494880_spu_func_014948B0(spu_context* ctx);
void spu_job_01494880_spu_func_014948D0(spu_context* ctx);
void spu_job_01494880_spu_func_01494944(spu_context* ctx);
void spu_job_01494880_spu_func_01494970(spu_context* ctx);
void spu_job_01494880_spu_func_01494994(spu_context* ctx);
void spu_job_01494880_spu_func_014949B0(spu_context* ctx);
void spu_job_01494880_spu_func_014949D0(spu_context* ctx);
void spu_job_01494880_spu_func_014949F8(spu_context* ctx);
void spu_job_01494880_spu_func_01494AA8(spu_context* ctx);
void spu_job_01494880_spu_func_01494AD0(spu_context* ctx);
void spu_job_01494880_spu_func_01494B00(spu_context* ctx);
void spu_job_01494880_spu_func_01494B40(spu_context* ctx);
void spu_job_01494880_spu_func_01494B54(spu_context* ctx);
void spu_job_01494880_spu_func_01494B7C(spu_context* ctx);
void spu_job_01494880_spu_func_01494C10(spu_context* ctx);
void spu_job_01494880_spu_func_01495030(spu_context* ctx);
void spu_job_01494880_spu_func_01495100(spu_context* ctx);
void spu_job_01494880_spu_func_01495150(spu_context* ctx);
void spu_job_01494880_spu_func_014951A8(spu_context* ctx);
void spu_job_01494880_spu_func_01495248(spu_context* ctx);
void spu_job_01494880_spu_func_014952B8(spu_context* ctx);
void spu_job_01494880_spu_func_014952D0(spu_context* ctx);
void spu_job_01494880_spu_func_0149530C(spu_context* ctx);
void spu_job_01494880_spu_func_01495314(spu_context* ctx);
void spu_job_01494880_spu_func_0149531C(spu_context* ctx);
void spu_job_01494880_spu_func_01495370(spu_context* ctx);
void spu_job_01494880_spu_func_014953A0(spu_context* ctx);
void spu_job_01494880_spu_func_00014898(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_000148B0(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_000148D0(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_00014944(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_00014970(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_00014994(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_000149B0(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_000149D0(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_000149F8(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_00014AA8(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_00014AD0(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_00014B00(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_00014B40(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_00014B54(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_00014B7C(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_00014C10(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_00015030(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_00015100(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_00015150(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_000151A8(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_00015248(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_000152B8(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_000152D0(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_0001530C(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_00015314(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_0001531C(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_00015370(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_000153A0(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_00015410(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_000155B0(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_00015714(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_00015728(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_00015AF0(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_00015C20(spu_context* ctx); /* external */
void spu_job_01494880_spu_func_000168E8(spu_context* ctx); /* external */

/* Runtime glue (runtime/spu/spu_channels.c) */
void spu_register_function(uint32_t addr, void (*fn)(spu_context*));
/* Call once at init to register this image's functions for
 * indirect-branch dispatch (spu_indirect_branch). */
void spu_job_01494880_spu_recomp_register(void);
