/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#include "spu_recomp.h"
#include "../../runtime/spu/spu_helpers.h"


void spu_job_01466F00_spu_func_01466F00(spu_context* ctx) {
        ctx->gpr[2] = spu_ila(0x87F8);
        ctx->gpr[2] = spu_ila(0x99AD);
        ctx->gpr[2] = spu_ila(0x1594A);
        ctx->gpr[2] = spu_ila(0x17877);
        ctx->gpr[80] = spu_xori(ctx->gpr[80], 4);
        { ctx->pc = 0x26F18; SPU_TAILCALL(spu_job_01466F00_spu_func_00026F18(ctx)); }
}

void spu_job_01466F00_spu_func_01466F18(spu_context* ctx) {
        ctx->gpr[80] = spu_xori(ctx->gpr[80], 4);
        { ctx->pc = 0x26F30; SPU_TAILCALL(spu_job_01466F00_spu_func_00026F30(ctx)); }
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
}

void spu_job_01466F00_spu_func_01466F30(spu_context* ctx) {
        ctx->gpr[2] = spu_ori(ctx->gpr[3], 0);
        ctx->gpr[3] = spu_ai(ctx->gpr[4], 48);
        ctx->gpr[4] = spu_ls_read128(ctx, ctx->gpr[2]._u32[0] + 0x20);
        ctx->gpr[4] = spu_rotqby(ctx->gpr[4], ctx->gpr[2]);
        { ctx->pc = 0x32888; SPU_TAILCALL(spu_job_01466F00_spu_func_00032888(ctx)); }
        /* nop */;
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        /* nop */;
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        /* nop */;
        ctx->gpr[9] = spu_shli(ctx->gpr[6], 2);
        /* branch hint (ignored) */;
        ctx->gpr[5] = spu_il(11648);
        ctx->gpr[4] = spu_il(1);
        ctx->gpr[8] = spu_cwx(ctx->gpr[1], ctx->gpr[5]);
        ctx->gpr[11] = spu_ls_read128(ctx, ctx->gpr[9]._u32[0] + ctx->gpr[3]._u32[0]);
        ctx->gpr[12] = spu_cwx(ctx->gpr[9], ctx->gpr[3]);
        ctx->gpr[10] = spu_shufb(ctx->gpr[7], ctx->gpr[11], ctx->gpr[12]);
        spu_ls_write128(ctx, ctx->gpr[9]._u32[0] + ctx->gpr[3]._u32[0], ctx->gpr[10]);
        ctx->gpr[6] = spu_ls_read128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[5]._u32[0]);
        ctx->gpr[2] = spu_shufb(ctx->gpr[4], ctx->gpr[6], ctx->gpr[8]);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[5]._u32[0], ctx->gpr[2]);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        /* nop */;
        ctx->gpr[13] = spu_shli(ctx->gpr[6], 2);
        /* branch hint (ignored) */;
        ctx->gpr[5] = spu_il(11648);
        ctx->gpr[2] = spu_il(1);
        ctx->gpr[8] = spu_cwx(ctx->gpr[1], ctx->gpr[5]);
        ctx->gpr[9] = spu_a(ctx->gpr[13], ctx->gpr[3]);
        ctx->gpr[11] = spu_ls_read128(ctx, ctx->gpr[9]._u32[0] + 0x20);
        ctx->gpr[12] = spu_cwd(ctx->gpr[9], 0);
        ctx->gpr[10] = spu_shufb(ctx->gpr[7], ctx->gpr[11], ctx->gpr[12]);
        spu_ls_write128(ctx, ctx->gpr[9]._u32[0] + 0x20, ctx->gpr[10]);
        ctx->gpr[6] = spu_ls_read128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[5]._u32[0]);
        ctx->gpr[4] = spu_shufb(ctx->gpr[2], ctx->gpr[6], ctx->gpr[8]);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[5]._u32[0], ctx->gpr[4]);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        ctx->gpr[13] = spu_shli(ctx->gpr[6], 2);
        /* branch hint (ignored) */;
        ctx->gpr[5] = spu_il(11648);
        ctx->gpr[2] = spu_il(1);
        ctx->gpr[8] = spu_cwx(ctx->gpr[1], ctx->gpr[5]);
        ctx->gpr[9] = spu_a(ctx->gpr[13], ctx->gpr[3]);
        ctx->gpr[11] = spu_ls_read128(ctx, ctx->gpr[9]._u32[0] + 0x30);
        ctx->gpr[12] = spu_cwd(ctx->gpr[9], 0);
        ctx->gpr[10] = spu_shufb(ctx->gpr[7], ctx->gpr[11], ctx->gpr[12]);
        spu_ls_write128(ctx, ctx->gpr[9]._u32[0] + 0x30, ctx->gpr[10]);
        ctx->gpr[6] = spu_ls_read128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[5]._u32[0]);
        ctx->gpr[4] = spu_shufb(ctx->gpr[2], ctx->gpr[6], ctx->gpr[8]);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[5]._u32[0], ctx->gpr[4]);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        /* nop */;
        ctx->gpr[8] = spu_ila(0x110);
        ctx->gpr[79] = spu_link(0x1467010); spu_host_call_push(ctx, 0x1467010); spu_job_01466F00_spu_func_00027010(ctx); spu_host_call_pop(ctx);
        { ctx->pc = 0x1467010; SPU_TAILCALL(spu_job_01466F00_spu_func_01467010(ctx)); }
}

void spu_job_01466F00_spu_func_01467010(spu_context* ctx) {
        ctx->gpr[11] = spu_ori(ctx->gpr[3], 0);
        ctx->gpr[3] = spu_fsmbi(0x0);
        ctx->gpr[79] = spu_sf(ctx->gpr[8], ctx->gpr[79]);
        ctx->gpr[2] = spu_fceq(ctx->gpr[7], ctx->gpr[3]);
        if (ctx->gpr[2]._u32[0] != 0) { ctx->pc = 0x270F0; SPU_TAILCALL(spu_job_01466F00_spu_func_000270F0(ctx)); }
        ctx->gpr[23] = spu_ilhu(0x3F80);
        ctx->gpr[22] = spu_fceq(ctx->gpr[7], ctx->gpr[23]);
        if (ctx->gpr[22]._u32[0] == 0) { ctx->pc = 0x270B0; SPU_TAILCALL(spu_job_01466F00_spu_func_000270B0(ctx)); }
        ctx->gpr[32] = spu_ceq(ctx->gpr[11], ctx->gpr[5]);
        ctx->gpr[31] = spu_ceq(ctx->gpr[4], ctx->gpr[6]);
        ctx->gpr[30] = spu_nor(ctx->gpr[32], ctx->gpr[32]);
        ctx->gpr[29] = spu_nor(ctx->gpr[31], ctx->gpr[31]);
        ctx->gpr[27] = spu_sfi(ctx->gpr[30], 0);
        ctx->gpr[28] = spu_sfi(ctx->gpr[29], 0);
        ctx->gpr[26] = spu_or(ctx->gpr[27], ctx->gpr[28]);
        ctx->gpr[25] = spu_ceqbi(ctx->gpr[26], 0);
        ctx->gpr[24] = spu_xsbh(ctx->gpr[25]);
        if (ctx->gpr[24]._u16[1] != 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        ctx->gpr[34] = spu_shli(ctx->gpr[4], 10);
        /* branch hint (ignored) */;
        ctx->gpr[4] = spu_shli(ctx->gpr[6], 10);
        ctx->gpr[13] = spu_a(ctx->gpr[11], ctx->gpr[34]);
        ctx->gpr[12] = spu_a(ctx->gpr[5], ctx->gpr[4]);
        ctx->gpr[14] = spu_andi(ctx->gpr[13], 15);
        ctx->gpr[7] = spu_andi(ctx->gpr[12], 15);
        ctx->gpr[33] = spu_or(ctx->gpr[7], ctx->gpr[14]);
        if (ctx->gpr[33]._u32[0] != 0) { ctx->pc = 0x27138; SPU_TAILCALL(spu_job_01466F00_spu_func_00027138(ctx)); }
        ctx->gpr[3] = spu_il(0);
        ctx->gpr[4] = spu_il(1024);
        { ctx->pc = 0x1467084; SPU_TAILCALL(spu_job_01466F00_spu_func_01467084(ctx)); }
}

void spu_job_01466F00_spu_func_01467084(spu_context* ctx) {
        ctx->gpr[36] = spu_ls_read128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[12]._u32[0]);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[13]._u32[0], ctx->gpr[36]);
        ctx->gpr[3] = spu_ai(ctx->gpr[3], 16);
        ctx->gpr[35] = spu_ceq(ctx->gpr[3], ctx->gpr[4]);
        if (ctx->gpr[35]._u32[0] != 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        ctx->gpr[36] = spu_ls_read128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[12]._u32[0]);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[13]._u32[0], ctx->gpr[36]);
        ctx->gpr[3] = spu_ai(ctx->gpr[3], 16);
        ctx->gpr[35] = spu_ceq(ctx->gpr[3], ctx->gpr[4]);
        if (ctx->gpr[35]._u32[0] == 0) { ctx->pc = 0x27084; SPU_TAILCALL(spu_job_01466F00_spu_func_00027084(ctx)); }
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
}

void spu_job_01466F00_spu_func_014670B0(spu_context* ctx) {
        ctx->gpr[9] = spu_shli(ctx->gpr[4], 10);
        /* branch hint (ignored) */;
        ctx->gpr[13] = spu_shli(ctx->gpr[6], 10);
        ctx->gpr[8] = spu_fsmbi(0x0);
        ctx->gpr[10] = spu_ila(0x10203);
        ctx->gpr[3] = spu_il(1024);
        ctx->gpr[11] = spu_a(ctx->gpr[9], ctx->gpr[11]);
        ctx->gpr[7] = spu_shufb(ctx->gpr[7], ctx->gpr[7], ctx->gpr[10]);
        ctx->gpr[4] = spu_a(ctx->gpr[13], ctx->gpr[5]);
        { ctx->pc = 0x14670D4; SPU_TAILCALL(spu_job_01466F00_spu_func_014670D4(ctx)); }
}

void spu_job_01466F00_spu_func_014670D4(spu_context* ctx) {
        ctx->gpr[14] = spu_ls_read128(ctx, ctx->gpr[8]._u32[0] + ctx->gpr[4]._u32[0]);
        ctx->gpr[6] = spu_fm(ctx->gpr[14], ctx->gpr[7]);
        spu_ls_write128(ctx, ctx->gpr[8]._u32[0] + ctx->gpr[11]._u32[0], ctx->gpr[6]);
        ctx->gpr[8] = spu_ai(ctx->gpr[8], 16);
        ctx->gpr[5] = spu_ceq(ctx->gpr[8], ctx->gpr[3]);
        if (ctx->gpr[5]._u32[0] == 0) { ctx->pc = 0x270D4; SPU_TAILCALL(spu_job_01466F00_spu_func_000270D4(ctx)); }
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
}

void spu_job_01466F00_spu_func_014670F0(spu_context* ctx) {
        ctx->gpr[7] = spu_shli(ctx->gpr[4], 10);
        /* branch hint (ignored) */;
        ctx->gpr[6] = spu_il(0);
        ctx->gpr[5] = spu_a(ctx->gpr[11], ctx->gpr[7]);
        ctx->gpr[2] = spu_andi(ctx->gpr[5], 15);
        if (ctx->gpr[2]._u32[0] != 0) { ctx->pc = 0x27240; SPU_TAILCALL(spu_job_01466F00_spu_func_00027240(ctx)); }
        ctx->gpr[3] = spu_il(0);
        ctx->gpr[4] = spu_il(1024);
        { ctx->pc = 0x1467110; SPU_TAILCALL(spu_job_01466F00_spu_func_01467110(ctx)); }
}

void spu_job_01466F00_spu_func_01467110(spu_context* ctx) {
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[5]._u32[0], ctx->gpr[6]);
        ctx->gpr[3] = spu_ai(ctx->gpr[3], 16);
        ctx->gpr[7] = spu_ceq(ctx->gpr[3], ctx->gpr[4]);
        if (ctx->gpr[7]._u32[0] != 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[5]._u32[0], ctx->gpr[6]);
        ctx->gpr[3] = spu_ai(ctx->gpr[3], 16);
        ctx->gpr[7] = spu_ceq(ctx->gpr[3], ctx->gpr[4]);
        if (ctx->gpr[7]._u32[0] == 0) { ctx->pc = 0x27110; SPU_TAILCALL(spu_job_01466F00_spu_func_00027110(ctx)); }
        /* nop */;
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
}

void spu_job_01466F00_spu_func_01467138(spu_context* ctx) {
        ctx->gpr[57] = spu_sf(ctx->gpr[14], ctx->gpr[7]);
        ctx->gpr[53] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + ctx->gpr[4]._u32[0]);
        ctx->gpr[61] = spu_ila(0x11990);
        ctx->gpr[54] = spu_ls_read128(ctx, ctx->gpr[12]._u32[0] + 0x10);
        ctx->gpr[60] = spu_shli(ctx->gpr[57], 4);
        ctx->gpr[51] = spu_fsmbi(0xFFFF);
        ctx->gpr[63] = spu_il(1024);
        ctx->gpr[41] = spu_ls_read128(ctx, ctx->gpr[13]._u32[0] + 0x0);
        ctx->gpr[59] = spu_a(ctx->gpr[61], ctx->gpr[79]);
        ctx->gpr[58] = spu_a(ctx->gpr[14], ctx->gpr[63]);
        ctx->gpr[55] = spu_cgti(ctx->gpr[57], 0);
        ctx->gpr[52] = spu_ls_read128(ctx, ctx->gpr[60]._u32[0] + ctx->gpr[59]._u32[0]);
        ctx->gpr[56] = spu_sfi(ctx->gpr[58], 0);
        ctx->gpr[46] = spu_rotqmby(ctx->gpr[53], ctx->gpr[57]);
        ctx->gpr[37] = spu_clgti(ctx->gpr[58], 15);
        /* nop */;
        ctx->gpr[5] = spu_sfi(ctx->gpr[14], 16);
        ctx->gpr[48] = spu_rotqmby(ctx->gpr[51], ctx->gpr[56]);
        ctx->gpr[50] = spu_ceqi(ctx->gpr[55], 0);
        ctx->gpr[49] = spu_ceqi(ctx->gpr[37], 0);
        ctx->gpr[42] = spu_shlqby(ctx->gpr[51], ctx->gpr[5]);
        ctx->gpr[47] = spu_shufb(ctx->gpr[53], ctx->gpr[54], ctx->gpr[52]);
        ctx->gpr[45] = spu_fsm(ctx->gpr[50]);
        ctx->gpr[43] = spu_fsm(ctx->gpr[49]);
        ctx->gpr[44] = spu_or(ctx->gpr[42], ctx->gpr[48]);
        ctx->gpr[39] = spu_selb(ctx->gpr[47], ctx->gpr[46], ctx->gpr[45]);
        ctx->gpr[40] = spu_selb(ctx->gpr[42], ctx->gpr[44], ctx->gpr[43]);
        ctx->gpr[38] = spu_selb(ctx->gpr[39], ctx->gpr[41], ctx->gpr[40]);
        spu_ls_write128(ctx, ctx->gpr[13]._u32[0] + 0x0, ctx->gpr[38]);
        if (ctx->gpr[37]._u32[0] == 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        ctx->gpr[7] = spu_a(ctx->gpr[12], ctx->gpr[5]);
        /* branch hint (ignored) */;
        ctx->gpr[67] = spu_ila(0x11990);
        ctx->gpr[69] = spu_andi(ctx->gpr[7], 15);
        ctx->gpr[68] = spu_il(1024);
        ctx->gpr[66] = spu_shli(ctx->gpr[69], 4);
        ctx->gpr[65] = spu_a(ctx->gpr[67], ctx->gpr[79]);
        ctx->gpr[8] = spu_sf(ctx->gpr[5], ctx->gpr[68]);
        ctx->gpr[11] = spu_a(ctx->gpr[13], ctx->gpr[5]);
        /* nop */;
        ctx->gpr[64] = spu_clgti(ctx->gpr[8], 15);
        ctx->gpr[9] = spu_ls_read128(ctx, ctx->gpr[66]._u32[0] + ctx->gpr[65]._u32[0]);
        /* nop */;
        if (ctx->gpr[64]._u32[0] == 0) { ctx->pc = 0x27210; SPU_TAILCALL(spu_job_01466F00_spu_func_00027210(ctx)); }
        { ctx->pc = 0x14671E8; SPU_TAILCALL(spu_job_01466F00_spu_func_014671E8(ctx)); }
}

void spu_job_01466F00_spu_func_014671E8(spu_context* ctx) {
        ctx->gpr[8] = spu_ai(ctx->gpr[8], -16);
        ctx->gpr[72] = spu_ls_read128(ctx, ctx->gpr[7]._u32[0] + 0x0);
        ctx->gpr[7] = spu_ai(ctx->gpr[7], 16);
        ctx->gpr[70] = spu_clgti(ctx->gpr[8], 15);
        ctx->gpr[73] = spu_ls_read128(ctx, ctx->gpr[7]._u32[0] + 0x0);
        ctx->gpr[71] = spu_shufb(ctx->gpr[72], ctx->gpr[73], ctx->gpr[9]);
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[11]._u32[0] + 0x0, ctx->gpr[71]);
        ctx->gpr[11] = spu_ai(ctx->gpr[11], 16);
        if (ctx->gpr[70]._u32[0] != 0) { ctx->pc = 0x271E8; SPU_TAILCALL(spu_job_01466F00_spu_func_000271E8(ctx)); }
        { ctx->pc = 0x1467210; SPU_TAILCALL(spu_job_01466F00_spu_func_01467210(ctx)); }
}

void spu_job_01466F00_spu_func_01467210(spu_context* ctx) {
        /* branch hint (ignored) */;
        if (ctx->gpr[8]._u32[0] == 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        ctx->gpr[79] = spu_sfi(ctx->gpr[8], 0);
        ctx->gpr[3] = spu_ls_read128(ctx, ctx->gpr[7]._u32[0] + 0x10);
        ctx->gpr[2] = spu_il(-1);
        ctx->gpr[78] = spu_ls_read128(ctx, ctx->gpr[7]._u32[0] + 0x0);
        ctx->gpr[77] = spu_ls_read128(ctx, ctx->gpr[11]._u32[0] + 0x0);
        ctx->gpr[76] = spu_rotqmby(ctx->gpr[2], ctx->gpr[79]);
        ctx->gpr[75] = spu_shufb(ctx->gpr[78], ctx->gpr[3], ctx->gpr[9]);
        ctx->gpr[74] = spu_selb(ctx->gpr[75], ctx->gpr[77], ctx->gpr[76]);
        spu_ls_write128(ctx, ctx->gpr[11]._u32[0] + 0x0, ctx->gpr[74]);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
}

void spu_job_01466F00_spu_func_01467240(spu_context* ctx) {
        ctx->gpr[4] = spu_il(1024);
        /* branch hint (ignored) */;
        ctx->gpr[8] = spu_sfi(ctx->gpr[2], 16);
        ctx->gpr[12] = spu_fsmbi(0xFFFF);
        ctx->gpr[9] = spu_a(ctx->gpr[2], ctx->gpr[4]);
        ctx->gpr[13] = spu_clgti(ctx->gpr[9], 15);
        ctx->gpr[10] = spu_shlqby(ctx->gpr[12], ctx->gpr[8]);
        if (ctx->gpr[13]._u32[0] == 0) { ctx->pc = 0x272BC; SPU_TAILCALL(spu_job_01466F00_spu_func_000272BC(ctx)); }
        ctx->gpr[4] = spu_sf(ctx->gpr[8], ctx->gpr[4]);
        ctx->gpr[16] = spu_ls_read128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[7]._u32[0]);
        ctx->gpr[5] = spu_a(ctx->gpr[5], ctx->gpr[8]);
        ctx->gpr[12] = spu_clgti(ctx->gpr[4], 15);
        ctx->gpr[15] = spu_and(ctx->gpr[16], ctx->gpr[10]);
        spu_ls_write128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[7]._u32[0], ctx->gpr[15]);
        /* nop */;
        if (ctx->gpr[12]._u32[0] == 0) { ctx->pc = 0x27294; SPU_TAILCALL(spu_job_01466F00_spu_func_00027294(ctx)); }
        { ctx->pc = 0x1467280; SPU_TAILCALL(spu_job_01466F00_spu_func_01467280(ctx)); }
}

void spu_job_01466F00_spu_func_01467280(spu_context* ctx) {
        ctx->gpr[4] = spu_ai(ctx->gpr[4], -16);
        spu_ls_write128(ctx, ctx->gpr[5]._u32[0] + 0x0, ctx->gpr[6]);
        ctx->gpr[5] = spu_ai(ctx->gpr[5], 16);
        ctx->gpr[11] = spu_clgti(ctx->gpr[4], 15);
        if (ctx->gpr[11]._u32[0] != 0) { ctx->pc = 0x27280; SPU_TAILCALL(spu_job_01466F00_spu_func_00027280(ctx)); }
        { ctx->pc = 0x1467294; SPU_TAILCALL(spu_job_01466F00_spu_func_01467294(ctx)); }
}

void spu_job_01466F00_spu_func_01467294(spu_context* ctx) {
        /* branch hint (ignored) */;
        /* nop */;
        if (ctx->gpr[4]._u32[0] == 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        ctx->gpr[21] = spu_sfi(ctx->gpr[4], 0);
        ctx->gpr[18] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + 0x0);
        ctx->gpr[20] = spu_il(-1);
        ctx->gpr[19] = spu_rotqmby(ctx->gpr[20], ctx->gpr[21]);
        ctx->gpr[17] = spu_and(ctx->gpr[18], ctx->gpr[19]);
        spu_ls_write128(ctx, ctx->gpr[5]._u32[0] + 0x0, ctx->gpr[17]);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
}

void spu_job_01466F00_spu_func_014672BC(spu_context* ctx) {
        /* branch hint (ignored) */;
        ctx->gpr[14] = spu_sfi(ctx->gpr[9], 0);
        ctx->gpr[5] = spu_ls_read128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[7]._u32[0]);
        /* nop */;
        /* nop */;
        /* nop */;
        ctx->gpr[9] = spu_rotqmby(ctx->gpr[12], ctx->gpr[14]);
        ctx->gpr[6] = spu_or(ctx->gpr[10], ctx->gpr[9]);
        ctx->gpr[4] = spu_and(ctx->gpr[5], ctx->gpr[6]);
        spu_ls_write128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[7]._u32[0], ctx->gpr[4]);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        ctx->gpr[26] = spu_ori(ctx->gpr[3], 0);
        ctx->gpr[2] = spu_ls_read128(ctx, ctx->gpr[3]._u32[0] + 0x0);
        ctx->gpr[23] = spu_ori(ctx->gpr[5], 0);
        ctx->gpr[2] = spu_rotqbyi(ctx->gpr[2], 4);
        /* nop */;
        if (ctx->gpr[2]._u32[0] != 0) { ctx->pc = 0x274C0; SPU_TAILCALL(spu_job_01466F00_spu_func_000274C0(ctx)); }
        ctx->gpr[13] = spu_csflt(ctx->gpr[6], 155);
        ctx->gpr[17] = spu_ls_read128(ctx, ctx->gpr[3]._u32[0] + 0x10);
        ctx->gpr[16] = spu_ilhu(0x40C9);
        ctx->gpr[18] = spu_cwd(ctx->gpr[1], 0);
        ctx->gpr[19] = spu_ls_read128(ctx, ctx->gpr[3]._u32[0] + 0x0);
        ctx->gpr[16] = spu_iohl(ctx->gpr[16], 0xFDA);
        ctx->gpr[25] = spu_cwd(ctx->gpr[1], 8);
        ctx->gpr[10] = spu_cwd(ctx->gpr[1], 12);
        /* nop */;
        ctx->gpr[11] = spu_shufb(ctx->gpr[7], ctx->gpr[17], ctx->gpr[18]);
        ctx->gpr[5] = spu_fm(ctx->gpr[13], ctx->gpr[16]);
        ctx->gpr[7] = spu_frest(ctx->gpr[4]);
        ctx->gpr[12] = spu_shufb(ctx->gpr[4], ctx->gpr[19], ctx->gpr[18]);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + 0x10, ctx->gpr[11]);
        ctx->gpr[3] = spu_fi(ctx->gpr[4], ctx->gpr[7]);
        ctx->gpr[9] = spu_shufb(ctx->gpr[23], ctx->gpr[12], ctx->gpr[25]);
        ctx->gpr[8] = spu_shufb(ctx->gpr[6], ctx->gpr[9], ctx->gpr[10]);
        ctx->gpr[6] = spu_fm(ctx->gpr[5], ctx->gpr[3]);
        spu_ls_write128(ctx, ctx->gpr[26]._u32[0] + 0x0, ctx->gpr[8]);
        ctx->gpr[4] = spu_fnms(ctx->gpr[6], ctx->gpr[4], ctx->gpr[5]);
        ctx->gpr[4] = spu_fma(ctx->gpr[4], ctx->gpr[3], ctx->gpr[6]);
        if (ctx->gpr[23]._u32[0] != 0) { ctx->pc = 0x276AC; SPU_TAILCALL(spu_job_01466F00_spu_func_000276AC(ctx)); }
        ctx->gpr[6] = spu_ori(ctx->gpr[4], 0);
        /* branch hint (ignored) */;
        ctx->gpr[14] = spu_ilhu(0x3F22);
        ctx->gpr[27] = spu_ls_read128(ctx, ctx->gpr[26]._u32[0] + 0x20);
        ctx->gpr[16] = spu_ori(ctx->gpr[6], 0);
        ctx->gpr[14] = spu_iohl(ctx->gpr[14], 0xF983);
        ctx->gpr[41] = spu_ilhu(0x8000);
        ctx->gpr[23] = spu_fm(ctx->gpr[16], ctx->gpr[14]);
        ctx->gpr[29] = spu_ilhu(0x3F00);
        ctx->gpr[3] = spu_ilhu(0x3FC9);
        ctx->gpr[79] = spu_ilhu(0x33A2);
        ctx->gpr[3] = spu_iohl(ctx->gpr[3], 0xFD9);
        ctx->gpr[79] = spu_iohl(ctx->gpr[79], 0x2168);
        ctx->gpr[15] = spu_selb(ctx->gpr[29], ctx->gpr[23], ctx->gpr[41]);
        ctx->gpr[17] = spu_fm(ctx->gpr[6], ctx->gpr[14]);
        ctx->gpr[19] = spu_fa(ctx->gpr[23], ctx->gpr[15]);
        ctx->gpr[70] = spu_ilhu(0xBAB2);
        ctx->gpr[71] = spu_ilhu(0x3D2A);
        ctx->gpr[68] = spu_ilhu(0xB94C);
        ctx->gpr[69] = spu_ilhu(0x3C08);
        ctx->gpr[18] = spu_selb(ctx->gpr[29], ctx->gpr[17], ctx->gpr[41]);
        ctx->gpr[13] = spu_cflts(ctx->gpr[19], 173);
        ctx->gpr[70] = spu_iohl(ctx->gpr[70], 0x4992);
        ctx->gpr[4] = spu_fa(ctx->gpr[17], ctx->gpr[18]);
        ctx->gpr[71] = spu_iohl(ctx->gpr[71], 0xA035);
        ctx->gpr[68] = spu_iohl(ctx->gpr[68], 0x8C6D);
        ctx->gpr[69] = spu_iohl(ctx->gpr[69], 0x8342);
        ctx->gpr[61] = spu_ilhu(0xBEFF);
        ctx->gpr[10] = spu_csflt(ctx->gpr[13], 155);
        ctx->gpr[59] = spu_ilhu(0xBE2A);
        ctx->gpr[8] = spu_cflts(ctx->gpr[4], 173);
        ctx->gpr[61] = spu_iohl(ctx->gpr[61], 0xFFDF);
        ctx->gpr[59] = spu_iohl(ctx->gpr[59], 0xAAA1);
        ctx->gpr[53] = spu_ilhu(0x3F80);
        ctx->gpr[12] = spu_andi(ctx->gpr[13], 3);
        ctx->gpr[7] = spu_fnms(ctx->gpr[10], ctx->gpr[3], ctx->gpr[16]);
        ctx->gpr[9] = spu_ai(ctx->gpr[12], 1);
        ctx->gpr[78] = spu_csflt(ctx->gpr[8], 155);
        ctx->gpr[11] = spu_andi(ctx->gpr[9], 1);
        ctx->gpr[5] = spu_andi(ctx->gpr[9], 2);
        ctx->gpr[56] = spu_ceqi(ctx->gpr[11], 0);
        ctx->gpr[64] = spu_fnms(ctx->gpr[10], ctx->gpr[79], ctx->gpr[7]);
        ctx->gpr[50] = spu_ceqi(ctx->gpr[5], 0);
        ctx->gpr[34] = spu_ilhu(0x4000);
        ctx->gpr[2] = spu_fnms(ctx->gpr[78], ctx->gpr[3], ctx->gpr[6]);
        ctx->gpr[40] = spu_ilhu(0x3F80);
        ctx->gpr[77] = spu_andi(ctx->gpr[8], 3);
        ctx->gpr[67] = spu_fm(ctx->gpr[64], ctx->gpr[64]);
        ctx->gpr[75] = spu_ai(ctx->gpr[77], 1);
        ctx->gpr[76] = spu_ilhu(0x3F80);
        ctx->gpr[47] = spu_fnms(ctx->gpr[78], ctx->gpr[79], ctx->gpr[2]);
        ctx->gpr[72] = spu_andi(ctx->gpr[75], 1);
        ctx->gpr[31] = spu_ori(ctx->gpr[76], 1);
        ctx->gpr[74] = spu_fma(ctx->gpr[67], ctx->gpr[70], ctx->gpr[71]);
        ctx->gpr[73] = spu_fma(ctx->gpr[67], ctx->gpr[68], ctx->gpr[69]);
        ctx->gpr[65] = spu_fm(ctx->gpr[67], ctx->gpr[64]);
        ctx->gpr[54] = spu_fm(ctx->gpr[47], ctx->gpr[47]);
        ctx->gpr[43] = spu_ceqi(ctx->gpr[72], 0);
        ctx->gpr[62] = spu_andi(ctx->gpr[75], 2);
        ctx->gpr[66] = spu_fma(ctx->gpr[74], ctx->gpr[67], ctx->gpr[61]);
        ctx->gpr[63] = spu_fma(ctx->gpr[73], ctx->gpr[67], ctx->gpr[59]);
        ctx->gpr[37] = spu_ceqi(ctx->gpr[62], 0);
        ctx->gpr[60] = spu_fma(ctx->gpr[54], ctx->gpr[70], ctx->gpr[71]);
        ctx->gpr[58] = spu_fma(ctx->gpr[54], ctx->gpr[68], ctx->gpr[69]);
        ctx->gpr[48] = spu_fm(ctx->gpr[54], ctx->gpr[47]);
        ctx->gpr[55] = spu_fma(ctx->gpr[66], ctx->gpr[67], ctx->gpr[53]);
        ctx->gpr[57] = spu_fma(ctx->gpr[63], ctx->gpr[65], ctx->gpr[64]);
        ctx->gpr[52] = spu_fma(ctx->gpr[60], ctx->gpr[54], ctx->gpr[61]);
        ctx->gpr[46] = spu_fma(ctx->gpr[58], ctx->gpr[54], ctx->gpr[59]);
        ctx->gpr[51] = spu_selb(ctx->gpr[55], ctx->gpr[57], ctx->gpr[56]);
        ctx->gpr[49] = spu_xor(ctx->gpr[51], ctx->gpr[41]);
        ctx->gpr[42] = spu_fma(ctx->gpr[52], ctx->gpr[54], ctx->gpr[53]);
        ctx->gpr[45] = spu_selb(ctx->gpr[49], ctx->gpr[51], ctx->gpr[50]);
        ctx->gpr[44] = spu_fma(ctx->gpr[46], ctx->gpr[48], ctx->gpr[47]);
        ctx->gpr[39] = spu_fs(ctx->gpr[34], ctx->gpr[45]);
        ctx->gpr[38] = spu_selb(ctx->gpr[42], ctx->gpr[44], ctx->gpr[43]);
        ctx->gpr[32] = spu_fms(ctx->gpr[39], ctx->gpr[39], ctx->gpr[40]);
        ctx->gpr[36] = spu_xor(ctx->gpr[38], ctx->gpr[41]);
        ctx->gpr[35] = spu_selb(ctx->gpr[36], ctx->gpr[38], ctx->gpr[37]);
        ctx->gpr[21] = spu_fs(ctx->gpr[34], ctx->gpr[35]);
        ctx->gpr[33] = spu_frsqest(ctx->gpr[32]);
        ctx->gpr[30] = spu_fi(ctx->gpr[32], ctx->gpr[33]);
        ctx->gpr[28] = spu_fm(ctx->gpr[30], ctx->gpr[32]);
        ctx->gpr[24] = spu_fnms(ctx->gpr[30], ctx->gpr[28], ctx->gpr[31]);
        ctx->gpr[22] = spu_fm(ctx->gpr[28], ctx->gpr[29]);
        ctx->gpr[20] = spu_fma(ctx->gpr[24], ctx->gpr[22], ctx->gpr[28]);
        ctx->gpr[15] = spu_fs(ctx->gpr[21], ctx->gpr[20]);
        ctx->gpr[23] = spu_shufb(ctx->gpr[15], ctx->gpr[27], ctx->gpr[25]);
        spu_ls_write128(ctx, ctx->gpr[26]._u32[0] + 0x20, ctx->gpr[23]);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
}

void spu_job_01466F00_spu_func_014674C0(spu_context* ctx) {
        ctx->gpr[25] = spu_ceqi(ctx->gpr[2], 1);
        if (ctx->gpr[25]._u32[0] == 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        ctx->gpr[55] = spu_csflt(ctx->gpr[6], 155);
        ctx->gpr[50] = spu_frest(ctx->gpr[4]);
        ctx->gpr[56] = spu_ilhu(0x40C9);
        ctx->gpr[59] = spu_ls_read128(ctx, ctx->gpr[3]._u32[0] + 0x0);
        ctx->gpr[44] = spu_ilhu(0x3F22);
        ctx->gpr[58] = spu_cwd(ctx->gpr[1], 0);
        ctx->gpr[56] = spu_iohl(ctx->gpr[56], 0xFDA);
        ctx->gpr[57] = spu_ls_read128(ctx, ctx->gpr[3]._u32[0] + 0x10);
        ctx->gpr[48] = spu_fi(ctx->gpr[4], ctx->gpr[50]);
        ctx->gpr[54] = spu_cwd(ctx->gpr[1], 8);
        ctx->gpr[44] = spu_iohl(ctx->gpr[44], 0xF983);
        ctx->gpr[25] = spu_cwd(ctx->gpr[1], 12);
        ctx->gpr[65] = spu_ilhu(0x8000);
        ctx->gpr[49] = spu_fm(ctx->gpr[55], ctx->gpr[56]);
        ctx->gpr[43] = spu_ilhu(0x3F00);
        ctx->gpr[53] = spu_shufb(ctx->gpr[4], ctx->gpr[59], ctx->gpr[58]);
        ctx->gpr[31] = spu_ilhu(0x3FC9);
        ctx->gpr[52] = spu_shufb(ctx->gpr[7], ctx->gpr[57], ctx->gpr[58]);
        ctx->gpr[20] = spu_ilhu(0x33A2);
        ctx->gpr[31] = spu_iohl(ctx->gpr[31], 0xFD9);
        ctx->gpr[20] = spu_iohl(ctx->gpr[20], 0x2168);
        ctx->gpr[51] = spu_shufb(ctx->gpr[5], ctx->gpr[53], ctx->gpr[54]);
        ctx->gpr[47] = spu_fm(ctx->gpr[49], ctx->gpr[48]);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + 0x10, ctx->gpr[52]);
        ctx->gpr[27] = spu_ilhu(0xBAB2);
        ctx->gpr[19] = spu_ilhu(0x3D2A);
        ctx->gpr[10] = spu_ilhu(0xB94C);
        ctx->gpr[45] = spu_shufb(ctx->gpr[6], ctx->gpr[51], ctx->gpr[25]);
        ctx->gpr[18] = spu_ilhu(0x3C08);
        ctx->gpr[27] = spu_iohl(ctx->gpr[27], 0x4992);
        ctx->gpr[46] = spu_fnms(ctx->gpr[47], ctx->gpr[4], ctx->gpr[49]);
        ctx->gpr[19] = spu_iohl(ctx->gpr[19], 0xA035);
        ctx->gpr[10] = spu_iohl(ctx->gpr[10], 0x8C6D);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + 0x0, ctx->gpr[45]);
        ctx->gpr[18] = spu_iohl(ctx->gpr[18], 0x8342);
        ctx->gpr[14] = spu_ilhu(0xBEFF);
        ctx->gpr[15] = spu_ilhu(0xBE2A);
        ctx->gpr[32] = spu_fma(ctx->gpr[46], ctx->gpr[48], ctx->gpr[47]);
        ctx->gpr[14] = spu_iohl(ctx->gpr[14], 0xFFDF);
        ctx->gpr[15] = spu_iohl(ctx->gpr[15], 0xAAA1);
        ctx->gpr[56] = spu_fa(ctx->gpr[7], ctx->gpr[7]);
        ctx->gpr[76] = spu_ilhu(0x3F80);
        ctx->gpr[52] = spu_ceqi(ctx->gpr[5], 1);
        ctx->gpr[39] = spu_fm(ctx->gpr[32], ctx->gpr[44]);
        ctx->gpr[33] = spu_ori(ctx->gpr[32], 0);
        ctx->gpr[41] = spu_fm(ctx->gpr[33], ctx->gpr[44]);
        ctx->gpr[58] = spu_frest(ctx->gpr[56]);
        ctx->gpr[40] = spu_selb(ctx->gpr[43], ctx->gpr[39], ctx->gpr[65]);
        ctx->gpr[37] = spu_fa(ctx->gpr[39], ctx->gpr[40]);
        ctx->gpr[42] = spu_selb(ctx->gpr[43], ctx->gpr[41], ctx->gpr[65]);
        ctx->gpr[55] = spu_fi(ctx->gpr[56], ctx->gpr[58]);
        ctx->gpr[38] = spu_fa(ctx->gpr[41], ctx->gpr[42]);
        ctx->gpr[35] = spu_cflts(ctx->gpr[37], 173);
        ctx->gpr[36] = spu_cflts(ctx->gpr[38], 173);
        ctx->gpr[28] = spu_csflt(ctx->gpr[35], 155);
        ctx->gpr[30] = spu_andi(ctx->gpr[35], 3);
        ctx->gpr[17] = spu_andi(ctx->gpr[30], 1);
        ctx->gpr[8] = spu_csflt(ctx->gpr[36], 155);
        ctx->gpr[67] = spu_ceqi(ctx->gpr[17], 0);
        ctx->gpr[6] = spu_andi(ctx->gpr[30], 2);
        ctx->gpr[24] = spu_fnms(ctx->gpr[28], ctx->gpr[31], ctx->gpr[32]);
        ctx->gpr[60] = spu_ceqi(ctx->gpr[6], 0);
        ctx->gpr[34] = spu_andi(ctx->gpr[36], 3);
        ctx->gpr[29] = spu_fnms(ctx->gpr[8], ctx->gpr[31], ctx->gpr[33]);
        ctx->gpr[21] = spu_ai(ctx->gpr[34], 1);
        ctx->gpr[73] = spu_fnms(ctx->gpr[28], ctx->gpr[20], ctx->gpr[24]);
        ctx->gpr[16] = spu_andi(ctx->gpr[21], 1);
        ctx->gpr[4] = spu_andi(ctx->gpr[21], 2);
        ctx->gpr[70] = spu_ceqi(ctx->gpr[16], 0);
        ctx->gpr[79] = spu_fnms(ctx->gpr[8], ctx->gpr[20], ctx->gpr[29]);
        ctx->gpr[63] = spu_ceqi(ctx->gpr[4], 0);
        ctx->gpr[77] = spu_fm(ctx->gpr[73], ctx->gpr[73]);
        ctx->gpr[2] = spu_fm(ctx->gpr[79], ctx->gpr[79]);
        ctx->gpr[11] = spu_fma(ctx->gpr[77], ctx->gpr[27], ctx->gpr[19]);
        ctx->gpr[12] = spu_fma(ctx->gpr[77], ctx->gpr[10], ctx->gpr[18]);
        ctx->gpr[74] = spu_fm(ctx->gpr[77], ctx->gpr[73]);
        ctx->gpr[7] = spu_fma(ctx->gpr[2], ctx->gpr[27], ctx->gpr[19]);
        ctx->gpr[13] = spu_fma(ctx->gpr[2], ctx->gpr[10], ctx->gpr[18]);
        ctx->gpr[75] = spu_fma(ctx->gpr[11], ctx->gpr[77], ctx->gpr[14]);
        ctx->gpr[72] = spu_fma(ctx->gpr[12], ctx->gpr[77], ctx->gpr[15]);
        ctx->gpr[5] = spu_fm(ctx->gpr[2], ctx->gpr[79]);
        ctx->gpr[3] = spu_fma(ctx->gpr[7], ctx->gpr[2], ctx->gpr[14]);
        ctx->gpr[78] = spu_fma(ctx->gpr[13], ctx->gpr[2], ctx->gpr[15]);
        ctx->gpr[66] = spu_fma(ctx->gpr[75], ctx->gpr[77], ctx->gpr[76]);
        ctx->gpr[68] = spu_fma(ctx->gpr[72], ctx->gpr[74], ctx->gpr[73]);
        ctx->gpr[69] = spu_fma(ctx->gpr[3], ctx->gpr[2], ctx->gpr[76]);
        ctx->gpr[71] = spu_fma(ctx->gpr[78], ctx->gpr[5], ctx->gpr[79]);
        ctx->gpr[61] = spu_selb(ctx->gpr[66], ctx->gpr[68], ctx->gpr[67]);
        ctx->gpr[59] = spu_xor(ctx->gpr[61], ctx->gpr[65]);
        ctx->gpr[57] = spu_selb(ctx->gpr[59], ctx->gpr[61], ctx->gpr[60]);
        ctx->gpr[64] = spu_selb(ctx->gpr[69], ctx->gpr[71], ctx->gpr[70]);
        ctx->gpr[54] = spu_fm(ctx->gpr[57], ctx->gpr[55]);
        ctx->gpr[62] = spu_xor(ctx->gpr[64], ctx->gpr[65]);
        ctx->gpr[9] = spu_selb(ctx->gpr[62], ctx->gpr[64], ctx->gpr[63]);
        ctx->gpr[53] = spu_fnms(ctx->gpr[54], ctx->gpr[56], ctx->gpr[57]);
        ctx->gpr[7] = spu_fma(ctx->gpr[53], ctx->gpr[55], ctx->gpr[54]);
        if (ctx->gpr[52]._u32[0] != 0) { ctx->pc = 0x27920; SPU_TAILCALL(spu_job_01466F00_spu_func_00027920(ctx)); }
        ctx->gpr[22] = spu_ceqi(ctx->gpr[23], 2);
        if (ctx->gpr[22]._u32[0] != 0) { ctx->pc = 0x279A8; SPU_TAILCALL(spu_job_01466F00_spu_func_000279A8(ctx)); }
        ctx->gpr[10] = spu_il(0);
        ctx->gpr[11] = spu_ilhu(0x3F80);
        /* nop */;
        ctx->gpr[8] = spu_ori(ctx->gpr[10], 0);
        ctx->gpr[22] = spu_shlqbyi(ctx->gpr[10], 0);
        ctx->gpr[12] = spu_ori(ctx->gpr[10], 0);
        if (ctx->gpr[23]._u32[0] == 0) { ctx->pc = 0x278A8; SPU_TAILCALL(spu_job_01466F00_spu_func_000278A8(ctx)); }
        { ctx->pc = 0x1467670; SPU_TAILCALL(spu_job_01466F00_spu_func_01467670(ctx)); }
}

void spu_job_01466F00_spu_func_01467670(spu_context* ctx) {
        ctx->gpr[60] = spu_ls_read128(ctx, ctx->gpr[26]._u32[0] + 0x20);
        ctx->gpr[23] = spu_cwd(ctx->gpr[1], 0);
        /* branch hint (ignored) */;
        ctx->gpr[58] = spu_cwd(ctx->gpr[1], 4);
        ctx->gpr[55] = spu_cwd(ctx->gpr[1], 8);
        ctx->gpr[59] = spu_ls_read128(ctx, ctx->gpr[26]._u32[0] + 0x30);
        ctx->gpr[57] = spu_shufb(ctx->gpr[12], ctx->gpr[60], ctx->gpr[23]);
        ctx->gpr[53] = spu_cwd(ctx->gpr[1], 12);
        ctx->gpr[54] = spu_shufb(ctx->gpr[10], ctx->gpr[57], ctx->gpr[58]);
        ctx->gpr[56] = spu_shufb(ctx->gpr[11], ctx->gpr[59], ctx->gpr[23]);
        ctx->gpr[52] = spu_shufb(ctx->gpr[22], ctx->gpr[54], ctx->gpr[55]);
        spu_ls_write128(ctx, ctx->gpr[26]._u32[0] + 0x30, ctx->gpr[56]);
        ctx->gpr[25] = spu_shufb(ctx->gpr[8], ctx->gpr[52], ctx->gpr[53]);
        spu_ls_write128(ctx, ctx->gpr[26]._u32[0] + 0x20, ctx->gpr[25]);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
}

void spu_job_01466F00_spu_func_014676AC(spu_context* ctx) {
        ctx->gpr[14] = spu_ceqi(ctx->gpr[23], 1);
        /* nop */;
        if (ctx->gpr[14]._u32[0] != 0) { ctx->pc = 0x27738; SPU_TAILCALL(spu_job_01466F00_spu_func_00027738(ctx)); }
        ctx->gpr[48] = spu_ilhu(0x3F7F);
        /* branch hint (ignored) */;
        ctx->gpr[50] = spu_ilhu(0x33BB);
        ctx->gpr[20] = spu_ls_read128(ctx, ctx->gpr[26]._u32[0] + 0x20);
        ctx->gpr[51] = spu_il(1);
        ctx->gpr[48] = spu_iohl(ctx->gpr[48], 0xFFFF);
        ctx->gpr[50] = spu_iohl(ctx->gpr[50], 0xBD2F);
        ctx->gpr[49] = spu_ceqi(ctx->gpr[51], 0);
        ctx->gpr[47] = spu_ilhu(0x8000);
        ctx->gpr[45] = spu_selb(ctx->gpr[48], ctx->gpr[50], ctx->gpr[49]);
        ctx->gpr[46] = spu_il(2);
        ctx->gpr[43] = spu_xor(ctx->gpr[45], ctx->gpr[47]);
        ctx->gpr[44] = spu_ceqi(ctx->gpr[46], 0);
        ctx->gpr[41] = spu_ilhu(0x4000);
        ctx->gpr[40] = spu_selb(ctx->gpr[43], ctx->gpr[45], ctx->gpr[44]);
        ctx->gpr[39] = spu_ilhu(0x3F80);
        ctx->gpr[38] = spu_fs(ctx->gpr[41], ctx->gpr[40]);
        ctx->gpr[42] = spu_ilhu(0x3F80);
        ctx->gpr[33] = spu_ilhu(0x3F00);
        ctx->gpr[35] = spu_ori(ctx->gpr[42], 1);
        ctx->gpr[22] = spu_fa(ctx->gpr[40], ctx->gpr[41]);
        ctx->gpr[36] = spu_fms(ctx->gpr[38], ctx->gpr[38], ctx->gpr[39]);
        ctx->gpr[37] = spu_frsqest(ctx->gpr[36]);
        ctx->gpr[34] = spu_fi(ctx->gpr[36], ctx->gpr[37]);
        ctx->gpr[31] = spu_fm(ctx->gpr[34], ctx->gpr[36]);
        ctx->gpr[30] = spu_fnms(ctx->gpr[34], ctx->gpr[31], ctx->gpr[35]);
        ctx->gpr[32] = spu_fm(ctx->gpr[31], ctx->gpr[33]);
        ctx->gpr[29] = spu_fma(ctx->gpr[30], ctx->gpr[32], ctx->gpr[31]);
        ctx->gpr[24] = spu_fs(ctx->gpr[22], ctx->gpr[29]);
        ctx->gpr[28] = spu_shufb(ctx->gpr[24], ctx->gpr[20], ctx->gpr[25]);
        spu_ls_write128(ctx, ctx->gpr[26]._u32[0] + 0x20, ctx->gpr[28]);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
}

void spu_job_01466F00_spu_func_01467738(spu_context* ctx) {
        ctx->gpr[6] = spu_ori(ctx->gpr[4], 0);
        /* branch hint (ignored) */;
        ctx->gpr[15] = spu_ilhu(0x3F22);
        ctx->gpr[28] = spu_ls_read128(ctx, ctx->gpr[26]._u32[0] + 0x20);
        ctx->gpr[18] = spu_ori(ctx->gpr[6], 0);
        ctx->gpr[25] = spu_cwd(ctx->gpr[1], 8);
        ctx->gpr[15] = spu_iohl(ctx->gpr[15], 0xF983);
        ctx->gpr[43] = spu_ilhu(0x8000);
        ctx->gpr[27] = spu_fm(ctx->gpr[18], ctx->gpr[15]);
        ctx->gpr[31] = spu_ilhu(0x3F00);
        ctx->gpr[11] = spu_ilhu(0x3FC9);
        ctx->gpr[8] = spu_ilhu(0x33A2);
        ctx->gpr[11] = spu_iohl(ctx->gpr[11], 0xFD9);
        ctx->gpr[8] = spu_iohl(ctx->gpr[8], 0x2168);
        ctx->gpr[21] = spu_selb(ctx->gpr[31], ctx->gpr[27], ctx->gpr[43]);
        ctx->gpr[19] = spu_fm(ctx->gpr[6], ctx->gpr[15]);
        ctx->gpr[23] = spu_fa(ctx->gpr[27], ctx->gpr[21]);
        ctx->gpr[72] = spu_ilhu(0xBAB2);
        ctx->gpr[73] = spu_ilhu(0x3D2A);
        ctx->gpr[70] = spu_ilhu(0xB94C);
        ctx->gpr[71] = spu_ilhu(0x3C08);
        ctx->gpr[14] = spu_selb(ctx->gpr[31], ctx->gpr[19], ctx->gpr[43]);
        ctx->gpr[17] = spu_cflts(ctx->gpr[23], 173);
        ctx->gpr[72] = spu_iohl(ctx->gpr[72], 0x4992);
        ctx->gpr[4] = spu_fa(ctx->gpr[19], ctx->gpr[14]);
        ctx->gpr[73] = spu_iohl(ctx->gpr[73], 0xA035);
        ctx->gpr[70] = spu_iohl(ctx->gpr[70], 0x8C6D);
        ctx->gpr[71] = spu_iohl(ctx->gpr[71], 0x8342);
        ctx->gpr[63] = spu_ilhu(0xBEFF);
        ctx->gpr[10] = spu_csflt(ctx->gpr[17], 155);
        ctx->gpr[61] = spu_ilhu(0xBE2A);
        ctx->gpr[9] = spu_cflts(ctx->gpr[4], 173);
        ctx->gpr[63] = spu_iohl(ctx->gpr[63], 0xFFDF);
        ctx->gpr[61] = spu_iohl(ctx->gpr[61], 0xAAA1);
        ctx->gpr[55] = spu_ilhu(0x3F80);
        ctx->gpr[16] = spu_andi(ctx->gpr[17], 3);
        ctx->gpr[7] = spu_fnms(ctx->gpr[10], ctx->gpr[11], ctx->gpr[18]);
        ctx->gpr[12] = spu_ai(ctx->gpr[16], 1);
        ctx->gpr[2] = spu_csflt(ctx->gpr[9], 155);
        ctx->gpr[13] = spu_andi(ctx->gpr[12], 1);
        ctx->gpr[5] = spu_andi(ctx->gpr[12], 2);
        ctx->gpr[58] = spu_ceqi(ctx->gpr[13], 0);
        ctx->gpr[66] = spu_fnms(ctx->gpr[10], ctx->gpr[8], ctx->gpr[7]);
        ctx->gpr[52] = spu_ceqi(ctx->gpr[5], 0);
        ctx->gpr[37] = spu_ilhu(0x4000);
        ctx->gpr[3] = spu_fnms(ctx->gpr[2], ctx->gpr[11], ctx->gpr[6]);
        ctx->gpr[42] = spu_ilhu(0x3F80);
        ctx->gpr[79] = spu_andi(ctx->gpr[9], 3);
        ctx->gpr[69] = spu_fm(ctx->gpr[66], ctx->gpr[66]);
        ctx->gpr[77] = spu_ai(ctx->gpr[79], 1);
        ctx->gpr[78] = spu_ilhu(0x3F80);
        ctx->gpr[49] = spu_fnms(ctx->gpr[2], ctx->gpr[8], ctx->gpr[3]);
        ctx->gpr[74] = spu_andi(ctx->gpr[77], 1);
        ctx->gpr[33] = spu_ori(ctx->gpr[78], 1);
        ctx->gpr[76] = spu_fma(ctx->gpr[69], ctx->gpr[72], ctx->gpr[73]);
        ctx->gpr[75] = spu_fma(ctx->gpr[69], ctx->gpr[70], ctx->gpr[71]);
        ctx->gpr[67] = spu_fm(ctx->gpr[69], ctx->gpr[66]);
        ctx->gpr[56] = spu_fm(ctx->gpr[49], ctx->gpr[49]);
        ctx->gpr[45] = spu_ceqi(ctx->gpr[74], 0);
        ctx->gpr[64] = spu_andi(ctx->gpr[77], 2);
        ctx->gpr[68] = spu_fma(ctx->gpr[76], ctx->gpr[69], ctx->gpr[63]);
        ctx->gpr[65] = spu_fma(ctx->gpr[75], ctx->gpr[69], ctx->gpr[61]);
        ctx->gpr[39] = spu_ceqi(ctx->gpr[64], 0);
        ctx->gpr[62] = spu_fma(ctx->gpr[56], ctx->gpr[72], ctx->gpr[73]);
        ctx->gpr[60] = spu_fma(ctx->gpr[56], ctx->gpr[70], ctx->gpr[71]);
        ctx->gpr[50] = spu_fm(ctx->gpr[56], ctx->gpr[49]);
        ctx->gpr[57] = spu_fma(ctx->gpr[68], ctx->gpr[69], ctx->gpr[55]);
        ctx->gpr[59] = spu_fma(ctx->gpr[65], ctx->gpr[67], ctx->gpr[66]);
        ctx->gpr[54] = spu_fma(ctx->gpr[62], ctx->gpr[56], ctx->gpr[63]);
        ctx->gpr[48] = spu_fma(ctx->gpr[60], ctx->gpr[56], ctx->gpr[61]);
        ctx->gpr[53] = spu_selb(ctx->gpr[57], ctx->gpr[59], ctx->gpr[58]);
        ctx->gpr[51] = spu_xor(ctx->gpr[53], ctx->gpr[43]);
        ctx->gpr[44] = spu_fma(ctx->gpr[54], ctx->gpr[56], ctx->gpr[55]);
        ctx->gpr[47] = spu_selb(ctx->gpr[51], ctx->gpr[53], ctx->gpr[52]);
        ctx->gpr[46] = spu_fma(ctx->gpr[48], ctx->gpr[50], ctx->gpr[49]);
        ctx->gpr[41] = spu_fa(ctx->gpr[47], ctx->gpr[37]);
        ctx->gpr[40] = spu_selb(ctx->gpr[44], ctx->gpr[46], ctx->gpr[45]);
        ctx->gpr[34] = spu_fms(ctx->gpr[41], ctx->gpr[41], ctx->gpr[42]);
        ctx->gpr[38] = spu_xor(ctx->gpr[40], ctx->gpr[43]);
        ctx->gpr[36] = spu_selb(ctx->gpr[38], ctx->gpr[40], ctx->gpr[39]);
        ctx->gpr[20] = spu_fa(ctx->gpr[36], ctx->gpr[37]);
        ctx->gpr[35] = spu_frsqest(ctx->gpr[34]);
        ctx->gpr[32] = spu_fi(ctx->gpr[34], ctx->gpr[35]);
        ctx->gpr[29] = spu_fm(ctx->gpr[32], ctx->gpr[34]);
        ctx->gpr[22] = spu_fnms(ctx->gpr[32], ctx->gpr[29], ctx->gpr[33]);
        ctx->gpr[30] = spu_fm(ctx->gpr[29], ctx->gpr[31]);
        ctx->gpr[24] = spu_fma(ctx->gpr[22], ctx->gpr[30], ctx->gpr[29]);
        ctx->gpr[21] = spu_fs(ctx->gpr[20], ctx->gpr[24]);
        ctx->gpr[27] = spu_shufb(ctx->gpr[21], ctx->gpr[28], ctx->gpr[25]);
        spu_ls_write128(ctx, ctx->gpr[26]._u32[0] + 0x20, ctx->gpr[27]);
        /* nop */;
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
}

void spu_job_01466F00_spu_func_014678A8(spu_context* ctx) {
        ctx->gpr[62] = spu_fa(ctx->gpr[7], ctx->gpr[11]);
        /* branch hint (ignored) */;
        ctx->gpr[72] = spu_fs(ctx->gpr[11], ctx->gpr[9]);
        ctx->gpr[3] = spu_ilhu(0xC000);
        ctx->gpr[79] = spu_ilhu(0x3F00);
        ctx->gpr[63] = spu_fm(ctx->gpr[9], ctx->gpr[3]);
        ctx->gpr[77] = spu_fs(ctx->gpr[11], ctx->gpr[7]);
        ctx->gpr[68] = spu_frest(ctx->gpr[62]);
        ctx->gpr[67] = spu_fm(ctx->gpr[72], ctx->gpr[79]);
        ctx->gpr[78] = spu_frest(ctx->gpr[62]);
        ctx->gpr[73] = spu_frest(ctx->gpr[62]);
        ctx->gpr[9] = spu_frest(ctx->gpr[62]);
        ctx->gpr[66] = spu_fi(ctx->gpr[62], ctx->gpr[68]);
        ctx->gpr[76] = spu_fi(ctx->gpr[62], ctx->gpr[78]);
        ctx->gpr[71] = spu_fi(ctx->gpr[62], ctx->gpr[73]);
        ctx->gpr[61] = spu_fi(ctx->gpr[62], ctx->gpr[9]);
        ctx->gpr[65] = spu_fm(ctx->gpr[67], ctx->gpr[66]);
        ctx->gpr[75] = spu_fm(ctx->gpr[77], ctx->gpr[76]);
        ctx->gpr[70] = spu_fm(ctx->gpr[72], ctx->gpr[71]);
        ctx->gpr[60] = spu_fm(ctx->gpr[63], ctx->gpr[61]);
        ctx->gpr[64] = spu_fnms(ctx->gpr[65], ctx->gpr[62], ctx->gpr[67]);
        ctx->gpr[74] = spu_fnms(ctx->gpr[75], ctx->gpr[62], ctx->gpr[77]);
        ctx->gpr[69] = spu_fnms(ctx->gpr[70], ctx->gpr[62], ctx->gpr[72]);
        ctx->gpr[23] = spu_fnms(ctx->gpr[60], ctx->gpr[62], ctx->gpr[63]);
        ctx->gpr[12] = spu_fma(ctx->gpr[64], ctx->gpr[66], ctx->gpr[65]);
        ctx->gpr[8] = spu_fma(ctx->gpr[74], ctx->gpr[76], ctx->gpr[75]);
        ctx->gpr[10] = spu_fma(ctx->gpr[69], ctx->gpr[71], ctx->gpr[70]);
        ctx->gpr[22] = spu_fma(ctx->gpr[23], ctx->gpr[61], ctx->gpr[60]);
        ctx->gpr[11] = spu_ori(ctx->gpr[12], 0);
        { ctx->pc = 0x27670; SPU_TAILCALL(spu_job_01466F00_spu_func_00027670(ctx)); }
}

void spu_job_01466F00_spu_func_01467920(spu_context* ctx) {
        ctx->gpr[33] = spu_ilhu(0x3F80);
        /* branch hint (ignored) */;
        ctx->gpr[32] = spu_ilhu(0x3F00);
        ctx->gpr[2] = spu_fa(ctx->gpr[7], ctx->gpr[33]);
        ctx->gpr[17] = spu_fa(ctx->gpr[9], ctx->gpr[33]);
        ctx->gpr[30] = spu_fs(ctx->gpr[33], ctx->gpr[7]);
        ctx->gpr[34] = spu_ilhu(0xC000);
        ctx->gpr[31] = spu_ilhu(0x8000);
        ctx->gpr[18] = spu_fm(ctx->gpr[9], ctx->gpr[34]);
        ctx->gpr[4] = spu_frest(ctx->gpr[2]);
        ctx->gpr[19] = spu_fm(ctx->gpr[17], ctx->gpr[32]);
        ctx->gpr[16] = spu_frest(ctx->gpr[2]);
        ctx->gpr[28] = spu_xor(ctx->gpr[17], ctx->gpr[31]);
        ctx->gpr[20] = spu_frest(ctx->gpr[2]);
        ctx->gpr[7] = spu_frest(ctx->gpr[2]);
        ctx->gpr[27] = spu_fi(ctx->gpr[2], ctx->gpr[4]);
        ctx->gpr[29] = spu_fi(ctx->gpr[2], ctx->gpr[16]);
        ctx->gpr[21] = spu_fi(ctx->gpr[2], ctx->gpr[20]);
        ctx->gpr[13] = spu_fi(ctx->gpr[2], ctx->gpr[7]);
        ctx->gpr[11] = spu_fm(ctx->gpr[19], ctx->gpr[27]);
        ctx->gpr[8] = spu_fm(ctx->gpr[30], ctx->gpr[29]);
        ctx->gpr[6] = spu_fm(ctx->gpr[28], ctx->gpr[21]);
        ctx->gpr[14] = spu_fm(ctx->gpr[18], ctx->gpr[13]);
        ctx->gpr[12] = spu_fnms(ctx->gpr[11], ctx->gpr[2], ctx->gpr[19]);
        ctx->gpr[24] = spu_fnms(ctx->gpr[8], ctx->gpr[2], ctx->gpr[30]);
        ctx->gpr[10] = spu_fnms(ctx->gpr[6], ctx->gpr[2], ctx->gpr[28]);
        ctx->gpr[15] = spu_fnms(ctx->gpr[14], ctx->gpr[2], ctx->gpr[18]);
        ctx->gpr[11] = spu_fma(ctx->gpr[12], ctx->gpr[27], ctx->gpr[11]);
        ctx->gpr[8] = spu_fma(ctx->gpr[24], ctx->gpr[29], ctx->gpr[8]);
        ctx->gpr[10] = spu_fma(ctx->gpr[10], ctx->gpr[21], ctx->gpr[6]);
        ctx->gpr[22] = spu_fma(ctx->gpr[15], ctx->gpr[13], ctx->gpr[14]);
        ctx->gpr[12] = spu_ori(ctx->gpr[11], 0);
        /* nop */;
        { ctx->pc = 0x27670; SPU_TAILCALL(spu_job_01466F00_spu_func_00027670(ctx)); }
}

void spu_job_01466F00_spu_func_014679A8(spu_context* ctx) {
        ctx->gpr[50] = spu_ilhu(0x3F80);
        /* branch hint (ignored) */;
        ctx->gpr[51] = spu_ilhu(0xC000);
        ctx->gpr[38] = spu_fa(ctx->gpr[7], ctx->gpr[50]);
        ctx->gpr[48] = spu_fs(ctx->gpr[50], ctx->gpr[7]);
        ctx->gpr[43] = spu_fm(ctx->gpr[9], ctx->gpr[51]);
        ctx->gpr[49] = spu_frest(ctx->gpr[38]);
        ctx->gpr[44] = spu_frest(ctx->gpr[38]);
        ctx->gpr[39] = spu_frest(ctx->gpr[38]);
        ctx->gpr[47] = spu_fi(ctx->gpr[38], ctx->gpr[49]);
        ctx->gpr[42] = spu_fi(ctx->gpr[38], ctx->gpr[44]);
        ctx->gpr[37] = spu_fi(ctx->gpr[38], ctx->gpr[39]);
        ctx->gpr[46] = spu_fm(ctx->gpr[48], ctx->gpr[47]);
        ctx->gpr[41] = spu_fm(ctx->gpr[43], ctx->gpr[42]);
        ctx->gpr[36] = spu_fm(ctx->gpr[38], ctx->gpr[37]);
        ctx->gpr[45] = spu_fnms(ctx->gpr[46], ctx->gpr[38], ctx->gpr[48]);
        ctx->gpr[40] = spu_fnms(ctx->gpr[41], ctx->gpr[38], ctx->gpr[43]);
        ctx->gpr[35] = spu_fnms(ctx->gpr[36], ctx->gpr[38], ctx->gpr[38]);
        ctx->gpr[8] = spu_fma(ctx->gpr[45], ctx->gpr[47], ctx->gpr[46]);
        ctx->gpr[22] = spu_fma(ctx->gpr[40], ctx->gpr[42], ctx->gpr[41]);
        ctx->gpr[12] = spu_fma(ctx->gpr[35], ctx->gpr[37], ctx->gpr[36]);
        ctx->gpr[11] = spu_ori(ctx->gpr[8], 0);
        ctx->gpr[10] = spu_ori(ctx->gpr[22], 0);
        { ctx->pc = 0x27670; SPU_TAILCALL(spu_job_01466F00_spu_func_00027670(ctx)); }
        ctx->gpr[10] = spu_ila(0xB10);
        ctx->gpr[79] = spu_link(0x1467A10); spu_host_call_push(ctx, 0x1467A10); spu_job_01466F00_spu_func_00027A10(ctx); spu_host_call_pop(ctx);
        { ctx->pc = 0x1467A10; SPU_TAILCALL(spu_job_01466F00_spu_func_01467A10(ctx)); }
}

void spu_job_01466F00_spu_func_01467A10(spu_context* ctx) {
        ctx->gpr[6] = spu_ila(0x118D0);
        /* branch hint (ignored) */;
        ctx->gpr[8] = spu_ila(0xFFFF);
        ctx->gpr[79] = spu_sf(ctx->gpr[10], ctx->gpr[79]);
        ctx->gpr[10] = spu_ori(ctx->gpr[3], 0);
        ctx->gpr[6] = spu_a(ctx->gpr[6], ctx->gpr[79]);
        ctx->gpr[11] = spu_andi(ctx->gpr[6], 15);
        ctx->gpr[5] = spu_sf(ctx->gpr[11], ctx->gpr[6]);
        ctx->gpr[9] = spu_sfi(ctx->gpr[11], 0);
        ctx->gpr[7] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + 0x0);
        ctx->gpr[3] = spu_rotm(ctx->gpr[8], ctx->gpr[9]);
        ctx->gpr[5] = spu_ai(ctx->gpr[5], 16);
        ctx->gpr[4] = spu_ceqbi(ctx->gpr[7], 0);
        ctx->gpr[2] = spu_gbb(ctx->gpr[4]);
        ctx->gpr[2] = spu_and(ctx->gpr[2], ctx->gpr[3]);
        if (ctx->gpr[2]._u32[0] != 0) { ctx->pc = 0x27A78; SPU_TAILCALL(spu_job_01466F00_spu_func_00027A78(ctx)); }
        { ctx->pc = 0x1467A50; SPU_TAILCALL(spu_job_01466F00_spu_func_01467A50(ctx)); }
}

void spu_job_01466F00_spu_func_01467A50(spu_context* ctx) {
        ctx->gpr[18] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + 0x0);
        ctx->gpr[17] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + 0x10);
        ctx->gpr[5] = spu_ai(ctx->gpr[5], 32);
        ctx->gpr[16] = spu_ceqbi(ctx->gpr[18], 0);
        ctx->gpr[14] = spu_ceqbi(ctx->gpr[17], 0);
        ctx->gpr[15] = spu_gbb(ctx->gpr[16]);
        ctx->gpr[13] = spu_gbb(ctx->gpr[14]);
        ctx->gpr[12] = spu_shli(ctx->gpr[15], 16);
        ctx->gpr[2] = spu_or(ctx->gpr[12], ctx->gpr[13]);
        if (ctx->gpr[2]._u32[0] == 0) { ctx->pc = 0x27A50; SPU_TAILCALL(spu_job_01466F00_spu_func_00027A50(ctx)); }
        { ctx->pc = 0x1467A78; SPU_TAILCALL(spu_job_01466F00_spu_func_01467A78(ctx)); }
}

void spu_job_01466F00_spu_func_01467A78(spu_context* ctx) {
        ctx->gpr[3] = spu_clz(ctx->gpr[2]);
        if (ctx->gpr[10]._u32[0] == 0) { ctx->pc = 0x27B64; SPU_TAILCALL(spu_job_01466F00_spu_func_00027B64(ctx)); }
        ctx->gpr[22] = spu_sf(ctx->gpr[6], ctx->gpr[5]);
        ctx->gpr[21] = spu_a(ctx->gpr[3], ctx->gpr[22]);
        ctx->gpr[20] = spu_ai(ctx->gpr[21], -16);
        ctx->gpr[8] = spu_andi(ctx->gpr[20], -16);
        ctx->gpr[19] = spu_cgti(ctx->gpr[8], 0);
        if (ctx->gpr[19]._u32[0] == 0) { ctx->pc = 0x27B64; SPU_TAILCALL(spu_job_01466F00_spu_func_00027B64(ctx)); }
        ctx->gpr[23] = spu_ila(0x118D0);
        ctx->gpr[9] = spu_fsmbi(0x0);
        ctx->gpr[16] = spu_il(16383);
        ctx->gpr[13] = spu_fsmbi(0x0);
        ctx->gpr[11] = spu_a(ctx->gpr[23], ctx->gpr[79]);
        ctx->gpr[15] = spu_il(4);
        ctx->gpr[12] = spu_il(2);
        ctx->gpr[14] = spu_il(32);
        { ctx->pc = 0x1467AB8; SPU_TAILCALL(spu_job_01466F00_spu_func_01467AB8(ctx)); }
}

void spu_job_01466F00_spu_func_01467AB8(spu_context* ctx) {
        ctx->gpr[31] = spu_sf(ctx->gpr[9], ctx->gpr[8]);
        /* branch hint (ignored) */;
        ctx->gpr[26] = spu_il(16384);
        spu_wrch(ctx, MFC_WrTagUpdate, ctx->gpr[13]);
        ctx->gpr[37] = spu_cgti(ctx->gpr[31], 4);
        ctx->gpr[39] = spu_ai(ctx->gpr[31], 3);
        ctx->gpr[38] = spu_ai(ctx->gpr[31], 7);
        ctx->gpr[35] = spu_andi(ctx->gpr[39], -4);
        ctx->gpr[36] = spu_andi(ctx->gpr[38], -8);
        ctx->gpr[34] = spu_ceqi(ctx->gpr[37], 0);
        ctx->gpr[33] = spu_ai(ctx->gpr[31], 15);
        ctx->gpr[32] = spu_cgti(ctx->gpr[31], 8);
        ctx->gpr[29] = spu_selb(ctx->gpr[36], ctx->gpr[35], ctx->gpr[34]);
        ctx->gpr[30] = spu_andi(ctx->gpr[33], -16);
        ctx->gpr[28] = spu_ceqi(ctx->gpr[32], 0);
        ctx->gpr[27] = spu_cgt(ctx->gpr[31], ctx->gpr[16]);
        ctx->gpr[25] = spu_selb(ctx->gpr[30], ctx->gpr[29], ctx->gpr[28]);
        ctx->gpr[24] = spu_ceqi(ctx->gpr[27], 0);
        ctx->gpr[7] = spu_selb(ctx->gpr[26], ctx->gpr[25], ctx->gpr[24]);
        { ctx->pc = 0x1467B04; SPU_TAILCALL(spu_job_01466F00_spu_func_01467B04(ctx)); }
}

void spu_job_01466F00_spu_func_01467B04(spu_context* ctx) {
        ctx->gpr[41] = spu_pref_u32(spu_rchcnt(ctx, MFC_WrTagUpdate));
        ctx->gpr[40] = spu_ceqi(ctx->gpr[41], 1);
        if (ctx->gpr[40]._u32[0] == 0) { ctx->pc = 0x27B04; SPU_TAILCALL(spu_job_01466F00_spu_func_00027B04(ctx)); }
        ctx->gpr[45] = spu_ori(ctx->gpr[11], 0);
        /* branch hint (ignored) */;
        ctx->gpr[44] = spu_ori(ctx->gpr[10], 0);
        ctx->gpr[3] = spu_rdch(ctx, MFC_RdTagStat);
        ctx->gpr[43] = spu_ori(ctx->gpr[7], 0);
        spu_wrch(ctx, MFC_WrTagMask, ctx->gpr[15]);
        ctx->gpr[9] = spu_a(ctx->gpr[9], ctx->gpr[7]);
        spu_wrch(ctx, MFC_WrTagUpdate, ctx->gpr[12]);
        /* nop */;
        ctx->gpr[6] = spu_rdch(ctx, MFC_RdTagStat);
        ctx->gpr[42] = spu_cgt(ctx->gpr[8], ctx->gpr[9]);
        spu_wrch(ctx, MFC_LSA, ctx->gpr[45]);
        spu_wrch(ctx, MFC_EAH, ctx->gpr[13]);
        spu_wrch(ctx, MFC_EAL, ctx->gpr[44]);
        spu_wrch(ctx, MFC_Size, ctx->gpr[43]);
        spu_wrch(ctx, MFC_TagID, ctx->gpr[12]);
        spu_wrch(ctx, MFC_Cmd, ctx->gpr[14]);
        if (ctx->gpr[42]._u32[0] == 0) { ctx->pc = 0x27B64; SPU_TAILCALL(spu_job_01466F00_spu_func_00027B64(ctx)); }
        ctx->gpr[10] = spu_a(ctx->gpr[10], ctx->gpr[7]);
        ctx->gpr[11] = spu_a(ctx->gpr[11], ctx->gpr[7]);
        { ctx->pc = 0x27AB8; SPU_TAILCALL(spu_job_01466F00_spu_func_00027AB8(ctx)); }
}

void spu_job_01466F00_spu_func_01467B64(spu_context* ctx) {
        ctx->gpr[46] = spu_il(0);
        spu_wrch(ctx, MFC_WrTagUpdate, ctx->gpr[46]);
        { ctx->pc = 0x1467B6C; SPU_TAILCALL(spu_job_01466F00_spu_func_01467B6C(ctx)); }
}

void spu_job_01466F00_spu_func_01467B6C(spu_context* ctx) {
        ctx->gpr[48] = spu_pref_u32(spu_rchcnt(ctx, MFC_WrTagUpdate));
        ctx->gpr[47] = spu_ceqi(ctx->gpr[48], 1);
        if (ctx->gpr[47]._u32[0] == 0) { ctx->pc = 0x27B6C; SPU_TAILCALL(spu_job_01466F00_spu_func_00027B6C(ctx)); }
        /* nop */;
        /* branch hint (ignored) */;
        ctx->gpr[50] = spu_il(4);
        ctx->gpr[3] = spu_rdch(ctx, MFC_RdTagStat);
        ctx->gpr[49] = spu_il(2);
        /* nop */;
        /* nop */;
        spu_wrch(ctx, MFC_WrTagMask, ctx->gpr[50]);
        /* nop */;
        spu_wrch(ctx, MFC_WrTagUpdate, ctx->gpr[49]);
        ctx->gpr[2] = spu_rdch(ctx, MFC_RdTagStat);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        ctx->gpr[10] = spu_ila(0xCB0);
        ctx->gpr[79] = spu_link(0x1467BB0); spu_host_call_push(ctx, 0x1467BB0); spu_job_01466F00_spu_func_00027BB0(ctx); spu_host_call_pop(ctx);
        { ctx->pc = 0x1467BB0; SPU_TAILCALL(spu_job_01466F00_spu_func_01467BB0(ctx)); }
}

void spu_job_01466F00_spu_func_01467BB0(spu_context* ctx) {
        ctx->gpr[6] = spu_ila(0x11840);
        /* branch hint (ignored) */;
        ctx->gpr[8] = spu_ila(0xFFFF);
        ctx->gpr[79] = spu_sf(ctx->gpr[10], ctx->gpr[79]);
        ctx->gpr[10] = spu_ori(ctx->gpr[3], 0);
        ctx->gpr[6] = spu_a(ctx->gpr[6], ctx->gpr[79]);
        ctx->gpr[11] = spu_andi(ctx->gpr[6], 15);
        ctx->gpr[5] = spu_sf(ctx->gpr[11], ctx->gpr[6]);
        ctx->gpr[9] = spu_sfi(ctx->gpr[11], 0);
        ctx->gpr[7] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + 0x0);
        ctx->gpr[3] = spu_rotm(ctx->gpr[8], ctx->gpr[9]);
        ctx->gpr[5] = spu_ai(ctx->gpr[5], 16);
        ctx->gpr[4] = spu_ceqbi(ctx->gpr[7], 0);
        ctx->gpr[2] = spu_gbb(ctx->gpr[4]);
        ctx->gpr[2] = spu_and(ctx->gpr[2], ctx->gpr[3]);
        if (ctx->gpr[2]._u32[0] != 0) { ctx->pc = 0x27C18; SPU_TAILCALL(spu_job_01466F00_spu_func_00027C18(ctx)); }
        { ctx->pc = 0x1467BF0; SPU_TAILCALL(spu_job_01466F00_spu_func_01467BF0(ctx)); }
}

void spu_job_01466F00_spu_func_01467BF0(spu_context* ctx) {
        ctx->gpr[18] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + 0x0);
        ctx->gpr[17] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + 0x10);
        ctx->gpr[5] = spu_ai(ctx->gpr[5], 32);
        ctx->gpr[16] = spu_ceqbi(ctx->gpr[18], 0);
        ctx->gpr[14] = spu_ceqbi(ctx->gpr[17], 0);
        ctx->gpr[15] = spu_gbb(ctx->gpr[16]);
        ctx->gpr[13] = spu_gbb(ctx->gpr[14]);
        ctx->gpr[12] = spu_shli(ctx->gpr[15], 16);
        ctx->gpr[2] = spu_or(ctx->gpr[12], ctx->gpr[13]);
        if (ctx->gpr[2]._u32[0] == 0) { ctx->pc = 0x27BF0; SPU_TAILCALL(spu_job_01466F00_spu_func_00027BF0(ctx)); }
        { ctx->pc = 0x1467C18; SPU_TAILCALL(spu_job_01466F00_spu_func_01467C18(ctx)); }
}

void spu_job_01466F00_spu_func_01467C18(spu_context* ctx) {
        ctx->gpr[3] = spu_clz(ctx->gpr[2]);
        if (ctx->gpr[10]._u32[0] == 0) { ctx->pc = 0x27D04; SPU_TAILCALL(spu_job_01466F00_spu_func_00027D04(ctx)); }
        ctx->gpr[22] = spu_sf(ctx->gpr[6], ctx->gpr[5]);
        ctx->gpr[21] = spu_a(ctx->gpr[3], ctx->gpr[22]);
        ctx->gpr[20] = spu_ai(ctx->gpr[21], -16);
        ctx->gpr[8] = spu_andi(ctx->gpr[20], -16);
        ctx->gpr[19] = spu_cgti(ctx->gpr[8], 0);
        if (ctx->gpr[19]._u32[0] == 0) { ctx->pc = 0x27D04; SPU_TAILCALL(spu_job_01466F00_spu_func_00027D04(ctx)); }
        ctx->gpr[23] = spu_ila(0x11840);
        ctx->gpr[9] = spu_fsmbi(0x0);
        ctx->gpr[16] = spu_il(16383);
        ctx->gpr[13] = spu_fsmbi(0x0);
        ctx->gpr[11] = spu_a(ctx->gpr[23], ctx->gpr[79]);
        ctx->gpr[15] = spu_il(4);
        ctx->gpr[12] = spu_il(2);
        ctx->gpr[14] = spu_il(32);
        { ctx->pc = 0x1467C58; SPU_TAILCALL(spu_job_01466F00_spu_func_01467C58(ctx)); }
}

void spu_job_01466F00_spu_func_01467C58(spu_context* ctx) {
        ctx->gpr[31] = spu_sf(ctx->gpr[9], ctx->gpr[8]);
        /* branch hint (ignored) */;
        ctx->gpr[26] = spu_il(16384);
        spu_wrch(ctx, MFC_WrTagUpdate, ctx->gpr[13]);
        ctx->gpr[37] = spu_cgti(ctx->gpr[31], 4);
        ctx->gpr[39] = spu_ai(ctx->gpr[31], 3);
        ctx->gpr[38] = spu_ai(ctx->gpr[31], 7);
        ctx->gpr[35] = spu_andi(ctx->gpr[39], -4);
        ctx->gpr[36] = spu_andi(ctx->gpr[38], -8);
        ctx->gpr[34] = spu_ceqi(ctx->gpr[37], 0);
        ctx->gpr[33] = spu_ai(ctx->gpr[31], 15);
        ctx->gpr[32] = spu_cgti(ctx->gpr[31], 8);
        ctx->gpr[29] = spu_selb(ctx->gpr[36], ctx->gpr[35], ctx->gpr[34]);
        ctx->gpr[30] = spu_andi(ctx->gpr[33], -16);
        ctx->gpr[28] = spu_ceqi(ctx->gpr[32], 0);
        ctx->gpr[27] = spu_cgt(ctx->gpr[31], ctx->gpr[16]);
        ctx->gpr[25] = spu_selb(ctx->gpr[30], ctx->gpr[29], ctx->gpr[28]);
        ctx->gpr[24] = spu_ceqi(ctx->gpr[27], 0);
        ctx->gpr[7] = spu_selb(ctx->gpr[26], ctx->gpr[25], ctx->gpr[24]);
        { ctx->pc = 0x1467CA4; SPU_TAILCALL(spu_job_01466F00_spu_func_01467CA4(ctx)); }
}

void spu_job_01466F00_spu_func_01467CA4(spu_context* ctx) {
        ctx->gpr[41] = spu_pref_u32(spu_rchcnt(ctx, MFC_WrTagUpdate));
        ctx->gpr[40] = spu_ceqi(ctx->gpr[41], 1);
        if (ctx->gpr[40]._u32[0] == 0) { ctx->pc = 0x27CA4; SPU_TAILCALL(spu_job_01466F00_spu_func_00027CA4(ctx)); }
        ctx->gpr[45] = spu_ori(ctx->gpr[11], 0);
        /* branch hint (ignored) */;
        ctx->gpr[44] = spu_ori(ctx->gpr[10], 0);
        ctx->gpr[3] = spu_rdch(ctx, MFC_RdTagStat);
        ctx->gpr[43] = spu_ori(ctx->gpr[7], 0);
        spu_wrch(ctx, MFC_WrTagMask, ctx->gpr[15]);
        ctx->gpr[9] = spu_a(ctx->gpr[9], ctx->gpr[7]);
        spu_wrch(ctx, MFC_WrTagUpdate, ctx->gpr[12]);
        /* nop */;
        ctx->gpr[6] = spu_rdch(ctx, MFC_RdTagStat);
        ctx->gpr[42] = spu_cgt(ctx->gpr[8], ctx->gpr[9]);
        spu_wrch(ctx, MFC_LSA, ctx->gpr[45]);
        spu_wrch(ctx, MFC_EAH, ctx->gpr[13]);
        spu_wrch(ctx, MFC_EAL, ctx->gpr[44]);
        spu_wrch(ctx, MFC_Size, ctx->gpr[43]);
        spu_wrch(ctx, MFC_TagID, ctx->gpr[12]);
        spu_wrch(ctx, MFC_Cmd, ctx->gpr[14]);
        if (ctx->gpr[42]._u32[0] == 0) { ctx->pc = 0x27D04; SPU_TAILCALL(spu_job_01466F00_spu_func_00027D04(ctx)); }
        ctx->gpr[10] = spu_a(ctx->gpr[10], ctx->gpr[7]);
        ctx->gpr[11] = spu_a(ctx->gpr[11], ctx->gpr[7]);
        { ctx->pc = 0x27C58; SPU_TAILCALL(spu_job_01466F00_spu_func_00027C58(ctx)); }
}

void spu_job_01466F00_spu_func_01467D04(spu_context* ctx) {
        ctx->gpr[46] = spu_il(0);
        spu_wrch(ctx, MFC_WrTagUpdate, ctx->gpr[46]);
        { ctx->pc = 0x1467D0C; SPU_TAILCALL(spu_job_01466F00_spu_func_01467D0C(ctx)); }
}

void spu_job_01466F00_spu_func_01467D0C(spu_context* ctx) {
        ctx->gpr[48] = spu_pref_u32(spu_rchcnt(ctx, MFC_WrTagUpdate));
        ctx->gpr[47] = spu_ceqi(ctx->gpr[48], 1);
        if (ctx->gpr[47]._u32[0] == 0) { ctx->pc = 0x27D0C; SPU_TAILCALL(spu_job_01466F00_spu_func_00027D0C(ctx)); }
        /* nop */;
        /* branch hint (ignored) */;
        ctx->gpr[50] = spu_il(4);
        ctx->gpr[3] = spu_rdch(ctx, MFC_RdTagStat);
        ctx->gpr[49] = spu_il(2);
        /* nop */;
        /* nop */;
        spu_wrch(ctx, MFC_WrTagMask, ctx->gpr[50]);
        /* nop */;
        spu_wrch(ctx, MFC_WrTagUpdate, ctx->gpr[49]);
        ctx->gpr[2] = spu_rdch(ctx, MFC_RdTagStat);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        ctx->gpr[10] = spu_ila(0xE50);
        ctx->gpr[79] = spu_link(0x1467D50); spu_host_call_push(ctx, 0x1467D50); spu_job_01466F00_spu_func_00027D50(ctx); spu_host_call_pop(ctx);
        { ctx->pc = 0x1467D50; SPU_TAILCALL(spu_job_01466F00_spu_func_01467D50(ctx)); }
}

void spu_job_01466F00_spu_func_01467D50(spu_context* ctx) {
        ctx->gpr[6] = spu_ila(0x116D0);
        /* branch hint (ignored) */;
        ctx->gpr[8] = spu_ila(0xFFFF);
        ctx->gpr[79] = spu_sf(ctx->gpr[10], ctx->gpr[79]);
        ctx->gpr[10] = spu_ori(ctx->gpr[3], 0);
        ctx->gpr[6] = spu_a(ctx->gpr[6], ctx->gpr[79]);
        ctx->gpr[11] = spu_andi(ctx->gpr[6], 15);
        ctx->gpr[5] = spu_sf(ctx->gpr[11], ctx->gpr[6]);
        ctx->gpr[9] = spu_sfi(ctx->gpr[11], 0);
        ctx->gpr[7] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + 0x0);
        ctx->gpr[3] = spu_rotm(ctx->gpr[8], ctx->gpr[9]);
        ctx->gpr[5] = spu_ai(ctx->gpr[5], 16);
        ctx->gpr[4] = spu_ceqbi(ctx->gpr[7], 0);
        ctx->gpr[2] = spu_gbb(ctx->gpr[4]);
        ctx->gpr[2] = spu_and(ctx->gpr[2], ctx->gpr[3]);
        if (ctx->gpr[2]._u32[0] != 0) { ctx->pc = 0x27DB8; SPU_TAILCALL(spu_job_01466F00_spu_func_00027DB8(ctx)); }
        { ctx->pc = 0x1467D90; SPU_TAILCALL(spu_job_01466F00_spu_func_01467D90(ctx)); }
}

void spu_job_01466F00_spu_func_01467D90(spu_context* ctx) {
        ctx->gpr[18] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + 0x0);
        ctx->gpr[17] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + 0x10);
        ctx->gpr[5] = spu_ai(ctx->gpr[5], 32);
        ctx->gpr[16] = spu_ceqbi(ctx->gpr[18], 0);
        ctx->gpr[14] = spu_ceqbi(ctx->gpr[17], 0);
        ctx->gpr[15] = spu_gbb(ctx->gpr[16]);
        ctx->gpr[13] = spu_gbb(ctx->gpr[14]);
        ctx->gpr[12] = spu_shli(ctx->gpr[15], 16);
        ctx->gpr[2] = spu_or(ctx->gpr[12], ctx->gpr[13]);
        if (ctx->gpr[2]._u32[0] == 0) { ctx->pc = 0x27D90; SPU_TAILCALL(spu_job_01466F00_spu_func_00027D90(ctx)); }
        { ctx->pc = 0x1467DB8; SPU_TAILCALL(spu_job_01466F00_spu_func_01467DB8(ctx)); }
}

void spu_job_01466F00_spu_func_01467DB8(spu_context* ctx) {
        ctx->gpr[3] = spu_clz(ctx->gpr[2]);
        if (ctx->gpr[10]._u32[0] == 0) { ctx->pc = 0x27EA4; SPU_TAILCALL(spu_job_01466F00_spu_func_00027EA4(ctx)); }
        ctx->gpr[22] = spu_sf(ctx->gpr[6], ctx->gpr[5]);
        ctx->gpr[21] = spu_a(ctx->gpr[3], ctx->gpr[22]);
        ctx->gpr[20] = spu_ai(ctx->gpr[21], -16);
        ctx->gpr[8] = spu_andi(ctx->gpr[20], -16);
        ctx->gpr[19] = spu_cgti(ctx->gpr[8], 0);
        if (ctx->gpr[19]._u32[0] == 0) { ctx->pc = 0x27EA4; SPU_TAILCALL(spu_job_01466F00_spu_func_00027EA4(ctx)); }
        ctx->gpr[23] = spu_ila(0x116D0);
        ctx->gpr[9] = spu_fsmbi(0x0);
        ctx->gpr[16] = spu_il(16383);
        ctx->gpr[13] = spu_fsmbi(0x0);
        ctx->gpr[11] = spu_a(ctx->gpr[23], ctx->gpr[79]);
        ctx->gpr[15] = spu_il(4);
        ctx->gpr[12] = spu_il(2);
        ctx->gpr[14] = spu_il(32);
        { ctx->pc = 0x1467DF8; SPU_TAILCALL(spu_job_01466F00_spu_func_01467DF8(ctx)); }
}

void spu_job_01466F00_spu_func_01467DF8(spu_context* ctx) {
        ctx->gpr[31] = spu_sf(ctx->gpr[9], ctx->gpr[8]);
        /* branch hint (ignored) */;
        ctx->gpr[26] = spu_il(16384);
        spu_wrch(ctx, MFC_WrTagUpdate, ctx->gpr[13]);
        ctx->gpr[37] = spu_cgti(ctx->gpr[31], 4);
        ctx->gpr[39] = spu_ai(ctx->gpr[31], 3);
        ctx->gpr[38] = spu_ai(ctx->gpr[31], 7);
        ctx->gpr[35] = spu_andi(ctx->gpr[39], -4);
        ctx->gpr[36] = spu_andi(ctx->gpr[38], -8);
        ctx->gpr[34] = spu_ceqi(ctx->gpr[37], 0);
        ctx->gpr[33] = spu_ai(ctx->gpr[31], 15);
        ctx->gpr[32] = spu_cgti(ctx->gpr[31], 8);
        ctx->gpr[29] = spu_selb(ctx->gpr[36], ctx->gpr[35], ctx->gpr[34]);
        ctx->gpr[30] = spu_andi(ctx->gpr[33], -16);
        ctx->gpr[28] = spu_ceqi(ctx->gpr[32], 0);
        ctx->gpr[27] = spu_cgt(ctx->gpr[31], ctx->gpr[16]);
        ctx->gpr[25] = spu_selb(ctx->gpr[30], ctx->gpr[29], ctx->gpr[28]);
        ctx->gpr[24] = spu_ceqi(ctx->gpr[27], 0);
        ctx->gpr[7] = spu_selb(ctx->gpr[26], ctx->gpr[25], ctx->gpr[24]);
        { ctx->pc = 0x1467E44; SPU_TAILCALL(spu_job_01466F00_spu_func_01467E44(ctx)); }
}

void spu_job_01466F00_spu_func_01467E44(spu_context* ctx) {
        ctx->gpr[41] = spu_pref_u32(spu_rchcnt(ctx, MFC_WrTagUpdate));
        ctx->gpr[40] = spu_ceqi(ctx->gpr[41], 1);
        if (ctx->gpr[40]._u32[0] == 0) { ctx->pc = 0x27E44; SPU_TAILCALL(spu_job_01466F00_spu_func_00027E44(ctx)); }
        ctx->gpr[45] = spu_ori(ctx->gpr[11], 0);
        /* branch hint (ignored) */;
        ctx->gpr[44] = spu_ori(ctx->gpr[10], 0);
        ctx->gpr[3] = spu_rdch(ctx, MFC_RdTagStat);
        ctx->gpr[43] = spu_ori(ctx->gpr[7], 0);
        spu_wrch(ctx, MFC_WrTagMask, ctx->gpr[15]);
        ctx->gpr[9] = spu_a(ctx->gpr[9], ctx->gpr[7]);
        spu_wrch(ctx, MFC_WrTagUpdate, ctx->gpr[12]);
        /* nop */;
        ctx->gpr[6] = spu_rdch(ctx, MFC_RdTagStat);
        ctx->gpr[42] = spu_cgt(ctx->gpr[8], ctx->gpr[9]);
        spu_wrch(ctx, MFC_LSA, ctx->gpr[45]);
        spu_wrch(ctx, MFC_EAH, ctx->gpr[13]);
        spu_wrch(ctx, MFC_EAL, ctx->gpr[44]);
        spu_wrch(ctx, MFC_Size, ctx->gpr[43]);
        spu_wrch(ctx, MFC_TagID, ctx->gpr[12]);
        spu_wrch(ctx, MFC_Cmd, ctx->gpr[14]);
        if (ctx->gpr[42]._u32[0] == 0) { ctx->pc = 0x27EA4; SPU_TAILCALL(spu_job_01466F00_spu_func_00027EA4(ctx)); }
        ctx->gpr[10] = spu_a(ctx->gpr[10], ctx->gpr[7]);
        ctx->gpr[11] = spu_a(ctx->gpr[11], ctx->gpr[7]);
        { ctx->pc = 0x27DF8; SPU_TAILCALL(spu_job_01466F00_spu_func_00027DF8(ctx)); }
}

void spu_job_01466F00_spu_func_01467EA4(spu_context* ctx) {
        ctx->gpr[46] = spu_il(0);
        spu_wrch(ctx, MFC_WrTagUpdate, ctx->gpr[46]);
        { ctx->pc = 0x1467EAC; SPU_TAILCALL(spu_job_01466F00_spu_func_01467EAC(ctx)); }
}

void spu_job_01466F00_spu_func_01467EAC(spu_context* ctx) {
        ctx->gpr[48] = spu_pref_u32(spu_rchcnt(ctx, MFC_WrTagUpdate));
        ctx->gpr[47] = spu_ceqi(ctx->gpr[48], 1);
        if (ctx->gpr[47]._u32[0] == 0) { ctx->pc = 0x27EAC; SPU_TAILCALL(spu_job_01466F00_spu_func_00027EAC(ctx)); }
        /* nop */;
        /* branch hint (ignored) */;
        ctx->gpr[50] = spu_il(4);
        ctx->gpr[3] = spu_rdch(ctx, MFC_RdTagStat);
        ctx->gpr[49] = spu_il(2);
        /* nop */;
        /* nop */;
        spu_wrch(ctx, MFC_WrTagMask, ctx->gpr[50]);
        /* nop */;
        spu_wrch(ctx, MFC_WrTagUpdate, ctx->gpr[49]);
        ctx->gpr[2] = spu_rdch(ctx, MFC_RdTagStat);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        ctx->gpr[2] = spu_ila(0xFF0);
        ctx->gpr[79] = spu_link(0x1467EF0); spu_host_call_push(ctx, 0x1467EF0); spu_job_01466F00_spu_func_00027EF0(ctx); spu_host_call_pop(ctx);
        { ctx->pc = 0x1467EF0; SPU_TAILCALL(spu_job_01466F00_spu_func_01467EF0(ctx)); }
}

void spu_job_01466F00_spu_func_01467EF0(spu_context* ctx) {
        ctx->gpr[16] = spu_ori(ctx->gpr[5], 0);
        /* branch hint (ignored) */;
        ctx->gpr[14] = spu_ori(ctx->gpr[3], 0);
        ctx->gpr[15] = spu_shlqbyi(ctx->gpr[4], 0);
        ctx->gpr[17] = spu_ori(ctx->gpr[6], 0);
        ctx->gpr[79] = spu_sf(ctx->gpr[2], ctx->gpr[79]);
        if (ctx->gpr[5]._u32[0] == 0) { ctx->pc = 0x28330; SPU_TAILCALL(spu_job_01466F00_spu_func_00028330(ctx)); }
        ctx->gpr[3] = spu_cgti(ctx->gpr[5], -1);
        if (ctx->gpr[3]._u32[0] == 0) { ctx->pc = 0x28088; SPU_TAILCALL(spu_job_01466F00_spu_func_00028088(ctx)); }
        ctx->gpr[4] = spu_cgti(ctx->gpr[5], 2);
        if (ctx->gpr[4]._u32[0] != 0) { ctx->pc = 0x28088; SPU_TAILCALL(spu_job_01466F00_spu_func_00028088(ctx)); }
        ctx->gpr[5] = spu_andi(ctx->gpr[15], 15);
        ctx->gpr[12] = spu_andi(ctx->gpr[14], 15);
        ctx->gpr[6] = spu_or(ctx->gpr[5], ctx->gpr[12]);
        if (ctx->gpr[6]._u32[0] != 0) { ctx->pc = 0x28DB0; SPU_TAILCALL(spu_job_01466F00_spu_func_00028DB0(ctx)); }
        ctx->gpr[3] = spu_il(0);
        ctx->gpr[4] = spu_il(512);
        { ctx->pc = 0x1467F34; SPU_TAILCALL(spu_job_01466F00_spu_func_01467F34(ctx)); }
}

void spu_job_01466F00_spu_func_01467F34(spu_context* ctx) {
        ctx->gpr[7] = spu_ls_read128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[15]._u32[0]);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[14]._u32[0], ctx->gpr[7]);
        ctx->gpr[3] = spu_ai(ctx->gpr[3], 16);
        ctx->gpr[5] = spu_ceq(ctx->gpr[3], ctx->gpr[4]);
        if (ctx->gpr[5]._u32[0] == 0) { ctx->pc = 0x27F34; SPU_TAILCALL(spu_job_01466F00_spu_func_00027F34(ctx)); }
        ctx->gpr[3] = spu_il(512);
        /* branch hint (ignored) */;
        ctx->gpr[18] = spu_a(ctx->gpr[14], ctx->gpr[3]);
        ctx->gpr[12] = spu_a(ctx->gpr[15], ctx->gpr[3]);
        ctx->gpr[13] = spu_andi(ctx->gpr[18], 15);
        ctx->gpr[4] = spu_shlqbyi(ctx->gpr[18], 0);
        ctx->gpr[5] = spu_andi(ctx->gpr[12], 15);
        ctx->gpr[57] = spu_or(ctx->gpr[5], ctx->gpr[13]);
        if (ctx->gpr[57]._u32[0] != 0) { ctx->pc = 0x28EC0; SPU_TAILCALL(spu_job_01466F00_spu_func_00028EC0(ctx)); }
        ctx->gpr[58] = spu_il(1024);
        ctx->gpr[5] = spu_a(ctx->gpr[15], ctx->gpr[58]);
        { ctx->pc = 0x1467F74; SPU_TAILCALL(spu_job_01466F00_spu_func_01467F74(ctx)); }
}

void spu_job_01466F00_spu_func_01467F74(spu_context* ctx) {
        ctx->gpr[60] = spu_ls_read128(ctx, ctx->gpr[12]._u32[0] + 0x0);
        ctx->gpr[12] = spu_ai(ctx->gpr[12], 16);
        ctx->gpr[59] = spu_ceq(ctx->gpr[5], ctx->gpr[12]);
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[4]._u32[0] + 0x0, ctx->gpr[60]);
        ctx->gpr[4] = spu_ai(ctx->gpr[4], 16);
        if (ctx->gpr[59]._u32[0] == 0) { ctx->pc = 0x27F74; SPU_TAILCALL(spu_job_01466F00_spu_func_00027F74(ctx)); }
        ctx->gpr[7] = spu_ilhu(0x3F34);
        /* branch hint (ignored) */;
        ctx->gpr[33] = spu_il(1024);
        ctx->gpr[5] = spu_fsmbi(0x0);
        ctx->gpr[7] = spu_iohl(ctx->gpr[7], 0xFDF3);
        ctx->gpr[6] = spu_a(ctx->gpr[15], ctx->gpr[33]);
        ctx->gpr[8] = spu_il(512);
        /* nop */;
        { ctx->pc = 0x1467FB0; SPU_TAILCALL(spu_job_01466F00_spu_func_01467FB0(ctx)); }
}

void spu_job_01466F00_spu_func_01467FB0(spu_context* ctx) {
        ctx->gpr[37] = spu_a(ctx->gpr[15], ctx->gpr[5]);
        ctx->gpr[13] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + ctx->gpr[14]._u32[0]);
        ctx->gpr[36] = spu_ls_read128(ctx, ctx->gpr[37]._u32[0] + 0x400);
        ctx->gpr[35] = spu_fma(ctx->gpr[36], ctx->gpr[7], ctx->gpr[13]);
        spu_ls_write128(ctx, ctx->gpr[5]._u32[0] + ctx->gpr[14]._u32[0], ctx->gpr[35]);
        ctx->gpr[5] = spu_ai(ctx->gpr[5], 16);
        ctx->gpr[34] = spu_ceq(ctx->gpr[5], ctx->gpr[8]);
        if (ctx->gpr[34]._u32[0] == 0) { ctx->pc = 0x27FB0; SPU_TAILCALL(spu_job_01466F00_spu_func_00027FB0(ctx)); }
        ctx->gpr[8] = spu_ilhu(0x3F34);
        /* branch hint (ignored) */;
        ctx->gpr[11] = spu_ori(ctx->gpr[18], 0);
        ctx->gpr[5] = spu_shlqbyi(ctx->gpr[18], 0);
        ctx->gpr[18] = spu_il(1536);
        ctx->gpr[8] = spu_iohl(ctx->gpr[8], 0xFDF3);
        ctx->gpr[7] = spu_a(ctx->gpr[15], ctx->gpr[18]);
        { ctx->pc = 0x1467FEC; SPU_TAILCALL(spu_job_01466F00_spu_func_01467FEC(ctx)); }
}

void spu_job_01466F00_spu_func_01467FEC(spu_context* ctx) {
        ctx->gpr[41] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + 0x0);
        ctx->gpr[40] = spu_ls_read128(ctx, ctx->gpr[6]._u32[0] + 0x0);
        ctx->gpr[6] = spu_ai(ctx->gpr[6], 16);
        ctx->gpr[38] = spu_ceq(ctx->gpr[7], ctx->gpr[6]);
        ctx->gpr[39] = spu_fma(ctx->gpr[40], ctx->gpr[8], ctx->gpr[41]);
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[5]._u32[0] + 0x0, ctx->gpr[39]);
        ctx->gpr[5] = spu_ai(ctx->gpr[5], 16);
        if (ctx->gpr[38]._u32[0] == 0) { ctx->pc = 0x27FEC; SPU_TAILCALL(spu_job_01466F00_spu_func_00027FEC(ctx)); }
        ctx->gpr[6] = spu_ilhu(0x3F34);
        /* branch hint (ignored) */;
        ctx->gpr[5] = spu_il(0);
        ctx->gpr[6] = spu_iohl(ctx->gpr[6], 0xFDF3);
        ctx->gpr[7] = spu_il(512);
        /* nop */;
        { ctx->pc = 0x1468028; SPU_TAILCALL(spu_job_01466F00_spu_func_01468028(ctx)); }
}

void spu_job_01466F00_spu_func_01468028(spu_context* ctx) {
        ctx->gpr[46] = spu_a(ctx->gpr[15], ctx->gpr[5]);
        ctx->gpr[45] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + ctx->gpr[14]._u32[0]);
        ctx->gpr[44] = spu_ls_read128(ctx, ctx->gpr[46]._u32[0] + 0x800);
        ctx->gpr[43] = spu_fma(ctx->gpr[44], ctx->gpr[6], ctx->gpr[45]);
        spu_ls_write128(ctx, ctx->gpr[5]._u32[0] + ctx->gpr[14]._u32[0], ctx->gpr[43]);
        ctx->gpr[5] = spu_ai(ctx->gpr[5], 16);
        ctx->gpr[42] = spu_ceq(ctx->gpr[5], ctx->gpr[7]);
        if (ctx->gpr[42]._u32[0] == 0) { ctx->pc = 0x28028; SPU_TAILCALL(spu_job_01466F00_spu_func_00028028(ctx)); }
        ctx->gpr[6] = spu_ilhu(0x3F34);
        /* branch hint (ignored) */;
        ctx->gpr[48] = spu_il(2560);
        ctx->gpr[47] = spu_il(3072);
        ctx->gpr[5] = spu_a(ctx->gpr[15], ctx->gpr[48]);
        ctx->gpr[9] = spu_a(ctx->gpr[15], ctx->gpr[47]);
        ctx->gpr[6] = spu_iohl(ctx->gpr[6], 0xFDF3);
        { ctx->pc = 0x1468064; SPU_TAILCALL(spu_job_01466F00_spu_func_01468064(ctx)); }
}

void spu_job_01466F00_spu_func_01468064(spu_context* ctx) {
        ctx->gpr[51] = spu_ls_read128(ctx, ctx->gpr[11]._u32[0] + 0x0);
        ctx->gpr[50] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + 0x0);
        ctx->gpr[5] = spu_ai(ctx->gpr[5], 16);
        ctx->gpr[15] = spu_ceq(ctx->gpr[9], ctx->gpr[5]);
        ctx->gpr[49] = spu_fma(ctx->gpr[50], ctx->gpr[6], ctx->gpr[51]);
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[11]._u32[0] + 0x0, ctx->gpr[49]);
        ctx->gpr[11] = spu_ai(ctx->gpr[11], 16);
        if (ctx->gpr[15]._u32[0] == 0) { ctx->pc = 0x28064; SPU_TAILCALL(spu_job_01466F00_spu_func_00028064(ctx)); }
        { ctx->pc = 0x1468088; SPU_TAILCALL(spu_job_01466F00_spu_func_01468088(ctx)); }
}

void spu_job_01466F00_spu_func_01468088(spu_context* ctx) {
        ctx->gpr[77] = spu_ceqi(ctx->gpr[16], 2);
        if (ctx->gpr[77]._u32[0] != 0) { ctx->pc = 0x28688; SPU_TAILCALL(spu_job_01466F00_spu_func_00028688(ctx)); }
        ctx->gpr[13] = spu_ai(ctx->gpr[16], -1);
        ctx->gpr[6] = spu_clgti(ctx->gpr[13], 1);
        /* nop */;
        if (ctx->gpr[6]._u32[0] != 0) { ctx->pc = 0x281F0; SPU_TAILCALL(spu_job_01466F00_spu_func_000281F0(ctx)); }
        ctx->gpr[7] = spu_ilhu(0x3F34);
        /* branch hint (ignored) */;
        ctx->gpr[9] = spu_il(1024);
        ctx->gpr[6] = spu_fsmbi(0x0);
}

/* Indirect-dispatch stubs for cross-function targets the
 * function detector did not seed (typically conditional
 * branches that escape a function's range). */
void spu_job_01466F00_spu_func_00026F18(spu_context* ctx) {
    ctx->pc = 0x26F18u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00026F30(spu_context* ctx) {
    ctx->pc = 0x26F30u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027010(spu_context* ctx) {
    ctx->pc = 0x27010u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027084(spu_context* ctx) {
    ctx->pc = 0x27084u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_000270B0(spu_context* ctx) {
    ctx->pc = 0x270B0u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_000270D4(spu_context* ctx) {
    ctx->pc = 0x270D4u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_000270F0(spu_context* ctx) {
    ctx->pc = 0x270F0u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027110(spu_context* ctx) {
    ctx->pc = 0x27110u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027138(spu_context* ctx) {
    ctx->pc = 0x27138u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_000271E8(spu_context* ctx) {
    ctx->pc = 0x271E8u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027210(spu_context* ctx) {
    ctx->pc = 0x27210u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027240(spu_context* ctx) {
    ctx->pc = 0x27240u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027280(spu_context* ctx) {
    ctx->pc = 0x27280u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027294(spu_context* ctx) {
    ctx->pc = 0x27294u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_000272BC(spu_context* ctx) {
    ctx->pc = 0x272BCu; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_000274C0(spu_context* ctx) {
    ctx->pc = 0x274C0u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027670(spu_context* ctx) {
    ctx->pc = 0x27670u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_000276AC(spu_context* ctx) {
    ctx->pc = 0x276ACu; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027738(spu_context* ctx) {
    ctx->pc = 0x27738u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_000278A8(spu_context* ctx) {
    ctx->pc = 0x278A8u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027920(spu_context* ctx) {
    ctx->pc = 0x27920u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_000279A8(spu_context* ctx) {
    ctx->pc = 0x279A8u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027A10(spu_context* ctx) {
    ctx->pc = 0x27A10u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027A50(spu_context* ctx) {
    ctx->pc = 0x27A50u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027A78(spu_context* ctx) {
    ctx->pc = 0x27A78u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027AB8(spu_context* ctx) {
    ctx->pc = 0x27AB8u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027B04(spu_context* ctx) {
    ctx->pc = 0x27B04u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027B64(spu_context* ctx) {
    ctx->pc = 0x27B64u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027B6C(spu_context* ctx) {
    ctx->pc = 0x27B6Cu; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027BB0(spu_context* ctx) {
    ctx->pc = 0x27BB0u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027BF0(spu_context* ctx) {
    ctx->pc = 0x27BF0u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027C18(spu_context* ctx) {
    ctx->pc = 0x27C18u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027C58(spu_context* ctx) {
    ctx->pc = 0x27C58u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027CA4(spu_context* ctx) {
    ctx->pc = 0x27CA4u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027D04(spu_context* ctx) {
    ctx->pc = 0x27D04u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027D0C(spu_context* ctx) {
    ctx->pc = 0x27D0Cu; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027D50(spu_context* ctx) {
    ctx->pc = 0x27D50u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027D90(spu_context* ctx) {
    ctx->pc = 0x27D90u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027DB8(spu_context* ctx) {
    ctx->pc = 0x27DB8u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027DF8(spu_context* ctx) {
    ctx->pc = 0x27DF8u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027E44(spu_context* ctx) {
    ctx->pc = 0x27E44u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027EA4(spu_context* ctx) {
    ctx->pc = 0x27EA4u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027EAC(spu_context* ctx) {
    ctx->pc = 0x27EACu; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027EF0(spu_context* ctx) {
    ctx->pc = 0x27EF0u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027F34(spu_context* ctx) {
    ctx->pc = 0x27F34u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027F74(spu_context* ctx) {
    ctx->pc = 0x27F74u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027FB0(spu_context* ctx) {
    ctx->pc = 0x27FB0u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00027FEC(spu_context* ctx) {
    ctx->pc = 0x27FECu; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00028028(spu_context* ctx) {
    ctx->pc = 0x28028u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00028064(spu_context* ctx) {
    ctx->pc = 0x28064u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00028088(spu_context* ctx) {
    ctx->pc = 0x28088u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_000281F0(spu_context* ctx) {
    ctx->pc = 0x281F0u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00028330(spu_context* ctx) {
    ctx->pc = 0x28330u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00028688(spu_context* ctx) {
    ctx->pc = 0x28688u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00028DB0(spu_context* ctx) {
    ctx->pc = 0x28DB0u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00028EC0(spu_context* ctx) {
    ctx->pc = 0x28EC0u; spu_indirect_branch(ctx);
}
void spu_job_01466F00_spu_func_00032888(spu_context* ctx) {
    ctx->pc = 0x32888u; spu_indirect_branch(ctx);
}

/* Function table */
typedef struct { uint32_t addr; void (*func)(spu_context*); const char* name; } spu_func_entry;
static const spu_func_entry spu_function_table[] = {
    { 0x01466F00u, spu_job_01466F00_spu_func_01466F00, "spu_job_01466F00_spu_func_01466F00" },
    { 0x01466F18u, spu_job_01466F00_spu_func_01466F18, "spu_job_01466F00_spu_func_01466F18" },
    { 0x01466F30u, spu_job_01466F00_spu_func_01466F30, "spu_job_01466F00_spu_func_01466F30" },
    { 0x01467010u, spu_job_01466F00_spu_func_01467010, "spu_job_01466F00_spu_func_01467010" },
    { 0x01467084u, spu_job_01466F00_spu_func_01467084, "spu_job_01466F00_spu_func_01467084" },
    { 0x014670B0u, spu_job_01466F00_spu_func_014670B0, "spu_job_01466F00_spu_func_014670B0" },
    { 0x014670D4u, spu_job_01466F00_spu_func_014670D4, "spu_job_01466F00_spu_func_014670D4" },
    { 0x014670F0u, spu_job_01466F00_spu_func_014670F0, "spu_job_01466F00_spu_func_014670F0" },
    { 0x01467110u, spu_job_01466F00_spu_func_01467110, "spu_job_01466F00_spu_func_01467110" },
    { 0x01467138u, spu_job_01466F00_spu_func_01467138, "spu_job_01466F00_spu_func_01467138" },
    { 0x014671E8u, spu_job_01466F00_spu_func_014671E8, "spu_job_01466F00_spu_func_014671E8" },
    { 0x01467210u, spu_job_01466F00_spu_func_01467210, "spu_job_01466F00_spu_func_01467210" },
    { 0x01467240u, spu_job_01466F00_spu_func_01467240, "spu_job_01466F00_spu_func_01467240" },
    { 0x01467280u, spu_job_01466F00_spu_func_01467280, "spu_job_01466F00_spu_func_01467280" },
    { 0x01467294u, spu_job_01466F00_spu_func_01467294, "spu_job_01466F00_spu_func_01467294" },
    { 0x014672BCu, spu_job_01466F00_spu_func_014672BC, "spu_job_01466F00_spu_func_014672BC" },
    { 0x014674C0u, spu_job_01466F00_spu_func_014674C0, "spu_job_01466F00_spu_func_014674C0" },
    { 0x01467670u, spu_job_01466F00_spu_func_01467670, "spu_job_01466F00_spu_func_01467670" },
    { 0x014676ACu, spu_job_01466F00_spu_func_014676AC, "spu_job_01466F00_spu_func_014676AC" },
    { 0x01467738u, spu_job_01466F00_spu_func_01467738, "spu_job_01466F00_spu_func_01467738" },
    { 0x014678A8u, spu_job_01466F00_spu_func_014678A8, "spu_job_01466F00_spu_func_014678A8" },
    { 0x01467920u, spu_job_01466F00_spu_func_01467920, "spu_job_01466F00_spu_func_01467920" },
    { 0x014679A8u, spu_job_01466F00_spu_func_014679A8, "spu_job_01466F00_spu_func_014679A8" },
    { 0x01467A10u, spu_job_01466F00_spu_func_01467A10, "spu_job_01466F00_spu_func_01467A10" },
    { 0x01467A50u, spu_job_01466F00_spu_func_01467A50, "spu_job_01466F00_spu_func_01467A50" },
    { 0x01467A78u, spu_job_01466F00_spu_func_01467A78, "spu_job_01466F00_spu_func_01467A78" },
    { 0x01467AB8u, spu_job_01466F00_spu_func_01467AB8, "spu_job_01466F00_spu_func_01467AB8" },
    { 0x01467B04u, spu_job_01466F00_spu_func_01467B04, "spu_job_01466F00_spu_func_01467B04" },
    { 0x01467B64u, spu_job_01466F00_spu_func_01467B64, "spu_job_01466F00_spu_func_01467B64" },
    { 0x01467B6Cu, spu_job_01466F00_spu_func_01467B6C, "spu_job_01466F00_spu_func_01467B6C" },
    { 0x01467BB0u, spu_job_01466F00_spu_func_01467BB0, "spu_job_01466F00_spu_func_01467BB0" },
    { 0x01467BF0u, spu_job_01466F00_spu_func_01467BF0, "spu_job_01466F00_spu_func_01467BF0" },
    { 0x01467C18u, spu_job_01466F00_spu_func_01467C18, "spu_job_01466F00_spu_func_01467C18" },
    { 0x01467C58u, spu_job_01466F00_spu_func_01467C58, "spu_job_01466F00_spu_func_01467C58" },
    { 0x01467CA4u, spu_job_01466F00_spu_func_01467CA4, "spu_job_01466F00_spu_func_01467CA4" },
    { 0x01467D04u, spu_job_01466F00_spu_func_01467D04, "spu_job_01466F00_spu_func_01467D04" },
    { 0x01467D0Cu, spu_job_01466F00_spu_func_01467D0C, "spu_job_01466F00_spu_func_01467D0C" },
    { 0x01467D50u, spu_job_01466F00_spu_func_01467D50, "spu_job_01466F00_spu_func_01467D50" },
    { 0x01467D90u, spu_job_01466F00_spu_func_01467D90, "spu_job_01466F00_spu_func_01467D90" },
    { 0x01467DB8u, spu_job_01466F00_spu_func_01467DB8, "spu_job_01466F00_spu_func_01467DB8" },
    { 0x01467DF8u, spu_job_01466F00_spu_func_01467DF8, "spu_job_01466F00_spu_func_01467DF8" },
    { 0x01467E44u, spu_job_01466F00_spu_func_01467E44, "spu_job_01466F00_spu_func_01467E44" },
    { 0x01467EA4u, spu_job_01466F00_spu_func_01467EA4, "spu_job_01466F00_spu_func_01467EA4" },
    { 0x01467EACu, spu_job_01466F00_spu_func_01467EAC, "spu_job_01466F00_spu_func_01467EAC" },
    { 0x01467EF0u, spu_job_01466F00_spu_func_01467EF0, "spu_job_01466F00_spu_func_01467EF0" },
    { 0x01467F34u, spu_job_01466F00_spu_func_01467F34, "spu_job_01466F00_spu_func_01467F34" },
    { 0x01467F74u, spu_job_01466F00_spu_func_01467F74, "spu_job_01466F00_spu_func_01467F74" },
    { 0x01467FB0u, spu_job_01466F00_spu_func_01467FB0, "spu_job_01466F00_spu_func_01467FB0" },
    { 0x01467FECu, spu_job_01466F00_spu_func_01467FEC, "spu_job_01466F00_spu_func_01467FEC" },
    { 0x01468028u, spu_job_01466F00_spu_func_01468028, "spu_job_01466F00_spu_func_01468028" },
    { 0x01468064u, spu_job_01466F00_spu_func_01468064, "spu_job_01466F00_spu_func_01468064" },
    { 0x01468088u, spu_job_01466F00_spu_func_01468088, "spu_job_01466F00_spu_func_01468088" },
    { 0, NULL, NULL }
};

void spu_job_01466F00_spu_recomp_register(void) {
    for (const spu_func_entry* e = spu_function_table; e->func; ++e)
        spu_register_function(e->addr, e->func);
}
