/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#pragma once
#include "../../runtime/spu/spu_context.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Cross-function branch/loop = a guest tail-jump to another lifted function's
 * entry. It MUST reuse the current host frame, not nest one: SPURS task loops
 * iterate via these, so nesting overflows the host stack and silently kills the
 * process. clang's musttail guarantees the tail call (a jump); without it (or on
 * a non-clang compiler) we fall back to call+return, which only stays bounded if
 * the compiler happens to do sibling-call optimization. All lifted SPU functions
 * share the signature `void f(spu_context*)`, so the tail call is always valid. */
#if defined(__clang__)
#  define SPU_TAILCALL(call) __attribute__((musttail)) return call
#else
#  define SPU_TAILCALL(call) do { call; return; } while (0)
#endif

/* Indirect branch dispatch (bi/bisl/bid...): PC has been set to the target
 * local-store address; the runtime resolves it to the matching lifted
 * function and continues execution. Implemented by the SPU program glue. */
void spu_indirect_branch(spu_context* ctx);

/* stop/stopd hook (YDKJ): the runtime inspects the stop code, may deliver a
 * stop-and-signal event to the PPU (SPURS bring-up handshake), and longjmps the
 * host SPU thread back to spu_run_with_halt so the job does not spin past the
 * stop. Complements ctx->status; harmless where the runtime handles status. */
void spu_stop(spu_context* ctx);
/* Lower-level longjmp helper: abort the host SPU thread back to spu_run_with_halt
 * (used for the infinite no-op self-loop / idle halt idiom). */
void spu_halt(spu_context* ctx);

/* Channel access -- implemented by the runtime (MFC DMA engine, mailboxes,
 * signal notification, decrementer). See runtime/spu/spu_dma.h. */
u128 spu_rdch(spu_context* ctx, uint32_t channel);
uint32_t spu_rchcnt(spu_context* ctx, uint32_t channel);
void spu_wrch(spu_context* ctx, uint32_t channel, u128 value);

/* Execution trace (only emitted when the lifter was invoked with --trace). */
void spu_trace_init(const char* path);
void spu_trace_pc(spu_context* ctx, uint32_t pc);
void spu_trace_rt(spu_context* ctx, uint32_t rt);

#ifdef __cplusplus
}
#endif


void spu_job_01492300_spu_func_01492300(spu_context* ctx);
void spu_job_01492300_spu_func_01492318(spu_context* ctx);
void spu_job_01492300_spu_func_01492330(spu_context* ctx);
void spu_job_01492300_spu_func_01492348(spu_context* ctx);
void spu_job_01492300_spu_func_01492350(spu_context* ctx);
void spu_job_01492300_spu_func_014923C4(spu_context* ctx);
void spu_job_01492300_spu_func_014923F0(spu_context* ctx);
void spu_job_01492300_spu_func_01492414(spu_context* ctx);
void spu_job_01492300_spu_func_01492430(spu_context* ctx);
void spu_job_01492300_spu_func_01492450(spu_context* ctx);
void spu_job_01492300_spu_func_01492478(spu_context* ctx);
void spu_job_01492300_spu_func_01492528(spu_context* ctx);
void spu_job_01492300_spu_func_01492550(spu_context* ctx);
void spu_job_01492300_spu_func_00012318(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012330(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012348(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012350(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000123C4(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000123F0(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012414(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012430(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012450(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012478(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012528(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012550(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012580(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000125C0(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000125D4(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000125FC(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012628(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012630(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012660(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012690(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012740(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012768(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012798(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000127A0(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000127E0(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012808(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012848(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012894(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000128F4(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000128FC(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012938(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012948(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000129F8(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012A0C(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012A10(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012A7C(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012AA8(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012B00(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012B08(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012B60(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012BD0(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012C1C(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012C7C(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012C9C(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012CA0(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012CD4(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012D10(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012D78(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012DC4(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012E24(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012E38(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012E60(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012E70(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012F7C(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012F90(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00012FD4(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013000(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013040(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_0001308C(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000130EC(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000130F4(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_0001312C(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013158(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_0001318C(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000131A0(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000131A4(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000131B8(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000131C0(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000131F0(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_0001323C(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013250(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013268(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013280(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013298(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000132B0(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000132C8(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000132E0(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000132F8(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013310(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013328(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013340(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013358(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013370(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013388(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000133A0(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000133B0(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013420(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_0001346C(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000134CC(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013504(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013508(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013540(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013548(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013580(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013590(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000135B4(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000135C8(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000135E0(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013608(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013638(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013668(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013698(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000136C8(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000136F8(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013728(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013750(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000137E8(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013810(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013840(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013880(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013894(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000138B0(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000138E0(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013914(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013950(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013988(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000139B8(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000139E4(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013A1C(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013A58(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013A7C(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013AC0(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013B00(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013B40(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013B7C(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013BB8(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013BF8(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013C38(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013C64(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013C90(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013CC0(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013D08(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013D48(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013D88(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013DC8(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013E08(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013E48(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013E88(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013EC8(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013EE8(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013EFC(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013F30(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013F50(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013F64(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013F98(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013FB8(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00013FCC(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00014000(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00014020(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00014034(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00014068(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00014088(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_0001409C(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000140D0(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000140F0(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00014104(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00014138(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00014158(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_0001416C(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000141A0(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000141C0(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_000141D4(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00014208(spu_context* ctx); /* external */
void spu_job_01492300_spu_func_00014394(spu_context* ctx); /* external */

/* Runtime glue (runtime/spu/spu_channels.c) */
void spu_register_function(uint32_t addr, void (*fn)(spu_context*));
/* Call once at init to register this image's functions for
 * indirect-branch dispatch (spu_indirect_branch). */
void spu_job_01492300_spu_recomp_register(void);
