/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#include "spu_recomp.h"
#include "../../runtime/spu/spu_helpers.h"


void spu_job_01485F00_spu_func_01485F00(spu_context* ctx) {
        ctx->gpr[2] = spu_ila(0x18030);
        ctx->gpr[2] = spu_ila(0x104F1);
        ctx->gpr[2] = spu_ila(0x365C6);
        ctx->gpr[2] = spu_ila(0x2FF27);
        ctx->gpr[80] = spu_xori(ctx->gpr[80], 4);
        { ctx->pc = 0x5F18; SPU_TAILCALL(spu_job_01485F00_spu_func_00005F18(ctx)); }
}

void spu_job_01485F00_spu_func_01485F18(spu_context* ctx) {
        ctx->gpr[80] = spu_xori(ctx->gpr[80], 4);
        { ctx->pc = 0x5F30; SPU_TAILCALL(spu_job_01485F00_spu_func_00005F30(ctx)); }
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
}

void spu_job_01485F00_spu_func_01485F30(spu_context* ctx) {
        ctx->gpr[2] = spu_ori(ctx->gpr[3], 0);
        ctx->gpr[3] = spu_ai(ctx->gpr[4], 48);
        ctx->gpr[4] = spu_ls_read128(ctx, ctx->gpr[2]._u32[0] + 0x20);
        ctx->gpr[4] = spu_rotqby(ctx->gpr[4], ctx->gpr[2]);
        { ctx->pc = 0xB038; SPU_TAILCALL(spu_job_01485F00_spu_func_0000B038(ctx)); }
        /* nop */;
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        /* nop */;
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        /* nop */;
        ctx->gpr[14] = spu_shli(ctx->gpr[6], 2);
        /* branch hint (ignored) */;
        ctx->gpr[10] = spu_ila(0x8760);
        ctx->gpr[8] = spu_ila(0x88B0);
        ctx->gpr[2] = spu_il(1);
        ctx->gpr[6] = spu_a(ctx->gpr[14], ctx->gpr[3]);
        ctx->gpr[9] = spu_cwx(ctx->gpr[1], ctx->gpr[8]);
        ctx->gpr[12] = spu_ls_read128(ctx, ctx->gpr[6]._u32[0] + ctx->gpr[10]._u32[0]);
        ctx->gpr[13] = spu_cwx(ctx->gpr[6], ctx->gpr[10]);
        ctx->gpr[11] = spu_shufb(ctx->gpr[7], ctx->gpr[12], ctx->gpr[13]);
        spu_ls_write128(ctx, ctx->gpr[6]._u32[0] + ctx->gpr[10]._u32[0], ctx->gpr[11]);
        ctx->gpr[5] = spu_ls_read128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[8]._u32[0]);
        ctx->gpr[4] = spu_shufb(ctx->gpr[2], ctx->gpr[5], ctx->gpr[9]);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[8]._u32[0], ctx->gpr[4]);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        /* nop */;
        ctx->gpr[14] = spu_shli(ctx->gpr[6], 2);
        /* branch hint (ignored) */;
        ctx->gpr[10] = spu_ila(0x8780);
        ctx->gpr[8] = spu_ila(0x88B0);
        ctx->gpr[2] = spu_il(1);
        ctx->gpr[6] = spu_a(ctx->gpr[14], ctx->gpr[3]);
        ctx->gpr[9] = spu_cwx(ctx->gpr[1], ctx->gpr[8]);
        ctx->gpr[12] = spu_ls_read128(ctx, ctx->gpr[6]._u32[0] + ctx->gpr[10]._u32[0]);
        ctx->gpr[13] = spu_cwx(ctx->gpr[6], ctx->gpr[10]);
        ctx->gpr[11] = spu_shufb(ctx->gpr[7], ctx->gpr[12], ctx->gpr[13]);
        spu_ls_write128(ctx, ctx->gpr[6]._u32[0] + ctx->gpr[10]._u32[0], ctx->gpr[11]);
        ctx->gpr[5] = spu_ls_read128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[8]._u32[0]);
        ctx->gpr[4] = spu_shufb(ctx->gpr[2], ctx->gpr[5], ctx->gpr[9]);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[8]._u32[0], ctx->gpr[4]);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        /* nop */;
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        /* nop */;
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        /* nop */;
        ctx->gpr[13] = spu_cgti(ctx->gpr[4], -1);
        ctx->gpr[16] = spu_shlqbyi(ctx->gpr[3], 0);
        ctx->gpr[11] = spu_il(3);
        ctx->gpr[21] = spu_fsmbi(0xFF);
        ctx->gpr[12] = spu_and(ctx->gpr[4], ctx->gpr[13]);
        ctx->gpr[18] = spu_fsmbi(0x0);
        ctx->gpr[6] = spu_ila(0x88B6);
        ctx->gpr[13] = spu_fsmbi(0x0);
        ctx->gpr[10] = spu_cgti(ctx->gpr[12], 3);
        ctx->gpr[22] = spu_fsmbi(0xFFFF);
        ctx->gpr[9] = spu_il(308);
        ctx->gpr[8] = spu_ls_read128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[6]._u32[0]);
        ctx->gpr[17] = spu_selb(ctx->gpr[12], ctx->gpr[11], ctx->gpr[10]);
        ctx->gpr[4] = spu_chx(ctx->gpr[1], ctx->gpr[6]);
        ctx->gpr[15] = spu_ila(0x128);
        ctx->gpr[14] = spu_link(0x1486028); spu_host_call_push(ctx, 0x1486028); spu_job_01485F00_spu_func_00006028(ctx); spu_host_call_pop(ctx);
        { ctx->pc = 0x1486028; SPU_TAILCALL(spu_job_01485F00_spu_func_01486028(ctx)); }
}

void spu_job_01485F00_spu_func_01486028(spu_context* ctx) {
        ctx->gpr[7] = spu_mpyh(ctx->gpr[17], ctx->gpr[9]);
        ctx->gpr[12] = spu_shlqbyi(ctx->gpr[16], 0);
        ctx->gpr[3] = spu_mpyui(ctx->gpr[17], 308);
        ctx->gpr[23] = spu_ila(0x5A50);
        ctx->gpr[79] = spu_sf(ctx->gpr[15], ctx->gpr[14]);
        ctx->gpr[5] = spu_shufb(ctx->gpr[17], ctx->gpr[8], ctx->gpr[4]);
        ctx->gpr[14] = spu_il(8512);
        ctx->gpr[23] = spu_a(ctx->gpr[23], ctx->gpr[79]);
        ctx->gpr[19] = spu_il(8568);
        /* nop */;
        ctx->gpr[20] = spu_il(8656);
        spu_ls_write128(ctx, ctx->gpr[16]._u32[0] + ctx->gpr[6]._u32[0], ctx->gpr[5]);
        ctx->gpr[2] = spu_a(ctx->gpr[7], ctx->gpr[3]);
        ctx->gpr[15] = spu_ai(ctx->gpr[2], 240);
        { ctx->pc = 0x1486060; SPU_TAILCALL(spu_job_01485F00_spu_func_01486060(ctx)); }
}

void spu_job_01485F00_spu_func_01486060(spu_context* ctx) {
        ctx->gpr[6] = spu_a(ctx->gpr[12], ctx->gpr[14]);
        ctx->gpr[2] = spu_andi(ctx->gpr[6], 15);
        if (ctx->gpr[2]._u32[0] != 0) { ctx->pc = 0x63D8; SPU_TAILCALL(spu_job_01485F00_spu_func_000063D8(ctx)); }
        spu_ls_write128(ctx, ctx->gpr[12]._u32[0] + ctx->gpr[14]._u32[0], ctx->gpr[18]);
        { ctx->pc = 0x1486070; SPU_TAILCALL(spu_job_01485F00_spu_func_01486070(ctx)); }
}

void spu_job_01485F00_spu_func_01486070(spu_context* ctx) {
        ctx->gpr[6] = spu_il(8544);
        ctx->gpr[10] = spu_fsmbi(0x0);
        ctx->gpr[7] = spu_a(ctx->gpr[12], ctx->gpr[6]);
        ctx->gpr[2] = spu_andi(ctx->gpr[7], 15);
        if (ctx->gpr[2]._u32[0] != 0) { ctx->pc = 0x6348; SPU_TAILCALL(spu_job_01485F00_spu_func_00006348(ctx)); }
        ctx->gpr[39] = spu_ls_read128(ctx, ctx->gpr[12]._u32[0] + ctx->gpr[6]._u32[0]);
        ctx->gpr[38] = spu_and(ctx->gpr[39], ctx->gpr[21]);
        spu_ls_write128(ctx, ctx->gpr[12]._u32[0] + ctx->gpr[6]._u32[0], ctx->gpr[38]);
        { ctx->pc = 0x1486090; SPU_TAILCALL(spu_job_01485F00_spu_func_01486090(ctx)); }
}

void spu_job_01485F00_spu_func_01486090(spu_context* ctx) {
        ctx->gpr[10] = spu_a(ctx->gpr[15], ctx->gpr[23]);
        /* branch hint (ignored) */;
        ctx->gpr[9] = spu_a(ctx->gpr[12], ctx->gpr[19]);
        ctx->gpr[11] = spu_fsmbi(0x0);
        { ctx->pc = 0x14860A0; SPU_TAILCALL(spu_job_01485F00_spu_func_014860A0(ctx)); }
}

void spu_job_01485F00_spu_func_014860A0(spu_context* ctx) {
        ctx->gpr[63] = spu_ai(ctx->gpr[10], 14);
        ctx->gpr[64] = spu_ls_read128(ctx, ctx->gpr[10]._u32[0] + 0x0);
        ctx->gpr[11] = spu_ahi(ctx->gpr[11], 1);
        ctx->gpr[62] = spu_ls_read128(ctx, ctx->gpr[10]._u32[0] + 0x10);
        ctx->gpr[10] = spu_ai(ctx->gpr[10], 2);
        ctx->gpr[60] = spu_ls_read128(ctx, ctx->gpr[9]._u32[0] + 0x0);
        ctx->gpr[54] = spu_ceqhi(ctx->gpr[11], 8);
        ctx->gpr[57] = spu_ls_read128(ctx, ctx->gpr[9]._u32[0] + 0x30);
        ctx->gpr[59] = spu_chd(ctx->gpr[9], 0);
        ctx->gpr[61] = spu_rotqby(ctx->gpr[64], ctx->gpr[63]);
        ctx->gpr[58] = spu_rotqby(ctx->gpr[62], ctx->gpr[63]);
        ctx->gpr[56] = spu_shufb(ctx->gpr[61], ctx->gpr[60], ctx->gpr[59]);
        ctx->gpr[55] = spu_shufb(ctx->gpr[58], ctx->gpr[57], ctx->gpr[59]);
        spu_ls_write128(ctx, ctx->gpr[9]._u32[0] + 0x0, ctx->gpr[56]);
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[9]._u32[0] + 0x30, ctx->gpr[55]);
        ctx->gpr[9] = spu_ai(ctx->gpr[9], 2);
        if (ctx->gpr[54]._u16[1] == 0) { ctx->pc = 0x60A0; SPU_TAILCALL(spu_job_01485F00_spu_func_000060A0(ctx)); }
        ctx->gpr[13] = spu_ai(ctx->gpr[13], 1);
        ctx->gpr[12] = spu_a(ctx->gpr[12], ctx->gpr[20]);
        ctx->gpr[65] = spu_ceqi(ctx->gpr[13], 4);
        if (ctx->gpr[65]._u32[0] == 0) { ctx->pc = 0x6060; SPU_TAILCALL(spu_job_01485F00_spu_func_00006060(ctx)); }
        ctx->gpr[14] = spu_il(0);
        ctx->gpr[20] = spu_fsmbi(0x0);
        ctx->gpr[15] = spu_il(8512);
        ctx->gpr[24] = spu_fsmbi(0xFFFF);
        ctx->gpr[22] = spu_il(8584);
        ctx->gpr[11] = spu_shlqbyi(ctx->gpr[16], 0);
        ctx->gpr[13] = spu_il(8604);
        ctx->gpr[18] = spu_il(8606);
        ctx->gpr[12] = spu_il(8590);
        ctx->gpr[19] = spu_il(8588);
        ctx->gpr[21] = spu_il(8656);
        { ctx->pc = 0x1486124; SPU_TAILCALL(spu_job_01485F00_spu_func_01486124(ctx)); }
}

void spu_job_01485F00_spu_func_01486124(spu_context* ctx) {
        ctx->gpr[6] = spu_a(ctx->gpr[11], ctx->gpr[15]);
        ctx->gpr[2] = spu_andi(ctx->gpr[6], 15);
        if (ctx->gpr[2]._u32[0] != 0) { ctx->pc = 0x6308; SPU_TAILCALL(spu_job_01485F00_spu_func_00006308(ctx)); }
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[15]._u32[0], ctx->gpr[20]);
        { ctx->pc = 0x1486138; SPU_TAILCALL(spu_job_01485F00_spu_func_01486138(ctx)); }
}

void spu_job_01485F00_spu_func_01486138(spu_context* ctx) {
        ctx->gpr[8] = spu_a(ctx->gpr[11], ctx->gpr[22]);
        /* branch hint (ignored) */;
        ctx->gpr[9] = spu_il(0);
        ctx->gpr[10] = spu_fsmbi(0x0);
        { ctx->pc = 0x1486148; SPU_TAILCALL(spu_job_01485F00_spu_func_01486148(ctx)); }
}

void spu_job_01485F00_spu_func_01486148(spu_context* ctx) {
        ctx->gpr[32] = spu_ai(ctx->gpr[8], 14);
        ctx->gpr[31] = spu_ls_read128(ctx, ctx->gpr[8]._u32[0] + -0x10);
        ctx->gpr[10] = spu_ahi(ctx->gpr[10], 1);
        ctx->gpr[29] = spu_ls_read128(ctx, ctx->gpr[8]._u32[0] + 0x0);
        /* nop */;
        ctx->gpr[28] = spu_ls_read128(ctx, ctx->gpr[8]._u32[0] + -0x20);
        ctx->gpr[79] = spu_ceqhi(ctx->gpr[10], 8);
        ctx->gpr[3] = spu_chd(ctx->gpr[8], 0);
        ctx->gpr[25] = spu_ls_read128(ctx, ctx->gpr[8]._u32[0] + 0x10);
        ctx->gpr[30] = spu_rotqby(ctx->gpr[31], ctx->gpr[32]);
        ctx->gpr[4] = spu_shufb(ctx->gpr[9], ctx->gpr[29], ctx->gpr[3]);
        ctx->gpr[26] = spu_shufb(ctx->gpr[9], ctx->gpr[28], ctx->gpr[3]);
        ctx->gpr[27] = spu_xshw(ctx->gpr[30]);
        spu_ls_write128(ctx, ctx->gpr[8]._u32[0] + 0x0, ctx->gpr[4]);
        ctx->gpr[9] = spu_a(ctx->gpr[9], ctx->gpr[27]);
        spu_ls_write128(ctx, ctx->gpr[8]._u32[0] + -0x20, ctx->gpr[26]);
        ctx->gpr[5] = spu_ahi(ctx->gpr[9], -1);
        ctx->gpr[6] = spu_shufb(ctx->gpr[5], ctx->gpr[25], ctx->gpr[3]);
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[8]._u32[0] + 0x10, ctx->gpr[6]);
        ctx->gpr[8] = spu_ai(ctx->gpr[8], 2);
        if (ctx->gpr[79]._u16[1] == 0) { ctx->pc = 0x6148; SPU_TAILCALL(spu_job_01485F00_spu_func_00006148(ctx)); }
        ctx->gpr[42] = spu_ai(ctx->gpr[18], 14);
        ctx->gpr[41] = spu_ls_read128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[18]._u32[0]);
        ctx->gpr[38] = spu_ai(ctx->gpr[19], 14);
        ctx->gpr[39] = spu_ls_read128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[13]._u32[0]);
        ctx->gpr[14] = spu_ai(ctx->gpr[14], 1);
        /* branch hint (ignored) */;
        ctx->gpr[8] = spu_chx(ctx->gpr[1], ctx->gpr[13]);
        ctx->gpr[37] = spu_ls_read128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[19]._u32[0]);
        ctx->gpr[9] = spu_ceqi(ctx->gpr[14], 4);
        ctx->gpr[35] = spu_chx(ctx->gpr[1], ctx->gpr[12]);
        ctx->gpr[40] = spu_rotqby(ctx->gpr[41], ctx->gpr[42]);
        ctx->gpr[36] = spu_shufb(ctx->gpr[40], ctx->gpr[39], ctx->gpr[8]);
        ctx->gpr[34] = spu_rotqby(ctx->gpr[37], ctx->gpr[38]);
        spu_ls_write128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[13]._u32[0], ctx->gpr[36]);
        ctx->gpr[33] = spu_ls_read128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[12]._u32[0]);
        ctx->gpr[10] = spu_shufb(ctx->gpr[34], ctx->gpr[33], ctx->gpr[35]);
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[12]._u32[0], ctx->gpr[10]);
        ctx->gpr[11] = spu_a(ctx->gpr[11], ctx->gpr[21]);
        if (ctx->gpr[9]._u32[0] == 0) { ctx->pc = 0x6124; SPU_TAILCALL(spu_job_01485F00_spu_func_00006124(ctx)); }
        ctx->gpr[13] = spu_il(0);
        /* nop */;
        { ctx->pc = 0x14861F8; SPU_TAILCALL(spu_job_01485F00_spu_func_014861F8(ctx)); }
}

void spu_job_01485F00_spu_func_014861F8(spu_context* ctx) {
        ctx->gpr[71] = spu_il(308);
        /* branch hint (ignored) */;
        ctx->gpr[68] = spu_mpyui(ctx->gpr[17], 308);
        ctx->gpr[12] = spu_fsmbi(0x0);
        ctx->gpr[67] = spu_mpyh(ctx->gpr[17], ctx->gpr[71]);
        ctx->gpr[70] = spu_a(ctx->gpr[13], ctx->gpr[13]);
        ctx->gpr[7] = spu_ila(0x8790);
        ctx->gpr[69] = spu_a(ctx->gpr[70], ctx->gpr[13]);
        ctx->gpr[65] = spu_shli(ctx->gpr[69], 4);
        ctx->gpr[66] = spu_a(ctx->gpr[67], ctx->gpr[68]);
        ctx->gpr[64] = spu_a(ctx->gpr[65], ctx->gpr[7]);
        ctx->gpr[63] = spu_a(ctx->gpr[65], ctx->gpr[66]);
        ctx->gpr[10] = spu_a(ctx->gpr[16], ctx->gpr[64]);
        ctx->gpr[11] = spu_a(ctx->gpr[63], ctx->gpr[23]);
        { ctx->pc = 0x1486230; SPU_TAILCALL(spu_job_01485F00_spu_func_01486230(ctx)); }
}

void spu_job_01485F00_spu_func_01486230(spu_context* ctx) {
        ctx->gpr[19] = spu_il(4);
        ctx->gpr[47] = spu_ls_read128(ctx, ctx->gpr[11]._u32[0] + 0x0);
        ctx->gpr[43] = spu_ai(ctx->gpr[11], 4);
        ctx->gpr[44] = spu_ls_read128(ctx, ctx->gpr[10]._u32[0] + 0x0);
        ctx->gpr[12] = spu_ahi(ctx->gpr[12], 1);
        ctx->gpr[46] = spu_cwd(ctx->gpr[10], 0);
        ctx->gpr[24] = spu_ls_read128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[19]._u32[0]);
        ctx->gpr[14] = spu_cwd(ctx->gpr[10], 4);
        ctx->gpr[18] = spu_ceqhi(ctx->gpr[12], 6);
        ctx->gpr[45] = spu_rotqby(ctx->gpr[47], ctx->gpr[11]);
        ctx->gpr[11] = spu_ai(ctx->gpr[11], 8);
        ctx->gpr[22] = spu_rotqby(ctx->gpr[24], ctx->gpr[43]);
        ctx->gpr[15] = spu_shufb(ctx->gpr[45], ctx->gpr[44], ctx->gpr[46]);
        spu_ls_write128(ctx, ctx->gpr[10]._u32[0] + 0x0, ctx->gpr[15]);
        ctx->gpr[21] = spu_ls_read128(ctx, ctx->gpr[10]._u32[0] + ctx->gpr[19]._u32[0]);
        ctx->gpr[20] = spu_shufb(ctx->gpr[22], ctx->gpr[21], ctx->gpr[14]);
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[10]._u32[0] + ctx->gpr[19]._u32[0], ctx->gpr[20]);
        ctx->gpr[10] = spu_ai(ctx->gpr[10], 8);
        if (ctx->gpr[18]._u16[1] == 0) { ctx->pc = 0x6230; SPU_TAILCALL(spu_job_01485F00_spu_func_00006230(ctx)); }
        ctx->gpr[13] = spu_ai(ctx->gpr[13], 1);
        ctx->gpr[11] = spu_ceqi(ctx->gpr[13], 5);
        /* nop */;
        if (ctx->gpr[11]._u32[0] == 0) { ctx->pc = 0x61F8; SPU_TAILCALL(spu_job_01485F00_spu_func_000061F8(ctx)); }
        ctx->gpr[55] = spu_il(308);
        /* branch hint (ignored) */;
        ctx->gpr[54] = spu_mpyui(ctx->gpr[17], 308);
        ctx->gpr[9] = spu_fsmbi(0x0);
        ctx->gpr[53] = spu_mpyh(ctx->gpr[17], ctx->gpr[55]);
        ctx->gpr[17] = spu_ila(0x88A8);
        ctx->gpr[10] = spu_ila(0x8880);
        ctx->gpr[12] = spu_ls_read128(ctx, ctx->gpr[16]._u32[0] + ctx->gpr[17]._u32[0]);
        ctx->gpr[48] = spu_cwx(ctx->gpr[1], ctx->gpr[17]);
        ctx->gpr[52] = spu_a(ctx->gpr[53], ctx->gpr[54]);
        ctx->gpr[50] = spu_a(ctx->gpr[52], ctx->gpr[23]);
        ctx->gpr[51] = spu_ai(ctx->gpr[52], 272);
        ctx->gpr[49] = spu_ls_read128(ctx, ctx->gpr[50]._u32[0] + 0x130);
        ctx->gpr[8] = spu_a(ctx->gpr[51], ctx->gpr[23]);
        ctx->gpr[13] = spu_rotqby(ctx->gpr[49], ctx->gpr[50]);
        ctx->gpr[23] = spu_shufb(ctx->gpr[13], ctx->gpr[12], ctx->gpr[48]);
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[16]._u32[0] + ctx->gpr[17]._u32[0], ctx->gpr[23]);
        { ctx->pc = 0x14862D8; SPU_TAILCALL(spu_job_01485F00_spu_func_014862D8(ctx)); }
}

void spu_job_01485F00_spu_func_014862D8(spu_context* ctx) {
        ctx->gpr[57] = spu_a(ctx->gpr[9], ctx->gpr[16]);
        ctx->gpr[62] = spu_ls_read128(ctx, ctx->gpr[8]._u32[0] + 0x0);
        ctx->gpr[9] = spu_ai(ctx->gpr[9], 4);
        ctx->gpr[59] = spu_ls_read128(ctx, ctx->gpr[57]._u32[0] + ctx->gpr[10]._u32[0]);
        ctx->gpr[56] = spu_ceqi(ctx->gpr[9], 32);
        ctx->gpr[61] = spu_cwx(ctx->gpr[57], ctx->gpr[10]);
        ctx->gpr[60] = spu_rotqby(ctx->gpr[62], ctx->gpr[8]);
        ctx->gpr[8] = spu_ai(ctx->gpr[8], 4);
        ctx->gpr[58] = spu_shufb(ctx->gpr[60], ctx->gpr[59], ctx->gpr[61]);
        spu_ls_write128(ctx, ctx->gpr[57]._u32[0] + ctx->gpr[10]._u32[0], ctx->gpr[58]);
        if (ctx->gpr[56]._u32[0] == 0) { ctx->pc = 0x62D8; SPU_TAILCALL(spu_job_01485F00_spu_func_000062D8(ctx)); }
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
}

void spu_job_01485F00_spu_func_01486308(spu_context* ctx) {
        ctx->gpr[4] = spu_ai(ctx->gpr[2], 16);
        /* branch hint (ignored) */;
        ctx->gpr[5] = spu_sfi(ctx->gpr[2], 16);
        ctx->gpr[8] = spu_fsmbi(0xFFFF);
        ctx->gpr[66] = spu_clgti(ctx->gpr[4], 15);
        ctx->gpr[7] = spu_shlqby(ctx->gpr[8], ctx->gpr[5]);
        /* nop */;
        if (ctx->gpr[66]._u32[0] != 0) { ctx->pc = 0x6388; SPU_TAILCALL(spu_job_01485F00_spu_func_00006388(ctx)); }
        ctx->gpr[71] = spu_sfi(ctx->gpr[4], 0);
        ctx->gpr[68] = spu_ls_read128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[15]._u32[0]);
        ctx->gpr[70] = spu_rotqmby(ctx->gpr[8], ctx->gpr[71]);
        ctx->gpr[69] = spu_or(ctx->gpr[7], ctx->gpr[70]);
        ctx->gpr[67] = spu_and(ctx->gpr[68], ctx->gpr[69]);
        spu_ls_write128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[15]._u32[0], ctx->gpr[67]);
        /* nop */;
        { ctx->pc = 0x6138; SPU_TAILCALL(spu_job_01485F00_spu_func_00006138(ctx)); }
}

void spu_job_01485F00_spu_func_01486348(spu_context* ctx) {
        ctx->gpr[4] = spu_ai(ctx->gpr[2], 8);
        /* branch hint (ignored) */;
        ctx->gpr[5] = spu_sfi(ctx->gpr[2], 16);
        ctx->gpr[9] = spu_fsmbi(0xFFFF);
        ctx->gpr[40] = spu_clgti(ctx->gpr[4], 15);
        ctx->gpr[8] = spu_shlqby(ctx->gpr[9], ctx->gpr[5]);
        /* nop */;
        if (ctx->gpr[40]._u32[0] != 0) { ctx->pc = 0x6418; SPU_TAILCALL(spu_job_01485F00_spu_func_00006418(ctx)); }
        ctx->gpr[45] = spu_sfi(ctx->gpr[4], 0);
        ctx->gpr[42] = spu_ls_read128(ctx, ctx->gpr[12]._u32[0] + ctx->gpr[6]._u32[0]);
        ctx->gpr[44] = spu_rotqmby(ctx->gpr[9], ctx->gpr[45]);
        ctx->gpr[43] = spu_or(ctx->gpr[8], ctx->gpr[44]);
        ctx->gpr[41] = spu_and(ctx->gpr[42], ctx->gpr[43]);
        spu_ls_write128(ctx, ctx->gpr[12]._u32[0] + ctx->gpr[6]._u32[0], ctx->gpr[41]);
        /* nop */;
        { ctx->pc = 0x6090; SPU_TAILCALL(spu_job_01485F00_spu_func_00006090(ctx)); }
}

void spu_job_01485F00_spu_func_01486388(spu_context* ctx) {
        ctx->gpr[4] = spu_sfi(ctx->gpr[5], 16);
        /* branch hint (ignored) */;
        ctx->gpr[5] = spu_a(ctx->gpr[6], ctx->gpr[5]);
        ctx->gpr[74] = spu_ls_read128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[15]._u32[0]);
        ctx->gpr[72] = spu_clgti(ctx->gpr[4], 15);
        ctx->gpr[73] = spu_and(ctx->gpr[74], ctx->gpr[7]);
        spu_ls_write128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[15]._u32[0], ctx->gpr[73]);
        if (ctx->gpr[72]._u32[0] == 0) { ctx->pc = 0x63BC; SPU_TAILCALL(spu_job_01485F00_spu_func_000063BC(ctx)); }
        { ctx->pc = 0x14863A8; SPU_TAILCALL(spu_job_01485F00_spu_func_014863A8(ctx)); }
}

void spu_job_01485F00_spu_func_014863A8(spu_context* ctx) {
        ctx->gpr[4] = spu_ai(ctx->gpr[4], -16);
        spu_ls_write128(ctx, ctx->gpr[5]._u32[0] + 0x0, ctx->gpr[20]);
        ctx->gpr[5] = spu_ai(ctx->gpr[5], 16);
        ctx->gpr[75] = spu_clgti(ctx->gpr[4], 15);
        if (ctx->gpr[75]._u32[0] != 0) { ctx->pc = 0x63A8; SPU_TAILCALL(spu_job_01485F00_spu_func_000063A8(ctx)); }
        { ctx->pc = 0x14863BC; SPU_TAILCALL(spu_job_01485F00_spu_func_014863BC(ctx)); }
}

void spu_job_01485F00_spu_func_014863BC(spu_context* ctx) {
        if (ctx->gpr[4]._u32[0] == 0) { ctx->pc = 0x6138; SPU_TAILCALL(spu_job_01485F00_spu_func_00006138(ctx)); }
        ctx->gpr[2] = spu_sfi(ctx->gpr[4], 0);
        ctx->gpr[77] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + 0x0);
        ctx->gpr[78] = spu_rotqmby(ctx->gpr[24], ctx->gpr[2]);
        ctx->gpr[76] = spu_and(ctx->gpr[77], ctx->gpr[78]);
        spu_ls_write128(ctx, ctx->gpr[5]._u32[0] + 0x0, ctx->gpr[76]);
        { ctx->pc = 0x6138; SPU_TAILCALL(spu_job_01485F00_spu_func_00006138(ctx)); }
}

void spu_job_01485F00_spu_func_014863D8(spu_context* ctx) {
        ctx->gpr[4] = spu_ai(ctx->gpr[2], 16);
        /* branch hint (ignored) */;
        ctx->gpr[5] = spu_sfi(ctx->gpr[2], 16);
        ctx->gpr[8] = spu_fsmbi(0xFFFF);
        ctx->gpr[24] = spu_clgti(ctx->gpr[4], 15);
        ctx->gpr[7] = spu_shlqby(ctx->gpr[8], ctx->gpr[5]);
        /* nop */;
        if (ctx->gpr[24]._u32[0] != 0) { ctx->pc = 0x6468; SPU_TAILCALL(spu_job_01485F00_spu_func_00006468(ctx)); }
        ctx->gpr[29] = spu_sfi(ctx->gpr[4], 0);
        ctx->gpr[26] = spu_ls_read128(ctx, ctx->gpr[12]._u32[0] + ctx->gpr[14]._u32[0]);
        ctx->gpr[28] = spu_rotqmby(ctx->gpr[8], ctx->gpr[29]);
        ctx->gpr[27] = spu_or(ctx->gpr[7], ctx->gpr[28]);
        ctx->gpr[25] = spu_and(ctx->gpr[26], ctx->gpr[27]);
        spu_ls_write128(ctx, ctx->gpr[12]._u32[0] + ctx->gpr[14]._u32[0], ctx->gpr[25]);
        /* nop */;
        { ctx->pc = 0x6070; SPU_TAILCALL(spu_job_01485F00_spu_func_00006070(ctx)); }
}

void spu_job_01485F00_spu_func_01486418(spu_context* ctx) {
        ctx->gpr[4] = spu_sfi(ctx->gpr[5], 8);
        /* branch hint (ignored) */;
        ctx->gpr[5] = spu_a(ctx->gpr[7], ctx->gpr[5]);
        ctx->gpr[48] = spu_ls_read128(ctx, ctx->gpr[12]._u32[0] + ctx->gpr[6]._u32[0]);
        ctx->gpr[46] = spu_clgti(ctx->gpr[4], 15);
        ctx->gpr[47] = spu_and(ctx->gpr[48], ctx->gpr[8]);
        spu_ls_write128(ctx, ctx->gpr[12]._u32[0] + ctx->gpr[6]._u32[0], ctx->gpr[47]);
        if (ctx->gpr[46]._u32[0] == 0) { ctx->pc = 0x644C; SPU_TAILCALL(spu_job_01485F00_spu_func_0000644C(ctx)); }
        { ctx->pc = 0x1486438; SPU_TAILCALL(spu_job_01485F00_spu_func_01486438(ctx)); }
}

void spu_job_01485F00_spu_func_01486438(spu_context* ctx) {
        ctx->gpr[4] = spu_ai(ctx->gpr[4], -16);
        spu_ls_write128(ctx, ctx->gpr[5]._u32[0] + 0x0, ctx->gpr[10]);
        ctx->gpr[5] = spu_ai(ctx->gpr[5], 16);
        ctx->gpr[49] = spu_clgti(ctx->gpr[4], 15);
        if (ctx->gpr[49]._u32[0] != 0) { ctx->pc = 0x6438; SPU_TAILCALL(spu_job_01485F00_spu_func_00006438(ctx)); }
        { ctx->pc = 0x148644C; SPU_TAILCALL(spu_job_01485F00_spu_func_0148644C(ctx)); }
}

void spu_job_01485F00_spu_func_0148644C(spu_context* ctx) {
        if (ctx->gpr[4]._u32[0] == 0) { ctx->pc = 0x6090; SPU_TAILCALL(spu_job_01485F00_spu_func_00006090(ctx)); }
        ctx->gpr[53] = spu_sfi(ctx->gpr[4], 0);
        ctx->gpr[51] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + 0x0);
        ctx->gpr[52] = spu_rotqmby(ctx->gpr[22], ctx->gpr[53]);
        ctx->gpr[50] = spu_and(ctx->gpr[51], ctx->gpr[52]);
        spu_ls_write128(ctx, ctx->gpr[5]._u32[0] + 0x0, ctx->gpr[50]);
        { ctx->pc = 0x6090; SPU_TAILCALL(spu_job_01485F00_spu_func_00006090(ctx)); }
}

void spu_job_01485F00_spu_func_01486468(spu_context* ctx) {
        ctx->gpr[4] = spu_sfi(ctx->gpr[5], 16);
        /* branch hint (ignored) */;
        ctx->gpr[5] = spu_a(ctx->gpr[6], ctx->gpr[5]);
        ctx->gpr[32] = spu_ls_read128(ctx, ctx->gpr[12]._u32[0] + ctx->gpr[14]._u32[0]);
        ctx->gpr[30] = spu_clgti(ctx->gpr[4], 15);
        ctx->gpr[31] = spu_and(ctx->gpr[32], ctx->gpr[7]);
        spu_ls_write128(ctx, ctx->gpr[12]._u32[0] + ctx->gpr[14]._u32[0], ctx->gpr[31]);
        if (ctx->gpr[30]._u32[0] == 0) { ctx->pc = 0x649C; SPU_TAILCALL(spu_job_01485F00_spu_func_0000649C(ctx)); }
        { ctx->pc = 0x1486488; SPU_TAILCALL(spu_job_01485F00_spu_func_01486488(ctx)); }
}

void spu_job_01485F00_spu_func_01486488(spu_context* ctx) {
        ctx->gpr[4] = spu_ai(ctx->gpr[4], -16);
        spu_ls_write128(ctx, ctx->gpr[5]._u32[0] + 0x0, ctx->gpr[18]);
        ctx->gpr[5] = spu_ai(ctx->gpr[5], 16);
        ctx->gpr[33] = spu_clgti(ctx->gpr[4], 15);
        if (ctx->gpr[33]._u32[0] != 0) { ctx->pc = 0x6488; SPU_TAILCALL(spu_job_01485F00_spu_func_00006488(ctx)); }
        { ctx->pc = 0x148649C; SPU_TAILCALL(spu_job_01485F00_spu_func_0148649C(ctx)); }
}

void spu_job_01485F00_spu_func_0148649C(spu_context* ctx) {
        if (ctx->gpr[4]._u32[0] == 0) { ctx->pc = 0x6070; SPU_TAILCALL(spu_job_01485F00_spu_func_00006070(ctx)); }
        ctx->gpr[37] = spu_sfi(ctx->gpr[4], 0);
        ctx->gpr[35] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + 0x0);
        ctx->gpr[36] = spu_rotqmby(ctx->gpr[22], ctx->gpr[37]);
        ctx->gpr[34] = spu_and(ctx->gpr[35], ctx->gpr[36]);
        spu_ls_write128(ctx, ctx->gpr[5]._u32[0] + 0x0, ctx->gpr[34]);
        { ctx->pc = 0x6070; SPU_TAILCALL(spu_job_01485F00_spu_func_00006070(ctx)); }
        ctx->gpr[8] = spu_ila(0x5C0);
        ctx->gpr[79] = spu_link(0x14864C0); spu_host_call_push(ctx, 0x14864C0); spu_job_01485F00_spu_func_000064C0(ctx); spu_host_call_pop(ctx);
        { ctx->pc = 0x14864C0; SPU_TAILCALL(spu_job_01485F00_spu_func_014864C0(ctx)); }
}

void spu_job_01485F00_spu_func_014864C0(spu_context* ctx) {
        ctx->gpr[11] = spu_ori(ctx->gpr[3], 0);
        ctx->gpr[3] = spu_fsmbi(0x0);
        ctx->gpr[79] = spu_sf(ctx->gpr[8], ctx->gpr[79]);
        ctx->gpr[2] = spu_fceq(ctx->gpr[7], ctx->gpr[3]);
        if (ctx->gpr[2]._u32[0] != 0) { ctx->pc = 0x65A0; SPU_TAILCALL(spu_job_01485F00_spu_func_000065A0(ctx)); }
        ctx->gpr[23] = spu_ilhu(0x3F80);
        ctx->gpr[22] = spu_fceq(ctx->gpr[7], ctx->gpr[23]);
        if (ctx->gpr[22]._u32[0] == 0) { ctx->pc = 0x6560; SPU_TAILCALL(spu_job_01485F00_spu_func_00006560(ctx)); }
        ctx->gpr[32] = spu_ceq(ctx->gpr[11], ctx->gpr[5]);
        ctx->gpr[31] = spu_ceq(ctx->gpr[4], ctx->gpr[6]);
        ctx->gpr[30] = spu_nor(ctx->gpr[32], ctx->gpr[32]);
        ctx->gpr[29] = spu_nor(ctx->gpr[31], ctx->gpr[31]);
        ctx->gpr[27] = spu_sfi(ctx->gpr[30], 0);
        ctx->gpr[28] = spu_sfi(ctx->gpr[29], 0);
        ctx->gpr[26] = spu_or(ctx->gpr[27], ctx->gpr[28]);
        ctx->gpr[25] = spu_ceqbi(ctx->gpr[26], 0);
        ctx->gpr[24] = spu_xsbh(ctx->gpr[25]);
        if (ctx->gpr[24]._u16[1] != 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
}

/* Indirect-dispatch stubs for cross-function targets the
 * function detector did not seed (typically conditional
 * branches that escape a function's range). */
void spu_job_01485F00_spu_func_00005F18(spu_context* ctx) {
    ctx->pc = 0x5F18u; spu_indirect_branch(ctx);
}
void spu_job_01485F00_spu_func_00005F30(spu_context* ctx) {
    ctx->pc = 0x5F30u; spu_indirect_branch(ctx);
}
void spu_job_01485F00_spu_func_00006028(spu_context* ctx) {
    ctx->pc = 0x6028u; spu_indirect_branch(ctx);
}
void spu_job_01485F00_spu_func_00006060(spu_context* ctx) {
    ctx->pc = 0x6060u; spu_indirect_branch(ctx);
}
void spu_job_01485F00_spu_func_00006070(spu_context* ctx) {
    ctx->pc = 0x6070u; spu_indirect_branch(ctx);
}
void spu_job_01485F00_spu_func_00006090(spu_context* ctx) {
    ctx->pc = 0x6090u; spu_indirect_branch(ctx);
}
void spu_job_01485F00_spu_func_000060A0(spu_context* ctx) {
    ctx->pc = 0x60A0u; spu_indirect_branch(ctx);
}
void spu_job_01485F00_spu_func_00006124(spu_context* ctx) {
    ctx->pc = 0x6124u; spu_indirect_branch(ctx);
}
void spu_job_01485F00_spu_func_00006138(spu_context* ctx) {
    ctx->pc = 0x6138u; spu_indirect_branch(ctx);
}
void spu_job_01485F00_spu_func_00006148(spu_context* ctx) {
    ctx->pc = 0x6148u; spu_indirect_branch(ctx);
}
void spu_job_01485F00_spu_func_000061F8(spu_context* ctx) {
    ctx->pc = 0x61F8u; spu_indirect_branch(ctx);
}
void spu_job_01485F00_spu_func_00006230(spu_context* ctx) {
    ctx->pc = 0x6230u; spu_indirect_branch(ctx);
}
void spu_job_01485F00_spu_func_000062D8(spu_context* ctx) {
    ctx->pc = 0x62D8u; spu_indirect_branch(ctx);
}
void spu_job_01485F00_spu_func_00006308(spu_context* ctx) {
    ctx->pc = 0x6308u; spu_indirect_branch(ctx);
}
void spu_job_01485F00_spu_func_00006348(spu_context* ctx) {
    ctx->pc = 0x6348u; spu_indirect_branch(ctx);
}
void spu_job_01485F00_spu_func_00006388(spu_context* ctx) {
    ctx->pc = 0x6388u; spu_indirect_branch(ctx);
}
void spu_job_01485F00_spu_func_000063A8(spu_context* ctx) {
    ctx->pc = 0x63A8u; spu_indirect_branch(ctx);
}
void spu_job_01485F00_spu_func_000063BC(spu_context* ctx) {
    ctx->pc = 0x63BCu; spu_indirect_branch(ctx);
}
void spu_job_01485F00_spu_func_000063D8(spu_context* ctx) {
    ctx->pc = 0x63D8u; spu_indirect_branch(ctx);
}
void spu_job_01485F00_spu_func_00006418(spu_context* ctx) {
    ctx->pc = 0x6418u; spu_indirect_branch(ctx);
}
void spu_job_01485F00_spu_func_00006438(spu_context* ctx) {
    ctx->pc = 0x6438u; spu_indirect_branch(ctx);
}
void spu_job_01485F00_spu_func_0000644C(spu_context* ctx) {
    ctx->pc = 0x644Cu; spu_indirect_branch(ctx);
}
void spu_job_01485F00_spu_func_00006468(spu_context* ctx) {
    ctx->pc = 0x6468u; spu_indirect_branch(ctx);
}
void spu_job_01485F00_spu_func_00006488(spu_context* ctx) {
    ctx->pc = 0x6488u; spu_indirect_branch(ctx);
}
void spu_job_01485F00_spu_func_0000649C(spu_context* ctx) {
    ctx->pc = 0x649Cu; spu_indirect_branch(ctx);
}
void spu_job_01485F00_spu_func_000064C0(spu_context* ctx) {
    ctx->pc = 0x64C0u; spu_indirect_branch(ctx);
}
void spu_job_01485F00_spu_func_00006560(spu_context* ctx) {
    ctx->pc = 0x6560u; spu_indirect_branch(ctx);
}
void spu_job_01485F00_spu_func_000065A0(spu_context* ctx) {
    ctx->pc = 0x65A0u; spu_indirect_branch(ctx);
}
void spu_job_01485F00_spu_func_0000B038(spu_context* ctx) {
    ctx->pc = 0xB038u; spu_indirect_branch(ctx);
}

/* Function table */
typedef struct { uint32_t addr; void (*func)(spu_context*); const char* name; } spu_func_entry;
static const spu_func_entry spu_function_table[] = {
    { 0x01485F00u, spu_job_01485F00_spu_func_01485F00, "spu_job_01485F00_spu_func_01485F00" },
    { 0x01485F18u, spu_job_01485F00_spu_func_01485F18, "spu_job_01485F00_spu_func_01485F18" },
    { 0x01485F30u, spu_job_01485F00_spu_func_01485F30, "spu_job_01485F00_spu_func_01485F30" },
    { 0x01486028u, spu_job_01485F00_spu_func_01486028, "spu_job_01485F00_spu_func_01486028" },
    { 0x01486060u, spu_job_01485F00_spu_func_01486060, "spu_job_01485F00_spu_func_01486060" },
    { 0x01486070u, spu_job_01485F00_spu_func_01486070, "spu_job_01485F00_spu_func_01486070" },
    { 0x01486090u, spu_job_01485F00_spu_func_01486090, "spu_job_01485F00_spu_func_01486090" },
    { 0x014860A0u, spu_job_01485F00_spu_func_014860A0, "spu_job_01485F00_spu_func_014860A0" },
    { 0x01486124u, spu_job_01485F00_spu_func_01486124, "spu_job_01485F00_spu_func_01486124" },
    { 0x01486138u, spu_job_01485F00_spu_func_01486138, "spu_job_01485F00_spu_func_01486138" },
    { 0x01486148u, spu_job_01485F00_spu_func_01486148, "spu_job_01485F00_spu_func_01486148" },
    { 0x014861F8u, spu_job_01485F00_spu_func_014861F8, "spu_job_01485F00_spu_func_014861F8" },
    { 0x01486230u, spu_job_01485F00_spu_func_01486230, "spu_job_01485F00_spu_func_01486230" },
    { 0x014862D8u, spu_job_01485F00_spu_func_014862D8, "spu_job_01485F00_spu_func_014862D8" },
    { 0x01486308u, spu_job_01485F00_spu_func_01486308, "spu_job_01485F00_spu_func_01486308" },
    { 0x01486348u, spu_job_01485F00_spu_func_01486348, "spu_job_01485F00_spu_func_01486348" },
    { 0x01486388u, spu_job_01485F00_spu_func_01486388, "spu_job_01485F00_spu_func_01486388" },
    { 0x014863A8u, spu_job_01485F00_spu_func_014863A8, "spu_job_01485F00_spu_func_014863A8" },
    { 0x014863BCu, spu_job_01485F00_spu_func_014863BC, "spu_job_01485F00_spu_func_014863BC" },
    { 0x014863D8u, spu_job_01485F00_spu_func_014863D8, "spu_job_01485F00_spu_func_014863D8" },
    { 0x01486418u, spu_job_01485F00_spu_func_01486418, "spu_job_01485F00_spu_func_01486418" },
    { 0x01486438u, spu_job_01485F00_spu_func_01486438, "spu_job_01485F00_spu_func_01486438" },
    { 0x0148644Cu, spu_job_01485F00_spu_func_0148644C, "spu_job_01485F00_spu_func_0148644C" },
    { 0x01486468u, spu_job_01485F00_spu_func_01486468, "spu_job_01485F00_spu_func_01486468" },
    { 0x01486488u, spu_job_01485F00_spu_func_01486488, "spu_job_01485F00_spu_func_01486488" },
    { 0x0148649Cu, spu_job_01485F00_spu_func_0148649C, "spu_job_01485F00_spu_func_0148649C" },
    { 0x014864C0u, spu_job_01485F00_spu_func_014864C0, "spu_job_01485F00_spu_func_014864C0" },
    { 0, NULL, NULL }
};

void spu_job_01485F00_spu_recomp_register(void) {
    for (const spu_func_entry* e = spu_function_table; e->func; ++e)
        spu_register_function(e->addr, e->func);
}
