/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#pragma once
#include "../../runtime/spu/spu_context.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Cross-function branch/loop = a guest tail-jump to another lifted function's
 * entry. It MUST reuse the current host frame, not nest one: SPURS task loops
 * iterate via these, so nesting overflows the host stack and silently kills the
 * process. clang's musttail guarantees the tail call (a jump); without it (or on
 * a non-clang compiler) we fall back to call+return, which only stays bounded if
 * the compiler happens to do sibling-call optimization. All lifted SPU functions
 * share the signature `void f(spu_context*)`, so the tail call is always valid. */
#if defined(__clang__)
#  define SPU_TAILCALL(call) __attribute__((musttail)) return call
#else
#  define SPU_TAILCALL(call) do { call; return; } while (0)
#endif

/* Indirect branch dispatch (bi/bisl/bid...): PC has been set to the target
 * local-store address; the runtime resolves it to the matching lifted
 * function and continues execution. Implemented by the SPU program glue. */
void spu_indirect_branch(spu_context* ctx);

/* stop/stopd hook (YDKJ): the runtime inspects the stop code, may deliver a
 * stop-and-signal event to the PPU (SPURS bring-up handshake), and longjmps the
 * host SPU thread back to spu_run_with_halt so the job does not spin past the
 * stop. Complements ctx->status; harmless where the runtime handles status. */
void spu_stop(spu_context* ctx);
/* Lower-level longjmp helper: abort the host SPU thread back to spu_run_with_halt
 * (used for the infinite no-op self-loop / idle halt idiom). */
void spu_halt(spu_context* ctx);

/* Channel access -- implemented by the runtime (MFC DMA engine, mailboxes,
 * signal notification, decrementer). See runtime/spu/spu_dma.h. */
u128 spu_rdch(spu_context* ctx, uint32_t channel);
uint32_t spu_rchcnt(spu_context* ctx, uint32_t channel);
void spu_wrch(spu_context* ctx, uint32_t channel, u128 value);

/* Execution trace (only emitted when the lifter was invoked with --trace). */
void spu_trace_init(const char* path);
void spu_trace_pc(spu_context* ctx, uint32_t pc);
void spu_trace_rt(spu_context* ctx, uint32_t rt);

#ifdef __cplusplus
}
#endif


void spu_job_01485F00_spu_func_01485F00(spu_context* ctx);
void spu_job_01485F00_spu_func_01485F18(spu_context* ctx);
void spu_job_01485F00_spu_func_01485F30(spu_context* ctx);
void spu_job_01485F00_spu_func_01486028(spu_context* ctx);
void spu_job_01485F00_spu_func_01486060(spu_context* ctx);
void spu_job_01485F00_spu_func_01486070(spu_context* ctx);
void spu_job_01485F00_spu_func_01486090(spu_context* ctx);
void spu_job_01485F00_spu_func_014860A0(spu_context* ctx);
void spu_job_01485F00_spu_func_01486124(spu_context* ctx);
void spu_job_01485F00_spu_func_01486138(spu_context* ctx);
void spu_job_01485F00_spu_func_01486148(spu_context* ctx);
void spu_job_01485F00_spu_func_014861F8(spu_context* ctx);
void spu_job_01485F00_spu_func_01486230(spu_context* ctx);
void spu_job_01485F00_spu_func_014862D8(spu_context* ctx);
void spu_job_01485F00_spu_func_01486308(spu_context* ctx);
void spu_job_01485F00_spu_func_01486348(spu_context* ctx);
void spu_job_01485F00_spu_func_01486388(spu_context* ctx);
void spu_job_01485F00_spu_func_014863A8(spu_context* ctx);
void spu_job_01485F00_spu_func_014863BC(spu_context* ctx);
void spu_job_01485F00_spu_func_014863D8(spu_context* ctx);
void spu_job_01485F00_spu_func_01486418(spu_context* ctx);
void spu_job_01485F00_spu_func_01486438(spu_context* ctx);
void spu_job_01485F00_spu_func_0148644C(spu_context* ctx);
void spu_job_01485F00_spu_func_01486468(spu_context* ctx);
void spu_job_01485F00_spu_func_01486488(spu_context* ctx);
void spu_job_01485F00_spu_func_0148649C(spu_context* ctx);
void spu_job_01485F00_spu_func_014864C0(spu_context* ctx);
void spu_job_01485F00_spu_func_00005F18(spu_context* ctx); /* external */
void spu_job_01485F00_spu_func_00005F30(spu_context* ctx); /* external */
void spu_job_01485F00_spu_func_00006028(spu_context* ctx); /* external */
void spu_job_01485F00_spu_func_00006060(spu_context* ctx); /* external */
void spu_job_01485F00_spu_func_00006070(spu_context* ctx); /* external */
void spu_job_01485F00_spu_func_00006090(spu_context* ctx); /* external */
void spu_job_01485F00_spu_func_000060A0(spu_context* ctx); /* external */
void spu_job_01485F00_spu_func_00006124(spu_context* ctx); /* external */
void spu_job_01485F00_spu_func_00006138(spu_context* ctx); /* external */
void spu_job_01485F00_spu_func_00006148(spu_context* ctx); /* external */
void spu_job_01485F00_spu_func_000061F8(spu_context* ctx); /* external */
void spu_job_01485F00_spu_func_00006230(spu_context* ctx); /* external */
void spu_job_01485F00_spu_func_000062D8(spu_context* ctx); /* external */
void spu_job_01485F00_spu_func_00006308(spu_context* ctx); /* external */
void spu_job_01485F00_spu_func_00006348(spu_context* ctx); /* external */
void spu_job_01485F00_spu_func_00006388(spu_context* ctx); /* external */
void spu_job_01485F00_spu_func_000063A8(spu_context* ctx); /* external */
void spu_job_01485F00_spu_func_000063BC(spu_context* ctx); /* external */
void spu_job_01485F00_spu_func_000063D8(spu_context* ctx); /* external */
void spu_job_01485F00_spu_func_00006418(spu_context* ctx); /* external */
void spu_job_01485F00_spu_func_00006438(spu_context* ctx); /* external */
void spu_job_01485F00_spu_func_0000644C(spu_context* ctx); /* external */
void spu_job_01485F00_spu_func_00006468(spu_context* ctx); /* external */
void spu_job_01485F00_spu_func_00006488(spu_context* ctx); /* external */
void spu_job_01485F00_spu_func_0000649C(spu_context* ctx); /* external */
void spu_job_01485F00_spu_func_000064C0(spu_context* ctx); /* external */
void spu_job_01485F00_spu_func_00006560(spu_context* ctx); /* external */
void spu_job_01485F00_spu_func_000065A0(spu_context* ctx); /* external */
void spu_job_01485F00_spu_func_0000B038(spu_context* ctx); /* external */

/* Runtime glue (runtime/spu/spu_channels.c) */
void spu_register_function(uint32_t addr, void (*fn)(spu_context*));
/* Call once at init to register this image's functions for
 * indirect-branch dispatch (spu_indirect_branch). */
void spu_job_01485F00_spu_recomp_register(void);
