/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#pragma once
#include "../../runtime/spu/spu_context.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Cross-function branch/loop = a guest tail-jump to another lifted function's
 * entry. It MUST reuse the current host frame, not nest one: SPURS task loops
 * iterate via these, so nesting overflows the host stack and silently kills the
 * process. clang's musttail guarantees the tail call (a jump); without it (or on
 * a non-clang compiler) we fall back to call+return, which only stays bounded if
 * the compiler happens to do sibling-call optimization. All lifted SPU functions
 * share the signature `void f(spu_context*)`, so the tail call is always valid. */
#if defined(__clang__)
#  define SPU_TAILCALL(call) __attribute__((musttail)) return call
#else
#  define SPU_TAILCALL(call) do { call; return; } while (0)
#endif

/* Indirect branch dispatch (bi/bisl/bid...): PC has been set to the target
 * local-store address; the runtime resolves it to the matching lifted
 * function and continues execution. Implemented by the SPU program glue. */
void spu_indirect_branch(spu_context* ctx);

/* stop/stopd hook (YDKJ): the runtime inspects the stop code, may deliver a
 * stop-and-signal event to the PPU (SPURS bring-up handshake), and longjmps the
 * host SPU thread back to spu_run_with_halt so the job does not spin past the
 * stop. Complements ctx->status; harmless where the runtime handles status. */
void spu_stop(spu_context* ctx);
/* Lower-level longjmp helper: abort the host SPU thread back to spu_run_with_halt
 * (used for the infinite no-op self-loop / idle halt idiom). */
void spu_halt(spu_context* ctx);

/* Channel access -- implemented by the runtime (MFC DMA engine, mailboxes,
 * signal notification, decrementer). See runtime/spu/spu_dma.h. */
u128 spu_rdch(spu_context* ctx, uint32_t channel);
uint32_t spu_rchcnt(spu_context* ctx, uint32_t channel);
void spu_wrch(spu_context* ctx, uint32_t channel, u128 value);

/* Execution trace (only emitted when the lifter was invoked with --trace). */
void spu_trace_init(const char* path);
void spu_trace_pc(spu_context* ctx, uint32_t pc);
void spu_trace_rt(spu_context* ctx, uint32_t rt);

#ifdef __cplusplus
}
#endif


void spu_job_01478A80_spu_func_01478A80(spu_context* ctx);
void spu_job_01478A80_spu_func_01478A98(spu_context* ctx);
void spu_job_01478A80_spu_func_01478AB0(spu_context* ctx);
void spu_job_01478A80_spu_func_01478AC8(spu_context* ctx);
void spu_job_01478A80_spu_func_01478AD8(spu_context* ctx);
void spu_job_01478A80_spu_func_01478C18(spu_context* ctx);
void spu_job_01478A80_spu_func_01478C70(spu_context* ctx);
void spu_job_01478A80_spu_func_01478C90(spu_context* ctx);
void spu_job_01478A80_spu_func_01478C94(spu_context* ctx);
void spu_job_01478A80_spu_func_01478CE8(spu_context* ctx);
void spu_job_01478A80_spu_func_01478D0C(spu_context* ctx);
void spu_job_01478A80_spu_func_01478D40(spu_context* ctx);
void spu_job_01478A80_spu_func_01478D60(spu_context* ctx);
void spu_job_01478A80_spu_func_01478D68(spu_context* ctx);
void spu_job_01478A80_spu_func_01478D84(spu_context* ctx);
void spu_job_01478A80_spu_func_01478DAC(spu_context* ctx);
void spu_job_01478A80_spu_func_01478DCC(spu_context* ctx);
void spu_job_01478A80_spu_func_01478DD8(spu_context* ctx);
void spu_job_01478A80_spu_func_01478E80(spu_context* ctx);
void spu_job_01478A80_spu_func_01478EA8(spu_context* ctx);
void spu_job_01478A80_spu_func_01478EDC(spu_context* ctx);
void spu_job_01478A80_spu_func_01478EE8(spu_context* ctx);
void spu_job_01478A80_spu_func_01478F18(spu_context* ctx);
void spu_job_01478A80_spu_func_01478FD0(spu_context* ctx);
void spu_job_01478A80_spu_func_01478FF8(spu_context* ctx);
void spu_job_01478A80_spu_func_01479028(spu_context* ctx);
void spu_job_01478A80_spu_func_014790D0(spu_context* ctx);
void spu_job_01478A80_spu_func_014790F8(spu_context* ctx);
void spu_job_01478A80_spu_func_0147912C(spu_context* ctx);
void spu_job_01478A80_spu_func_01479154(spu_context* ctx);
void spu_job_01478A80_spu_func_0147917C(spu_context* ctx);
void spu_job_01478A80_spu_func_014791A8(spu_context* ctx);
void spu_job_01478A80_spu_func_01479248(spu_context* ctx);
void spu_job_01478A80_spu_func_01479270(spu_context* ctx);
void spu_job_01478A80_spu_func_014792A8(spu_context* ctx);
void spu_job_01478A80_spu_func_014792E4(spu_context* ctx);
void spu_job_01478A80_spu_func_00038A98(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00038AB0(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00038AC8(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00038AD8(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00038C18(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00038C70(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00038C90(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00038C94(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00038CE8(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00038D0C(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00038D40(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00038D60(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00038D68(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00038D84(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00038DAC(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00038DCC(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00038DD8(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00038E80(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00038EA8(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00038EDC(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00038EE8(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00038F18(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00038FD0(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00038FF8(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039028(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_000390D0(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_000390F8(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003912C(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039154(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003917C(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_000391A8(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039248(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039270(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_000392A8(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_000392E4(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039318(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039340(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039354(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039380(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039430(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039458(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039488(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039490(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039504(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039530(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039554(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039570(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039590(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_000395B8(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039668(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039690(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_000396C0(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039700(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039714(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003973C(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039768(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039890(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_000398A8(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039940(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003998C(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_000399EC(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_000399F4(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039A30(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039A38(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039A78(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039AA0(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039AE0(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039B2C(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039B8C(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039B94(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039BD0(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039C28(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039CC4(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039CC8(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039D38(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039D50(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039D84(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039D90(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039DD4(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039E00(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039E40(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039E8C(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039EEC(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039EF4(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039F2C(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039F40(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039F58(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_00039FB0(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A030(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A0A0(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A0EC(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A150(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A188(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A1C0(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A210(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A25C(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A2BC(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A2D0(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A2D4(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A310(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A348(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A364(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A394(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A398(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A408(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A470(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A4BC(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A51C(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A530(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A560(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A570(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A680(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A6B8(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A718(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A764(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A7C4(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A7C8(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A830(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A87C(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A8DC(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A8E0(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A920(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A930(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A988(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A9A8(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A9DC(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003A9F0(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003AA5C(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003AA70(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003AA88(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003ACB8(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003AE10(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003B340(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003B358(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003B4F8(spu_context* ctx); /* external */
void spu_job_01478A80_spu_func_0003C168(spu_context* ctx); /* external */

/* Runtime glue (runtime/spu/spu_channels.c) */
void spu_register_function(uint32_t addr, void (*fn)(spu_context*));
/* Call once at init to register this image's functions for
 * indirect-branch dispatch (spu_indirect_branch). */
void spu_job_01478A80_spu_recomp_register(void);
