/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#include "spu_recomp.h"
#include "../../runtime/spu/spu_helpers.h"


void spu_job_01462A80_spu_func_01462A80(spu_context* ctx) {
        ctx->gpr[2] = spu_ila(0xB70C);
        ctx->gpr[2] = spu_ila(0x32F5);
        ctx->gpr[2] = spu_ila(0xCD8A);
        ctx->gpr[2] = spu_ila(0x7CEF);
        ctx->gpr[80] = spu_xori(ctx->gpr[80], 4);
        { ctx->pc = 0x22A98; SPU_TAILCALL(spu_job_01462A80_spu_func_00022A98(ctx)); }
}

void spu_job_01462A80_spu_func_01462A98(spu_context* ctx) {
        ctx->gpr[80] = spu_xori(ctx->gpr[80], 4);
        { ctx->pc = 0x22AB0; SPU_TAILCALL(spu_job_01462A80_spu_func_00022AB0(ctx)); }
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
}

void spu_job_01462A80_spu_func_01462AB0(spu_context* ctx) {
        ctx->gpr[2] = spu_ori(ctx->gpr[3], 0);
        ctx->gpr[3] = spu_ai(ctx->gpr[4], 48);
        ctx->gpr[4] = spu_ls_read128(ctx, ctx->gpr[2]._u32[0] + 0x20);
        ctx->gpr[4] = spu_rotqby(ctx->gpr[4], ctx->gpr[2]);
        { ctx->pc = 0x25AA0; SPU_TAILCALL(spu_job_01462A80_spu_func_00025AA0(ctx)); }
        /* nop */;
        /* branch hint (ignored) */;
        ctx->gpr[5] = spu_ila(0x83D8);
        ctx->gpr[4] = spu_il(1);
        /* nop */;
        /* nop */;
        ctx->gpr[7] = spu_ls_read128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[5]._u32[0]);
        /* nop */;
        ctx->gpr[6] = spu_cwx(ctx->gpr[1], ctx->gpr[5]);
        ctx->gpr[2] = spu_shufb(ctx->gpr[4], ctx->gpr[7], ctx->gpr[6]);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[5]._u32[0], ctx->gpr[2]);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        /* nop */;
        ctx->gpr[14] = spu_shli(ctx->gpr[6], 2);
        /* branch hint (ignored) */;
        ctx->gpr[8] = spu_il(276);
        ctx->gpr[5] = spu_ila(0x83D8);
        ctx->gpr[2] = spu_il(1);
        ctx->gpr[10] = spu_a(ctx->gpr[14], ctx->gpr[3]);
        ctx->gpr[9] = spu_cwx(ctx->gpr[1], ctx->gpr[5]);
        ctx->gpr[12] = spu_ls_read128(ctx, ctx->gpr[10]._u32[0] + ctx->gpr[8]._u32[0]);
        ctx->gpr[13] = spu_cwd(ctx->gpr[10], 4);
        ctx->gpr[11] = spu_shufb(ctx->gpr[7], ctx->gpr[12], ctx->gpr[13]);
        spu_ls_write128(ctx, ctx->gpr[10]._u32[0] + ctx->gpr[8]._u32[0], ctx->gpr[11]);
        ctx->gpr[6] = spu_ls_read128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[5]._u32[0]);
        ctx->gpr[4] = spu_shufb(ctx->gpr[2], ctx->gpr[6], ctx->gpr[9]);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[5]._u32[0], ctx->gpr[4]);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        /* nop */;
        ctx->gpr[5] = spu_shli(ctx->gpr[6], 2);
        /* branch hint (ignored) */;
        ctx->gpr[4] = spu_ori(ctx->gpr[3], 0);
        ctx->gpr[10] = spu_ila(0x83D8);
        ctx->gpr[12] = spu_il(1);
        ctx->gpr[8] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + ctx->gpr[3]._u32[0]);
        ctx->gpr[9] = spu_cwx(ctx->gpr[5], ctx->gpr[3]);
        ctx->gpr[13] = spu_cwx(ctx->gpr[1], ctx->gpr[10]);
        ctx->gpr[3] = spu_rotqby(ctx->gpr[8], ctx->gpr[5]);
        ctx->gpr[2] = spu_ceq(ctx->gpr[3], ctx->gpr[7]);
        /* nop */;
        if (ctx->gpr[2]._u32[0] != 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        ctx->gpr[8] = spu_ila(0x83DC);
        ctx->gpr[15] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + ctx->gpr[4]._u32[0]);
        ctx->gpr[11] = spu_cwx(ctx->gpr[1], ctx->gpr[8]);
        ctx->gpr[14] = spu_shufb(ctx->gpr[7], ctx->gpr[15], ctx->gpr[9]);
        spu_ls_write128(ctx, ctx->gpr[5]._u32[0] + ctx->gpr[4]._u32[0], ctx->gpr[14]);
        ctx->gpr[7] = spu_ls_read128(ctx, ctx->gpr[4]._u32[0] + ctx->gpr[10]._u32[0]);
        ctx->gpr[5] = spu_shufb(ctx->gpr[12], ctx->gpr[7], ctx->gpr[13]);
        spu_ls_write128(ctx, ctx->gpr[4]._u32[0] + ctx->gpr[10]._u32[0], ctx->gpr[5]);
        if (ctx->gpr[6]._u32[0] != 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        ctx->gpr[9] = spu_ls_read128(ctx, ctx->gpr[4]._u32[0] + ctx->gpr[8]._u32[0]);
        ctx->gpr[6] = spu_shufb(ctx->gpr[12], ctx->gpr[9], ctx->gpr[11]);
        spu_ls_write128(ctx, ctx->gpr[4]._u32[0] + ctx->gpr[8]._u32[0], ctx->gpr[6]);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        /* nop */;
        ctx->gpr[6] = spu_shli(ctx->gpr[6], 2);
        /* branch hint (ignored) */;
        ctx->gpr[5] = spu_il(20);
        ctx->gpr[4] = spu_shlqbyi(ctx->gpr[3], 0);
        ctx->gpr[9] = spu_ila(0x83D8);
        ctx->gpr[6] = spu_a(ctx->gpr[6], ctx->gpr[3]);
        /* nop */;
        ctx->gpr[10] = spu_cwx(ctx->gpr[1], ctx->gpr[9]);
        ctx->gpr[3] = spu_ai(ctx->gpr[6], 20);
        ctx->gpr[12] = spu_ls_read128(ctx, ctx->gpr[6]._u32[0] + ctx->gpr[5]._u32[0]);
        ctx->gpr[8] = spu_cwd(ctx->gpr[6], 4);
        ctx->gpr[11] = spu_rotqby(ctx->gpr[12], ctx->gpr[3]);
        ctx->gpr[2] = spu_ceq(ctx->gpr[11], ctx->gpr[7]);
        if (ctx->gpr[2]._u32[0] != 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        ctx->gpr[14] = spu_ls_read128(ctx, ctx->gpr[6]._u32[0] + ctx->gpr[5]._u32[0]);
        ctx->gpr[13] = spu_shufb(ctx->gpr[7], ctx->gpr[14], ctx->gpr[8]);
        ctx->gpr[8] = spu_il(1);
        spu_ls_write128(ctx, ctx->gpr[6]._u32[0] + ctx->gpr[5]._u32[0], ctx->gpr[13]);
        ctx->gpr[7] = spu_ls_read128(ctx, ctx->gpr[4]._u32[0] + ctx->gpr[9]._u32[0]);
        ctx->gpr[5] = spu_shufb(ctx->gpr[8], ctx->gpr[7], ctx->gpr[10]);
        spu_ls_write128(ctx, ctx->gpr[4]._u32[0] + ctx->gpr[9]._u32[0], ctx->gpr[5]);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        ctx->gpr[8] = spu_ila(0x180);
        ctx->gpr[79] = spu_link(0x1462C00); spu_host_call_push(ctx, 0x1462C00); spu_job_01462A80_spu_func_00022C00(ctx); spu_host_call_pop(ctx);
        { ctx->pc = 0x1462C00; SPU_TAILCALL(spu_job_01462A80_spu_func_01462C00(ctx)); }
}

void spu_job_01462A80_spu_func_01462C00(spu_context* ctx) {
        ctx->gpr[11] = spu_ori(ctx->gpr[3], 0);
        ctx->gpr[3] = spu_fsmbi(0x0);
        ctx->gpr[79] = spu_sf(ctx->gpr[8], ctx->gpr[79]);
        ctx->gpr[2] = spu_fceq(ctx->gpr[7], ctx->gpr[3]);
        if (ctx->gpr[2]._u32[0] != 0) { ctx->pc = 0x22CE0; SPU_TAILCALL(spu_job_01462A80_spu_func_00022CE0(ctx)); }
        ctx->gpr[23] = spu_ilhu(0x3F80);
        ctx->gpr[22] = spu_fceq(ctx->gpr[7], ctx->gpr[23]);
        if (ctx->gpr[22]._u32[0] == 0) { ctx->pc = 0x22CA0; SPU_TAILCALL(spu_job_01462A80_spu_func_00022CA0(ctx)); }
        ctx->gpr[32] = spu_ceq(ctx->gpr[11], ctx->gpr[5]);
        ctx->gpr[31] = spu_ceq(ctx->gpr[4], ctx->gpr[6]);
        ctx->gpr[30] = spu_nor(ctx->gpr[32], ctx->gpr[32]);
        ctx->gpr[29] = spu_nor(ctx->gpr[31], ctx->gpr[31]);
        ctx->gpr[27] = spu_sfi(ctx->gpr[30], 0);
        ctx->gpr[28] = spu_sfi(ctx->gpr[29], 0);
        ctx->gpr[26] = spu_or(ctx->gpr[27], ctx->gpr[28]);
        ctx->gpr[25] = spu_ceqbi(ctx->gpr[26], 0);
        ctx->gpr[24] = spu_xsbh(ctx->gpr[25]);
        if (ctx->gpr[24]._u16[1] != 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        ctx->gpr[34] = spu_shli(ctx->gpr[4], 10);
        /* branch hint (ignored) */;
        ctx->gpr[4] = spu_shli(ctx->gpr[6], 10);
        ctx->gpr[13] = spu_a(ctx->gpr[11], ctx->gpr[34]);
        ctx->gpr[12] = spu_a(ctx->gpr[5], ctx->gpr[4]);
        ctx->gpr[14] = spu_andi(ctx->gpr[13], 15);
        ctx->gpr[7] = spu_andi(ctx->gpr[12], 15);
        ctx->gpr[33] = spu_or(ctx->gpr[7], ctx->gpr[14]);
        if (ctx->gpr[33]._u32[0] != 0) { ctx->pc = 0x22D28; SPU_TAILCALL(spu_job_01462A80_spu_func_00022D28(ctx)); }
        ctx->gpr[3] = spu_il(0);
        ctx->gpr[4] = spu_il(1024);
        { ctx->pc = 0x1462C74; SPU_TAILCALL(spu_job_01462A80_spu_func_01462C74(ctx)); }
}

void spu_job_01462A80_spu_func_01462C74(spu_context* ctx) {
        ctx->gpr[36] = spu_ls_read128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[12]._u32[0]);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[13]._u32[0], ctx->gpr[36]);
        ctx->gpr[3] = spu_ai(ctx->gpr[3], 16);
        ctx->gpr[35] = spu_ceq(ctx->gpr[3], ctx->gpr[4]);
        if (ctx->gpr[35]._u32[0] != 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        ctx->gpr[36] = spu_ls_read128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[12]._u32[0]);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[13]._u32[0], ctx->gpr[36]);
        ctx->gpr[3] = spu_ai(ctx->gpr[3], 16);
        ctx->gpr[35] = spu_ceq(ctx->gpr[3], ctx->gpr[4]);
        if (ctx->gpr[35]._u32[0] == 0) { ctx->pc = 0x22C74; SPU_TAILCALL(spu_job_01462A80_spu_func_00022C74(ctx)); }
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
}

void spu_job_01462A80_spu_func_01462CA0(spu_context* ctx) {
        ctx->gpr[9] = spu_shli(ctx->gpr[4], 10);
        /* branch hint (ignored) */;
        ctx->gpr[13] = spu_shli(ctx->gpr[6], 10);
        ctx->gpr[8] = spu_fsmbi(0x0);
        ctx->gpr[10] = spu_ila(0x10203);
        ctx->gpr[3] = spu_il(1024);
        ctx->gpr[11] = spu_a(ctx->gpr[9], ctx->gpr[11]);
        ctx->gpr[7] = spu_shufb(ctx->gpr[7], ctx->gpr[7], ctx->gpr[10]);
        ctx->gpr[4] = spu_a(ctx->gpr[13], ctx->gpr[5]);
        { ctx->pc = 0x1462CC4; SPU_TAILCALL(spu_job_01462A80_spu_func_01462CC4(ctx)); }
}

void spu_job_01462A80_spu_func_01462CC4(spu_context* ctx) {
        ctx->gpr[14] = spu_ls_read128(ctx, ctx->gpr[8]._u32[0] + ctx->gpr[4]._u32[0]);
        ctx->gpr[6] = spu_fm(ctx->gpr[14], ctx->gpr[7]);
        spu_ls_write128(ctx, ctx->gpr[8]._u32[0] + ctx->gpr[11]._u32[0], ctx->gpr[6]);
        ctx->gpr[8] = spu_ai(ctx->gpr[8], 16);
        ctx->gpr[5] = spu_ceq(ctx->gpr[8], ctx->gpr[3]);
        if (ctx->gpr[5]._u32[0] == 0) { ctx->pc = 0x22CC4; SPU_TAILCALL(spu_job_01462A80_spu_func_00022CC4(ctx)); }
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
}

void spu_job_01462A80_spu_func_01462CE0(spu_context* ctx) {
        ctx->gpr[7] = spu_shli(ctx->gpr[4], 10);
        /* branch hint (ignored) */;
        ctx->gpr[6] = spu_il(0);
        ctx->gpr[5] = spu_a(ctx->gpr[11], ctx->gpr[7]);
        ctx->gpr[2] = spu_andi(ctx->gpr[5], 15);
        if (ctx->gpr[2]._u32[0] != 0) { ctx->pc = 0x22E30; SPU_TAILCALL(spu_job_01462A80_spu_func_00022E30(ctx)); }
        ctx->gpr[3] = spu_il(0);
        ctx->gpr[4] = spu_il(1024);
        { ctx->pc = 0x1462D00; SPU_TAILCALL(spu_job_01462A80_spu_func_01462D00(ctx)); }
}

void spu_job_01462A80_spu_func_01462D00(spu_context* ctx) {
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[5]._u32[0], ctx->gpr[6]);
        ctx->gpr[3] = spu_ai(ctx->gpr[3], 16);
        ctx->gpr[7] = spu_ceq(ctx->gpr[3], ctx->gpr[4]);
        if (ctx->gpr[7]._u32[0] != 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[5]._u32[0], ctx->gpr[6]);
        ctx->gpr[3] = spu_ai(ctx->gpr[3], 16);
        ctx->gpr[7] = spu_ceq(ctx->gpr[3], ctx->gpr[4]);
        if (ctx->gpr[7]._u32[0] == 0) { ctx->pc = 0x22D00; SPU_TAILCALL(spu_job_01462A80_spu_func_00022D00(ctx)); }
        /* nop */;
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
}

void spu_job_01462A80_spu_func_01462D28(spu_context* ctx) {
        ctx->gpr[57] = spu_sf(ctx->gpr[14], ctx->gpr[7]);
        ctx->gpr[53] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + ctx->gpr[4]._u32[0]);
        ctx->gpr[61] = spu_ila(0x42F0);
        ctx->gpr[54] = spu_ls_read128(ctx, ctx->gpr[12]._u32[0] + 0x10);
        ctx->gpr[60] = spu_shli(ctx->gpr[57], 4);
        ctx->gpr[51] = spu_fsmbi(0xFFFF);
        ctx->gpr[63] = spu_il(1024);
        ctx->gpr[41] = spu_ls_read128(ctx, ctx->gpr[13]._u32[0] + 0x0);
        ctx->gpr[59] = spu_a(ctx->gpr[61], ctx->gpr[79]);
        ctx->gpr[58] = spu_a(ctx->gpr[14], ctx->gpr[63]);
        ctx->gpr[55] = spu_cgti(ctx->gpr[57], 0);
        ctx->gpr[52] = spu_ls_read128(ctx, ctx->gpr[60]._u32[0] + ctx->gpr[59]._u32[0]);
        ctx->gpr[56] = spu_sfi(ctx->gpr[58], 0);
        ctx->gpr[46] = spu_rotqmby(ctx->gpr[53], ctx->gpr[57]);
        ctx->gpr[37] = spu_clgti(ctx->gpr[58], 15);
        /* nop */;
        ctx->gpr[5] = spu_sfi(ctx->gpr[14], 16);
        ctx->gpr[48] = spu_rotqmby(ctx->gpr[51], ctx->gpr[56]);
        ctx->gpr[50] = spu_ceqi(ctx->gpr[55], 0);
        ctx->gpr[49] = spu_ceqi(ctx->gpr[37], 0);
        ctx->gpr[42] = spu_shlqby(ctx->gpr[51], ctx->gpr[5]);
        ctx->gpr[47] = spu_shufb(ctx->gpr[53], ctx->gpr[54], ctx->gpr[52]);
        ctx->gpr[45] = spu_fsm(ctx->gpr[50]);
        ctx->gpr[43] = spu_fsm(ctx->gpr[49]);
        ctx->gpr[44] = spu_or(ctx->gpr[42], ctx->gpr[48]);
        ctx->gpr[39] = spu_selb(ctx->gpr[47], ctx->gpr[46], ctx->gpr[45]);
        ctx->gpr[40] = spu_selb(ctx->gpr[42], ctx->gpr[44], ctx->gpr[43]);
        ctx->gpr[38] = spu_selb(ctx->gpr[39], ctx->gpr[41], ctx->gpr[40]);
        spu_ls_write128(ctx, ctx->gpr[13]._u32[0] + 0x0, ctx->gpr[38]);
        if (ctx->gpr[37]._u32[0] == 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        ctx->gpr[7] = spu_a(ctx->gpr[12], ctx->gpr[5]);
        /* branch hint (ignored) */;
        ctx->gpr[67] = spu_ila(0x42F0);
        ctx->gpr[69] = spu_andi(ctx->gpr[7], 15);
        ctx->gpr[68] = spu_il(1024);
        ctx->gpr[66] = spu_shli(ctx->gpr[69], 4);
        ctx->gpr[65] = spu_a(ctx->gpr[67], ctx->gpr[79]);
        ctx->gpr[8] = spu_sf(ctx->gpr[5], ctx->gpr[68]);
        ctx->gpr[11] = spu_a(ctx->gpr[13], ctx->gpr[5]);
        /* nop */;
        ctx->gpr[64] = spu_clgti(ctx->gpr[8], 15);
        ctx->gpr[9] = spu_ls_read128(ctx, ctx->gpr[66]._u32[0] + ctx->gpr[65]._u32[0]);
        /* nop */;
        if (ctx->gpr[64]._u32[0] == 0) { ctx->pc = 0x22E00; SPU_TAILCALL(spu_job_01462A80_spu_func_00022E00(ctx)); }
        { ctx->pc = 0x1462DD8; SPU_TAILCALL(spu_job_01462A80_spu_func_01462DD8(ctx)); }
}

void spu_job_01462A80_spu_func_01462DD8(spu_context* ctx) {
        ctx->gpr[8] = spu_ai(ctx->gpr[8], -16);
        ctx->gpr[72] = spu_ls_read128(ctx, ctx->gpr[7]._u32[0] + 0x0);
        ctx->gpr[7] = spu_ai(ctx->gpr[7], 16);
        ctx->gpr[70] = spu_clgti(ctx->gpr[8], 15);
        ctx->gpr[73] = spu_ls_read128(ctx, ctx->gpr[7]._u32[0] + 0x0);
        ctx->gpr[71] = spu_shufb(ctx->gpr[72], ctx->gpr[73], ctx->gpr[9]);
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[11]._u32[0] + 0x0, ctx->gpr[71]);
        ctx->gpr[11] = spu_ai(ctx->gpr[11], 16);
        if (ctx->gpr[70]._u32[0] != 0) { ctx->pc = 0x22DD8; SPU_TAILCALL(spu_job_01462A80_spu_func_00022DD8(ctx)); }
        { ctx->pc = 0x1462E00; SPU_TAILCALL(spu_job_01462A80_spu_func_01462E00(ctx)); }
}

void spu_job_01462A80_spu_func_01462E00(spu_context* ctx) {
        /* branch hint (ignored) */;
        if (ctx->gpr[8]._u32[0] == 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        ctx->gpr[79] = spu_sfi(ctx->gpr[8], 0);
        ctx->gpr[3] = spu_ls_read128(ctx, ctx->gpr[7]._u32[0] + 0x10);
        ctx->gpr[2] = spu_il(-1);
        ctx->gpr[78] = spu_ls_read128(ctx, ctx->gpr[7]._u32[0] + 0x0);
        ctx->gpr[77] = spu_ls_read128(ctx, ctx->gpr[11]._u32[0] + 0x0);
        ctx->gpr[76] = spu_rotqmby(ctx->gpr[2], ctx->gpr[79]);
        ctx->gpr[75] = spu_shufb(ctx->gpr[78], ctx->gpr[3], ctx->gpr[9]);
        ctx->gpr[74] = spu_selb(ctx->gpr[75], ctx->gpr[77], ctx->gpr[76]);
        spu_ls_write128(ctx, ctx->gpr[11]._u32[0] + 0x0, ctx->gpr[74]);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
}

void spu_job_01462A80_spu_func_01462E30(spu_context* ctx) {
        ctx->gpr[4] = spu_il(1024);
        /* branch hint (ignored) */;
        ctx->gpr[8] = spu_sfi(ctx->gpr[2], 16);
        ctx->gpr[12] = spu_fsmbi(0xFFFF);
        ctx->gpr[9] = spu_a(ctx->gpr[2], ctx->gpr[4]);
        ctx->gpr[13] = spu_clgti(ctx->gpr[9], 15);
        ctx->gpr[10] = spu_shlqby(ctx->gpr[12], ctx->gpr[8]);
        if (ctx->gpr[13]._u32[0] == 0) { ctx->pc = 0x22EAC; SPU_TAILCALL(spu_job_01462A80_spu_func_00022EAC(ctx)); }
        ctx->gpr[4] = spu_sf(ctx->gpr[8], ctx->gpr[4]);
        ctx->gpr[16] = spu_ls_read128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[7]._u32[0]);
        ctx->gpr[5] = spu_a(ctx->gpr[5], ctx->gpr[8]);
        ctx->gpr[12] = spu_clgti(ctx->gpr[4], 15);
        ctx->gpr[15] = spu_and(ctx->gpr[16], ctx->gpr[10]);
        spu_ls_write128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[7]._u32[0], ctx->gpr[15]);
        /* nop */;
        if (ctx->gpr[12]._u32[0] == 0) { ctx->pc = 0x22E84; SPU_TAILCALL(spu_job_01462A80_spu_func_00022E84(ctx)); }
        { ctx->pc = 0x1462E70; SPU_TAILCALL(spu_job_01462A80_spu_func_01462E70(ctx)); }
}

void spu_job_01462A80_spu_func_01462E70(spu_context* ctx) {
        ctx->gpr[4] = spu_ai(ctx->gpr[4], -16);
        spu_ls_write128(ctx, ctx->gpr[5]._u32[0] + 0x0, ctx->gpr[6]);
        ctx->gpr[5] = spu_ai(ctx->gpr[5], 16);
        ctx->gpr[11] = spu_clgti(ctx->gpr[4], 15);
        if (ctx->gpr[11]._u32[0] != 0) { ctx->pc = 0x22E70; SPU_TAILCALL(spu_job_01462A80_spu_func_00022E70(ctx)); }
        { ctx->pc = 0x1462E84; SPU_TAILCALL(spu_job_01462A80_spu_func_01462E84(ctx)); }
}

void spu_job_01462A80_spu_func_01462E84(spu_context* ctx) {
        /* branch hint (ignored) */;
        /* nop */;
        if (ctx->gpr[4]._u32[0] == 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        ctx->gpr[21] = spu_sfi(ctx->gpr[4], 0);
        ctx->gpr[18] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + 0x0);
        ctx->gpr[20] = spu_il(-1);
        ctx->gpr[19] = spu_rotqmby(ctx->gpr[20], ctx->gpr[21]);
        ctx->gpr[17] = spu_and(ctx->gpr[18], ctx->gpr[19]);
        spu_ls_write128(ctx, ctx->gpr[5]._u32[0] + 0x0, ctx->gpr[17]);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
}

void spu_job_01462A80_spu_func_01462EAC(spu_context* ctx) {
        /* branch hint (ignored) */;
        ctx->gpr[14] = spu_sfi(ctx->gpr[9], 0);
        ctx->gpr[5] = spu_ls_read128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[7]._u32[0]);
        /* nop */;
        /* nop */;
}

/* Indirect-dispatch stubs for cross-function targets the
 * function detector did not seed (typically conditional
 * branches that escape a function's range). */
void spu_job_01462A80_spu_func_00022A98(spu_context* ctx) {
    ctx->pc = 0x22A98u; spu_indirect_branch(ctx);
}
void spu_job_01462A80_spu_func_00022AB0(spu_context* ctx) {
    ctx->pc = 0x22AB0u; spu_indirect_branch(ctx);
}
void spu_job_01462A80_spu_func_00022C00(spu_context* ctx) {
    ctx->pc = 0x22C00u; spu_indirect_branch(ctx);
}
void spu_job_01462A80_spu_func_00022C74(spu_context* ctx) {
    ctx->pc = 0x22C74u; spu_indirect_branch(ctx);
}
void spu_job_01462A80_spu_func_00022CA0(spu_context* ctx) {
    ctx->pc = 0x22CA0u; spu_indirect_branch(ctx);
}
void spu_job_01462A80_spu_func_00022CC4(spu_context* ctx) {
    ctx->pc = 0x22CC4u; spu_indirect_branch(ctx);
}
void spu_job_01462A80_spu_func_00022CE0(spu_context* ctx) {
    ctx->pc = 0x22CE0u; spu_indirect_branch(ctx);
}
void spu_job_01462A80_spu_func_00022D00(spu_context* ctx) {
    ctx->pc = 0x22D00u; spu_indirect_branch(ctx);
}
void spu_job_01462A80_spu_func_00022D28(spu_context* ctx) {
    ctx->pc = 0x22D28u; spu_indirect_branch(ctx);
}
void spu_job_01462A80_spu_func_00022DD8(spu_context* ctx) {
    ctx->pc = 0x22DD8u; spu_indirect_branch(ctx);
}
void spu_job_01462A80_spu_func_00022E00(spu_context* ctx) {
    ctx->pc = 0x22E00u; spu_indirect_branch(ctx);
}
void spu_job_01462A80_spu_func_00022E30(spu_context* ctx) {
    ctx->pc = 0x22E30u; spu_indirect_branch(ctx);
}
void spu_job_01462A80_spu_func_00022E70(spu_context* ctx) {
    ctx->pc = 0x22E70u; spu_indirect_branch(ctx);
}
void spu_job_01462A80_spu_func_00022E84(spu_context* ctx) {
    ctx->pc = 0x22E84u; spu_indirect_branch(ctx);
}
void spu_job_01462A80_spu_func_00022EAC(spu_context* ctx) {
    ctx->pc = 0x22EACu; spu_indirect_branch(ctx);
}
void spu_job_01462A80_spu_func_00025AA0(spu_context* ctx) {
    ctx->pc = 0x25AA0u; spu_indirect_branch(ctx);
}

/* Function table */
typedef struct { uint32_t addr; void (*func)(spu_context*); const char* name; } spu_func_entry;
static const spu_func_entry spu_function_table[] = {
    { 0x01462A80u, spu_job_01462A80_spu_func_01462A80, "spu_job_01462A80_spu_func_01462A80" },
    { 0x01462A98u, spu_job_01462A80_spu_func_01462A98, "spu_job_01462A80_spu_func_01462A98" },
    { 0x01462AB0u, spu_job_01462A80_spu_func_01462AB0, "spu_job_01462A80_spu_func_01462AB0" },
    { 0x01462C00u, spu_job_01462A80_spu_func_01462C00, "spu_job_01462A80_spu_func_01462C00" },
    { 0x01462C74u, spu_job_01462A80_spu_func_01462C74, "spu_job_01462A80_spu_func_01462C74" },
    { 0x01462CA0u, spu_job_01462A80_spu_func_01462CA0, "spu_job_01462A80_spu_func_01462CA0" },
    { 0x01462CC4u, spu_job_01462A80_spu_func_01462CC4, "spu_job_01462A80_spu_func_01462CC4" },
    { 0x01462CE0u, spu_job_01462A80_spu_func_01462CE0, "spu_job_01462A80_spu_func_01462CE0" },
    { 0x01462D00u, spu_job_01462A80_spu_func_01462D00, "spu_job_01462A80_spu_func_01462D00" },
    { 0x01462D28u, spu_job_01462A80_spu_func_01462D28, "spu_job_01462A80_spu_func_01462D28" },
    { 0x01462DD8u, spu_job_01462A80_spu_func_01462DD8, "spu_job_01462A80_spu_func_01462DD8" },
    { 0x01462E00u, spu_job_01462A80_spu_func_01462E00, "spu_job_01462A80_spu_func_01462E00" },
    { 0x01462E30u, spu_job_01462A80_spu_func_01462E30, "spu_job_01462A80_spu_func_01462E30" },
    { 0x01462E70u, spu_job_01462A80_spu_func_01462E70, "spu_job_01462A80_spu_func_01462E70" },
    { 0x01462E84u, spu_job_01462A80_spu_func_01462E84, "spu_job_01462A80_spu_func_01462E84" },
    { 0x01462EACu, spu_job_01462A80_spu_func_01462EAC, "spu_job_01462A80_spu_func_01462EAC" },
    { 0, NULL, NULL }
};

void spu_job_01462A80_spu_recomp_register(void) {
    for (const spu_func_entry* e = spu_function_table; e->func; ++e)
        spu_register_function(e->addr, e->func);
}
