/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#include "spu_recomp.h"
#include "../../runtime/spu/spu_helpers.h"


void spu_job_01341000_spu_func_01341000(spu_context* ctx) {
        ctx->gpr[2] = spu_ila(0x3F374);
        ctx->gpr[2] = spu_ila(0x2121);
        ctx->gpr[2] = spu_ila(0x93CE);
        ctx->gpr[2] = spu_ila(0x5703);
        ctx->gpr[80] = spu_xori(ctx->gpr[80], 4);
        { ctx->pc = 0x1018; SPU_TAILCALL(spu_job_01341000_spu_func_00001018(ctx)); }
}

void spu_job_01341000_spu_func_01341018(spu_context* ctx) {
        ctx->gpr[80] = spu_xori(ctx->gpr[80], 4);
        { ctx->pc = 0x1030; SPU_TAILCALL(spu_job_01341000_spu_func_00001030(ctx)); }
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
}

void spu_job_01341000_spu_func_01341030(spu_context* ctx) {
        ctx->gpr[2] = spu_ori(ctx->gpr[3], 0);
        ctx->gpr[3] = spu_ai(ctx->gpr[4], 48);
        ctx->gpr[4] = spu_ls_read128(ctx, ctx->gpr[2]._u32[0] + 0x20);
        ctx->gpr[4] = spu_rotqby(ctx->gpr[4], ctx->gpr[2]);
        { ctx->pc = 0x3188; SPU_TAILCALL(spu_job_01341000_spu_func_00003188(ctx)); }
        /* nop */;
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        /* nop */;
        { ctx->pc = 0x1341050; SPU_TAILCALL(spu_job_01341000_spu_func_01341050(ctx)); }
}

void spu_job_01341000_spu_func_01341050(spu_context* ctx) {
        ctx->gpr[8] = spu_ila(0xFFFF);
        /* branch hint (ignored) */;
        ctx->gpr[7] = spu_ceqi(ctx->gpr[3], 1);
        ctx->gpr[6] = spu_ceq(ctx->gpr[4], ctx->gpr[8]);
        ctx->gpr[11] = spu_ila(0x68);
        ctx->gpr[10] = spu_link(0x1341068); spu_host_call_push(ctx, 0x1341068); spu_job_01341000_spu_func_00001068(ctx); spu_host_call_pop(ctx);
        { ctx->pc = 0x1341068; SPU_TAILCALL(spu_job_01341000_spu_func_01341068(ctx)); }
}

void spu_job_01341000_spu_func_01341068(spu_context* ctx) {
        ctx->gpr[2] = spu_nor(ctx->gpr[7], ctx->gpr[7]);
        ctx->gpr[5] = spu_nor(ctx->gpr[6], ctx->gpr[6]);
        ctx->gpr[3] = spu_ila(0x38A0);
        ctx->gpr[79] = spu_sf(ctx->gpr[11], ctx->gpr[10]);
        ctx->gpr[4] = spu_or(ctx->gpr[2], ctx->gpr[5]);
        ctx->gpr[3] = spu_a(ctx->gpr[3], ctx->gpr[79]);
        if (ctx->gpr[4]._u32[0] != 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        { ctx->pc = 0x3628; SPU_TAILCALL(spu_job_01341000_spu_func_00003628(ctx)); }
        ctx->gpr[3] = spu_il(1);
        /* nop */;
        ctx->gpr[4] = spu_ila(0xFFFF);
        { ctx->pc = 0x1050; SPU_TAILCALL(spu_job_01341000_spu_func_00001050(ctx)); }
}

void spu_job_01341000_spu_func_01341098(spu_context* ctx) {
        ctx->gpr[2] = spu_il(0);
        ctx->gpr[4] = spu_shlqbyi(ctx->gpr[3], 0);
        spu_wrch(ctx, MFC_WrTagUpdate, ctx->gpr[2]);
        { ctx->pc = 0x13410A4; SPU_TAILCALL(spu_job_01341000_spu_func_013410A4(ctx)); }
}

void spu_job_01341000_spu_func_013410A4(spu_context* ctx) {
        ctx->gpr[2] = spu_pref_u32(spu_rchcnt(ctx, MFC_WrTagUpdate));
        ctx->gpr[3] = spu_ceqi(ctx->gpr[2], 1);
        if (ctx->gpr[3]._u32[0] == 0) { ctx->pc = 0x10A4; SPU_TAILCALL(spu_job_01341000_spu_func_000010A4(ctx)); }
        /* nop */;
        /* branch hint (ignored) */;
        ctx->gpr[5] = spu_shl(ctx->gpr[2], ctx->gpr[4]);
        ctx->gpr[3] = spu_rdch(ctx, MFC_RdTagStat);
        ctx->gpr[4] = spu_il(2);
        /* nop */;
        /* nop */;
        spu_wrch(ctx, MFC_WrTagMask, ctx->gpr[5]);
        spu_wrch(ctx, MFC_WrTagUpdate, ctx->gpr[4]);
        ctx->gpr[2] = spu_rdch(ctx, MFC_RdTagStat);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        /* nop */;
        ctx->gpr[9] = spu_ceqi(ctx->gpr[4], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x50, ctx->gpr[84]);
        ctx->gpr[8] = spu_ceqi(ctx->gpr[5], 0);
        ctx->gpr[84] = spu_shlqbyi(ctx->gpr[4], 0);
        ctx->gpr[7] = spu_sfi(ctx->gpr[9], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x40, ctx->gpr[83]);
        ctx->gpr[4] = spu_sfi(ctx->gpr[8], 0);
        ctx->gpr[83] = spu_shlqbyi(ctx->gpr[5], 0);
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x80, ctx->gpr[87]);
        ctx->gpr[5] = spu_or(ctx->gpr[7], ctx->gpr[4]);
        ctx->gpr[87] = spu_shlqbyi(ctx->gpr[3], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x60, ctx->gpr[85]);
        ctx->gpr[3] = spu_ceqbi(ctx->gpr[5], 0);
        ctx->gpr[85] = spu_ori(ctx->gpr[6], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + 0x10, ctx->gpr[0]);
        ctx->gpr[2] = spu_xsbh(ctx->gpr[3]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x10, ctx->gpr[80]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x20, ctx->gpr[81]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x30, ctx->gpr[82]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x70, ctx->gpr[86]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x90, ctx->gpr[88]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xA0, ctx->gpr[89]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xB0, ctx->gpr[90]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xC0, ctx->gpr[91]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xD0, ctx->gpr[126]);
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xF0, ctx->gpr[1]);
        ctx->gpr[1] = spu_ai(ctx->gpr[1], -240);
        if (ctx->gpr[2]._u16[1] == 0) { ctx->pc = 0x1204; SPU_TAILCALL(spu_job_01341000_spu_func_00001204(ctx)); }
        ctx->gpr[6] = spu_cgti(ctx->gpr[6], 0);
        if (ctx->gpr[6]._u32[0] == 0) { ctx->pc = 0x1204; SPU_TAILCALL(spu_job_01341000_spu_func_00001204(ctx)); }
        ctx->gpr[88] = spu_ori(ctx->gpr[87], 0);
        /* branch hint (ignored) */;
        ctx->gpr[86] = spu_il(0);
        ctx->gpr[90] = spu_fsmbi(0x0);
        ctx->gpr[91] = spu_il(16383);
        ctx->gpr[89] = spu_il(32);
        { ctx->pc = 0x1341178; SPU_TAILCALL(spu_job_01341000_spu_func_01341178(ctx)); }
}

void spu_job_01341000_spu_func_01341178(spu_context* ctx) {
        ctx->gpr[20] = spu_sf(ctx->gpr[86], ctx->gpr[85]);
        ctx->gpr[3] = spu_shlqbyi(ctx->gpr[87], 0);
        ctx->gpr[13] = spu_il(16384);
        ctx->gpr[28] = spu_ai(ctx->gpr[20], 3);
        ctx->gpr[27] = spu_ai(ctx->gpr[20], 7);
        ctx->gpr[25] = spu_cgti(ctx->gpr[20], 4);
        ctx->gpr[23] = spu_andi(ctx->gpr[28], -4);
        ctx->gpr[24] = spu_andi(ctx->gpr[27], -8);
        ctx->gpr[26] = spu_ai(ctx->gpr[20], 15);
        ctx->gpr[22] = spu_ceqi(ctx->gpr[25], 0);
        ctx->gpr[21] = spu_cgti(ctx->gpr[20], 8);
        ctx->gpr[19] = spu_andi(ctx->gpr[26], -16);
        ctx->gpr[17] = spu_selb(ctx->gpr[24], ctx->gpr[23], ctx->gpr[22]);
        ctx->gpr[18] = spu_ceqi(ctx->gpr[21], 0);
        ctx->gpr[16] = spu_cgt(ctx->gpr[20], ctx->gpr[91]);
        ctx->gpr[15] = spu_selb(ctx->gpr[19], ctx->gpr[17], ctx->gpr[18]);
        ctx->gpr[14] = spu_ceqi(ctx->gpr[16], 0);
        /* nop */;
        ctx->gpr[81] = spu_selb(ctx->gpr[13], ctx->gpr[15], ctx->gpr[14]);
        ctx->gpr[0] = spu_link(0x13411C8); spu_host_call_push(ctx, 0x13411C8); spu_job_01341000_spu_func_00001098(ctx); spu_host_call_pop(ctx);
        ctx->gpr[12] = spu_ori(ctx->gpr[83], 0);
        /* branch hint (ignored) */;
        ctx->gpr[11] = spu_ori(ctx->gpr[84], 0);
        ctx->gpr[80] = spu_shlqbyi(ctx->gpr[81], 0);
        ctx->gpr[86] = spu_a(ctx->gpr[86], ctx->gpr[81]);
        spu_wrch(ctx, MFC_LSA, ctx->gpr[12]);
        ctx->gpr[83] = spu_a(ctx->gpr[83], ctx->gpr[81]);
        spu_wrch(ctx, MFC_EAH, ctx->gpr[90]);
        ctx->gpr[10] = spu_cgt(ctx->gpr[85], ctx->gpr[86]);
        spu_wrch(ctx, MFC_EAL, ctx->gpr[11]);
        ctx->gpr[84] = spu_a(ctx->gpr[84], ctx->gpr[81]);
        spu_wrch(ctx, MFC_Size, ctx->gpr[80]);
        spu_wrch(ctx, MFC_TagID, ctx->gpr[88]);
        spu_wrch(ctx, MFC_Cmd, ctx->gpr[89]);
        if (ctx->gpr[10]._u32[0] != 0) { ctx->pc = 0x1178; SPU_TAILCALL(spu_job_01341000_spu_func_00001178(ctx)); }
        { ctx->pc = 0x1341204; SPU_TAILCALL(spu_job_01341000_spu_func_01341204(ctx)); }
}

void spu_job_01341000_spu_func_01341204(spu_context* ctx) {
        ctx->gpr[0] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + 0x100);
        ctx->gpr[1] = spu_ai(ctx->gpr[1], 240);
        ctx->gpr[80] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x10);
        ctx->gpr[81] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x20);
        ctx->gpr[82] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x30);
        /* branch hint (ignored) */;
        ctx->gpr[83] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x40);
        ctx->gpr[84] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x50);
        ctx->gpr[85] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x60);
        ctx->gpr[86] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x70);
        ctx->gpr[87] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x80);
        ctx->gpr[88] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x90);
        ctx->gpr[89] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0xA0);
        ctx->gpr[90] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0xB0);
        ctx->gpr[91] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0xC0);
        ctx->gpr[126] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0xD0);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        ctx->gpr[9] = spu_ceqi(ctx->gpr[4], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x50, ctx->gpr[84]);
        ctx->gpr[8] = spu_ceqi(ctx->gpr[5], 0);
        ctx->gpr[84] = spu_shlqbyi(ctx->gpr[4], 0);
        ctx->gpr[7] = spu_sfi(ctx->gpr[9], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x40, ctx->gpr[83]);
        ctx->gpr[4] = spu_sfi(ctx->gpr[8], 0);
        ctx->gpr[83] = spu_shlqbyi(ctx->gpr[5], 0);
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x80, ctx->gpr[87]);
        ctx->gpr[5] = spu_or(ctx->gpr[7], ctx->gpr[4]);
        ctx->gpr[87] = spu_shlqbyi(ctx->gpr[3], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x60, ctx->gpr[85]);
        ctx->gpr[3] = spu_ceqbi(ctx->gpr[5], 0);
        ctx->gpr[85] = spu_ori(ctx->gpr[6], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + 0x10, ctx->gpr[0]);
        ctx->gpr[2] = spu_xsbh(ctx->gpr[3]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x10, ctx->gpr[80]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x20, ctx->gpr[81]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x30, ctx->gpr[82]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x70, ctx->gpr[86]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x90, ctx->gpr[88]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xA0, ctx->gpr[89]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xB0, ctx->gpr[90]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xC0, ctx->gpr[91]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xD0, ctx->gpr[126]);
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xF0, ctx->gpr[1]);
        ctx->gpr[1] = spu_ai(ctx->gpr[1], -240);
        if (ctx->gpr[2]._u16[1] == 0) { ctx->pc = 0x136C; SPU_TAILCALL(spu_job_01341000_spu_func_0000136C(ctx)); }
        ctx->gpr[6] = spu_cgti(ctx->gpr[6], 0);
        if (ctx->gpr[6]._u32[0] == 0) { ctx->pc = 0x136C; SPU_TAILCALL(spu_job_01341000_spu_func_0000136C(ctx)); }
        ctx->gpr[88] = spu_ori(ctx->gpr[87], 0);
        /* branch hint (ignored) */;
        ctx->gpr[86] = spu_il(0);
        ctx->gpr[90] = spu_fsmbi(0x0);
        ctx->gpr[91] = spu_il(16383);
        ctx->gpr[89] = spu_il(64);
        { ctx->pc = 0x13412E0; SPU_TAILCALL(spu_job_01341000_spu_func_013412E0(ctx)); }
}

void spu_job_01341000_spu_func_013412E0(spu_context* ctx) {
        ctx->gpr[20] = spu_sf(ctx->gpr[86], ctx->gpr[85]);
        ctx->gpr[3] = spu_shlqbyi(ctx->gpr[87], 0);
        ctx->gpr[13] = spu_il(16384);
        ctx->gpr[28] = spu_ai(ctx->gpr[20], 3);
        ctx->gpr[27] = spu_ai(ctx->gpr[20], 7);
        ctx->gpr[25] = spu_cgti(ctx->gpr[20], 4);
        ctx->gpr[23] = spu_andi(ctx->gpr[28], -4);
        ctx->gpr[24] = spu_andi(ctx->gpr[27], -8);
        ctx->gpr[26] = spu_ai(ctx->gpr[20], 15);
        ctx->gpr[22] = spu_ceqi(ctx->gpr[25], 0);
        ctx->gpr[21] = spu_cgti(ctx->gpr[20], 8);
        ctx->gpr[19] = spu_andi(ctx->gpr[26], -16);
        ctx->gpr[17] = spu_selb(ctx->gpr[24], ctx->gpr[23], ctx->gpr[22]);
        ctx->gpr[18] = spu_ceqi(ctx->gpr[21], 0);
        ctx->gpr[16] = spu_cgt(ctx->gpr[20], ctx->gpr[91]);
        ctx->gpr[15] = spu_selb(ctx->gpr[19], ctx->gpr[17], ctx->gpr[18]);
        ctx->gpr[14] = spu_ceqi(ctx->gpr[16], 0);
        /* nop */;
        ctx->gpr[81] = spu_selb(ctx->gpr[13], ctx->gpr[15], ctx->gpr[14]);
        ctx->gpr[0] = spu_link(0x1341330); spu_host_call_push(ctx, 0x1341330); spu_job_01341000_spu_func_00001098(ctx); spu_host_call_pop(ctx);
        ctx->gpr[12] = spu_ori(ctx->gpr[84], 0);
        /* branch hint (ignored) */;
        ctx->gpr[11] = spu_ori(ctx->gpr[83], 0);
        ctx->gpr[80] = spu_shlqbyi(ctx->gpr[81], 0);
        ctx->gpr[86] = spu_a(ctx->gpr[86], ctx->gpr[81]);
        spu_wrch(ctx, MFC_LSA, ctx->gpr[12]);
        ctx->gpr[83] = spu_a(ctx->gpr[83], ctx->gpr[81]);
        spu_wrch(ctx, MFC_EAH, ctx->gpr[90]);
        ctx->gpr[10] = spu_cgt(ctx->gpr[85], ctx->gpr[86]);
        spu_wrch(ctx, MFC_EAL, ctx->gpr[11]);
        ctx->gpr[84] = spu_a(ctx->gpr[84], ctx->gpr[81]);
        spu_wrch(ctx, MFC_Size, ctx->gpr[80]);
        spu_wrch(ctx, MFC_TagID, ctx->gpr[88]);
        spu_wrch(ctx, MFC_Cmd, ctx->gpr[89]);
        if (ctx->gpr[10]._u32[0] != 0) { ctx->pc = 0x12E0; SPU_TAILCALL(spu_job_01341000_spu_func_000012E0(ctx)); }
        { ctx->pc = 0x134136C; SPU_TAILCALL(spu_job_01341000_spu_func_0134136C(ctx)); }
}

void spu_job_01341000_spu_func_0134136C(spu_context* ctx) {
        ctx->gpr[0] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + 0x100);
        ctx->gpr[1] = spu_ai(ctx->gpr[1], 240);
        ctx->gpr[80] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x10);
        ctx->gpr[81] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x20);
        ctx->gpr[82] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x30);
        /* branch hint (ignored) */;
        ctx->gpr[83] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x40);
        ctx->gpr[84] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x50);
        ctx->gpr[85] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x60);
        ctx->gpr[86] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x70);
}

/* Indirect-dispatch stubs for cross-function targets the
 * function detector did not seed (typically conditional
 * branches that escape a function's range). */
void spu_job_01341000_spu_func_00001018(spu_context* ctx) {
    ctx->pc = 0x1018u; spu_indirect_branch(ctx);
}
void spu_job_01341000_spu_func_00001030(spu_context* ctx) {
    ctx->pc = 0x1030u; spu_indirect_branch(ctx);
}
void spu_job_01341000_spu_func_00001050(spu_context* ctx) {
    ctx->pc = 0x1050u; spu_indirect_branch(ctx);
}
void spu_job_01341000_spu_func_00001068(spu_context* ctx) {
    ctx->pc = 0x1068u; spu_indirect_branch(ctx);
}
void spu_job_01341000_spu_func_00001098(spu_context* ctx) {
    ctx->pc = 0x1098u; spu_indirect_branch(ctx);
}
void spu_job_01341000_spu_func_000010A4(spu_context* ctx) {
    ctx->pc = 0x10A4u; spu_indirect_branch(ctx);
}
void spu_job_01341000_spu_func_00001178(spu_context* ctx) {
    ctx->pc = 0x1178u; spu_indirect_branch(ctx);
}
void spu_job_01341000_spu_func_00001204(spu_context* ctx) {
    ctx->pc = 0x1204u; spu_indirect_branch(ctx);
}
void spu_job_01341000_spu_func_000012E0(spu_context* ctx) {
    ctx->pc = 0x12E0u; spu_indirect_branch(ctx);
}
void spu_job_01341000_spu_func_0000136C(spu_context* ctx) {
    ctx->pc = 0x136Cu; spu_indirect_branch(ctx);
}
void spu_job_01341000_spu_func_00003188(spu_context* ctx) {
    ctx->pc = 0x3188u; spu_indirect_branch(ctx);
}
void spu_job_01341000_spu_func_00003628(spu_context* ctx) {
    ctx->pc = 0x3628u; spu_indirect_branch(ctx);
}

/* Function table */
typedef struct { uint32_t addr; void (*func)(spu_context*); const char* name; } spu_func_entry;
static const spu_func_entry spu_function_table[] = {
    { 0x01341000u, spu_job_01341000_spu_func_01341000, "spu_job_01341000_spu_func_01341000" },
    { 0x01341018u, spu_job_01341000_spu_func_01341018, "spu_job_01341000_spu_func_01341018" },
    { 0x01341030u, spu_job_01341000_spu_func_01341030, "spu_job_01341000_spu_func_01341030" },
    { 0x01341050u, spu_job_01341000_spu_func_01341050, "spu_job_01341000_spu_func_01341050" },
    { 0x01341068u, spu_job_01341000_spu_func_01341068, "spu_job_01341000_spu_func_01341068" },
    { 0x01341098u, spu_job_01341000_spu_func_01341098, "spu_job_01341000_spu_func_01341098" },
    { 0x013410A4u, spu_job_01341000_spu_func_013410A4, "spu_job_01341000_spu_func_013410A4" },
    { 0x01341178u, spu_job_01341000_spu_func_01341178, "spu_job_01341000_spu_func_01341178" },
    { 0x01341204u, spu_job_01341000_spu_func_01341204, "spu_job_01341000_spu_func_01341204" },
    { 0x013412E0u, spu_job_01341000_spu_func_013412E0, "spu_job_01341000_spu_func_013412E0" },
    { 0x0134136Cu, spu_job_01341000_spu_func_0134136C, "spu_job_01341000_spu_func_0134136C" },
    { 0, NULL, NULL }
};

void spu_job_01341000_spu_recomp_register(void) {
    for (const spu_func_entry* e = spu_function_table; e->func; ++e)
        spu_register_function(e->addr, e->func);
}
