/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#include "spu_recomp.h"
#include "../../runtime/spu/spu_helpers.h"


void spu_job_0145F400_spu_func_0145F400(spu_context* ctx) {
        ctx->gpr[2] = spu_ila(0x3A884);
        ctx->gpr[2] = spu_ila(0x3750D);
        ctx->gpr[2] = spu_ila(0x6CA2);
        ctx->gpr[2] = spu_ila(0x30C9F);
        ctx->gpr[80] = spu_xori(ctx->gpr[80], 4);
        { ctx->pc = 0x1F418; SPU_TAILCALL(spu_job_0145F400_spu_func_0001F418(ctx)); }
}

void spu_job_0145F400_spu_func_0145F418(spu_context* ctx) {
        ctx->gpr[80] = spu_xori(ctx->gpr[80], 4);
        { ctx->pc = 0x1F430; SPU_TAILCALL(spu_job_0145F400_spu_func_0001F430(ctx)); }
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
}

void spu_job_0145F400_spu_func_0145F430(spu_context* ctx) {
        ctx->gpr[2] = spu_ori(ctx->gpr[3], 0);
        ctx->gpr[3] = spu_ai(ctx->gpr[4], 48);
        ctx->gpr[4] = spu_ls_read128(ctx, ctx->gpr[2]._u32[0] + 0x20);
        ctx->gpr[4] = spu_rotqby(ctx->gpr[4], ctx->gpr[2]);
        { ctx->pc = 0x21B48; SPU_TAILCALL(spu_job_0145F400_spu_func_00021B48(ctx)); }
        /* nop */;
        ctx->gpr[6] = spu_shli(ctx->gpr[6], 2);
        ctx->gpr[5] = spu_ls_read128(ctx, ctx->gpr[6]._u32[0] + ctx->gpr[3]._u32[0]);
        ctx->gpr[4] = spu_cwx(ctx->gpr[6], ctx->gpr[3]);
        ctx->gpr[2] = spu_shufb(ctx->gpr[7], ctx->gpr[5], ctx->gpr[4]);
        spu_ls_write128(ctx, ctx->gpr[6]._u32[0] + ctx->gpr[3]._u32[0], ctx->gpr[2]);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        /* branch hint (ignored) */;
        ctx->gpr[5] = spu_shli(ctx->gpr[6], 2);
        /* nop */;
        /* nop */;
        ctx->gpr[6] = spu_a(ctx->gpr[5], ctx->gpr[3]);
        ctx->gpr[4] = spu_ls_read128(ctx, ctx->gpr[6]._u32[0] + 0x20);
        ctx->gpr[3] = spu_cwd(ctx->gpr[6], 0);
        ctx->gpr[2] = spu_shufb(ctx->gpr[7], ctx->gpr[4], ctx->gpr[3]);
        spu_ls_write128(ctx, ctx->gpr[6]._u32[0] + 0x20, ctx->gpr[2]);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        /* branch hint (ignored) */;
        ctx->gpr[5] = spu_shli(ctx->gpr[6], 2);
        /* nop */;
        /* nop */;
        ctx->gpr[6] = spu_a(ctx->gpr[5], ctx->gpr[3]);
        ctx->gpr[4] = spu_ls_read128(ctx, ctx->gpr[6]._u32[0] + 0x120);
        ctx->gpr[3] = spu_cwd(ctx->gpr[6], 0);
        ctx->gpr[2] = spu_shufb(ctx->gpr[7], ctx->gpr[4], ctx->gpr[3]);
        spu_ls_write128(ctx, ctx->gpr[6]._u32[0] + 0x120, ctx->gpr[2]);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        ctx->gpr[8] = spu_ila(0xB8);
        ctx->gpr[79] = spu_link(0x145F4B8); spu_host_call_push(ctx, 0x145F4B8); spu_job_0145F400_spu_func_0001F4B8(ctx); spu_host_call_pop(ctx);
        { ctx->pc = 0x145F4B8; SPU_TAILCALL(spu_job_0145F400_spu_func_0145F4B8(ctx)); }
}

void spu_job_0145F400_spu_func_0145F4B8(spu_context* ctx) {
        ctx->gpr[11] = spu_ori(ctx->gpr[3], 0);
        ctx->gpr[3] = spu_fsmbi(0x0);
        ctx->gpr[79] = spu_sf(ctx->gpr[8], ctx->gpr[79]);
        ctx->gpr[2] = spu_fceq(ctx->gpr[7], ctx->gpr[3]);
        if (ctx->gpr[2]._u32[0] != 0) { ctx->pc = 0x1F598; SPU_TAILCALL(spu_job_0145F400_spu_func_0001F598(ctx)); }
        ctx->gpr[23] = spu_ilhu(0x3F80);
        ctx->gpr[22] = spu_fceq(ctx->gpr[7], ctx->gpr[23]);
        if (ctx->gpr[22]._u32[0] == 0) { ctx->pc = 0x1F558; SPU_TAILCALL(spu_job_0145F400_spu_func_0001F558(ctx)); }
        ctx->gpr[32] = spu_ceq(ctx->gpr[11], ctx->gpr[5]);
        ctx->gpr[31] = spu_ceq(ctx->gpr[4], ctx->gpr[6]);
        ctx->gpr[30] = spu_nor(ctx->gpr[32], ctx->gpr[32]);
        ctx->gpr[29] = spu_nor(ctx->gpr[31], ctx->gpr[31]);
        ctx->gpr[27] = spu_sfi(ctx->gpr[30], 0);
        ctx->gpr[28] = spu_sfi(ctx->gpr[29], 0);
        ctx->gpr[26] = spu_or(ctx->gpr[27], ctx->gpr[28]);
        ctx->gpr[25] = spu_ceqbi(ctx->gpr[26], 0);
        ctx->gpr[24] = spu_xsbh(ctx->gpr[25]);
        if (ctx->gpr[24]._u16[1] != 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        ctx->gpr[34] = spu_shli(ctx->gpr[4], 10);
        /* branch hint (ignored) */;
        ctx->gpr[4] = spu_shli(ctx->gpr[6], 10);
        ctx->gpr[13] = spu_a(ctx->gpr[11], ctx->gpr[34]);
        ctx->gpr[12] = spu_a(ctx->gpr[5], ctx->gpr[4]);
        ctx->gpr[14] = spu_andi(ctx->gpr[13], 15);
        ctx->gpr[7] = spu_andi(ctx->gpr[12], 15);
        ctx->gpr[33] = spu_or(ctx->gpr[7], ctx->gpr[14]);
        if (ctx->gpr[33]._u32[0] != 0) { ctx->pc = 0x1F5E0; SPU_TAILCALL(spu_job_0145F400_spu_func_0001F5E0(ctx)); }
        ctx->gpr[3] = spu_il(0);
        ctx->gpr[4] = spu_il(1024);
        { ctx->pc = 0x145F52C; SPU_TAILCALL(spu_job_0145F400_spu_func_0145F52C(ctx)); }
}

void spu_job_0145F400_spu_func_0145F52C(spu_context* ctx) {
        ctx->gpr[36] = spu_ls_read128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[12]._u32[0]);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[13]._u32[0], ctx->gpr[36]);
        ctx->gpr[3] = spu_ai(ctx->gpr[3], 16);
        ctx->gpr[35] = spu_ceq(ctx->gpr[3], ctx->gpr[4]);
        if (ctx->gpr[35]._u32[0] != 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        ctx->gpr[36] = spu_ls_read128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[12]._u32[0]);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[13]._u32[0], ctx->gpr[36]);
        ctx->gpr[3] = spu_ai(ctx->gpr[3], 16);
        ctx->gpr[35] = spu_ceq(ctx->gpr[3], ctx->gpr[4]);
        if (ctx->gpr[35]._u32[0] == 0) { ctx->pc = 0x1F52C; SPU_TAILCALL(spu_job_0145F400_spu_func_0001F52C(ctx)); }
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
}

void spu_job_0145F400_spu_func_0145F558(spu_context* ctx) {
        ctx->gpr[9] = spu_shli(ctx->gpr[4], 10);
        /* branch hint (ignored) */;
        ctx->gpr[13] = spu_shli(ctx->gpr[6], 10);
        ctx->gpr[8] = spu_fsmbi(0x0);
        ctx->gpr[10] = spu_ila(0x10203);
        ctx->gpr[3] = spu_il(1024);
        ctx->gpr[11] = spu_a(ctx->gpr[9], ctx->gpr[11]);
        ctx->gpr[7] = spu_shufb(ctx->gpr[7], ctx->gpr[7], ctx->gpr[10]);
        ctx->gpr[4] = spu_a(ctx->gpr[13], ctx->gpr[5]);
        { ctx->pc = 0x145F57C; SPU_TAILCALL(spu_job_0145F400_spu_func_0145F57C(ctx)); }
}

void spu_job_0145F400_spu_func_0145F57C(spu_context* ctx) {
        ctx->gpr[14] = spu_ls_read128(ctx, ctx->gpr[8]._u32[0] + ctx->gpr[4]._u32[0]);
        ctx->gpr[6] = spu_fm(ctx->gpr[14], ctx->gpr[7]);
        spu_ls_write128(ctx, ctx->gpr[8]._u32[0] + ctx->gpr[11]._u32[0], ctx->gpr[6]);
        ctx->gpr[8] = spu_ai(ctx->gpr[8], 16);
        ctx->gpr[5] = spu_ceq(ctx->gpr[8], ctx->gpr[3]);
        if (ctx->gpr[5]._u32[0] == 0) { ctx->pc = 0x1F57C; SPU_TAILCALL(spu_job_0145F400_spu_func_0001F57C(ctx)); }
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
}

void spu_job_0145F400_spu_func_0145F598(spu_context* ctx) {
        ctx->gpr[7] = spu_shli(ctx->gpr[4], 10);
        /* branch hint (ignored) */;
        ctx->gpr[6] = spu_il(0);
        ctx->gpr[5] = spu_a(ctx->gpr[11], ctx->gpr[7]);
        ctx->gpr[2] = spu_andi(ctx->gpr[5], 15);
        if (ctx->gpr[2]._u32[0] != 0) { ctx->pc = 0x1F6E8; SPU_TAILCALL(spu_job_0145F400_spu_func_0001F6E8(ctx)); }
        ctx->gpr[3] = spu_il(0);
        ctx->gpr[4] = spu_il(1024);
        { ctx->pc = 0x145F5B8; SPU_TAILCALL(spu_job_0145F400_spu_func_0145F5B8(ctx)); }
}

void spu_job_0145F400_spu_func_0145F5B8(spu_context* ctx) {
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[5]._u32[0], ctx->gpr[6]);
        ctx->gpr[3] = spu_ai(ctx->gpr[3], 16);
        ctx->gpr[7] = spu_ceq(ctx->gpr[3], ctx->gpr[4]);
        if (ctx->gpr[7]._u32[0] != 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[5]._u32[0], ctx->gpr[6]);
        ctx->gpr[3] = spu_ai(ctx->gpr[3], 16);
        ctx->gpr[7] = spu_ceq(ctx->gpr[3], ctx->gpr[4]);
        if (ctx->gpr[7]._u32[0] == 0) { ctx->pc = 0x1F5B8; SPU_TAILCALL(spu_job_0145F400_spu_func_0001F5B8(ctx)); }
        /* nop */;
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
}

void spu_job_0145F400_spu_func_0145F5E0(spu_context* ctx) {
        ctx->gpr[57] = spu_sf(ctx->gpr[14], ctx->gpr[7]);
        ctx->gpr[53] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + ctx->gpr[4]._u32[0]);
        ctx->gpr[61] = spu_ila(0x34E0);
        ctx->gpr[54] = spu_ls_read128(ctx, ctx->gpr[12]._u32[0] + 0x10);
        ctx->gpr[60] = spu_shli(ctx->gpr[57], 4);
        ctx->gpr[51] = spu_fsmbi(0xFFFF);
        ctx->gpr[63] = spu_il(1024);
        ctx->gpr[41] = spu_ls_read128(ctx, ctx->gpr[13]._u32[0] + 0x0);
        ctx->gpr[59] = spu_a(ctx->gpr[61], ctx->gpr[79]);
        ctx->gpr[58] = spu_a(ctx->gpr[14], ctx->gpr[63]);
        ctx->gpr[55] = spu_cgti(ctx->gpr[57], 0);
        ctx->gpr[52] = spu_ls_read128(ctx, ctx->gpr[60]._u32[0] + ctx->gpr[59]._u32[0]);
        ctx->gpr[56] = spu_sfi(ctx->gpr[58], 0);
        ctx->gpr[46] = spu_rotqmby(ctx->gpr[53], ctx->gpr[57]);
        ctx->gpr[37] = spu_clgti(ctx->gpr[58], 15);
        /* nop */;
        ctx->gpr[5] = spu_sfi(ctx->gpr[14], 16);
        ctx->gpr[48] = spu_rotqmby(ctx->gpr[51], ctx->gpr[56]);
        ctx->gpr[50] = spu_ceqi(ctx->gpr[55], 0);
        ctx->gpr[49] = spu_ceqi(ctx->gpr[37], 0);
        ctx->gpr[42] = spu_shlqby(ctx->gpr[51], ctx->gpr[5]);
        ctx->gpr[47] = spu_shufb(ctx->gpr[53], ctx->gpr[54], ctx->gpr[52]);
        ctx->gpr[45] = spu_fsm(ctx->gpr[50]);
        ctx->gpr[43] = spu_fsm(ctx->gpr[49]);
        ctx->gpr[44] = spu_or(ctx->gpr[42], ctx->gpr[48]);
        ctx->gpr[39] = spu_selb(ctx->gpr[47], ctx->gpr[46], ctx->gpr[45]);
        ctx->gpr[40] = spu_selb(ctx->gpr[42], ctx->gpr[44], ctx->gpr[43]);
        ctx->gpr[38] = spu_selb(ctx->gpr[39], ctx->gpr[41], ctx->gpr[40]);
        spu_ls_write128(ctx, ctx->gpr[13]._u32[0] + 0x0, ctx->gpr[38]);
        if (ctx->gpr[37]._u32[0] == 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        ctx->gpr[7] = spu_a(ctx->gpr[12], ctx->gpr[5]);
        /* branch hint (ignored) */;
        ctx->gpr[67] = spu_ila(0x34E0);
        ctx->gpr[69] = spu_andi(ctx->gpr[7], 15);
        ctx->gpr[68] = spu_il(1024);
        ctx->gpr[66] = spu_shli(ctx->gpr[69], 4);
        ctx->gpr[65] = spu_a(ctx->gpr[67], ctx->gpr[79]);
        ctx->gpr[8] = spu_sf(ctx->gpr[5], ctx->gpr[68]);
        ctx->gpr[11] = spu_a(ctx->gpr[13], ctx->gpr[5]);
        /* nop */;
        ctx->gpr[64] = spu_clgti(ctx->gpr[8], 15);
        ctx->gpr[9] = spu_ls_read128(ctx, ctx->gpr[66]._u32[0] + ctx->gpr[65]._u32[0]);
        /* nop */;
        if (ctx->gpr[64]._u32[0] == 0) { ctx->pc = 0x1F6B8; SPU_TAILCALL(spu_job_0145F400_spu_func_0001F6B8(ctx)); }
        { ctx->pc = 0x145F690; SPU_TAILCALL(spu_job_0145F400_spu_func_0145F690(ctx)); }
}

void spu_job_0145F400_spu_func_0145F690(spu_context* ctx) {
        ctx->gpr[8] = spu_ai(ctx->gpr[8], -16);
        ctx->gpr[72] = spu_ls_read128(ctx, ctx->gpr[7]._u32[0] + 0x0);
        ctx->gpr[7] = spu_ai(ctx->gpr[7], 16);
        ctx->gpr[70] = spu_clgti(ctx->gpr[8], 15);
        ctx->gpr[73] = spu_ls_read128(ctx, ctx->gpr[7]._u32[0] + 0x0);
        ctx->gpr[71] = spu_shufb(ctx->gpr[72], ctx->gpr[73], ctx->gpr[9]);
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[11]._u32[0] + 0x0, ctx->gpr[71]);
        ctx->gpr[11] = spu_ai(ctx->gpr[11], 16);
        if (ctx->gpr[70]._u32[0] != 0) { ctx->pc = 0x1F690; SPU_TAILCALL(spu_job_0145F400_spu_func_0001F690(ctx)); }
        { ctx->pc = 0x145F6B8; SPU_TAILCALL(spu_job_0145F400_spu_func_0145F6B8(ctx)); }
}

void spu_job_0145F400_spu_func_0145F6B8(spu_context* ctx) {
        /* branch hint (ignored) */;
        if (ctx->gpr[8]._u32[0] == 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        ctx->gpr[79] = spu_sfi(ctx->gpr[8], 0);
        ctx->gpr[3] = spu_ls_read128(ctx, ctx->gpr[7]._u32[0] + 0x10);
        ctx->gpr[2] = spu_il(-1);
        ctx->gpr[78] = spu_ls_read128(ctx, ctx->gpr[7]._u32[0] + 0x0);
        ctx->gpr[77] = spu_ls_read128(ctx, ctx->gpr[11]._u32[0] + 0x0);
        ctx->gpr[76] = spu_rotqmby(ctx->gpr[2], ctx->gpr[79]);
        ctx->gpr[75] = spu_shufb(ctx->gpr[78], ctx->gpr[3], ctx->gpr[9]);
        ctx->gpr[74] = spu_selb(ctx->gpr[75], ctx->gpr[77], ctx->gpr[76]);
        spu_ls_write128(ctx, ctx->gpr[11]._u32[0] + 0x0, ctx->gpr[74]);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
}

void spu_job_0145F400_spu_func_0145F6E8(spu_context* ctx) {
        ctx->gpr[4] = spu_il(1024);
        /* branch hint (ignored) */;
        ctx->gpr[8] = spu_sfi(ctx->gpr[2], 16);
        ctx->gpr[12] = spu_fsmbi(0xFFFF);
        ctx->gpr[9] = spu_a(ctx->gpr[2], ctx->gpr[4]);
        ctx->gpr[13] = spu_clgti(ctx->gpr[9], 15);
        ctx->gpr[10] = spu_shlqby(ctx->gpr[12], ctx->gpr[8]);
        if (ctx->gpr[13]._u32[0] == 0) { ctx->pc = 0x1F764; SPU_TAILCALL(spu_job_0145F400_spu_func_0001F764(ctx)); }
        ctx->gpr[4] = spu_sf(ctx->gpr[8], ctx->gpr[4]);
        ctx->gpr[16] = spu_ls_read128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[7]._u32[0]);
        ctx->gpr[5] = spu_a(ctx->gpr[5], ctx->gpr[8]);
        ctx->gpr[12] = spu_clgti(ctx->gpr[4], 15);
        ctx->gpr[15] = spu_and(ctx->gpr[16], ctx->gpr[10]);
        spu_ls_write128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[7]._u32[0], ctx->gpr[15]);
        /* nop */;
        if (ctx->gpr[12]._u32[0] == 0) { ctx->pc = 0x1F73C; SPU_TAILCALL(spu_job_0145F400_spu_func_0001F73C(ctx)); }
        { ctx->pc = 0x145F728; SPU_TAILCALL(spu_job_0145F400_spu_func_0145F728(ctx)); }
}

void spu_job_0145F400_spu_func_0145F728(spu_context* ctx) {
        ctx->gpr[4] = spu_ai(ctx->gpr[4], -16);
        spu_ls_write128(ctx, ctx->gpr[5]._u32[0] + 0x0, ctx->gpr[6]);
        ctx->gpr[5] = spu_ai(ctx->gpr[5], 16);
        ctx->gpr[11] = spu_clgti(ctx->gpr[4], 15);
        if (ctx->gpr[11]._u32[0] != 0) { ctx->pc = 0x1F728; SPU_TAILCALL(spu_job_0145F400_spu_func_0001F728(ctx)); }
        { ctx->pc = 0x145F73C; SPU_TAILCALL(spu_job_0145F400_spu_func_0145F73C(ctx)); }
}

void spu_job_0145F400_spu_func_0145F73C(spu_context* ctx) {
        /* branch hint (ignored) */;
        /* nop */;
        if (ctx->gpr[4]._u32[0] == 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        ctx->gpr[21] = spu_sfi(ctx->gpr[4], 0);
        ctx->gpr[18] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + 0x0);
        ctx->gpr[20] = spu_il(-1);
        ctx->gpr[19] = spu_rotqmby(ctx->gpr[20], ctx->gpr[21]);
        ctx->gpr[17] = spu_and(ctx->gpr[18], ctx->gpr[19]);
        spu_ls_write128(ctx, ctx->gpr[5]._u32[0] + 0x0, ctx->gpr[17]);
}

/* Indirect-dispatch stubs for cross-function targets the
 * function detector did not seed (typically conditional
 * branches that escape a function's range). */
void spu_job_0145F400_spu_func_0001F418(spu_context* ctx) {
    ctx->pc = 0x1F418u; spu_indirect_branch(ctx);
}
void spu_job_0145F400_spu_func_0001F430(spu_context* ctx) {
    ctx->pc = 0x1F430u; spu_indirect_branch(ctx);
}
void spu_job_0145F400_spu_func_0001F4B8(spu_context* ctx) {
    ctx->pc = 0x1F4B8u; spu_indirect_branch(ctx);
}
void spu_job_0145F400_spu_func_0001F52C(spu_context* ctx) {
    ctx->pc = 0x1F52Cu; spu_indirect_branch(ctx);
}
void spu_job_0145F400_spu_func_0001F558(spu_context* ctx) {
    ctx->pc = 0x1F558u; spu_indirect_branch(ctx);
}
void spu_job_0145F400_spu_func_0001F57C(spu_context* ctx) {
    ctx->pc = 0x1F57Cu; spu_indirect_branch(ctx);
}
void spu_job_0145F400_spu_func_0001F598(spu_context* ctx) {
    ctx->pc = 0x1F598u; spu_indirect_branch(ctx);
}
void spu_job_0145F400_spu_func_0001F5B8(spu_context* ctx) {
    ctx->pc = 0x1F5B8u; spu_indirect_branch(ctx);
}
void spu_job_0145F400_spu_func_0001F5E0(spu_context* ctx) {
    ctx->pc = 0x1F5E0u; spu_indirect_branch(ctx);
}
void spu_job_0145F400_spu_func_0001F690(spu_context* ctx) {
    ctx->pc = 0x1F690u; spu_indirect_branch(ctx);
}
void spu_job_0145F400_spu_func_0001F6B8(spu_context* ctx) {
    ctx->pc = 0x1F6B8u; spu_indirect_branch(ctx);
}
void spu_job_0145F400_spu_func_0001F6E8(spu_context* ctx) {
    ctx->pc = 0x1F6E8u; spu_indirect_branch(ctx);
}
void spu_job_0145F400_spu_func_0001F728(spu_context* ctx) {
    ctx->pc = 0x1F728u; spu_indirect_branch(ctx);
}
void spu_job_0145F400_spu_func_0001F73C(spu_context* ctx) {
    ctx->pc = 0x1F73Cu; spu_indirect_branch(ctx);
}
void spu_job_0145F400_spu_func_0001F764(spu_context* ctx) {
    ctx->pc = 0x1F764u; spu_indirect_branch(ctx);
}
void spu_job_0145F400_spu_func_00021B48(spu_context* ctx) {
    ctx->pc = 0x21B48u; spu_indirect_branch(ctx);
}

/* Function table */
typedef struct { uint32_t addr; void (*func)(spu_context*); const char* name; } spu_func_entry;
static const spu_func_entry spu_function_table[] = {
    { 0x0145F400u, spu_job_0145F400_spu_func_0145F400, "spu_job_0145F400_spu_func_0145F400" },
    { 0x0145F418u, spu_job_0145F400_spu_func_0145F418, "spu_job_0145F400_spu_func_0145F418" },
    { 0x0145F430u, spu_job_0145F400_spu_func_0145F430, "spu_job_0145F400_spu_func_0145F430" },
    { 0x0145F4B8u, spu_job_0145F400_spu_func_0145F4B8, "spu_job_0145F400_spu_func_0145F4B8" },
    { 0x0145F52Cu, spu_job_0145F400_spu_func_0145F52C, "spu_job_0145F400_spu_func_0145F52C" },
    { 0x0145F558u, spu_job_0145F400_spu_func_0145F558, "spu_job_0145F400_spu_func_0145F558" },
    { 0x0145F57Cu, spu_job_0145F400_spu_func_0145F57C, "spu_job_0145F400_spu_func_0145F57C" },
    { 0x0145F598u, spu_job_0145F400_spu_func_0145F598, "spu_job_0145F400_spu_func_0145F598" },
    { 0x0145F5B8u, spu_job_0145F400_spu_func_0145F5B8, "spu_job_0145F400_spu_func_0145F5B8" },
    { 0x0145F5E0u, spu_job_0145F400_spu_func_0145F5E0, "spu_job_0145F400_spu_func_0145F5E0" },
    { 0x0145F690u, spu_job_0145F400_spu_func_0145F690, "spu_job_0145F400_spu_func_0145F690" },
    { 0x0145F6B8u, spu_job_0145F400_spu_func_0145F6B8, "spu_job_0145F400_spu_func_0145F6B8" },
    { 0x0145F6E8u, spu_job_0145F400_spu_func_0145F6E8, "spu_job_0145F400_spu_func_0145F6E8" },
    { 0x0145F728u, spu_job_0145F400_spu_func_0145F728, "spu_job_0145F400_spu_func_0145F728" },
    { 0x0145F73Cu, spu_job_0145F400_spu_func_0145F73C, "spu_job_0145F400_spu_func_0145F73C" },
    { 0, NULL, NULL }
};

void spu_job_0145F400_spu_recomp_register(void) {
    for (const spu_func_entry* e = spu_function_table; e->func; ++e)
        spu_register_function(e->addr, e->func);
}
