/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#include "spu_recomp.h"
#include "../../runtime/spu/spu_helpers.h"


void spu_job_01339880_spu_func_01339880(spu_context* ctx) {
        ctx->gpr[2] = spu_ila(0x1329C);
        ctx->gpr[2] = spu_ila(0x1B339);
        ctx->gpr[2] = spu_ila(0x3AD92);
        ctx->gpr[2] = spu_ila(0x20FAB);
        ctx->gpr[80] = spu_xori(ctx->gpr[80], 4);
        { ctx->pc = 0x39898; SPU_TAILCALL(spu_job_01339880_spu_func_00039898(ctx)); }
}

void spu_job_01339880_spu_func_01339898(spu_context* ctx) {
        ctx->gpr[80] = spu_xori(ctx->gpr[80], 4);
        { ctx->pc = 0x398B0; SPU_TAILCALL(spu_job_01339880_spu_func_000398B0(ctx)); }
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
}

void spu_job_01339880_spu_func_013398B0(spu_context* ctx) {
        ctx->gpr[2] = spu_ori(ctx->gpr[3], 0);
        ctx->gpr[3] = spu_ai(ctx->gpr[4], 48);
        ctx->gpr[4] = spu_ls_read128(ctx, ctx->gpr[2]._u32[0] + 0x20);
        ctx->gpr[4] = spu_rotqby(ctx->gpr[4], ctx->gpr[2]);
        { ctx->pc = 0x3D1E8; SPU_TAILCALL(spu_job_01339880_spu_func_0003D1E8(ctx)); }
        /* nop */;
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        /* nop */;
        ctx->gpr[16] = spu_a(ctx->gpr[4], ctx->gpr[5]);
        ctx->gpr[15] = spu_shlqbyi(ctx->gpr[4], 0);
        ctx->gpr[2] = spu_clgt(ctx->gpr[16], ctx->gpr[4]);
        if (ctx->gpr[2]._u32[0] == 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        ctx->gpr[14] = spu_ori(ctx->gpr[3], 0);
        /* branch hint (ignored) */;
        { ctx->pc = 0x13398E8; SPU_TAILCALL(spu_job_01339880_spu_func_013398E8(ctx)); }
}

void spu_job_01339880_spu_func_013398E8(spu_context* ctx) {
        ctx->gpr[22] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0x0);
        ctx->gpr[21] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0x10);
        ctx->gpr[20] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0x20);
        ctx->gpr[19] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0x30);
        ctx->gpr[18] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0x40);
        ctx->gpr[17] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0x50);
        ctx->gpr[10] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0x60);
        ctx->gpr[12] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0x70);
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0x0, ctx->gpr[22]);
        ctx->gpr[13] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0x80);
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0x10, ctx->gpr[21]);
        ctx->gpr[11] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0x90);
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0x20, ctx->gpr[20]);
        ctx->gpr[9] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0xA0);
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0x30, ctx->gpr[19]);
        ctx->gpr[7] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0xB0);
        /* branch hint (ignored) */;
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0x40, ctx->gpr[18]);
        ctx->gpr[5] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0xC0);
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0x50, ctx->gpr[17]);
        ctx->gpr[4] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0xD0);
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0x60, ctx->gpr[10]);
        ctx->gpr[8] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0xE0);
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0x70, ctx->gpr[12]);
        ctx->gpr[6] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0xF0);
        ctx->gpr[15] = spu_ai(ctx->gpr[15], 256);
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0x80, ctx->gpr[13]);
        ctx->gpr[3] = spu_clgt(ctx->gpr[16], ctx->gpr[15]);
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0x90, ctx->gpr[11]);
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0xA0, ctx->gpr[9]);
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0xB0, ctx->gpr[7]);
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0xC0, ctx->gpr[5]);
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0xD0, ctx->gpr[4]);
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0xE0, ctx->gpr[8]);
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0xF0, ctx->gpr[6]);
        ctx->gpr[14] = spu_ai(ctx->gpr[14], 256);
        if (ctx->gpr[3]._u32[0] != 0) { ctx->pc = 0x398E8; SPU_TAILCALL(spu_job_01339880_spu_func_000398E8(ctx)); }
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        /* nop */;
        { ctx->pc = 0x1339988; SPU_TAILCALL(spu_job_01339880_spu_func_01339988(ctx)); }
}

void spu_job_01339880_spu_func_01339988(spu_context* ctx) {
        ctx->gpr[8] = spu_ila(0xFFFF);
        /* branch hint (ignored) */;
        ctx->gpr[7] = spu_ceqi(ctx->gpr[3], 1);
        ctx->gpr[6] = spu_ceq(ctx->gpr[4], ctx->gpr[8]);
        ctx->gpr[11] = spu_ila(0x120);
        ctx->gpr[10] = spu_link(0x13399A0); spu_host_call_push(ctx, 0x13399A0); spu_job_01339880_spu_func_000399A0(ctx); spu_host_call_pop(ctx);
        { ctx->pc = 0x13399A0; SPU_TAILCALL(spu_job_01339880_spu_func_013399A0(ctx)); }
}

void spu_job_01339880_spu_func_013399A0(spu_context* ctx) {
        ctx->gpr[2] = spu_nor(ctx->gpr[7], ctx->gpr[7]);
        ctx->gpr[5] = spu_nor(ctx->gpr[6], ctx->gpr[6]);
        ctx->gpr[3] = spu_ila(0x76A0);
        ctx->gpr[79] = spu_sf(ctx->gpr[11], ctx->gpr[10]);
        ctx->gpr[4] = spu_or(ctx->gpr[2], ctx->gpr[5]);
        ctx->gpr[3] = spu_a(ctx->gpr[3], ctx->gpr[79]);
        if (ctx->gpr[4]._u32[0] != 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        { ctx->pc = 0x3E1D0; SPU_TAILCALL(spu_job_01339880_spu_func_0003E1D0(ctx)); }
        ctx->gpr[3] = spu_il(1);
        /* nop */;
        ctx->gpr[4] = spu_ila(0xFFFF);
        { ctx->pc = 0x39988; SPU_TAILCALL(spu_job_01339880_spu_func_00039988(ctx)); }
}

void spu_job_01339880_spu_func_013399D0(spu_context* ctx) {
        ctx->gpr[2] = spu_il(0);
        ctx->gpr[4] = spu_shlqbyi(ctx->gpr[3], 0);
        spu_wrch(ctx, MFC_WrTagUpdate, ctx->gpr[2]);
        { ctx->pc = 0x13399DC; SPU_TAILCALL(spu_job_01339880_spu_func_013399DC(ctx)); }
}

void spu_job_01339880_spu_func_013399DC(spu_context* ctx) {
        ctx->gpr[2] = spu_pref_u32(spu_rchcnt(ctx, MFC_WrTagUpdate));
        ctx->gpr[3] = spu_ceqi(ctx->gpr[2], 1);
        if (ctx->gpr[3]._u32[0] == 0) { ctx->pc = 0x399DC; SPU_TAILCALL(spu_job_01339880_spu_func_000399DC(ctx)); }
        /* nop */;
        /* branch hint (ignored) */;
        ctx->gpr[5] = spu_shl(ctx->gpr[2], ctx->gpr[4]);
        ctx->gpr[3] = spu_rdch(ctx, MFC_RdTagStat);
        ctx->gpr[4] = spu_il(2);
        /* nop */;
        /* nop */;
        spu_wrch(ctx, MFC_WrTagMask, ctx->gpr[5]);
        spu_wrch(ctx, MFC_WrTagUpdate, ctx->gpr[4]);
        ctx->gpr[2] = spu_rdch(ctx, MFC_RdTagStat);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        /* nop */;
        { ctx->pc = 0x1339A18; SPU_TAILCALL(spu_job_01339880_spu_func_01339A18(ctx)); }
}

void spu_job_01339880_spu_func_01339A18(spu_context* ctx) {
        ctx->gpr[9] = spu_ceqi(ctx->gpr[4], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x50, ctx->gpr[84]);
        ctx->gpr[8] = spu_ceqi(ctx->gpr[5], 0);
        ctx->gpr[84] = spu_shlqbyi(ctx->gpr[4], 0);
        ctx->gpr[7] = spu_sfi(ctx->gpr[9], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x40, ctx->gpr[83]);
        ctx->gpr[4] = spu_sfi(ctx->gpr[8], 0);
        ctx->gpr[83] = spu_shlqbyi(ctx->gpr[5], 0);
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x80, ctx->gpr[87]);
        ctx->gpr[5] = spu_or(ctx->gpr[7], ctx->gpr[4]);
        ctx->gpr[87] = spu_shlqbyi(ctx->gpr[3], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x60, ctx->gpr[85]);
        ctx->gpr[3] = spu_ceqbi(ctx->gpr[5], 0);
        ctx->gpr[85] = spu_ori(ctx->gpr[6], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + 0x10, ctx->gpr[0]);
        ctx->gpr[2] = spu_xsbh(ctx->gpr[3]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x10, ctx->gpr[80]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x20, ctx->gpr[81]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x30, ctx->gpr[82]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x70, ctx->gpr[86]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x90, ctx->gpr[88]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xA0, ctx->gpr[89]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xB0, ctx->gpr[90]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xC0, ctx->gpr[91]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xD0, ctx->gpr[126]);
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xF0, ctx->gpr[1]);
        ctx->gpr[1] = spu_ai(ctx->gpr[1], -240);
        if (ctx->gpr[2]._u16[1] == 0) { ctx->pc = 0x39B3C; SPU_TAILCALL(spu_job_01339880_spu_func_00039B3C(ctx)); }
        ctx->gpr[6] = spu_cgti(ctx->gpr[6], 0);
        if (ctx->gpr[6]._u32[0] == 0) { ctx->pc = 0x39B3C; SPU_TAILCALL(spu_job_01339880_spu_func_00039B3C(ctx)); }
        ctx->gpr[88] = spu_ori(ctx->gpr[87], 0);
        /* branch hint (ignored) */;
        ctx->gpr[86] = spu_il(0);
        ctx->gpr[90] = spu_fsmbi(0x0);
        ctx->gpr[91] = spu_il(16383);
        ctx->gpr[89] = spu_il(32);
        { ctx->pc = 0x1339AB0; SPU_TAILCALL(spu_job_01339880_spu_func_01339AB0(ctx)); }
}

void spu_job_01339880_spu_func_01339AB0(spu_context* ctx) {
        ctx->gpr[20] = spu_sf(ctx->gpr[86], ctx->gpr[85]);
        ctx->gpr[3] = spu_shlqbyi(ctx->gpr[87], 0);
        ctx->gpr[13] = spu_il(16384);
        ctx->gpr[28] = spu_ai(ctx->gpr[20], 3);
        ctx->gpr[27] = spu_ai(ctx->gpr[20], 7);
        ctx->gpr[25] = spu_cgti(ctx->gpr[20], 4);
        ctx->gpr[23] = spu_andi(ctx->gpr[28], -4);
        ctx->gpr[24] = spu_andi(ctx->gpr[27], -8);
        ctx->gpr[26] = spu_ai(ctx->gpr[20], 15);
        ctx->gpr[22] = spu_ceqi(ctx->gpr[25], 0);
        ctx->gpr[21] = spu_cgti(ctx->gpr[20], 8);
        ctx->gpr[19] = spu_andi(ctx->gpr[26], -16);
        ctx->gpr[17] = spu_selb(ctx->gpr[24], ctx->gpr[23], ctx->gpr[22]);
        ctx->gpr[18] = spu_ceqi(ctx->gpr[21], 0);
        ctx->gpr[16] = spu_cgt(ctx->gpr[20], ctx->gpr[91]);
        ctx->gpr[15] = spu_selb(ctx->gpr[19], ctx->gpr[17], ctx->gpr[18]);
        ctx->gpr[14] = spu_ceqi(ctx->gpr[16], 0);
        /* nop */;
        ctx->gpr[81] = spu_selb(ctx->gpr[13], ctx->gpr[15], ctx->gpr[14]);
        ctx->gpr[0] = spu_link(0x1339B00); spu_host_call_push(ctx, 0x1339B00); spu_job_01339880_spu_func_000399D0(ctx); spu_host_call_pop(ctx);
        ctx->gpr[12] = spu_ori(ctx->gpr[83], 0);
        /* branch hint (ignored) */;
        ctx->gpr[11] = spu_ori(ctx->gpr[84], 0);
        ctx->gpr[80] = spu_shlqbyi(ctx->gpr[81], 0);
        ctx->gpr[86] = spu_a(ctx->gpr[86], ctx->gpr[81]);
        spu_wrch(ctx, MFC_LSA, ctx->gpr[12]);
        ctx->gpr[83] = spu_a(ctx->gpr[83], ctx->gpr[81]);
        spu_wrch(ctx, MFC_EAH, ctx->gpr[90]);
        ctx->gpr[10] = spu_cgt(ctx->gpr[85], ctx->gpr[86]);
        spu_wrch(ctx, MFC_EAL, ctx->gpr[11]);
        ctx->gpr[84] = spu_a(ctx->gpr[84], ctx->gpr[81]);
        spu_wrch(ctx, MFC_Size, ctx->gpr[80]);
        spu_wrch(ctx, MFC_TagID, ctx->gpr[88]);
        spu_wrch(ctx, MFC_Cmd, ctx->gpr[89]);
        if (ctx->gpr[10]._u32[0] != 0) { ctx->pc = 0x39AB0; SPU_TAILCALL(spu_job_01339880_spu_func_00039AB0(ctx)); }
        { ctx->pc = 0x1339B3C; SPU_TAILCALL(spu_job_01339880_spu_func_01339B3C(ctx)); }
}

void spu_job_01339880_spu_func_01339B3C(spu_context* ctx) {
        ctx->gpr[0] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + 0x100);
        ctx->gpr[1] = spu_ai(ctx->gpr[1], 240);
        ctx->gpr[80] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x10);
        ctx->gpr[81] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x20);
        ctx->gpr[82] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x30);
        /* branch hint (ignored) */;
        ctx->gpr[83] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x40);
        ctx->gpr[84] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x50);
        ctx->gpr[85] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x60);
        ctx->gpr[86] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x70);
        ctx->gpr[87] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x80);
        ctx->gpr[88] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x90);
        ctx->gpr[89] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0xA0);
        ctx->gpr[90] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0xB0);
        ctx->gpr[91] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0xC0);
        ctx->gpr[126] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0xD0);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        ctx->gpr[9] = spu_ceqi(ctx->gpr[4], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x50, ctx->gpr[84]);
        ctx->gpr[8] = spu_ceqi(ctx->gpr[5], 0);
        ctx->gpr[84] = spu_shlqbyi(ctx->gpr[4], 0);
        ctx->gpr[7] = spu_sfi(ctx->gpr[9], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x40, ctx->gpr[83]);
        ctx->gpr[4] = spu_sfi(ctx->gpr[8], 0);
        ctx->gpr[83] = spu_shlqbyi(ctx->gpr[5], 0);
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x80, ctx->gpr[87]);
        ctx->gpr[5] = spu_or(ctx->gpr[7], ctx->gpr[4]);
        ctx->gpr[87] = spu_shlqbyi(ctx->gpr[3], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x60, ctx->gpr[85]);
        ctx->gpr[3] = spu_ceqbi(ctx->gpr[5], 0);
        ctx->gpr[85] = spu_ori(ctx->gpr[6], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + 0x10, ctx->gpr[0]);
        ctx->gpr[2] = spu_xsbh(ctx->gpr[3]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x10, ctx->gpr[80]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x20, ctx->gpr[81]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x30, ctx->gpr[82]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x70, ctx->gpr[86]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x90, ctx->gpr[88]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xA0, ctx->gpr[89]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xB0, ctx->gpr[90]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xC0, ctx->gpr[91]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xD0, ctx->gpr[126]);
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xF0, ctx->gpr[1]);
        ctx->gpr[1] = spu_ai(ctx->gpr[1], -240);
        if (ctx->gpr[2]._u16[1] == 0) { ctx->pc = 0x39CA4; SPU_TAILCALL(spu_job_01339880_spu_func_00039CA4(ctx)); }
        ctx->gpr[6] = spu_cgti(ctx->gpr[6], 0);
        if (ctx->gpr[6]._u32[0] == 0) { ctx->pc = 0x39CA4; SPU_TAILCALL(spu_job_01339880_spu_func_00039CA4(ctx)); }
        ctx->gpr[88] = spu_ori(ctx->gpr[87], 0);
        /* branch hint (ignored) */;
        ctx->gpr[86] = spu_il(0);
        ctx->gpr[90] = spu_fsmbi(0x0);
        ctx->gpr[91] = spu_il(16383);
        ctx->gpr[89] = spu_il(64);
        { ctx->pc = 0x1339C18; SPU_TAILCALL(spu_job_01339880_spu_func_01339C18(ctx)); }
}

void spu_job_01339880_spu_func_01339C18(spu_context* ctx) {
        ctx->gpr[20] = spu_sf(ctx->gpr[86], ctx->gpr[85]);
        ctx->gpr[3] = spu_shlqbyi(ctx->gpr[87], 0);
        ctx->gpr[13] = spu_il(16384);
        ctx->gpr[28] = spu_ai(ctx->gpr[20], 3);
        ctx->gpr[27] = spu_ai(ctx->gpr[20], 7);
        ctx->gpr[25] = spu_cgti(ctx->gpr[20], 4);
        ctx->gpr[23] = spu_andi(ctx->gpr[28], -4);
        ctx->gpr[24] = spu_andi(ctx->gpr[27], -8);
        ctx->gpr[26] = spu_ai(ctx->gpr[20], 15);
        ctx->gpr[22] = spu_ceqi(ctx->gpr[25], 0);
        ctx->gpr[21] = spu_cgti(ctx->gpr[20], 8);
        ctx->gpr[19] = spu_andi(ctx->gpr[26], -16);
        ctx->gpr[17] = spu_selb(ctx->gpr[24], ctx->gpr[23], ctx->gpr[22]);
        ctx->gpr[18] = spu_ceqi(ctx->gpr[21], 0);
        ctx->gpr[16] = spu_cgt(ctx->gpr[20], ctx->gpr[91]);
        ctx->gpr[15] = spu_selb(ctx->gpr[19], ctx->gpr[17], ctx->gpr[18]);
        ctx->gpr[14] = spu_ceqi(ctx->gpr[16], 0);
        /* nop */;
        ctx->gpr[81] = spu_selb(ctx->gpr[13], ctx->gpr[15], ctx->gpr[14]);
        ctx->gpr[0] = spu_link(0x1339C68); spu_host_call_push(ctx, 0x1339C68); spu_job_01339880_spu_func_000399D0(ctx); spu_host_call_pop(ctx);
        ctx->gpr[12] = spu_ori(ctx->gpr[84], 0);
        /* branch hint (ignored) */;
        ctx->gpr[11] = spu_ori(ctx->gpr[83], 0);
        ctx->gpr[80] = spu_shlqbyi(ctx->gpr[81], 0);
        ctx->gpr[86] = spu_a(ctx->gpr[86], ctx->gpr[81]);
        spu_wrch(ctx, MFC_LSA, ctx->gpr[12]);
        ctx->gpr[83] = spu_a(ctx->gpr[83], ctx->gpr[81]);
        spu_wrch(ctx, MFC_EAH, ctx->gpr[90]);
        ctx->gpr[10] = spu_cgt(ctx->gpr[85], ctx->gpr[86]);
        spu_wrch(ctx, MFC_EAL, ctx->gpr[11]);
        ctx->gpr[84] = spu_a(ctx->gpr[84], ctx->gpr[81]);
        spu_wrch(ctx, MFC_Size, ctx->gpr[80]);
        spu_wrch(ctx, MFC_TagID, ctx->gpr[88]);
        spu_wrch(ctx, MFC_Cmd, ctx->gpr[89]);
        if (ctx->gpr[10]._u32[0] != 0) { ctx->pc = 0x39C18; SPU_TAILCALL(spu_job_01339880_spu_func_00039C18(ctx)); }
        { ctx->pc = 0x1339CA4; SPU_TAILCALL(spu_job_01339880_spu_func_01339CA4(ctx)); }
}

void spu_job_01339880_spu_func_01339CA4(spu_context* ctx) {
        ctx->gpr[0] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + 0x100);
        ctx->gpr[1] = spu_ai(ctx->gpr[1], 240);
        ctx->gpr[80] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x10);
        ctx->gpr[81] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x20);
        ctx->gpr[82] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x30);
        /* branch hint (ignored) */;
        ctx->gpr[83] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x40);
        ctx->gpr[84] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x50);
        ctx->gpr[85] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x60);
        ctx->gpr[86] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x70);
        ctx->gpr[87] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x80);
        ctx->gpr[88] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x90);
        ctx->gpr[89] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0xA0);
        ctx->gpr[90] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0xB0);
        ctx->gpr[91] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0xC0);
        ctx->gpr[126] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0xD0);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        ctx->gpr[6] = spu_il(300);
        /* branch hint (ignored) */;
        ctx->gpr[12] = spu_ai(ctx->gpr[3], 314);
        ctx->gpr[5] = spu_shlqbyi(ctx->gpr[3], 0);
        ctx->gpr[11] = spu_ls_read128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[6]._u32[0]);
        ctx->gpr[6] = spu_il(0);
        ctx->gpr[10] = spu_rotqby(ctx->gpr[11], ctx->gpr[12]);
        ctx->gpr[7] = spu_xshw(ctx->gpr[10]);
        ctx->gpr[9] = spu_cgt(ctx->gpr[7], ctx->gpr[4]);
        ctx->gpr[7] = spu_selb(ctx->gpr[7], ctx->gpr[4], ctx->gpr[9]);
        ctx->gpr[8] = spu_cgti(ctx->gpr[7], 0);
        ctx->gpr[4] = spu_sfi(ctx->gpr[8], 0);
        ctx->gpr[3] = spu_ceqbi(ctx->gpr[4], 0);
        ctx->gpr[2] = spu_xsbh(ctx->gpr[3]);
        /* nop */;
        if (ctx->gpr[2]._u16[1] != 0) { ctx->pc = 0x39D64; SPU_TAILCALL(spu_job_01339880_spu_func_00039D64(ctx)); }
        ctx->gpr[4] = spu_ori(ctx->gpr[5], 0);
        ctx->gpr[5] = spu_fsmbi(0x0);
        { ctx->pc = 0x1339D30; SPU_TAILCALL(spu_job_01339880_spu_func_01339D30(ctx)); }
}

void spu_job_01339880_spu_func_01339D30(spu_context* ctx) {
        ctx->gpr[5] = spu_ai(ctx->gpr[5], 1);
        ctx->gpr[15] = spu_ls_read128(ctx, ctx->gpr[4]._u32[0] + 0x0);
        ctx->gpr[13] = spu_cgt(ctx->gpr[7], ctx->gpr[5]);
        ctx->gpr[14] = spu_rotqby(ctx->gpr[15], ctx->gpr[4]);
        ctx->gpr[4] = spu_ai(ctx->gpr[4], 4);
        ctx->gpr[6] = spu_fa(ctx->gpr[6], ctx->gpr[14]);
        if (ctx->gpr[13]._u32[0] != 0) { ctx->pc = 0x39D30; SPU_TAILCALL(spu_job_01339880_spu_func_00039D30(ctx)); }
        ctx->gpr[18] = spu_csflt(ctx->gpr[7], 155);
        ctx->gpr[19] = spu_frest(ctx->gpr[18]);
        ctx->gpr[17] = spu_fi(ctx->gpr[18], ctx->gpr[19]);
        ctx->gpr[16] = spu_fm(ctx->gpr[6], ctx->gpr[17]);
        ctx->gpr[5] = spu_fnms(ctx->gpr[16], ctx->gpr[18], ctx->gpr[6]);
        ctx->gpr[6] = spu_fma(ctx->gpr[5], ctx->gpr[17], ctx->gpr[16]);
        { ctx->pc = 0x1339D64; SPU_TAILCALL(spu_job_01339880_spu_func_01339D64(ctx)); }
}

void spu_job_01339880_spu_func_01339D64(spu_context* ctx) {
        ctx->gpr[3] = spu_ori(ctx->gpr[6], 0);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        /* nop */;
        ctx->gpr[7] = spu_il(148);
        /* branch hint (ignored) */;
        ctx->gpr[12] = spu_ai(ctx->gpr[3], 162);
        ctx->gpr[5] = spu_shlqbyi(ctx->gpr[3], 0);
        ctx->gpr[11] = spu_ls_read128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[7]._u32[0]);
        ctx->gpr[7] = spu_il(0);
        ctx->gpr[10] = spu_rotqby(ctx->gpr[11], ctx->gpr[12]);
        ctx->gpr[6] = spu_xshw(ctx->gpr[10]);
        ctx->gpr[9] = spu_cgt(ctx->gpr[6], ctx->gpr[4]);
        ctx->gpr[6] = spu_selb(ctx->gpr[6], ctx->gpr[4], ctx->gpr[9]);
        ctx->gpr[8] = spu_cgti(ctx->gpr[6], 0);
        ctx->gpr[4] = spu_sfi(ctx->gpr[8], 0);
        ctx->gpr[3] = spu_ceqbi(ctx->gpr[4], 0);
        ctx->gpr[2] = spu_xsbh(ctx->gpr[3]);
        /* nop */;
        if (ctx->gpr[2]._u16[1] != 0) { ctx->pc = 0x39DEC; SPU_TAILCALL(spu_job_01339880_spu_func_00039DEC(ctx)); }
        ctx->gpr[4] = spu_ori(ctx->gpr[5], 0);
        ctx->gpr[5] = spu_fsmbi(0x0);
        { ctx->pc = 0x1339DB8; SPU_TAILCALL(spu_job_01339880_spu_func_01339DB8(ctx)); }
}

void spu_job_01339880_spu_func_01339DB8(spu_context* ctx) {
        ctx->gpr[5] = spu_ai(ctx->gpr[5], 1);
        ctx->gpr[15] = spu_ls_read128(ctx, ctx->gpr[4]._u32[0] + 0x0);
        ctx->gpr[13] = spu_cgt(ctx->gpr[6], ctx->gpr[5]);
        ctx->gpr[14] = spu_rotqby(ctx->gpr[15], ctx->gpr[4]);
        ctx->gpr[4] = spu_ai(ctx->gpr[4], 4);
        ctx->gpr[7] = spu_fa(ctx->gpr[7], ctx->gpr[14]);
        if (ctx->gpr[13]._u32[0] != 0) { ctx->pc = 0x39DB8; SPU_TAILCALL(spu_job_01339880_spu_func_00039DB8(ctx)); }
        ctx->gpr[18] = spu_csflt(ctx->gpr[6], 155);
        ctx->gpr[19] = spu_frest(ctx->gpr[18]);
        ctx->gpr[17] = spu_fi(ctx->gpr[18], ctx->gpr[19]);
        ctx->gpr[16] = spu_fm(ctx->gpr[7], ctx->gpr[17]);
        ctx->gpr[5] = spu_fnms(ctx->gpr[16], ctx->gpr[18], ctx->gpr[7]);
        ctx->gpr[7] = spu_fma(ctx->gpr[5], ctx->gpr[17], ctx->gpr[16]);
        { ctx->pc = 0x1339DEC; SPU_TAILCALL(spu_job_01339880_spu_func_01339DEC(ctx)); }
}

void spu_job_01339880_spu_func_01339DEC(spu_context* ctx) {
        ctx->gpr[3] = spu_ori(ctx->gpr[7], 0);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        /* nop */;
        ctx->gpr[7] = spu_il(300);
        /* branch hint (ignored) */;
        ctx->gpr[5] = spu_ai(ctx->gpr[3], 314);
        ctx->gpr[8] = spu_cwd(ctx->gpr[4], 0);
        ctx->gpr[6] = spu_ori(ctx->gpr[3], 0);
        ctx->gpr[10] = spu_ls_read128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[7]._u32[0]);
        ctx->gpr[9] = spu_il(0);
        ctx->gpr[7] = spu_ori(ctx->gpr[8], 0);
        ctx->gpr[2] = spu_rotqby(ctx->gpr[10], ctx->gpr[5]);
        ctx->gpr[3] = spu_cgthi(ctx->gpr[2], 0);
        /* nop */;
        if (ctx->gpr[3]._u16[1] != 0) { ctx->pc = 0x39E40; SPU_TAILCALL(spu_job_01339880_spu_func_00039E40(ctx)); }
        ctx->gpr[11] = spu_il(0);
        ctx->gpr[8] = spu_ls_read128(ctx, ctx->gpr[4]._u32[0] + 0x0);
        ctx->gpr[6] = spu_shufb(ctx->gpr[11], ctx->gpr[8], ctx->gpr[7]);
        spu_ls_write128(ctx, ctx->gpr[4]._u32[0] + 0x0, ctx->gpr[6]);
        /* nop */;
        { ctx->pc = 0x39E58; SPU_TAILCALL(spu_job_01339880_spu_func_00039E58(ctx)); }
}

void spu_job_01339880_spu_func_01339E40(spu_context* ctx) {
        ctx->gpr[9] = spu_il(1);
        ctx->gpr[15] = spu_ls_read128(ctx, ctx->gpr[6]._u32[0] + 0x0);
        ctx->gpr[13] = spu_ls_read128(ctx, ctx->gpr[4]._u32[0] + 0x0);
        ctx->gpr[14] = spu_rotqby(ctx->gpr[15], ctx->gpr[6]);
        ctx->gpr[12] = spu_shufb(ctx->gpr[14], ctx->gpr[13], ctx->gpr[8]);
        spu_ls_write128(ctx, ctx->gpr[4]._u32[0] + 0x0, ctx->gpr[12]);
        { ctx->pc = 0x1339E58; SPU_TAILCALL(spu_job_01339880_spu_func_01339E58(ctx)); }
}

void spu_job_01339880_spu_func_01339E58(spu_context* ctx) {
        ctx->gpr[3] = spu_ori(ctx->gpr[9], 0);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        ctx->gpr[7] = spu_ila(0x6F40);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x10, ctx->gpr[126]);
        ctx->gpr[8] = spu_ila(0x5F0);
        ctx->gpr[126] = spu_link(0x1339E70); spu_host_call_push(ctx, 0x1339E70); spu_job_01339880_spu_func_00039E70(ctx); spu_host_call_pop(ctx);
        { ctx->pc = 0x1339E70; SPU_TAILCALL(spu_job_01339880_spu_func_01339E70(ctx)); }
}

void spu_job_01339880_spu_func_01339E70(spu_context* ctx) {
        ctx->gpr[9] = spu_ila(0xFFFF);
        /* branch hint (ignored) */;
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + 0x10, ctx->gpr[0]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x30, ctx->gpr[1]);
        ctx->gpr[126] = spu_sf(ctx->gpr[8], ctx->gpr[126]);
        ctx->gpr[8] = spu_shlqbyi(ctx->gpr[3], 0);
        ctx->gpr[1] = spu_ai(ctx->gpr[1], -48);
        ctx->gpr[7] = spu_a(ctx->gpr[7], ctx->gpr[126]);
        ctx->gpr[11] = spu_andi(ctx->gpr[7], 15);
        ctx->gpr[5] = spu_sf(ctx->gpr[11], ctx->gpr[7]);
        ctx->gpr[10] = spu_sfi(ctx->gpr[11], 0);
        ctx->gpr[6] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + 0x0);
        ctx->gpr[3] = spu_rotm(ctx->gpr[9], ctx->gpr[10]);
        ctx->gpr[5] = spu_ai(ctx->gpr[5], 16);
        ctx->gpr[4] = spu_ceqbi(ctx->gpr[6], 0);
        ctx->gpr[2] = spu_gbb(ctx->gpr[4]);
        ctx->gpr[2] = spu_and(ctx->gpr[2], ctx->gpr[3]);
        { ctx->pc = 0x39EE0; SPU_TAILCALL(spu_job_01339880_spu_func_00039EE0(ctx)); }
}

void spu_job_01339880_spu_func_01339EB8(spu_context* ctx) {
        /* branch hint (ignored) */;
        ctx->gpr[18] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + 0x0);
        ctx->gpr[17] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + 0x10);
        ctx->gpr[5] = spu_ai(ctx->gpr[5], 32);
        ctx->gpr[16] = spu_ceqbi(ctx->gpr[18], 0);
        ctx->gpr[14] = spu_ceqbi(ctx->gpr[17], 0);
        ctx->gpr[15] = spu_gbb(ctx->gpr[16]);
        ctx->gpr[13] = spu_gbb(ctx->gpr[14]);
        ctx->gpr[12] = spu_shli(ctx->gpr[15], 16);
        ctx->gpr[2] = spu_or(ctx->gpr[12], ctx->gpr[13]);
        { ctx->pc = 0x1339EE0; SPU_TAILCALL(spu_job_01339880_spu_func_01339EE0(ctx)); }
}

void spu_job_01339880_spu_func_01339EE0(spu_context* ctx) {
        /* nop */;
        if (ctx->gpr[2]._u32[0] == 0) { ctx->pc = 0x39EB8; SPU_TAILCALL(spu_job_01339880_spu_func_00039EB8(ctx)); }
        ctx->gpr[24] = spu_ori(ctx->gpr[2], 0);
        /* branch hint (ignored) */;
        ctx->gpr[23] = spu_sf(ctx->gpr[7], ctx->gpr[5]);
        ctx->gpr[4] = spu_shlqbyi(ctx->gpr[8], 0);
        ctx->gpr[22] = spu_clz(ctx->gpr[24]);
        ctx->gpr[19] = spu_ila(0x6F40);
        ctx->gpr[21] = spu_a(ctx->gpr[22], ctx->gpr[23]);
        ctx->gpr[3] = spu_il(2);
        ctx->gpr[20] = spu_ai(ctx->gpr[21], -16);
        ctx->gpr[5] = spu_a(ctx->gpr[19], ctx->gpr[126]);
        ctx->gpr[6] = spu_andi(ctx->gpr[20], -16);
        ctx->gpr[0] = spu_link(0x1339F18); spu_host_call_push(ctx, 0x1339F18); spu_job_01339880_spu_func_00039A18(ctx); spu_host_call_pop(ctx);
        ctx->gpr[3] = spu_il(2);
        ctx->gpr[0] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + 0x40);
        ctx->gpr[1] = spu_ai(ctx->gpr[1], 48);
        ctx->gpr[126] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x10);
        { ctx->pc = 0x399D0; SPU_TAILCALL(spu_job_01339880_spu_func_000399D0(ctx)); }
        /* nop */;
        ctx->gpr[2] = spu_il(0);
        /* branch hint (ignored) */;
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + 0xB0, ctx->gpr[2]);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + 0x0, ctx->gpr[2]);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + 0x10, ctx->gpr[2]);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + 0x20, ctx->gpr[2]);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + 0x30, ctx->gpr[2]);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + 0x40, ctx->gpr[2]);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + 0x50, ctx->gpr[2]);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + 0x60, ctx->gpr[2]);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + 0x70, ctx->gpr[2]);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + 0x80, ctx->gpr[2]);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + 0x90, ctx->gpr[2]);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + 0xA0, ctx->gpr[2]);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        /* nop */;
        ctx->gpr[9] = spu_ori(ctx->gpr[3], 0);
        ctx->gpr[3] = spu_fsmbi(0x0);
        ctx->gpr[8] = spu_ori(ctx->gpr[5], 0);
        ctx->gpr[2] = spu_fceq(ctx->gpr[7], ctx->gpr[3]);
        /* nop */;
        if (ctx->gpr[2]._u32[0] != 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        ctx->gpr[5] = spu_shli(ctx->gpr[6], 10);
        /* branch hint (ignored) */;
        ctx->gpr[4] = spu_shli(ctx->gpr[4], 10);
        ctx->gpr[11] = spu_ilhu(0x3F80);
        ctx->gpr[6] = spu_ila(0x10203);
        ctx->gpr[10] = spu_fceq(ctx->gpr[7], ctx->gpr[11]);
        ctx->gpr[5] = spu_a(ctx->gpr[5], ctx->gpr[8]);
        ctx->gpr[7] = spu_shufb(ctx->gpr[7], ctx->gpr[7], ctx->gpr[6]);
        ctx->gpr[4] = spu_a(ctx->gpr[4], ctx->gpr[9]);
        ctx->gpr[8] = spu_fsmbi(0x0);
        ctx->gpr[6] = spu_il(1024);
        if (ctx->gpr[10]._u32[0] == 0) { ctx->pc = 0x39FDC; SPU_TAILCALL(spu_job_01339880_spu_func_00039FDC(ctx)); }
        ctx->gpr[7] = spu_il(0);
        { ctx->pc = 0x1339FBC; SPU_TAILCALL(spu_job_01339880_spu_func_01339FBC(ctx)); }
}

void spu_job_01339880_spu_func_01339FBC(spu_context* ctx) {
        ctx->gpr[12] = spu_ls_read128(ctx, ctx->gpr[7]._u32[0] + ctx->gpr[4]._u32[0]);
        ctx->gpr[13] = spu_ls_read128(ctx, ctx->gpr[7]._u32[0] + ctx->gpr[5]._u32[0]);
        ctx->gpr[9] = spu_fa(ctx->gpr[12], ctx->gpr[13]);
        spu_ls_write128(ctx, ctx->gpr[7]._u32[0] + ctx->gpr[4]._u32[0], ctx->gpr[9]);
        ctx->gpr[7] = spu_ai(ctx->gpr[7], 16);
        ctx->gpr[8] = spu_ceq(ctx->gpr[7], ctx->gpr[6]);
        if (ctx->gpr[8]._u32[0] == 0) { ctx->pc = 0x39FBC; SPU_TAILCALL(spu_job_01339880_spu_func_00039FBC(ctx)); }
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
}

void spu_job_01339880_spu_func_01339FDC(spu_context* ctx) {
        /* branch hint (ignored) */;
        /* nop */;
        ctx->gpr[17] = spu_ls_read128(ctx, ctx->gpr[8]._u32[0] + ctx->gpr[4]._u32[0]);
        /* nop */;
        ctx->gpr[16] = spu_ls_read128(ctx, ctx->gpr[8]._u32[0] + ctx->gpr[5]._u32[0]);
        ctx->gpr[15] = spu_fma(ctx->gpr[16], ctx->gpr[7], ctx->gpr[17]);
}

/* Indirect-dispatch stubs for cross-function targets the
 * function detector did not seed (typically conditional
 * branches that escape a function's range). */
void spu_job_01339880_spu_func_00039898(spu_context* ctx) {
    ctx->pc = 0x39898u; spu_indirect_branch(ctx);
}
void spu_job_01339880_spu_func_000398B0(spu_context* ctx) {
    ctx->pc = 0x398B0u; spu_indirect_branch(ctx);
}
void spu_job_01339880_spu_func_000398E8(spu_context* ctx) {
    ctx->pc = 0x398E8u; spu_indirect_branch(ctx);
}
void spu_job_01339880_spu_func_00039988(spu_context* ctx) {
    ctx->pc = 0x39988u; spu_indirect_branch(ctx);
}
void spu_job_01339880_spu_func_000399A0(spu_context* ctx) {
    ctx->pc = 0x399A0u; spu_indirect_branch(ctx);
}
void spu_job_01339880_spu_func_000399D0(spu_context* ctx) {
    ctx->pc = 0x399D0u; spu_indirect_branch(ctx);
}
void spu_job_01339880_spu_func_000399DC(spu_context* ctx) {
    ctx->pc = 0x399DCu; spu_indirect_branch(ctx);
}
void spu_job_01339880_spu_func_00039A18(spu_context* ctx) {
    ctx->pc = 0x39A18u; spu_indirect_branch(ctx);
}
void spu_job_01339880_spu_func_00039AB0(spu_context* ctx) {
    ctx->pc = 0x39AB0u; spu_indirect_branch(ctx);
}
void spu_job_01339880_spu_func_00039B3C(spu_context* ctx) {
    ctx->pc = 0x39B3Cu; spu_indirect_branch(ctx);
}
void spu_job_01339880_spu_func_00039C18(spu_context* ctx) {
    ctx->pc = 0x39C18u; spu_indirect_branch(ctx);
}
void spu_job_01339880_spu_func_00039CA4(spu_context* ctx) {
    ctx->pc = 0x39CA4u; spu_indirect_branch(ctx);
}
void spu_job_01339880_spu_func_00039D30(spu_context* ctx) {
    ctx->pc = 0x39D30u; spu_indirect_branch(ctx);
}
void spu_job_01339880_spu_func_00039D64(spu_context* ctx) {
    ctx->pc = 0x39D64u; spu_indirect_branch(ctx);
}
void spu_job_01339880_spu_func_00039DB8(spu_context* ctx) {
    ctx->pc = 0x39DB8u; spu_indirect_branch(ctx);
}
void spu_job_01339880_spu_func_00039DEC(spu_context* ctx) {
    ctx->pc = 0x39DECu; spu_indirect_branch(ctx);
}
void spu_job_01339880_spu_func_00039E40(spu_context* ctx) {
    ctx->pc = 0x39E40u; spu_indirect_branch(ctx);
}
void spu_job_01339880_spu_func_00039E58(spu_context* ctx) {
    ctx->pc = 0x39E58u; spu_indirect_branch(ctx);
}
void spu_job_01339880_spu_func_00039E70(spu_context* ctx) {
    ctx->pc = 0x39E70u; spu_indirect_branch(ctx);
}
void spu_job_01339880_spu_func_00039EB8(spu_context* ctx) {
    ctx->pc = 0x39EB8u; spu_indirect_branch(ctx);
}
void spu_job_01339880_spu_func_00039EE0(spu_context* ctx) {
    ctx->pc = 0x39EE0u; spu_indirect_branch(ctx);
}
void spu_job_01339880_spu_func_00039FBC(spu_context* ctx) {
    ctx->pc = 0x39FBCu; spu_indirect_branch(ctx);
}
void spu_job_01339880_spu_func_00039FDC(spu_context* ctx) {
    ctx->pc = 0x39FDCu; spu_indirect_branch(ctx);
}
void spu_job_01339880_spu_func_0003D1E8(spu_context* ctx) {
    ctx->pc = 0x3D1E8u; spu_indirect_branch(ctx);
}
void spu_job_01339880_spu_func_0003E1D0(spu_context* ctx) {
    ctx->pc = 0x3E1D0u; spu_indirect_branch(ctx);
}

/* Function table */
typedef struct { uint32_t addr; void (*func)(spu_context*); const char* name; } spu_func_entry;
static const spu_func_entry spu_function_table[] = {
    { 0x01339880u, spu_job_01339880_spu_func_01339880, "spu_job_01339880_spu_func_01339880" },
    { 0x01339898u, spu_job_01339880_spu_func_01339898, "spu_job_01339880_spu_func_01339898" },
    { 0x013398B0u, spu_job_01339880_spu_func_013398B0, "spu_job_01339880_spu_func_013398B0" },
    { 0x013398E8u, spu_job_01339880_spu_func_013398E8, "spu_job_01339880_spu_func_013398E8" },
    { 0x01339988u, spu_job_01339880_spu_func_01339988, "spu_job_01339880_spu_func_01339988" },
    { 0x013399A0u, spu_job_01339880_spu_func_013399A0, "spu_job_01339880_spu_func_013399A0" },
    { 0x013399D0u, spu_job_01339880_spu_func_013399D0, "spu_job_01339880_spu_func_013399D0" },
    { 0x013399DCu, spu_job_01339880_spu_func_013399DC, "spu_job_01339880_spu_func_013399DC" },
    { 0x01339A18u, spu_job_01339880_spu_func_01339A18, "spu_job_01339880_spu_func_01339A18" },
    { 0x01339AB0u, spu_job_01339880_spu_func_01339AB0, "spu_job_01339880_spu_func_01339AB0" },
    { 0x01339B3Cu, spu_job_01339880_spu_func_01339B3C, "spu_job_01339880_spu_func_01339B3C" },
    { 0x01339C18u, spu_job_01339880_spu_func_01339C18, "spu_job_01339880_spu_func_01339C18" },
    { 0x01339CA4u, spu_job_01339880_spu_func_01339CA4, "spu_job_01339880_spu_func_01339CA4" },
    { 0x01339D30u, spu_job_01339880_spu_func_01339D30, "spu_job_01339880_spu_func_01339D30" },
    { 0x01339D64u, spu_job_01339880_spu_func_01339D64, "spu_job_01339880_spu_func_01339D64" },
    { 0x01339DB8u, spu_job_01339880_spu_func_01339DB8, "spu_job_01339880_spu_func_01339DB8" },
    { 0x01339DECu, spu_job_01339880_spu_func_01339DEC, "spu_job_01339880_spu_func_01339DEC" },
    { 0x01339E40u, spu_job_01339880_spu_func_01339E40, "spu_job_01339880_spu_func_01339E40" },
    { 0x01339E58u, spu_job_01339880_spu_func_01339E58, "spu_job_01339880_spu_func_01339E58" },
    { 0x01339E70u, spu_job_01339880_spu_func_01339E70, "spu_job_01339880_spu_func_01339E70" },
    { 0x01339EB8u, spu_job_01339880_spu_func_01339EB8, "spu_job_01339880_spu_func_01339EB8" },
    { 0x01339EE0u, spu_job_01339880_spu_func_01339EE0, "spu_job_01339880_spu_func_01339EE0" },
    { 0x01339FBCu, spu_job_01339880_spu_func_01339FBC, "spu_job_01339880_spu_func_01339FBC" },
    { 0x01339FDCu, spu_job_01339880_spu_func_01339FDC, "spu_job_01339880_spu_func_01339FDC" },
    { 0, NULL, NULL }
};

void spu_job_01339880_spu_recomp_register(void) {
    for (const spu_func_entry* e = spu_function_table; e->func; ++e)
        spu_register_function(e->addr, e->func);
}
