/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#include "spu_recomp.h"
#include "../../runtime/spu/spu_helpers.h"


void spu_job_01336400_spu_func_01336400(spu_context* ctx) {
        ctx->gpr[2] = spu_ila(0x334F0);
        ctx->gpr[2] = spu_ila(0x8045);
        ctx->gpr[2] = spu_ila(0x3989A);
        ctx->gpr[2] = spu_ila(0x3BD27);
        ctx->gpr[80] = spu_xori(ctx->gpr[80], 4);
        { ctx->pc = 0x36418; SPU_TAILCALL(spu_job_01336400_spu_func_00036418(ctx)); }
}

void spu_job_01336400_spu_func_01336418(spu_context* ctx) {
        ctx->gpr[80] = spu_xori(ctx->gpr[80], 4);
        { ctx->pc = 0x36430; SPU_TAILCALL(spu_job_01336400_spu_func_00036430(ctx)); }
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
}

void spu_job_01336400_spu_func_01336430(spu_context* ctx) {
        ctx->gpr[2] = spu_ori(ctx->gpr[3], 0);
        ctx->gpr[3] = spu_ai(ctx->gpr[4], 48);
        ctx->gpr[4] = spu_ls_read128(ctx, ctx->gpr[2]._u32[0] + 0x20);
        ctx->gpr[4] = spu_rotqby(ctx->gpr[4], ctx->gpr[2]);
        { ctx->pc = 0x38B40; SPU_TAILCALL(spu_job_01336400_spu_func_00038B40(ctx)); }
        /* nop */;
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        /* nop */;
        ctx->gpr[16] = spu_a(ctx->gpr[4], ctx->gpr[5]);
        ctx->gpr[15] = spu_shlqbyi(ctx->gpr[4], 0);
        ctx->gpr[2] = spu_clgt(ctx->gpr[16], ctx->gpr[4]);
        if (ctx->gpr[2]._u32[0] == 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        ctx->gpr[14] = spu_ori(ctx->gpr[3], 0);
        /* branch hint (ignored) */;
        { ctx->pc = 0x1336468; SPU_TAILCALL(spu_job_01336400_spu_func_01336468(ctx)); }
}

void spu_job_01336400_spu_func_01336468(spu_context* ctx) {
        ctx->gpr[22] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0x0);
        ctx->gpr[21] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0x10);
        ctx->gpr[20] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0x20);
        ctx->gpr[19] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0x30);
        ctx->gpr[18] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0x40);
        ctx->gpr[17] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0x50);
        ctx->gpr[10] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0x60);
        ctx->gpr[12] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0x70);
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0x0, ctx->gpr[22]);
        ctx->gpr[13] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0x80);
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0x10, ctx->gpr[21]);
        ctx->gpr[11] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0x90);
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0x20, ctx->gpr[20]);
        ctx->gpr[9] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0xA0);
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0x30, ctx->gpr[19]);
        ctx->gpr[7] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0xB0);
        /* branch hint (ignored) */;
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0x40, ctx->gpr[18]);
        ctx->gpr[5] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0xC0);
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0x50, ctx->gpr[17]);
        ctx->gpr[4] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0xD0);
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0x60, ctx->gpr[10]);
        ctx->gpr[8] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0xE0);
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0x70, ctx->gpr[12]);
        ctx->gpr[6] = spu_ls_read128(ctx, ctx->gpr[15]._u32[0] + 0xF0);
        ctx->gpr[15] = spu_ai(ctx->gpr[15], 256);
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0x80, ctx->gpr[13]);
        ctx->gpr[3] = spu_clgt(ctx->gpr[16], ctx->gpr[15]);
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0x90, ctx->gpr[11]);
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0xA0, ctx->gpr[9]);
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0xB0, ctx->gpr[7]);
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0xC0, ctx->gpr[5]);
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0xD0, ctx->gpr[4]);
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0xE0, ctx->gpr[8]);
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[14]._u32[0] + 0xF0, ctx->gpr[6]);
        ctx->gpr[14] = spu_ai(ctx->gpr[14], 256);
        if (ctx->gpr[3]._u32[0] != 0) { ctx->pc = 0x36468; SPU_TAILCALL(spu_job_01336400_spu_func_00036468(ctx)); }
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        /* nop */;
        { ctx->pc = 0x1336508; SPU_TAILCALL(spu_job_01336400_spu_func_01336508(ctx)); }
}

void spu_job_01336400_spu_func_01336508(spu_context* ctx) {
        ctx->gpr[2] = spu_il(0);
        ctx->gpr[4] = spu_shlqbyi(ctx->gpr[3], 0);
        spu_wrch(ctx, MFC_WrTagUpdate, ctx->gpr[2]);
        { ctx->pc = 0x1336514; SPU_TAILCALL(spu_job_01336400_spu_func_01336514(ctx)); }
}

void spu_job_01336400_spu_func_01336514(spu_context* ctx) {
        ctx->gpr[2] = spu_pref_u32(spu_rchcnt(ctx, MFC_WrTagUpdate));
        ctx->gpr[3] = spu_ceqi(ctx->gpr[2], 1);
        if (ctx->gpr[3]._u32[0] == 0) { ctx->pc = 0x36514; SPU_TAILCALL(spu_job_01336400_spu_func_00036514(ctx)); }
        /* nop */;
        /* branch hint (ignored) */;
        ctx->gpr[5] = spu_shl(ctx->gpr[2], ctx->gpr[4]);
        ctx->gpr[3] = spu_rdch(ctx, MFC_RdTagStat);
        ctx->gpr[4] = spu_il(2);
        /* nop */;
        /* nop */;
        spu_wrch(ctx, MFC_WrTagMask, ctx->gpr[5]);
        spu_wrch(ctx, MFC_WrTagUpdate, ctx->gpr[4]);
        ctx->gpr[2] = spu_rdch(ctx, MFC_RdTagStat);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        /* nop */;
        ctx->gpr[9] = spu_ceqi(ctx->gpr[4], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x50, ctx->gpr[84]);
        ctx->gpr[8] = spu_ceqi(ctx->gpr[5], 0);
        ctx->gpr[84] = spu_shlqbyi(ctx->gpr[4], 0);
        ctx->gpr[7] = spu_sfi(ctx->gpr[9], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x40, ctx->gpr[83]);
        ctx->gpr[4] = spu_sfi(ctx->gpr[8], 0);
        ctx->gpr[83] = spu_shlqbyi(ctx->gpr[5], 0);
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x80, ctx->gpr[87]);
        ctx->gpr[5] = spu_or(ctx->gpr[7], ctx->gpr[4]);
        ctx->gpr[87] = spu_shlqbyi(ctx->gpr[3], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x60, ctx->gpr[85]);
        ctx->gpr[3] = spu_ceqbi(ctx->gpr[5], 0);
        ctx->gpr[85] = spu_ori(ctx->gpr[6], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + 0x10, ctx->gpr[0]);
        ctx->gpr[2] = spu_xsbh(ctx->gpr[3]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x10, ctx->gpr[80]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x20, ctx->gpr[81]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x30, ctx->gpr[82]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x70, ctx->gpr[86]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x90, ctx->gpr[88]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xA0, ctx->gpr[89]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xB0, ctx->gpr[90]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xC0, ctx->gpr[91]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xD0, ctx->gpr[126]);
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xF0, ctx->gpr[1]);
        ctx->gpr[1] = spu_ai(ctx->gpr[1], -240);
        if (ctx->gpr[2]._u16[1] == 0) { ctx->pc = 0x36674; SPU_TAILCALL(spu_job_01336400_spu_func_00036674(ctx)); }
        ctx->gpr[6] = spu_cgti(ctx->gpr[6], 0);
        if (ctx->gpr[6]._u32[0] == 0) { ctx->pc = 0x36674; SPU_TAILCALL(spu_job_01336400_spu_func_00036674(ctx)); }
        ctx->gpr[88] = spu_ori(ctx->gpr[87], 0);
        /* branch hint (ignored) */;
        ctx->gpr[86] = spu_il(0);
        ctx->gpr[90] = spu_fsmbi(0x0);
        ctx->gpr[91] = spu_il(16383);
        ctx->gpr[89] = spu_il(32);
        { ctx->pc = 0x13365E8; SPU_TAILCALL(spu_job_01336400_spu_func_013365E8(ctx)); }
}

void spu_job_01336400_spu_func_013365E8(spu_context* ctx) {
        ctx->gpr[20] = spu_sf(ctx->gpr[86], ctx->gpr[85]);
        ctx->gpr[3] = spu_shlqbyi(ctx->gpr[87], 0);
        ctx->gpr[13] = spu_il(16384);
        ctx->gpr[28] = spu_ai(ctx->gpr[20], 3);
        ctx->gpr[27] = spu_ai(ctx->gpr[20], 7);
        ctx->gpr[25] = spu_cgti(ctx->gpr[20], 4);
        ctx->gpr[23] = spu_andi(ctx->gpr[28], -4);
        ctx->gpr[24] = spu_andi(ctx->gpr[27], -8);
        ctx->gpr[26] = spu_ai(ctx->gpr[20], 15);
        ctx->gpr[22] = spu_ceqi(ctx->gpr[25], 0);
        ctx->gpr[21] = spu_cgti(ctx->gpr[20], 8);
        ctx->gpr[19] = spu_andi(ctx->gpr[26], -16);
        ctx->gpr[17] = spu_selb(ctx->gpr[24], ctx->gpr[23], ctx->gpr[22]);
        ctx->gpr[18] = spu_ceqi(ctx->gpr[21], 0);
        ctx->gpr[16] = spu_cgt(ctx->gpr[20], ctx->gpr[91]);
        ctx->gpr[15] = spu_selb(ctx->gpr[19], ctx->gpr[17], ctx->gpr[18]);
        ctx->gpr[14] = spu_ceqi(ctx->gpr[16], 0);
        /* nop */;
        ctx->gpr[81] = spu_selb(ctx->gpr[13], ctx->gpr[15], ctx->gpr[14]);
        ctx->gpr[0] = spu_link(0x1336638); spu_host_call_push(ctx, 0x1336638); spu_job_01336400_spu_func_00036508(ctx); spu_host_call_pop(ctx);
        ctx->gpr[12] = spu_ori(ctx->gpr[83], 0);
        /* branch hint (ignored) */;
        ctx->gpr[11] = spu_ori(ctx->gpr[84], 0);
        ctx->gpr[80] = spu_shlqbyi(ctx->gpr[81], 0);
        ctx->gpr[86] = spu_a(ctx->gpr[86], ctx->gpr[81]);
        spu_wrch(ctx, MFC_LSA, ctx->gpr[12]);
        ctx->gpr[83] = spu_a(ctx->gpr[83], ctx->gpr[81]);
        spu_wrch(ctx, MFC_EAH, ctx->gpr[90]);
        ctx->gpr[10] = spu_cgt(ctx->gpr[85], ctx->gpr[86]);
        spu_wrch(ctx, MFC_EAL, ctx->gpr[11]);
        ctx->gpr[84] = spu_a(ctx->gpr[84], ctx->gpr[81]);
        spu_wrch(ctx, MFC_Size, ctx->gpr[80]);
        spu_wrch(ctx, MFC_TagID, ctx->gpr[88]);
        spu_wrch(ctx, MFC_Cmd, ctx->gpr[89]);
        if (ctx->gpr[10]._u32[0] != 0) { ctx->pc = 0x365E8; SPU_TAILCALL(spu_job_01336400_spu_func_000365E8(ctx)); }
        { ctx->pc = 0x1336674; SPU_TAILCALL(spu_job_01336400_spu_func_01336674(ctx)); }
}

void spu_job_01336400_spu_func_01336674(spu_context* ctx) {
        ctx->gpr[0] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + 0x100);
        ctx->gpr[1] = spu_ai(ctx->gpr[1], 240);
        ctx->gpr[80] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x10);
        ctx->gpr[81] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x20);
        ctx->gpr[82] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x30);
        /* branch hint (ignored) */;
        ctx->gpr[83] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x40);
        ctx->gpr[84] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x50);
        ctx->gpr[85] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x60);
        ctx->gpr[86] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x70);
        ctx->gpr[87] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x80);
        ctx->gpr[88] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x90);
        ctx->gpr[89] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0xA0);
        ctx->gpr[90] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0xB0);
        ctx->gpr[91] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0xC0);
        ctx->gpr[126] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0xD0);
        ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return;
        ctx->gpr[9] = spu_ceqi(ctx->gpr[4], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x50, ctx->gpr[84]);
        ctx->gpr[8] = spu_ceqi(ctx->gpr[5], 0);
        ctx->gpr[84] = spu_shlqbyi(ctx->gpr[4], 0);
        ctx->gpr[7] = spu_sfi(ctx->gpr[9], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x40, ctx->gpr[83]);
        ctx->gpr[4] = spu_sfi(ctx->gpr[8], 0);
        ctx->gpr[83] = spu_shlqbyi(ctx->gpr[5], 0);
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x80, ctx->gpr[87]);
        ctx->gpr[5] = spu_or(ctx->gpr[7], ctx->gpr[4]);
        ctx->gpr[87] = spu_shlqbyi(ctx->gpr[3], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x60, ctx->gpr[85]);
        ctx->gpr[3] = spu_ceqbi(ctx->gpr[5], 0);
        ctx->gpr[85] = spu_ori(ctx->gpr[6], 0);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + 0x10, ctx->gpr[0]);
        ctx->gpr[2] = spu_xsbh(ctx->gpr[3]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x10, ctx->gpr[80]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x20, ctx->gpr[81]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x30, ctx->gpr[82]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x70, ctx->gpr[86]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x90, ctx->gpr[88]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xA0, ctx->gpr[89]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xB0, ctx->gpr[90]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xC0, ctx->gpr[91]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xD0, ctx->gpr[126]);
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xF0, ctx->gpr[1]);
        ctx->gpr[1] = spu_ai(ctx->gpr[1], -240);
        if (ctx->gpr[2]._u16[1] == 0) { ctx->pc = 0x367DC; SPU_TAILCALL(spu_job_01336400_spu_func_000367DC(ctx)); }
        ctx->gpr[6] = spu_cgti(ctx->gpr[6], 0);
        if (ctx->gpr[6]._u32[0] == 0) { ctx->pc = 0x367DC; SPU_TAILCALL(spu_job_01336400_spu_func_000367DC(ctx)); }
        ctx->gpr[88] = spu_ori(ctx->gpr[87], 0);
        /* branch hint (ignored) */;
}

/* Indirect-dispatch stubs for cross-function targets the
 * function detector did not seed (typically conditional
 * branches that escape a function's range). */
void spu_job_01336400_spu_func_00036418(spu_context* ctx) {
    ctx->pc = 0x36418u; spu_indirect_branch(ctx);
}
void spu_job_01336400_spu_func_00036430(spu_context* ctx) {
    ctx->pc = 0x36430u; spu_indirect_branch(ctx);
}
void spu_job_01336400_spu_func_00036468(spu_context* ctx) {
    ctx->pc = 0x36468u; spu_indirect_branch(ctx);
}
void spu_job_01336400_spu_func_00036508(spu_context* ctx) {
    ctx->pc = 0x36508u; spu_indirect_branch(ctx);
}
void spu_job_01336400_spu_func_00036514(spu_context* ctx) {
    ctx->pc = 0x36514u; spu_indirect_branch(ctx);
}
void spu_job_01336400_spu_func_000365E8(spu_context* ctx) {
    ctx->pc = 0x365E8u; spu_indirect_branch(ctx);
}
void spu_job_01336400_spu_func_00036674(spu_context* ctx) {
    ctx->pc = 0x36674u; spu_indirect_branch(ctx);
}
void spu_job_01336400_spu_func_000367DC(spu_context* ctx) {
    ctx->pc = 0x367DCu; spu_indirect_branch(ctx);
}
void spu_job_01336400_spu_func_00038B40(spu_context* ctx) {
    ctx->pc = 0x38B40u; spu_indirect_branch(ctx);
}

/* Function table */
typedef struct { uint32_t addr; void (*func)(spu_context*); const char* name; } spu_func_entry;
static const spu_func_entry spu_function_table[] = {
    { 0x01336400u, spu_job_01336400_spu_func_01336400, "spu_job_01336400_spu_func_01336400" },
    { 0x01336418u, spu_job_01336400_spu_func_01336418, "spu_job_01336400_spu_func_01336418" },
    { 0x01336430u, spu_job_01336400_spu_func_01336430, "spu_job_01336400_spu_func_01336430" },
    { 0x01336468u, spu_job_01336400_spu_func_01336468, "spu_job_01336400_spu_func_01336468" },
    { 0x01336508u, spu_job_01336400_spu_func_01336508, "spu_job_01336400_spu_func_01336508" },
    { 0x01336514u, spu_job_01336400_spu_func_01336514, "spu_job_01336400_spu_func_01336514" },
    { 0x013365E8u, spu_job_01336400_spu_func_013365E8, "spu_job_01336400_spu_func_013365E8" },
    { 0x01336674u, spu_job_01336400_spu_func_01336674, "spu_job_01336400_spu_func_01336674" },
    { 0, NULL, NULL }
};

void spu_job_01336400_spu_recomp_register(void) {
    for (const spu_func_entry* e = spu_function_table; e->func; ++e)
        spu_register_function(e->addr, e->func);
}
