/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#pragma once
#include "../../runtime/spu/spu_context.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Cross-function branch/loop = a guest tail-jump to another lifted function's
 * entry. It MUST reuse the current host frame, not nest one: SPURS task loops
 * iterate via these, so nesting overflows the host stack and silently kills the
 * process. clang's musttail guarantees the tail call (a jump); without it (or on
 * a non-clang compiler) we fall back to call+return, which only stays bounded if
 * the compiler happens to do sibling-call optimization. All lifted SPU functions
 * share the signature `void f(spu_context*)`, so the tail call is always valid. */
#if defined(__clang__)
#  define SPU_TAILCALL(call) __attribute__((musttail)) return call
#else
#  define SPU_TAILCALL(call) do { call; return; } while (0)
#endif

/* Indirect branch dispatch (bi/bisl/bid...): PC has been set to the target
 * local-store address; the runtime resolves it to the matching lifted
 * function and continues execution. Implemented by the SPU program glue. */
void spu_indirect_branch(spu_context* ctx);

/* stop/stopd hook (YDKJ): the runtime inspects the stop code, may deliver a
 * stop-and-signal event to the PPU (SPURS bring-up handshake), and longjmps the
 * host SPU thread back to spu_run_with_halt so the job does not spin past the
 * stop. Complements ctx->status; harmless where the runtime handles status. */
void spu_stop(spu_context* ctx);
/* Lower-level longjmp helper: abort the host SPU thread back to spu_run_with_halt
 * (used for the infinite no-op self-loop / idle halt idiom). */
void spu_halt(spu_context* ctx);

/* Channel access -- implemented by the runtime (MFC DMA engine, mailboxes,
 * signal notification, decrementer). See runtime/spu/spu_dma.h. */
u128 spu_rdch(spu_context* ctx, uint32_t channel);
uint32_t spu_rchcnt(spu_context* ctx, uint32_t channel);
void spu_wrch(spu_context* ctx, uint32_t channel, u128 value);

/* Execution trace (only emitted when the lifter was invoked with --trace). */
void spu_trace_init(const char* path);
void spu_trace_pc(spu_context* ctx, uint32_t pc);
void spu_trace_rt(spu_context* ctx, uint32_t rt);

#ifdef __cplusplus
}
#endif


void spu_job_014A5100_spu_func_014A5100(spu_context* ctx);
void spu_job_014A5100_spu_func_014A5118(spu_context* ctx);
void spu_job_014A5100_spu_func_014A5130(spu_context* ctx);
void spu_job_014A5100_spu_func_014A5158(spu_context* ctx);
void spu_job_014A5100_spu_func_014A5208(spu_context* ctx);
void spu_job_014A5100_spu_func_014A521C(spu_context* ctx);
void spu_job_014A5100_spu_func_014A5278(spu_context* ctx);
void spu_job_014A5100_spu_func_014A5350(spu_context* ctx);
void spu_job_014A5100_spu_func_014A539C(spu_context* ctx);
void spu_job_014A5100_spu_func_014A5400(spu_context* ctx);
void spu_job_014A5100_spu_func_014A54D0(spu_context* ctx);
void spu_job_014A5100_spu_func_014A55B4(spu_context* ctx);
void spu_job_014A5100_spu_func_014A55D0(spu_context* ctx);
void spu_job_014A5100_spu_func_014A5688(spu_context* ctx);
void spu_job_014A5100_spu_func_014A5748(spu_context* ctx);
void spu_job_014A5100_spu_func_014A577C(spu_context* ctx);
void spu_job_014A5100_spu_func_014A5798(spu_context* ctx);
void spu_job_014A5100_spu_func_014A57B0(spu_context* ctx);
void spu_job_014A5100_spu_func_014A57F0(spu_context* ctx);
void spu_job_014A5100_spu_func_014A5800(spu_context* ctx);
void spu_job_014A5100_spu_func_014A5818(spu_context* ctx);
void spu_job_014A5100_spu_func_014A5844(spu_context* ctx);
void spu_job_014A5100_spu_func_014A586C(spu_context* ctx);
void spu_job_014A5100_spu_func_014A5894(spu_context* ctx);
void spu_job_014A5100_spu_func_014A58C8(spu_context* ctx);
void spu_job_014A5100_spu_func_014A58D0(spu_context* ctx);
void spu_job_014A5100_spu_func_014A5920(spu_context* ctx);
void spu_job_014A5100_spu_func_014A5948(spu_context* ctx);
void spu_job_014A5100_spu_func_014A59A8(spu_context* ctx);
void spu_job_014A5100_spu_func_014A5A00(spu_context* ctx);
void spu_job_014A5100_spu_func_014A5A30(spu_context* ctx);
void spu_job_014A5100_spu_func_014A5AF4(spu_context* ctx);
void spu_job_014A5100_spu_func_014A5B00(spu_context* ctx);
void spu_job_014A5100_spu_func_014A5B10(spu_context* ctx);
void spu_job_014A5100_spu_func_014A5BB8(spu_context* ctx);
void spu_job_014A5100_spu_func_014A5C80(spu_context* ctx);
void spu_job_014A5100_spu_func_014A5CD0(spu_context* ctx);
void spu_job_014A5100_spu_func_014A5D20(spu_context* ctx);
void spu_job_014A5100_spu_func_014A5D70(spu_context* ctx);
void spu_job_014A5100_spu_func_00025118(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00025130(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00025158(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00025208(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_0002521C(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00025278(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00025350(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_0002539C(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00025400(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_000254D0(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_000255B4(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_000255D0(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00025688(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00025748(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_0002577C(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00025798(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_000257B0(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_000257F0(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00025800(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00025818(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00025844(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_0002586C(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00025894(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_000258C8(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_000258D0(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00025920(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00025948(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_000259A8(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00025A00(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00025A30(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00025AF4(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00025B00(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00025B10(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00025BB8(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00025C80(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00025CD0(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00025D20(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00025D70(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00025EFC(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00025F44(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00025FA0(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00025FF0(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_0002617C(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00026218(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00026250(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00026270(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_0002628C(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00026308(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00026330(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00026388(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_0002639C(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00026418(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00026440(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00026498(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_000264B0(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00026560(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_000265A8(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_000265C8(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_000265D4(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00026608(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00026628(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00026634(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00026668(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00026690(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_000266A0(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_000266E0(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00026750(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_000267F8(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00026820(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00026878(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_000268E0(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00026948(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00026A00(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_000270E0(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_000272A8(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_000272F0(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00027770(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00027898(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00027AE8(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00027B60(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_00027BB0(spu_context* ctx); /* external */
void spu_job_014A5100_spu_func_0002BF78(spu_context* ctx); /* external */

/* Runtime glue (runtime/spu/spu_channels.c) */
void spu_register_function(uint32_t addr, void (*fn)(spu_context*));
/* Call once at init to register this image's functions for
 * indirect-branch dispatch (spu_indirect_branch). */
void spu_job_014A5100_spu_recomp_register(void);
