/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#pragma once
#include "../../runtime/spu/spu_context.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Cross-function branch/loop = a guest tail-jump to another lifted function's
 * entry. It MUST reuse the current host frame, not nest one: SPURS task loops
 * iterate via these, so nesting overflows the host stack and silently kills the
 * process. clang's musttail guarantees the tail call (a jump); without it (or on
 * a non-clang compiler) we fall back to call+return, which only stays bounded if
 * the compiler happens to do sibling-call optimization. All lifted SPU functions
 * share the signature `void f(spu_context*)`, so the tail call is always valid. */
#if defined(__clang__)
#  define SPU_TAILCALL(call) __attribute__((musttail)) return call
#else
#  define SPU_TAILCALL(call) do { call; return; } while (0)
#endif

/* Indirect branch dispatch (bi/bisl/bid...): PC has been set to the target
 * local-store address; the runtime resolves it to the matching lifted
 * function and continues execution. Implemented by the SPU program glue. */
void spu_indirect_branch(spu_context* ctx);

/* stop/stopd hook (YDKJ): the runtime inspects the stop code, may deliver a
 * stop-and-signal event to the PPU (SPURS bring-up handshake), and longjmps the
 * host SPU thread back to spu_run_with_halt so the job does not spin past the
 * stop. Complements ctx->status; harmless where the runtime handles status. */
void spu_stop(spu_context* ctx);
/* Lower-level longjmp helper: abort the host SPU thread back to spu_run_with_halt
 * (used for the infinite no-op self-loop / idle halt idiom). */
void spu_halt(spu_context* ctx);

/* Channel access -- implemented by the runtime (MFC DMA engine, mailboxes,
 * signal notification, decrementer). See runtime/spu/spu_dma.h. */
u128 spu_rdch(spu_context* ctx, uint32_t channel);
uint32_t spu_rchcnt(spu_context* ctx, uint32_t channel);
void spu_wrch(spu_context* ctx, uint32_t channel, u128 value);

/* Execution trace (only emitted when the lifter was invoked with --trace). */
void spu_trace_init(const char* path);
void spu_trace_pc(spu_context* ctx, uint32_t pc);
void spu_trace_rt(spu_context* ctx, uint32_t rt);

#ifdef __cplusplus
}
#endif


void spu_jobs_spu_func_0000F600(spu_context* ctx);
void spu_jobs_spu_func_0000F618(spu_context* ctx);
void spu_jobs_spu_func_0000F630(spu_context* ctx);
void spu_jobs_spu_func_0000F648(spu_context* ctx);
void spu_jobs_spu_func_0000F658(spu_context* ctx);
void spu_jobs_spu_func_0000F6C0(spu_context* ctx);
void spu_jobs_spu_func_0000F6E8(spu_context* ctx);
void spu_jobs_spu_func_0000F724(spu_context* ctx);
void spu_jobs_spu_func_0000F740(spu_context* ctx);
void spu_jobs_spu_func_0000F758(spu_context* ctx);
void spu_jobs_spu_func_0000F7B0(spu_context* ctx);
void spu_jobs_spu_func_0000F7E8(spu_context* ctx);
void spu_jobs_spu_func_0000F820(spu_context* ctx);
void spu_jobs_spu_func_0000F828(spu_context* ctx);
void spu_jobs_spu_func_0000F86C(spu_context* ctx);
void spu_jobs_spu_func_0000F898(spu_context* ctx);
void spu_jobs_spu_func_0000F8D8(spu_context* ctx);
void spu_jobs_spu_func_0000F924(spu_context* ctx);
void spu_jobs_spu_func_0000F984(spu_context* ctx);
void spu_jobs_spu_func_0000F98C(spu_context* ctx);
void spu_jobs_spu_func_0000F9C8(spu_context* ctx);
void spu_jobs_spu_func_0000FA00(spu_context* ctx);
void spu_jobs_spu_func_0000FA18(spu_context* ctx);
void spu_jobs_spu_func_0000FB04(spu_context* ctx);
void spu_jobs_spu_func_0000FB14(spu_context* ctx);
void spu_jobs_spu_func_0000FB60(spu_context* ctx);
void spu_jobs_spu_func_0000FBA0(spu_context* ctx);
void spu_jobs_spu_func_0000FBEC(spu_context* ctx);
void spu_jobs_spu_func_0000FC44(spu_context* ctx);
void spu_jobs_spu_func_0000FC4C(spu_context* ctx);
void spu_jobs_spu_func_0000FC50(spu_context* ctx);
void spu_jobs_spu_func_0000FCE8(spu_context* ctx);
void spu_jobs_spu_func_0000FD34(spu_context* ctx);
void spu_jobs_spu_func_0000FD98(spu_context* ctx);
void spu_jobs_spu_func_0000FE20(spu_context* ctx);
void spu_jobs_spu_func_0000FE6C(spu_context* ctx);
void spu_jobs_spu_func_0000FED0(spu_context* ctx);
void spu_jobs_spu_func_0000FF50(spu_context* ctx);
void spu_jobs_spu_func_0000FF9C(spu_context* ctx);
void spu_jobs_spu_func_0000FFFC(spu_context* ctx);
void spu_jobs_spu_func_00010018(spu_context* ctx);
void spu_jobs_spu_func_00010060(spu_context* ctx);
void spu_jobs_spu_func_000100C0(spu_context* ctx);
void spu_jobs_spu_func_000100F0(spu_context* ctx);
void spu_jobs_spu_func_000100F4(spu_context* ctx);
void spu_jobs_spu_func_00010120(spu_context* ctx);
void spu_jobs_spu_func_000101B0(spu_context* ctx);
void spu_jobs_spu_func_000101D8(spu_context* ctx);
void spu_jobs_spu_func_00010258(spu_context* ctx);
void spu_jobs_spu_func_00010280(spu_context* ctx);
void spu_jobs_spu_func_00010284(spu_context* ctx);
void spu_jobs_spu_func_000102B0(spu_context* ctx);
void spu_jobs_spu_func_000102E8(spu_context* ctx);
void spu_jobs_spu_func_00010330(spu_context* ctx);
void spu_jobs_spu_func_00010338(spu_context* ctx);
void spu_jobs_spu_func_0001040C(spu_context* ctx);
void spu_jobs_spu_func_00010440(spu_context* ctx);
void spu_jobs_spu_func_000104A0(spu_context* ctx);
void spu_jobs_spu_func_000104F8(spu_context* ctx);
void spu_jobs_spu_func_00010540(spu_context* ctx);
void spu_jobs_spu_func_0001058C(spu_context* ctx);
void spu_jobs_spu_func_000105EC(spu_context* ctx);
void spu_jobs_spu_func_00010618(spu_context* ctx);
void spu_jobs_spu_func_00010624(spu_context* ctx);
void spu_jobs_spu_func_00010668(spu_context* ctx);
void spu_jobs_spu_func_000106C8(spu_context* ctx);
void spu_jobs_spu_func_000106FC(spu_context* ctx);
void spu_jobs_spu_func_00010728(spu_context* ctx);
void spu_jobs_spu_func_00010750(spu_context* ctx);
void spu_jobs_spu_func_00010778(spu_context* ctx);
void spu_jobs_spu_func_000107A0(spu_context* ctx);
void spu_jobs_spu_func_000107C8(spu_context* ctx);
void spu_jobs_spu_func_000107F0(spu_context* ctx);
void spu_jobs_spu_func_00010818(spu_context* ctx);
void spu_jobs_spu_func_00010840(spu_context* ctx);
void spu_jobs_spu_func_00010874(spu_context* ctx);
void spu_jobs_spu_func_00010884(spu_context* ctx);
void spu_jobs_spu_func_0001088C(spu_context* ctx);
void spu_jobs_spu_func_000108BC(spu_context* ctx);
void spu_jobs_spu_func_000108EC(spu_context* ctx);
void spu_jobs_spu_func_0001091C(spu_context* ctx);
void spu_jobs_spu_func_0001094C(spu_context* ctx);
void spu_jobs_spu_func_0001097C(spu_context* ctx);
void spu_jobs_spu_func_000109AC(spu_context* ctx);
void spu_jobs_spu_func_000109DC(spu_context* ctx);
void spu_jobs_spu_func_00010A0C(spu_context* ctx);
void spu_jobs_spu_func_00010AF0(spu_context* ctx);
void spu_jobs_spu_func_00010B70(spu_context* ctx);
void spu_jobs_spu_func_00010B74(spu_context* ctx);
void spu_jobs_spu_func_00010BA0(spu_context* ctx);
void spu_jobs_spu_func_00010BD8(spu_context* ctx);
void spu_jobs_spu_func_00010BE8(spu_context* ctx);
void spu_jobs_spu_func_00010C40(spu_context* ctx);
void spu_jobs_spu_func_00010C8C(spu_context* ctx);
void spu_jobs_spu_func_00010CEC(spu_context* ctx);
void spu_jobs_spu_func_00010CF0(spu_context* ctx);
void spu_jobs_spu_func_00010D18(spu_context* ctx);
void spu_jobs_spu_func_00010D60(spu_context* ctx);
void spu_jobs_spu_func_00010DC0(spu_context* ctx);
void spu_jobs_spu_func_00010DF4(spu_context* ctx);
void spu_jobs_spu_func_00010E20(spu_context* ctx);
void spu_jobs_spu_func_00010E74(spu_context* ctx);
void spu_jobs_spu_func_00010E84(spu_context* ctx);
void spu_jobs_spu_func_00010ED0(spu_context* ctx);
void spu_jobs_spu_func_00010ED4(spu_context* ctx);
void spu_jobs_spu_func_00010F08(spu_context* ctx);
void spu_jobs_spu_func_00010F68(spu_context* ctx);
void spu_jobs_spu_func_00010F8C(spu_context* ctx);
void spu_jobs_spu_func_00010FD0(spu_context* ctx);
void spu_jobs_spu_func_00010FDC(spu_context* ctx);
void spu_jobs_spu_func_00011010(spu_context* ctx);
void spu_jobs_spu_func_00011050(spu_context* ctx);
void spu_jobs_spu_func_00011090(spu_context* ctx);
void spu_jobs_spu_func_000110D8(spu_context* ctx);
void spu_jobs_spu_func_0001110C(spu_context* ctx);
void spu_jobs_spu_func_00011118(spu_context* ctx);
void spu_jobs_spu_func_00011148(spu_context* ctx);
void spu_jobs_spu_func_000111E0(spu_context* ctx);
void spu_jobs_spu_func_00011208(spu_context* ctx);
void spu_jobs_spu_func_00011238(spu_context* ctx);
void spu_jobs_spu_func_00011258(spu_context* ctx);
void spu_jobs_spu_func_0001126C(spu_context* ctx);
void spu_jobs_spu_func_00011288(spu_context* ctx);
void spu_jobs_spu_func_000112A8(spu_context* ctx);
void spu_jobs_spu_func_000112BC(spu_context* ctx);
void spu_jobs_spu_func_000112D8(spu_context* ctx);
void spu_jobs_spu_func_00011370(spu_context* ctx);
void spu_jobs_spu_func_00011398(spu_context* ctx);
void spu_jobs_spu_func_000113C4(spu_context* ctx);
void spu_jobs_spu_func_000113F0(spu_context* ctx);
void spu_jobs_spu_func_00011430(spu_context* ctx);
void spu_jobs_spu_func_00011450(spu_context* ctx);
void spu_jobs_spu_func_00011464(spu_context* ctx);
void spu_jobs_spu_func_00011494(spu_context* ctx);
void spu_jobs_spu_func_00011498(spu_context* ctx);
void spu_jobs_spu_func_000115C4(spu_context* ctx);
void spu_jobs_spu_func_00011624(spu_context* ctx);
void spu_jobs_spu_func_00011940(spu_context* ctx);
void spu_jobs_spu_func_00011A60(spu_context* ctx);
void spu_jobs_spu_func_00012100(spu_context* ctx);
void spu_jobs_spu_func_00012300(spu_context* ctx);
void spu_jobs_spu_func_00012318(spu_context* ctx);
void spu_jobs_spu_func_00012330(spu_context* ctx);
void spu_jobs_spu_func_00012348(spu_context* ctx);
void spu_jobs_spu_func_00012350(spu_context* ctx);
void spu_jobs_spu_func_000123C4(spu_context* ctx);
void spu_jobs_spu_func_000123F0(spu_context* ctx);
void spu_jobs_spu_func_00012414(spu_context* ctx);
void spu_jobs_spu_func_00012430(spu_context* ctx);
void spu_jobs_spu_func_00012450(spu_context* ctx);
void spu_jobs_spu_func_00012478(spu_context* ctx);
void spu_jobs_spu_func_00012528(spu_context* ctx);
void spu_jobs_spu_func_00012550(spu_context* ctx);
void spu_jobs_spu_func_00012580(spu_context* ctx);
void spu_jobs_spu_func_000125C0(spu_context* ctx);
void spu_jobs_spu_func_000125D4(spu_context* ctx);
void spu_jobs_spu_func_000125FC(spu_context* ctx);
void spu_jobs_spu_func_00012628(spu_context* ctx);
void spu_jobs_spu_func_00012630(spu_context* ctx);
void spu_jobs_spu_func_00012660(spu_context* ctx);
void spu_jobs_spu_func_00012690(spu_context* ctx);
void spu_jobs_spu_func_00012740(spu_context* ctx);
void spu_jobs_spu_func_00012768(spu_context* ctx);
void spu_jobs_spu_func_00012798(spu_context* ctx);
void spu_jobs_spu_func_000127A0(spu_context* ctx);
void spu_jobs_spu_func_000127E0(spu_context* ctx);
void spu_jobs_spu_func_00012808(spu_context* ctx);
void spu_jobs_spu_func_00012848(spu_context* ctx);
void spu_jobs_spu_func_00012894(spu_context* ctx);
void spu_jobs_spu_func_000128F4(spu_context* ctx);
void spu_jobs_spu_func_000128FC(spu_context* ctx);
void spu_jobs_spu_func_00012938(spu_context* ctx);
void spu_jobs_spu_func_00012948(spu_context* ctx);
void spu_jobs_spu_func_000129F8(spu_context* ctx);
void spu_jobs_spu_func_00012A0C(spu_context* ctx);
void spu_jobs_spu_func_00012A10(spu_context* ctx);
void spu_jobs_spu_func_00012A7C(spu_context* ctx);
void spu_jobs_spu_func_00012AA8(spu_context* ctx);
void spu_jobs_spu_func_00012B00(spu_context* ctx);
void spu_jobs_spu_func_00012B08(spu_context* ctx);
void spu_jobs_spu_func_00012B60(spu_context* ctx);
void spu_jobs_spu_func_00012BD0(spu_context* ctx);
void spu_jobs_spu_func_00012C1C(spu_context* ctx);
void spu_jobs_spu_func_00012C7C(spu_context* ctx);
void spu_jobs_spu_func_00012C9C(spu_context* ctx);
void spu_jobs_spu_func_00012CA0(spu_context* ctx);
void spu_jobs_spu_func_00012CD4(spu_context* ctx);
void spu_jobs_spu_func_00012D10(spu_context* ctx);
void spu_jobs_spu_func_00012D78(spu_context* ctx);
void spu_jobs_spu_func_00012DC4(spu_context* ctx);
void spu_jobs_spu_func_00012E24(spu_context* ctx);
void spu_jobs_spu_func_00012E38(spu_context* ctx);
void spu_jobs_spu_func_00012E60(spu_context* ctx);
void spu_jobs_spu_func_00012E70(spu_context* ctx);
void spu_jobs_spu_func_00012F7C(spu_context* ctx);
void spu_jobs_spu_func_00012F90(spu_context* ctx);
void spu_jobs_spu_func_00012FD4(spu_context* ctx);
void spu_jobs_spu_func_00013000(spu_context* ctx);
void spu_jobs_spu_func_00013040(spu_context* ctx);
void spu_jobs_spu_func_0001308C(spu_context* ctx);
void spu_jobs_spu_func_000130EC(spu_context* ctx);
void spu_jobs_spu_func_000130F4(spu_context* ctx);
void spu_jobs_spu_func_0001312C(spu_context* ctx);
void spu_jobs_spu_func_00013158(spu_context* ctx);
void spu_jobs_spu_func_0001318C(spu_context* ctx);
void spu_jobs_spu_func_000131A0(spu_context* ctx);
void spu_jobs_spu_func_000131A4(spu_context* ctx);
void spu_jobs_spu_func_000131B8(spu_context* ctx);
void spu_jobs_spu_func_000131C0(spu_context* ctx);
void spu_jobs_spu_func_000131F0(spu_context* ctx);
void spu_jobs_spu_func_0001323C(spu_context* ctx);
void spu_jobs_spu_func_00013250(spu_context* ctx);
void spu_jobs_spu_func_00013268(spu_context* ctx);
void spu_jobs_spu_func_00013280(spu_context* ctx);
void spu_jobs_spu_func_00013298(spu_context* ctx);
void spu_jobs_spu_func_000132B0(spu_context* ctx);
void spu_jobs_spu_func_000132C8(spu_context* ctx);
void spu_jobs_spu_func_000132E0(spu_context* ctx);
void spu_jobs_spu_func_000132F8(spu_context* ctx);
void spu_jobs_spu_func_00013310(spu_context* ctx);
void spu_jobs_spu_func_00013328(spu_context* ctx);
void spu_jobs_spu_func_00013340(spu_context* ctx);
void spu_jobs_spu_func_00013358(spu_context* ctx);
void spu_jobs_spu_func_00013370(spu_context* ctx);
void spu_jobs_spu_func_00013388(spu_context* ctx);
void spu_jobs_spu_func_000133A0(spu_context* ctx);
void spu_jobs_spu_func_000133B0(spu_context* ctx);
void spu_jobs_spu_func_00013420(spu_context* ctx);
void spu_jobs_spu_func_0001346C(spu_context* ctx);
void spu_jobs_spu_func_000134CC(spu_context* ctx);
void spu_jobs_spu_func_00013504(spu_context* ctx);
void spu_jobs_spu_func_00013508(spu_context* ctx);
void spu_jobs_spu_func_00013540(spu_context* ctx);
void spu_jobs_spu_func_00013548(spu_context* ctx);
void spu_jobs_spu_func_00013580(spu_context* ctx);
void spu_jobs_spu_func_00013590(spu_context* ctx);
void spu_jobs_spu_func_000135B4(spu_context* ctx);
void spu_jobs_spu_func_000135C8(spu_context* ctx);
void spu_jobs_spu_func_000135E0(spu_context* ctx);
void spu_jobs_spu_func_00013608(spu_context* ctx);
void spu_jobs_spu_func_00013638(spu_context* ctx);
void spu_jobs_spu_func_00013668(spu_context* ctx);
void spu_jobs_spu_func_00013698(spu_context* ctx);
void spu_jobs_spu_func_000136C8(spu_context* ctx);
void spu_jobs_spu_func_000136F8(spu_context* ctx);
void spu_jobs_spu_func_00013728(spu_context* ctx);
void spu_jobs_spu_func_00013750(spu_context* ctx);
void spu_jobs_spu_func_000137E8(spu_context* ctx);
void spu_jobs_spu_func_00013810(spu_context* ctx);
void spu_jobs_spu_func_00013840(spu_context* ctx);
void spu_jobs_spu_func_00013880(spu_context* ctx);
void spu_jobs_spu_func_00013894(spu_context* ctx);
void spu_jobs_spu_func_000138B0(spu_context* ctx);
void spu_jobs_spu_func_000138E0(spu_context* ctx);
void spu_jobs_spu_func_00013914(spu_context* ctx);
void spu_jobs_spu_func_00013950(spu_context* ctx);
void spu_jobs_spu_func_00013988(spu_context* ctx);
void spu_jobs_spu_func_000139B8(spu_context* ctx);
void spu_jobs_spu_func_000139E4(spu_context* ctx);
void spu_jobs_spu_func_00013A1C(spu_context* ctx);
void spu_jobs_spu_func_00013A58(spu_context* ctx);
void spu_jobs_spu_func_00013A7C(spu_context* ctx);
void spu_jobs_spu_func_00013AC0(spu_context* ctx);
void spu_jobs_spu_func_00013B00(spu_context* ctx);
void spu_jobs_spu_func_00013B40(spu_context* ctx);
void spu_jobs_spu_func_00013B7C(spu_context* ctx);
void spu_jobs_spu_func_00013BB8(spu_context* ctx);
void spu_jobs_spu_func_00013BF8(spu_context* ctx);
void spu_jobs_spu_func_00013C38(spu_context* ctx);
void spu_jobs_spu_func_00013C64(spu_context* ctx);
void spu_jobs_spu_func_00013C90(spu_context* ctx);
void spu_jobs_spu_func_00013CC0(spu_context* ctx);
void spu_jobs_spu_func_00013D08(spu_context* ctx);
void spu_jobs_spu_func_00013D48(spu_context* ctx);
void spu_jobs_spu_func_00013D88(spu_context* ctx);
void spu_jobs_spu_func_00013DC8(spu_context* ctx);
void spu_jobs_spu_func_00013E08(spu_context* ctx);
void spu_jobs_spu_func_00013E48(spu_context* ctx);
void spu_jobs_spu_func_00013E88(spu_context* ctx);
void spu_jobs_spu_func_00013EC8(spu_context* ctx);
void spu_jobs_spu_func_00013EE8(spu_context* ctx);
void spu_jobs_spu_func_00013EFC(spu_context* ctx);
void spu_jobs_spu_func_00013F30(spu_context* ctx);
void spu_jobs_spu_func_00013F50(spu_context* ctx);
void spu_jobs_spu_func_00013F64(spu_context* ctx);
void spu_jobs_spu_func_00013F98(spu_context* ctx);
void spu_jobs_spu_func_00013FB8(spu_context* ctx);
void spu_jobs_spu_func_00013FCC(spu_context* ctx);
void spu_jobs_spu_func_00014000(spu_context* ctx);
void spu_jobs_spu_func_00014020(spu_context* ctx);
void spu_jobs_spu_func_00014034(spu_context* ctx);
void spu_jobs_spu_func_00014068(spu_context* ctx);
void spu_jobs_spu_func_00014088(spu_context* ctx);
void spu_jobs_spu_func_0001409C(spu_context* ctx);
void spu_jobs_spu_func_000140D0(spu_context* ctx);
void spu_jobs_spu_func_000140F0(spu_context* ctx);
void spu_jobs_spu_func_00014104(spu_context* ctx);
void spu_jobs_spu_func_00014138(spu_context* ctx);
void spu_jobs_spu_func_00014158(spu_context* ctx);
void spu_jobs_spu_func_0001416C(spu_context* ctx);
void spu_jobs_spu_func_000141A0(spu_context* ctx);
void spu_jobs_spu_func_000141C0(spu_context* ctx);
void spu_jobs_spu_func_000141D4(spu_context* ctx);
void spu_jobs_spu_func_00014208(spu_context* ctx);
void spu_jobs_spu_func_00014394(spu_context* ctx);
void spu_jobs_spu_func_0001C2E8(spu_context* ctx);
void spu_jobs_spu_func_0001C2F0(spu_context* ctx);
void spu_jobs_spu_func_0001D2A0(spu_context* ctx);
void spu_jobs_spu_func_00025100(spu_context* ctx);
void spu_jobs_spu_func_00025118(spu_context* ctx);
void spu_jobs_spu_func_00025130(spu_context* ctx);
void spu_jobs_spu_func_00025158(spu_context* ctx);
void spu_jobs_spu_func_00025208(spu_context* ctx);
void spu_jobs_spu_func_0002521C(spu_context* ctx);
void spu_jobs_spu_func_00025278(spu_context* ctx);
void spu_jobs_spu_func_00025350(spu_context* ctx);
void spu_jobs_spu_func_0002539C(spu_context* ctx);
void spu_jobs_spu_func_00025400(spu_context* ctx);
void spu_jobs_spu_func_000254D0(spu_context* ctx);
void spu_jobs_spu_func_000255B4(spu_context* ctx);
void spu_jobs_spu_func_000255D0(spu_context* ctx);
void spu_jobs_spu_func_00025688(spu_context* ctx);
void spu_jobs_spu_func_00025748(spu_context* ctx);
void spu_jobs_spu_func_0002577C(spu_context* ctx);
void spu_jobs_spu_func_00025798(spu_context* ctx);
void spu_jobs_spu_func_000257B0(spu_context* ctx);
void spu_jobs_spu_func_000257F0(spu_context* ctx);
void spu_jobs_spu_func_00025800(spu_context* ctx);
void spu_jobs_spu_func_00025818(spu_context* ctx);
void spu_jobs_spu_func_00025844(spu_context* ctx);
void spu_jobs_spu_func_0002586C(spu_context* ctx);
void spu_jobs_spu_func_00025894(spu_context* ctx);
void spu_jobs_spu_func_000258C8(spu_context* ctx);
void spu_jobs_spu_func_000258D0(spu_context* ctx);
void spu_jobs_spu_func_00025920(spu_context* ctx);
void spu_jobs_spu_func_00025948(spu_context* ctx);
void spu_jobs_spu_func_000259A8(spu_context* ctx);
void spu_jobs_spu_func_00025A00(spu_context* ctx);
void spu_jobs_spu_func_00025A30(spu_context* ctx);
void spu_jobs_spu_func_00025AF4(spu_context* ctx);
void spu_jobs_spu_func_00025B00(spu_context* ctx);
void spu_jobs_spu_func_00025B10(spu_context* ctx);
void spu_jobs_spu_func_00025BB8(spu_context* ctx);
void spu_jobs_spu_func_00025C80(spu_context* ctx);
void spu_jobs_spu_func_00025CD0(spu_context* ctx);
void spu_jobs_spu_func_00025D20(spu_context* ctx);
void spu_jobs_spu_func_00025D70(spu_context* ctx);
void spu_jobs_spu_func_00025EFC(spu_context* ctx);
void spu_jobs_spu_func_00025F44(spu_context* ctx);
void spu_jobs_spu_func_00025FA0(spu_context* ctx);
void spu_jobs_spu_func_00025FF0(spu_context* ctx);
void spu_jobs_spu_func_0002617C(spu_context* ctx);
void spu_jobs_spu_func_00026218(spu_context* ctx);
void spu_jobs_spu_func_00026250(spu_context* ctx);
void spu_jobs_spu_func_00026270(spu_context* ctx);
void spu_jobs_spu_func_0002628C(spu_context* ctx);
void spu_jobs_spu_func_00026308(spu_context* ctx);
void spu_jobs_spu_func_00026330(spu_context* ctx);
void spu_jobs_spu_func_00026388(spu_context* ctx);
void spu_jobs_spu_func_0002639C(spu_context* ctx);
void spu_jobs_spu_func_00026418(spu_context* ctx);
void spu_jobs_spu_func_00026440(spu_context* ctx);
void spu_jobs_spu_func_00026498(spu_context* ctx);
void spu_jobs_spu_func_000264B0(spu_context* ctx);
void spu_jobs_spu_func_00026560(spu_context* ctx);
void spu_jobs_spu_func_000265A8(spu_context* ctx);
void spu_jobs_spu_func_000265C8(spu_context* ctx);
void spu_jobs_spu_func_000265D4(spu_context* ctx);
void spu_jobs_spu_func_00026608(spu_context* ctx);
void spu_jobs_spu_func_00026628(spu_context* ctx);
void spu_jobs_spu_func_00026634(spu_context* ctx);
void spu_jobs_spu_func_00026668(spu_context* ctx);
void spu_jobs_spu_func_00026690(spu_context* ctx);
void spu_jobs_spu_func_000266A0(spu_context* ctx);
void spu_jobs_spu_func_000266E0(spu_context* ctx);
void spu_jobs_spu_func_00026750(spu_context* ctx);
void spu_jobs_spu_func_000267F8(spu_context* ctx);
void spu_jobs_spu_func_00026820(spu_context* ctx);
void spu_jobs_spu_func_00026878(spu_context* ctx);
void spu_jobs_spu_func_000268E0(spu_context* ctx);
void spu_jobs_spu_func_00026948(spu_context* ctx);
void spu_jobs_spu_func_00026A00(spu_context* ctx);
void spu_jobs_spu_func_000270E0(spu_context* ctx);
void spu_jobs_spu_func_000272A8(spu_context* ctx);
void spu_jobs_spu_func_000272F0(spu_context* ctx);
void spu_jobs_spu_func_00027770(spu_context* ctx);
void spu_jobs_spu_func_00027898(spu_context* ctx);
void spu_jobs_spu_func_00027AE8(spu_context* ctx);
void spu_jobs_spu_func_00027B60(spu_context* ctx);
void spu_jobs_spu_func_00027BB0(spu_context* ctx);
void spu_jobs_spu_func_0002BB70(spu_context* ctx);
void spu_jobs_spu_func_0002BF78(spu_context* ctx);
void spu_jobs_spu_func_0002DD50(spu_context* ctx);
void spu_jobs_spu_func_00030580(spu_context* ctx);
void spu_jobs_spu_func_00036400(spu_context* ctx);
void spu_jobs_spu_func_00038A80(spu_context* ctx);
void spu_jobs_spu_func_00038A98(spu_context* ctx);
void spu_jobs_spu_func_00038AB0(spu_context* ctx);
void spu_jobs_spu_func_00038AC8(spu_context* ctx);
void spu_jobs_spu_func_00038AD8(spu_context* ctx);
void spu_jobs_spu_func_00038C18(spu_context* ctx);
void spu_jobs_spu_func_00038C70(spu_context* ctx);
void spu_jobs_spu_func_00038C90(spu_context* ctx);
void spu_jobs_spu_func_00038C94(spu_context* ctx);
void spu_jobs_spu_func_00038CE8(spu_context* ctx);
void spu_jobs_spu_func_00038D0C(spu_context* ctx);
void spu_jobs_spu_func_00038D40(spu_context* ctx);
void spu_jobs_spu_func_00038D60(spu_context* ctx);
void spu_jobs_spu_func_00038D68(spu_context* ctx);
void spu_jobs_spu_func_00038D84(spu_context* ctx);
void spu_jobs_spu_func_00038DAC(spu_context* ctx);
void spu_jobs_spu_func_00038DCC(spu_context* ctx);
void spu_jobs_spu_func_00038DD8(spu_context* ctx);
void spu_jobs_spu_func_00038E80(spu_context* ctx);
void spu_jobs_spu_func_00038EA8(spu_context* ctx);
void spu_jobs_spu_func_00038EDC(spu_context* ctx);
void spu_jobs_spu_func_00038EE8(spu_context* ctx);
void spu_jobs_spu_func_00038F18(spu_context* ctx);
void spu_jobs_spu_func_00038FD0(spu_context* ctx);
void spu_jobs_spu_func_00038FF8(spu_context* ctx);
void spu_jobs_spu_func_00039028(spu_context* ctx);
void spu_jobs_spu_func_000390D0(spu_context* ctx);
void spu_jobs_spu_func_000390F8(spu_context* ctx);
void spu_jobs_spu_func_0003912C(spu_context* ctx);
void spu_jobs_spu_func_00039154(spu_context* ctx);
void spu_jobs_spu_func_0003917C(spu_context* ctx);
void spu_jobs_spu_func_000391A8(spu_context* ctx);
void spu_jobs_spu_func_00039248(spu_context* ctx);
void spu_jobs_spu_func_00039270(spu_context* ctx);
void spu_jobs_spu_func_000392A8(spu_context* ctx);
void spu_jobs_spu_func_000392E4(spu_context* ctx);
void spu_jobs_spu_func_00039318(spu_context* ctx);
void spu_jobs_spu_func_00039340(spu_context* ctx);
void spu_jobs_spu_func_00039354(spu_context* ctx);
void spu_jobs_spu_func_00039380(spu_context* ctx);
void spu_jobs_spu_func_00039430(spu_context* ctx);
void spu_jobs_spu_func_00039458(spu_context* ctx);
void spu_jobs_spu_func_00039488(spu_context* ctx);
void spu_jobs_spu_func_00039490(spu_context* ctx);
void spu_jobs_spu_func_00039504(spu_context* ctx);
void spu_jobs_spu_func_00039530(spu_context* ctx);
void spu_jobs_spu_func_00039554(spu_context* ctx);
void spu_jobs_spu_func_00039570(spu_context* ctx);
void spu_jobs_spu_func_00039590(spu_context* ctx);
void spu_jobs_spu_func_000395B8(spu_context* ctx);
void spu_jobs_spu_func_00039668(spu_context* ctx);
void spu_jobs_spu_func_00039690(spu_context* ctx);
void spu_jobs_spu_func_000396C0(spu_context* ctx);
void spu_jobs_spu_func_00039700(spu_context* ctx);
void spu_jobs_spu_func_00039714(spu_context* ctx);
void spu_jobs_spu_func_0003973C(spu_context* ctx);
void spu_jobs_spu_func_00039768(spu_context* ctx);
void spu_jobs_spu_func_00039890(spu_context* ctx);
void spu_jobs_spu_func_000398A8(spu_context* ctx);
void spu_jobs_spu_func_00039940(spu_context* ctx);
void spu_jobs_spu_func_0003998C(spu_context* ctx);
void spu_jobs_spu_func_000399EC(spu_context* ctx);
void spu_jobs_spu_func_000399F4(spu_context* ctx);
void spu_jobs_spu_func_00039A30(spu_context* ctx);
void spu_jobs_spu_func_00039A38(spu_context* ctx);
void spu_jobs_spu_func_00039A78(spu_context* ctx);
void spu_jobs_spu_func_00039AA0(spu_context* ctx);
void spu_jobs_spu_func_00039AE0(spu_context* ctx);
void spu_jobs_spu_func_00039B2C(spu_context* ctx);
void spu_jobs_spu_func_00039B8C(spu_context* ctx);
void spu_jobs_spu_func_00039B94(spu_context* ctx);
void spu_jobs_spu_func_00039BD0(spu_context* ctx);
void spu_jobs_spu_func_00039C28(spu_context* ctx);
void spu_jobs_spu_func_00039CC4(spu_context* ctx);
void spu_jobs_spu_func_00039CC8(spu_context* ctx);
void spu_jobs_spu_func_00039D38(spu_context* ctx);
void spu_jobs_spu_func_00039D50(spu_context* ctx);
void spu_jobs_spu_func_00039D84(spu_context* ctx);
void spu_jobs_spu_func_00039D90(spu_context* ctx);
void spu_jobs_spu_func_00039DD4(spu_context* ctx);
void spu_jobs_spu_func_00039E00(spu_context* ctx);
void spu_jobs_spu_func_00039E40(spu_context* ctx);
void spu_jobs_spu_func_00039E8C(spu_context* ctx);
void spu_jobs_spu_func_00039EEC(spu_context* ctx);
void spu_jobs_spu_func_00039EF4(spu_context* ctx);
void spu_jobs_spu_func_00039F2C(spu_context* ctx);
void spu_jobs_spu_func_00039F40(spu_context* ctx);
void spu_jobs_spu_func_00039F58(spu_context* ctx);
void spu_jobs_spu_func_00039FB0(spu_context* ctx);
void spu_jobs_spu_func_0003A030(spu_context* ctx);
void spu_jobs_spu_func_0003A0A0(spu_context* ctx);
void spu_jobs_spu_func_0003A0EC(spu_context* ctx);
void spu_jobs_spu_func_0003A150(spu_context* ctx);
void spu_jobs_spu_func_0003A188(spu_context* ctx);
void spu_jobs_spu_func_0003A1C0(spu_context* ctx);
void spu_jobs_spu_func_0003A210(spu_context* ctx);
void spu_jobs_spu_func_0003A25C(spu_context* ctx);
void spu_jobs_spu_func_0003A2BC(spu_context* ctx);
void spu_jobs_spu_func_0003A2D0(spu_context* ctx);
void spu_jobs_spu_func_0003A2D4(spu_context* ctx);
void spu_jobs_spu_func_0003A310(spu_context* ctx);
void spu_jobs_spu_func_0003A348(spu_context* ctx);
void spu_jobs_spu_func_0003A364(spu_context* ctx);
void spu_jobs_spu_func_0003A394(spu_context* ctx);
void spu_jobs_spu_func_0003A398(spu_context* ctx);
void spu_jobs_spu_func_0003A408(spu_context* ctx);
void spu_jobs_spu_func_0003A470(spu_context* ctx);
void spu_jobs_spu_func_0003A4BC(spu_context* ctx);
void spu_jobs_spu_func_0003A51C(spu_context* ctx);
void spu_jobs_spu_func_0003A530(spu_context* ctx);
void spu_jobs_spu_func_0003A560(spu_context* ctx);
void spu_jobs_spu_func_0003A570(spu_context* ctx);
void spu_jobs_spu_func_0003A680(spu_context* ctx);
void spu_jobs_spu_func_0003A6B8(spu_context* ctx);
void spu_jobs_spu_func_0003A718(spu_context* ctx);
void spu_jobs_spu_func_0003A764(spu_context* ctx);
void spu_jobs_spu_func_0003A7C4(spu_context* ctx);
void spu_jobs_spu_func_0003A7C8(spu_context* ctx);
void spu_jobs_spu_func_0003A830(spu_context* ctx);
void spu_jobs_spu_func_0003A87C(spu_context* ctx);
void spu_jobs_spu_func_0003A8DC(spu_context* ctx);
void spu_jobs_spu_func_0003A8E0(spu_context* ctx);
void spu_jobs_spu_func_0003A920(spu_context* ctx);
void spu_jobs_spu_func_0003A930(spu_context* ctx);
void spu_jobs_spu_func_0003A988(spu_context* ctx);
void spu_jobs_spu_func_0003A9A8(spu_context* ctx);
void spu_jobs_spu_func_0003A9DC(spu_context* ctx);
void spu_jobs_spu_func_0003A9F0(spu_context* ctx);
void spu_jobs_spu_func_0003AA5C(spu_context* ctx);
void spu_jobs_spu_func_0003AA70(spu_context* ctx);
void spu_jobs_spu_func_0003AA88(spu_context* ctx);
void spu_jobs_spu_func_0003ACB8(spu_context* ctx);
void spu_jobs_spu_func_0003AE10(spu_context* ctx);
void spu_jobs_spu_func_0003B340(spu_context* ctx);
void spu_jobs_spu_func_0003B358(spu_context* ctx);
void spu_jobs_spu_func_0003B4F8(spu_context* ctx);
void spu_jobs_spu_func_0003C168(spu_context* ctx);
void spu_jobs_spu_func_0000F708(spu_context* ctx); /* external */
void spu_jobs_spu_func_00011578(spu_context* ctx); /* external */
void spu_jobs_spu_func_00011840(spu_context* ctx); /* external */
void spu_jobs_spu_func_00011EF0(spu_context* ctx); /* external */
void spu_jobs_spu_func_000121E0(spu_context* ctx); /* external */
void spu_jobs_spu_func_0001233C(spu_context* ctx); /* external */
void spu_jobs_spu_func_000123A8(spu_context* ctx); /* external */
void spu_jobs_spu_func_00012420(spu_context* ctx); /* external */
void spu_jobs_spu_func_00012458(spu_context* ctx); /* external */
void spu_jobs_spu_func_00012548(spu_context* ctx); /* external */
void spu_jobs_spu_func_00012840(spu_context* ctx); /* external */
void spu_jobs_spu_func_000128B8(spu_context* ctx); /* external */
void spu_jobs_spu_func_00012968(spu_context* ctx); /* external */
void spu_jobs_spu_func_00012AB0(spu_context* ctx); /* external */
void spu_jobs_spu_func_00012AE4(spu_context* ctx); /* external */
void spu_jobs_spu_func_00012BB8(spu_context* ctx); /* external */
void spu_jobs_spu_func_00012BEC(spu_context* ctx); /* external */
void spu_jobs_spu_func_00012BF8(spu_context* ctx); /* external */
void spu_jobs_spu_func_00012CC0(spu_context* ctx); /* external */
void spu_jobs_spu_func_00012DD8(spu_context* ctx); /* external */
void spu_jobs_spu_func_00012E90(spu_context* ctx); /* external */
void spu_jobs_spu_func_00012F88(spu_context* ctx); /* external */
void spu_jobs_spu_func_00013020(spu_context* ctx); /* external */
void spu_jobs_spu_func_00013098(spu_context* ctx); /* external */
void spu_jobs_spu_func_000130A4(spu_context* ctx); /* external */
void spu_jobs_spu_func_000131D0(spu_context* ctx); /* external */
void spu_jobs_spu_func_00013234(spu_context* ctx); /* external */
void spu_jobs_spu_func_00013240(spu_context* ctx); /* external */
void spu_jobs_spu_func_000133D8(spu_context* ctx); /* external */
void spu_jobs_spu_func_000134B8(spu_context* ctx); /* external */
void spu_jobs_spu_func_000134D0(spu_context* ctx); /* external */
void spu_jobs_spu_func_00013568(spu_context* ctx); /* external */
void spu_jobs_spu_func_000135EC(spu_context* ctx); /* external */
void spu_jobs_spu_func_000136A0(spu_context* ctx); /* external */
void spu_jobs_spu_func_00013718(spu_context* ctx); /* external */
void spu_jobs_spu_func_0001377C(spu_context* ctx); /* external */
void spu_jobs_spu_func_00013788(spu_context* ctx); /* external */
void spu_jobs_spu_func_000137F8(spu_context* ctx); /* external */
void spu_jobs_spu_func_00013860(spu_context* ctx); /* external */
void spu_jobs_spu_func_00013928(spu_context* ctx); /* external */
void spu_jobs_spu_func_0001399C(spu_context* ctx); /* external */
void spu_jobs_spu_func_000139A8(spu_context* ctx); /* external */
void spu_jobs_spu_func_00013ACC(spu_context* ctx); /* external */
void spu_jobs_spu_func_00013AD8(spu_context* ctx); /* external */
void spu_jobs_spu_func_00013B88(spu_context* ctx); /* external */
void spu_jobs_spu_func_00013C78(spu_context* ctx); /* external */
void spu_jobs_spu_func_00013CD4(spu_context* ctx); /* external */
void spu_jobs_spu_func_00013D28(spu_context* ctx); /* external */
void spu_jobs_spu_func_00013D7C(spu_context* ctx); /* external */
void spu_jobs_spu_func_00013DA8(spu_context* ctx); /* external */
void spu_jobs_spu_func_00013DD8(spu_context* ctx); /* external */
void spu_jobs_spu_func_00013DEC(spu_context* ctx); /* external */
void spu_jobs_spu_func_00013E50(spu_context* ctx); /* external */
void spu_jobs_spu_func_00013EF0(spu_context* ctx); /* external */
void spu_jobs_spu_func_00013F40(spu_context* ctx); /* external */
void spu_jobs_spu_func_00014028(spu_context* ctx); /* external */
void spu_jobs_spu_func_00014054(spu_context* ctx); /* external */
void spu_jobs_spu_func_00014170(spu_context* ctx); /* external */
void spu_jobs_spu_func_000141D8(spu_context* ctx); /* external */
void spu_jobs_spu_func_00014240(spu_context* ctx); /* external */
void spu_jobs_spu_func_00014320(spu_context* ctx); /* external */
void spu_jobs_spu_func_000143B8(spu_context* ctx); /* external */
void spu_jobs_spu_func_000146C4(spu_context* ctx); /* external */
void spu_jobs_spu_func_00014714(spu_context* ctx); /* external */
void spu_jobs_spu_func_0001482C(spu_context* ctx); /* external */
void spu_jobs_spu_func_000148B0(spu_context* ctx); /* external */
void spu_jobs_spu_func_000148C8(spu_context* ctx); /* external */
void spu_jobs_spu_func_000148D8(spu_context* ctx); /* external */
void spu_jobs_spu_func_000148F8(spu_context* ctx); /* external */
void spu_jobs_spu_func_00014D28(spu_context* ctx); /* external */
void spu_jobs_spu_func_00014D68(spu_context* ctx); /* external */
void spu_jobs_spu_func_00015470(spu_context* ctx); /* external */
void spu_jobs_spu_func_000154D0(spu_context* ctx); /* external */
void spu_jobs_spu_func_000154FC(spu_context* ctx); /* external */
void spu_jobs_spu_func_000166D8(spu_context* ctx); /* external */
void spu_jobs_spu_func_00018448(spu_context* ctx); /* external */
void spu_jobs_spu_func_00018FA0(spu_context* ctx); /* external */
void spu_jobs_spu_func_000192C0(spu_context* ctx); /* external */
void spu_jobs_spu_func_0001C2F8(spu_context* ctx); /* external */
void spu_jobs_spu_func_0001C340(spu_context* ctx); /* external */
void spu_jobs_spu_func_0001C820(spu_context* ctx); /* external */
void spu_jobs_spu_func_0001CA48(spu_context* ctx); /* external */
void spu_jobs_spu_func_0001CE68(spu_context* ctx); /* external */
void spu_jobs_spu_func_0001D320(spu_context* ctx); /* external */
void spu_jobs_spu_func_000314E4(spu_context* ctx); /* external */

/* Runtime glue (runtime/spu/spu_channels.c) */
void spu_register_function(uint32_t addr, void (*fn)(spu_context*));
/* Call once at init to register this image's functions for
 * indirect-branch dispatch (spu_indirect_branch). */
void spu_jobs_spu_recomp_register(void);
